force-app/main/default/objects/NotificationSettings__c/NotificationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains configurable email settings utilized by certain custom notifications and alerts used in code.
IMPORTANT - Name value should be in ALL CAPS</description>
    <label>Notification Settings</label>
</CustomObject>

force-app/main/default/objects/NotificationSettings__c/fields/CcEmail__c.field-meta.xml
<CustomField>
    <fullName>CcEmail__c</fullName>
    <description>Optional - one or more email addresses separated by semi-colon to receive a copy of the notification or alert.</description>
    <inlineHelpText>Optional - one or more email addresses separated by semi-colon to receive a copy of the notification or alert.</inlineHelpText>
    <label>Cc Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationSettings__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows for enabling or disabling of the notification or alert.  If disabled, related notifications will NOT be sent.</description>
    <inlineHelpText>Allows for enabling or disabling of the notification or alert.  If disabled, related notifications will NOT be sent.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationSettings__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>&apos;NORMAL&apos;</defaultValue>
    <description>Determines how the notification or alert is sent.  Valid entries are HIGH, NORMAL and LOW.</description>
    <inlineHelpText>Determines how the notification or alert is sent.  Valid entries are HIGH, NORMAL and LOW.</inlineHelpText>
    <label>Priority</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationSettings__c/fields/ReplyToEmail__c.field-meta.xml
<CustomField>
    <fullName>ReplyToEmail__c</fullName>
    <description>The email address to be used if someone replies to the outbound message used by code.  This is normally an administrator or support address.</description>
    <inlineHelpText>The email address to be used if someone replies to the outbound message used by code.  This is normally an administrator or support address.</inlineHelpText>
    <label>Reply To Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/NotificationSettings__c/fields/ToEmail__c.field-meta.xml
<CustomField>
    <fullName>ToEmail__c</fullName>
    <description>Required - Primary email address to receive the notification.</description>
    <inlineHelpText>Required - Primary email address to receive the notification.</inlineHelpText>
    <label>To Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/NotificationUtils.cls
/**
* {Purpose} – The purpose of the class is to encapsulate the any logic necessary
*				to support the use of the NotificationSettings custom setting 
*				object.
* <p>
* {Function} – The NotificationSettings object allows system admins to easily
*				configure any email notification details that are generated
*				from Apex code such as ToEmail, ReplyToEmail, CcEmails and 
*				Priority
* <p>
* {Comments} – This class is dependent on the following components:
*				- NotificationSettings custom setting object
*
* @author	Mike Eaton
* @version	2013-07-13
*
	//	USAGE SAMPLE for Execute Anonymous:
	string sName = 'geocode';
	try{
		//NotificationUtils oNU = new NotificationUtils(sName);
		//system.debug(oNU.getNotificationSettings());
		NotificationUtils.SettingData myData = new  NotificationUtils.SettingData();
		myData = NotificationUtils.getNotificationSettings(sName);
		system.debug(myData.SettingName);
		if( myData.listCcEmail != NULL) {
			system.debug(myData.listCcEmail[0]);
			system.debug(myData.listCcEmail[1]);	
		}
	}
	catch (exception ex)
	{
		system.debug(ex.getMessage());
	}
*/

/**
* CHANGE HISTORY
* =============================================================================
* Date			Name			Description
* 2013-07-13	Mike Eaton		Created      
* {Date}    	{Changed By}	({Ticket}) – {Change Description}
* =============================================================================
*/

public with sharing class NotificationUtils{



	/* 	Contains the custom configuration setting data reformatted 
		for consumption by the Messaging.SingleEmailMessage class
	*/		 
    public class SettingData{
		public String settingName = '';
		public List<String> listToEmail = null;
		public List<String> listCcEmail = null;
		public String replyToEmail = '';
		public Boolean isActive = false;
		public String priority = '';
    }
    
    //	Class level exception
    public class ClassException extends Exception {}
    
    public static SettingData getNotificationSettings(string settingName){
		//	Member variables
		
    	string sNameAllCaps = null;
    	string sExMsg = '';
       
        //  validate argument
        if( string.isBlank(settingName) ){
        	sExMsg = 'Invalid value - settingName parameter cannot be blank!';
            throw new ClassException(sExMsg);
        }
       
        //  get custom setting data
        sNameAllCaps = settingName.toUpperCase();
    	NotificationSettings__c oNS = NotificationSettings__c.getValues(sNameAllCaps);
    	system.debug(oNS);
		if( oNS == null ){
			sExMsg = 'Invalid value - NotificationSetting.Name, "' + settingName + '" does not exist!';
			throw new ClassException(sExMsg);
			
		}
		
		//	set object data
		SettingData oData = new SettingData(); 
		oData.settingName = settingName;
		oData.listToEmail = new List<string>{oNS.ToEmail__c};
		oData.replyToEmail = oNS.ReplyToEmail__c;
		
		//  validate CcEmail__c contains data
		string sCcEmail = oNS.CcEmail__c;
		if( string.isNotBlank(sCcEmail) ){
			List<string> listCcEmail = sCcEmail.split(';');
			oData.listCcEmail = listCcEmail;
		}
		oData.priority = oNS.Priority__c;
		oData.isActive = oNS.IsActive__c;		

		//system.debug( moData );
		return oData;
	}
	
}