force-app/main/default/objects/APEX_Trigger_Settings__c/APEX_Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS consists of a list of triggers and true/false settings to enable/disable functionality without having to disable triggers or edit code.</description>
    <label>APEX Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/APEX_Trigger_Settings__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked - the code is enabled and will run.
Unchecked - the code will be DISABLED and will not run.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment_Role__c/Lead_Assignment_Role__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used by Lead trigger for determining precedence when assigning domestic leads based on zip code territories</description>
    <label>Lead Assignment Role</label>
</CustomObject>

force-app/main/default/objects/Lead_Assignment_Role__c/fields/Lead_Role_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Role_Field__c</fullName>
    <label>Lead Role Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Mapping__mdt/fields/Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Abbreviation__c</fullName>
    <description>2 character state abbreviation</description>
    <label>Abbreviation</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/Zip_Code_Area_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is a lookup table for Area Assignment. - ZIp Code assignment of Reps to Zips</description>
    <label>Zip Code Area Assignment</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Area Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zip Code Area Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This a a lookup to the user.</description>
    <inlineHelpText>This a a lookup to the user.</inlineHelpText>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Area_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is an active checkbox</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>This is the role.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ISM</fullName>
            </value>
            <value>
                <fullName>NAM</fullName>
            </value>
            <value>
                <fullName>RD</fullName>
            </value>
            <value>
                <fullName>ROM</fullName>
            </value>
            <value>
                <fullName>TSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <externalId>true</externalId>
    <label>Zipcode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadAssignmentHelper.cls
/**
 * LeadAssignmentHandler
 * Utility / Helper class for dealing with lead assignment, particular using the Zip Code Assignment table for providing
 * zip code territories and Sales representative roles.
 * @author Demand Chain Systems
 * @Date  11/15/2015
 *
 */

//TODO: Add Lead assignment helper on/off custom setting
//Todo: default owner RD -field
public with sharing class LeadAssignmentHelper {
    
    public static boolean hasAlreadyRun = false;

	//This method will loop through records on before * triggers, and attempt to map the state to its
	//2-char code.  This is to address the fact that some reps (not all) enter the state in the full-name versus 
	//the 2char abbreviation.
	public static void fixLeadStates(List<Lead> leadsToFix){
		//Grab the custom metadata mapping and create an Apex map.
		//Im also using toLowerCase, so there's no funky misses on capitilization weirdness.
		Map<String,String> stateMapping = new Map<String,String>();
		for(State_Mapping__mdt sm : [SELECT MasterLabel,Abbreviation__c FROM State_Mapping__mdt]){
			stateMapping.put(sm.MasterLabel.toLowerCase(),sm.Abbreviation__c);
		}

		for(Lead l : leadsToFix){
			if(!String.isEmpty(l.State)){
				String state = stateMapping.get(l.State.toLowerCase());
				//State may be null if it's aready the 2 char version or no match is found.
				if(state != null){
					l.State = state;
				}
			}
		}
	}

	public static void assignLeadsByZipcode(List<Lead> leadsToAssign){
		APEX_Trigger_Settings__c triggerSetting = APEX_Trigger_Settings__c.getValues('LeadAssignmentHelper');
		if(triggerSetting == null || triggerSetting.IsActive__c){
			//Get a list of the available roles by priority (stored in the Lead Assignment Role list custom setting).
			Map<String,Lead_Assignment_Role__c> roleMap = Lead_Assignment_Role__c.getAll();

			//Construct a map of zip codes to the leads that are connected with those zip codes.
			Set<String> zipcodes = new Set<String>();
			for(Lead l : leadsToAssign){
				String zipcodeOrCountryCode = getZipcodeOrCountryCode(l);
				if(!String.isEmpty(zipcodeOrCountryCode)){
					zipcodes.add(zipcodeOrCountryCode);
				}
			}

			System.debug('JWL: zipcodes: ' + zipcodes);

			List<Zip_Code_Area_Assignment__c> zipAssignments =
				[Select
					Account_Owner__r.Name
					,Role__c
					,Zipcode__c
					,State_Name__c
				 From
				 	Zip_Code_Area_Assignment__c
				 Where
				 	IsActive__c = true
				 	And Zipcode__c in :zipcodes];

			System.debug('JWL: zipAssignments: ' + zipAssignments);


			Map<String,String> stateMapping = new Map<String,String>();
			for(State_Mapping__mdt sm : [SELECT MasterLabel,Abbreviation__c FROM State_Mapping__mdt]){
				stateMapping.put(sm.MasterLabel.toLowerCase(),sm.Abbreviation__c);
			}
			System.debug('JWL: stateMapping: ' + stateMapping);

			//Query for any zip codes that pertain to leads in this scope.
			//Then loop through the zip codes and roles to determine which lead gets assigned to which sales rep.
			for(sObject l : leadsToAssign){
				String zipOrCountry = getZipcodeOrCountryCode((Lead)l);
				System.debug('JWL: zipOrCountry: ' + zipOrCountry);
				for(Zip_Code_Area_Assignment__c zcaa : zipAssignments){
					if(zcaa.Role__c != null && zcaa.Account_Owner__r != null && zcaa.Zipcode__c == zipOrCountry){
						System.debug('JWL: zcaa: ' + zcaa);
						Lead_Assignment_Role__c assignmentRole = roleMap.get(zcaa.Role__c);
						l.put(assignmentRole.Lead_Role_Field__c,zcaa.Account_Owner__r.Name);

						if(!String.isEmpty(zcaa.State_Name__c)){
							String state = stateMapping.get(zcaa.State_Name__c.toLowerCase());
							if(state != null){
								l.put('State',state);
							}
						}
					}
				}
				System.debug('JWL: lead after: ' + l);
			}
		}
	}

	private static String getZipcodeOrCountryCode(Lead l){
		String zip = (String.isEmpty(l.postalCode) || l.PostalCode.length() <= 5) ? l.PostalCode : l.PostalCode.substring(0,5);
		return (String.isEmpty(l.Country) || l.Country == 'US' || l.Country == 'USA') ? zip : l.Country;
	}
}