force-app/main/default/objects/APEX_Trigger_Settings__c/APEX_Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS consists of a list of triggers and true/false settings to enable/disable functionality without having to disable triggers or edit code.</description>
    <label>APEX Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/APEX_Trigger_Settings__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked - the code is enabled and will run.
Unchecked - the code will be DISABLED and will not run.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Marketing_Vendor_Shop_Lite.recordType-meta.xml
<RecordType>
    <fullName>Marketing_Vendor_Shop_Lite</fullName>
    <active>true</active>
    <businessProcess>Marketing Vendorshop Lite</businessProcess>
    <description>For Sales to order Marketing materials</description>
    <label>Marketing Vendor Shop Lite</label>
</RecordType>

force-app/main/default/objects/Case_Line_Item__c/Case_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Case Line Item</label>
    <nameField>
        <displayFormat>Panel-{0000}</displayFormat>
        <label>Case Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Line_Item__c/fields/Merchandising_System__c.field-meta.xml
<CustomField>
    <fullName>Merchandising_System__c</fullName>
    <label>Merchandising System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Slatwall</fullName>
            </value>
            <value>
                <fullName>Lozier End Cap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Line_Item__c/fields/Panels__c.field-meta.xml
<CustomField>
    <fullName>Panels__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Line Items</relationshipLabel>
    <relationshipName>Case_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Line_Item__c/fields/Total_Backer_Panels__c.field-meta.xml
<CustomField>
    <fullName>Total_Backer_Panels__c</fullName>
    <label>Total Backer Panels</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Line_Item__c/recordTypes/Vendor_Shop_Lite_Irish_Setter_Hunt.recordType-meta.xml
<RecordType>
    <fullName>Vendor_Shop_Lite_Irish_Setter_Hunt</fullName>
    <active>true</active>
    <label>Vendor Shop Lite Irish Setter Hunt</label>
</RecordType>

force-app/main/default/objects/Case_Line_Item__c/recordTypes/Vendor_Shop_Lite_Irish_Setter_Work.recordType-meta.xml
<RecordType>
    <fullName>Vendor_Shop_Lite_Irish_Setter_Work</fullName>
    <active>true</active>
    <label>Vendor Shop Lite Irish Setter Work</label>
</RecordType>

force-app/main/default/objects/Case_Line_Item__c/recordTypes/Vendor_Shop_Lite_Red_Wing_Brand.recordType-meta.xml
<RecordType>
    <fullName>Vendor_Shop_Lite_Red_Wing_Brand</fullName>
    <active>true</active>
    <label>Vendor Shop Lite Red Wing Brand</label>
</RecordType>

force-app/main/default/classes/Utility_CaseLI_UT.cls
@isTest
private class Utility_CaseLI_UT {
	
	@isTest static void test() {
		
		// Prep Test Data
		APEX_Trigger_Settings__c apexSetting = new APEX_Trigger_Settings__c(Name='calcMktVendorShopLiteCLI', IsActive__c=true);
		insert apexSetting;

		Map<String, Id> mapCLIRT = new Map<String, Id>();
		for(RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Case_Line_Item__c']) {
			mapCLIRT.put(rt.DeveloperName, rt.Id);
		}

		Map<String, Id> mapCaseRT = new Map<String, Id>();
		for(RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Case']) {
			mapCaseRT.put(rt.DeveloperName, rt.Id);
		}

		Id idScopeRT = mapCaseRT.get('Marketing_Vendor_Shop_Lite');
		System.Debug('************** ' + idScopeRT);
		Case cseRoot = new Case(Subject='Test Case',RecordTypeId=idScopeRT);
		insert cseRoot;

		// Start Test
		test.startTest();

		Case_Line_Item__c cliISHLozier = new Case_Line_Item__c(Panels__c=cseRoot.Id,RecordTypeId=mapCLIRT.get('Vendor_Shop_Lite_Irish_Setter_Hunt')); 
		cliISHLozier.Merchandising_System__c = 'Lozier End Cap';
		cliISHLozier.Total_Backer_Panels__c = 1;
		insert cliISHLozier;

		Case_Line_Item__c cliISWLozier = new Case_Line_Item__c(Panels__c=cseRoot.Id,RecordTypeId=mapCLIRT.get('Vendor_Shop_Lite_Irish_Setter_Work')); 
		cliISWLozier.Merchandising_System__c = 'Lozier End Cap';
		cliISWLozier.Total_Backer_Panels__c = 1;
		insert cliISWLozier;

		Case_Line_Item__c cliRWLozier = new Case_Line_Item__c(Panels__c=cseRoot.Id,RecordTypeId=mapCLIRT.get('Vendor_Shop_Lite_Red_Wing_Brand')); 
		cliRWLozier.Merchandising_System__c = 'Lozier End Cap';
		cliRWLozier.Total_Backer_Panels__c = 1;
		insert cliRWLozier;


		Case_Line_Item__c cliISHSlatwall = new Case_Line_Item__c(Panels__c=cseRoot.Id,RecordTypeId=mapCLIRT.get('Vendor_Shop_Lite_Irish_Setter_Hunt')); 
		cliISHSlatwall.Merchandising_System__c = 'Slatwall';
		cliISHSlatwall.Total_Backer_Panels__c = 1;
		insert cliISHSlatwall;

		Case_Line_Item__c cliISWSlatwall = new Case_Line_Item__c(Panels__c=cseRoot.Id,RecordTypeId=mapCLIRT.get('Vendor_Shop_Lite_Irish_Setter_Work')); 
		cliISWSlatwall.Merchandising_System__c = 'Slatwall';
		cliISWSlatwall.Total_Backer_Panels__c = 1;
		insert cliISWSlatwall;

		Case_Line_Item__c cliRWSlatwall = new Case_Line_Item__c(Panels__c=cseRoot.Id,RecordTypeId=mapCLIRT.get('Vendor_Shop_Lite_Red_Wing_Brand')); 
		cliRWSlatwall.Merchandising_System__c = 'Slatwall';
		cliRWSlatwall.Total_Backer_Panels__c = 1;
		insert cliRWSlatwall;



		// End Test
		test.stopTest();

	}
	
}