force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</description>
    <inlineHelpText>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</inlineHelpText>
    <label>Product Code</label>
    <length>25000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>The Industrial Account Program&apos;s expiration date.  A program will become inactive if the expiration date is less than today.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Industrial Account Program&apos;s expiration date.  A program will become inactive if the expiration date is less than today.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Outbound_Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Message_Type__c</fullName>
    <description>Outbound Message Type
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Outbound Message Type</inlineHelpText>
    <label>Outbound Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Program Publish Status</description>
    <inlineHelpText>Program Publish Status</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Active_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Active_PriceBook__c</fullName>
    <description>Formula Field to return the status (Active / Inactive) of a Program&apos;s Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <formula>Program__r.Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula Field to return the status (Active / Inactive) of a Program&apos;s Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Active PriceBook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Outbound_Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Message_Type__c</fullName>
    <description>Indicates the Outbound Message Type
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the Outbound Message Type</inlineHelpText>
    <label>Outbound Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update PriceBook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Active_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Active_PriceBook__c</fullName>
    <description>Formula Field to return the status (Active / Inactive) of a Program&apos;s Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <formula>Publish_PriceBook__r.Active_PriceBook__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula Field to return the status (Active / Inactive) of a Program&apos;s Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Active PriceBook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book Entry. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book Entry. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</description>
    <inlineHelpText>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</inlineHelpText>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Outbound_Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Message_Type__c</fullName>
    <description>Indicates the Outbound Message Type
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the Outbound Message Type</inlineHelpText>
    <label>Outbound Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update PriceBook Entry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number__c.field-meta.xml
<CustomField>
    <fullName>Style_Number__c</fullName>
    <description>Style Number (field is used to match against Product standard object). Used for outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number (field is used to match against Product standard object). Used for outbound messaging.</inlineHelpText>
    <label>Style Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_ProgramPublish_Util.cls
/********************************************************************************
*   PURPOSE :   Publish/Unpublish Price book and Price Book Entry recrods
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   12/04/2017  Usman Aslam/M360        Initial version
********************************************************************************/
public with sharing class RWS_ProgramPublish_Util {

    // method to publish Price book and Price Book Entry recrods
	@future
    public static void publishPriceBook(Id programId, String publishStatus) {

        if(!isProgramProcessingCompleted(programId)) return;

        // turn off flag to stop program update from Publish PriceBookEntry Trigger
        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = Test.isRunningTest();

        // initialize variable required for logic
        List<Publish_PriceBook__c> pricebookUpdateList = new List<Publish_PriceBook__c>();
        List<Publish_PriceBook_Entry__c> pricebookEntryUpdateList = new List<Publish_PriceBook_Entry__c>();
    
        Map<Id, Id> pricebookIds = new Map<Id, Id>();

        /*
        // get program pricebook Id
        Set<Id> stdPricebookIds = new Map<Id, Pricebook2>(
                [select Id from Pricebook2 where Program__c = :programId]
            ).keySet();


        // get program price book entries
        Set<Id> stdPricebookEntryIds = new Map<Id, PricebookEntry>(
                [select Id from PricebookEntry where Pricebook2Id in :stdPricebookIds]
            ).keySet(); 
		*/

        // get publish price book records that are in waiting or deactivated status
        for(Publish_PriceBook__c ppb : [select id, Name, Publish_Status__c, 
                                Outbound_Message_Type__c, Active_PriceBook__c, Program__c 
                                from Publish_PriceBook__c 
                                Where Program__c = :programId 
                                and (Publish_Status__c = 'Waiting' Or Publish_Status__c = 'Deactivated')]) {

            // set new values
            ppb.Publish_Status__c = publishStatus;
            ppb.Outbound_Message_Type__c = 'Update Pricebook';
            pricebookUpdateList.add(ppb); 
            pricebookIds.put(ppb.Id, programId); 
        }  

        Map<Decimal, Filter_Criteria__c> filterNumberToFC = getFilterNumberToFCMap(programId);

        Map<String, Decimal> productCodesCustomList = new Map<String, Decimal>();

        Map<String, Decimal> productCodeToFilterNumber = new Map<String, Decimal>();

        Map<String, Decimal> productCodeToDiscount = new Map<String, Decimal>();

        for(Filter_Criteria__c fc : filterNumberToFC.values()) {

            if(String.isBlank(fc.Product_Code__c)) continue;

            String codesSet = fc.Product_Code__c.split('-FPC-')[0];

            if(fc.Filter_Number__c > 0 ) {
                Set<String> productCodes = (Set<String>) JSON.deserialize(codesSet, Set<String>.class);

                for(String pc : productCodes) {
                    productCodeToFilterNumber.put(pc, fc.Filter_Number__c);
                    productCodeToDiscount.put(pc, fc.Discount__c);
                }
            } else {
                productCodesCustomList = (Map<String, Decimal>) JSON.deserialize(codesSet, Map<String, Decimal>.class);
            }
        }

        Set<String> processedCodes = new Set<String>();
        // get publish price book entry records that are in waiting or deactivated status
        for(Publish_PriceBook_Entry__c ppbe : [select id, Name, Publish_Status__c, 
                                    Outbound_Message_Type__c, Expiration_Date__c ,
                                    Active__c, Publish_PriceBook__c, Style_Number__c,
                                    Discount__c, Filter_Number__c
                                from Publish_PriceBook_Entry__c 
                                where Publish_PriceBook__c in :pricebookIds.keySet()
                                and (Publish_Status__c = 'Waiting' Or Publish_Status__c = 'Deactivated')
                                and (Style_Number__c in :productCodesCustomList.keySet() or 
                                    Style_Number__c in :productCodeToFilterNumber.keySet())
                                order by Filter_Number__c asc NULLS LAST, Id desc])
        {

            if(processedCodes.contains(ppbe.Style_Number__c)) continue;

            if(productCodesCustomList.containsKey(ppbe.Style_Number__c) ) {
                ppbe.Filter_Number__c = 0;
                //ppbe.Discount__c = productCodesCustomList.get(ppbe.Style_Number__c);
            } else if (productCodeToFilterNumber.containsKey(ppbe.Style_Number__c)){
                ppbe.Filter_Number__c = productCodeToFilterNumber.get(ppbe.Style_Number__c);
                //ppbe.Discount__c = productCodeToDiscount.get(ppbe.Style_Number__c);
            }

            processedCodes.add(ppbe.Style_Number__c);

            // set new values
            ppbe.Publish_Status__c = publishStatus;
            ppbe.Outbound_Message_Type__c = 'Update Pricebook Entry';
            ppbe.Expiration_Date__c = null;
            ppbe.Active__c = true;
            pricebookEntryUpdateList.add(ppbe); 
        }

        for(Filter_Criteria__c fc : filterNumberToFC.values()) {
            if(fc.Program__r.Active__c && fc.Program__r.Publish_Status__c == 'Published') fc.Product_Code__c = null;
        }

        update filterNumberToFC.values();

        // update publish price book records
        if(!pricebookUpdateList.isEmpty()) update pricebookUpdateList;

        // update publish price book entry records
        if(!pricebookEntryUpdateList.isEmpty()) updateRecords(pricebookEntryUpdateList);
    }

    // method to unpublish Price book and Price Book Entry recrods
	@future
    public static void unpublishPriceBook(Id programId) {
        if(!isProgramProcessingCompleted(programId)) return;

        // turn recursion flag off, so the code in PriceBook Trigger is not executed
        RWS_PriceBookTrigger_Handler.RUN_UPDATE = false;

        // initialize variable required for logic
        List<Publish_PriceBook__c> pricebookUpdateList = new List<Publish_PriceBook__c>();
        List<Publish_PriceBook_Entry__c> pricebookEntryUpdateList = new List<Publish_PriceBook_Entry__c>();
    
        // get program pricebook Id
        Set<Id> stdPricebookIds = new Map<Id, Pricebook2>(
                [select Id from Pricebook2 where Program__c = :programId]
            ).keySet();


        // get program pricebook entry IDs
        Set<Id> stdPricebookEntryIds = new Map<Id, PricebookEntry>(
                [select Id from PricebookEntry where Pricebook2Id in :stdPricebookIds]
            ).keySet(); 

        Set<Id> pricebookIds = new Set<Id>();

        // get Publish price book records
        for(Publish_PriceBook__c ppb : [select id, Name, Publish_Status__c, 
                                Outbound_Message_Type__c, Active_PriceBook__c 
                                from Publish_PriceBook__c 
                                Where Program__c = :programId]) {


            // set new values
            ppb.Publish_Status__c = 'Deactivated';
            ppb.Outbound_Message_Type__c = 'Update Pricebook';
            pricebookUpdateList.add(ppb); 
            pricebookIds.add(ppb.Id);
        }  

        Map<Decimal, Filter_Criteria__c> filterNumberToFC = getFilterNumberToFCMap(programId);

        Map<String, Decimal> productCodesCustomList = new Map<String, Decimal>();

        Map<Decimal, Set<String>> filterProductCodes = new Map<Decimal, Set<String>>();

        Set<String> fixedProductCodes = new Set<String>();
        
        /*
        // get Publish price book entry records
        for(Publish_PriceBook_Entry__c ppbe : [select Id, Name, Publish_Status__c, 
                                    Outbound_Message_Type__c, Expiration_Date__c,
                                    Active__c,
                                    Filter_Number__c,
                                    Style_Number__c,
                                    Discount__c
                                from Publish_PriceBook_Entry__c 
                                where Publish_PriceBook__c in :pricebookIds 
                                and (Publish_Status__c = 'Waiting' or Publish_Status__c = 'Published')
                                and Filter_Number__c != null
                                and Filter_Number__c in :filterNumberToFC.keySet()])
        {
		*/
        /*
        String waiting = 'Waiting';
        String published = 'Published';
        
        
        String query = 'SELECT Id, Name, Publish_Status__c, Outbound_Message_Type__c, Expiration_Date__c, Active__c, Filter_Number__c, Style_Number__c, Discount__c';
        query += ' FROM Publish_PriceBook_Entry__c';
        query += ' WHERE Publish_PriceBook__c in :pricebookIds';
        query += ' AND (Publish_Status__c = :waiting OR Publish_Status__c = :published)';        
        if (!filterNumberToFC.isEmpty()){                                
            Set<Decimal> keySet = filterNumberToFC.keySet();
            query += ' AND Filter_Number__c != null';
            query += ' AND Filter_Number__c in : keySet';
        } */
        
         // get Publish price book entry records
        for(Publish_PriceBook_Entry__c ppbe : [select Id, Name, Publish_Status__c, 
                                    Outbound_Message_Type__c, Expiration_Date__c,
                                    Active__c,
                                    Filter_Number__c,
                                    Style_Number__c,
                                    Discount__c
                                from Publish_PriceBook_Entry__c 
                                where Publish_PriceBook__c in :pricebookIds 
                                and (Publish_Status__c = 'Waiting' or Publish_Status__c = 'Published')]){
            
            If(filterNumberToFC.containsKey(PPBE.Filter_Number__c)) {                        
                if(ppbe.Filter_Number__c == 0) {
                    productCodesCustomList.put(ppbe.Style_Number__c, ppbe.Discount__c);
                } else {
                    Set<String> productCodes = filterProductCodes.get(ppbe.Filter_Number__c);
    
                    if(productCodes == null) {
                        productCodes = new Set<String>();
    
                        filterProductCodes.put(ppbe.Filter_Number__c, productCodes);
                    }
    
                    productCodes.add(ppbe.Style_Number__c);
                }
            }
            // set new values
            ppbe.Publish_Status__c = 'Deactivated';
            ppbe.Outbound_Message_Type__c = 'Update Pricebook Entry';
            ppbe.Expiration_Date__c = Date.today();
            ppbe.Active__c = false;
            pricebookEntryUpdateList.add(ppbe); 
        }

        for(Filter_Criteria__c fc : filterNumberToFC.values()) {
            if(fc.Filter_Number__c == 0) {
                fc.Product_Code__c = JSON.serialize(productCodesCustomList) + '-FPC-' + JSON.serialize(fixedProductCodes);
            } else {
                Set<String> productCodes = filterProductCodes.get(fc.Filter_Number__c);

                if(productCodes == null) continue;

                fc.Product_Code__c = JSON.serialize(productCodes) + '-FPC-' + JSON.serialize(fixedProductCodes);
            }
        }

        update filterNumberToFC.values();

        // update publish price book records
        if(!pricebookUpdateList.isEmpty()) update pricebookUpdateList;

        // update publish price book entry records
        if(!pricebookEntryUpdateList.isEmpty()) updateRecords(pricebookEntryUpdateList);

        // turn flag ON
        RWS_PriceBookTrigger_Handler.RUN_UPDATE = true;
    }


    private static Map<Decimal, Filter_Criteria__c> getFilterNumberToFCMap(Id programId) {
        Map<Decimal, Filter_Criteria__c> filterNumberToFC = new Map<Decimal, Filter_Criteria__c>(); 
        for(Filter_Criteria__c fc : [select Id, Discount__c, Product_Code__c, Filter_Number__c,
                                        Program__r.Active__c, Program__r.Publish_Status__c
                                    from Filter_Criteria__c 
                                    Where Program__c = :programId]) {

            filterNumberToFC.put(fc.Filter_Number__c, fc);
        }

        return filterNumberToFC;
    }

    private static Boolean isProgramProcessingCompleted(Id programId) {
        return [select Processing_Status__c from Program__c where Id = :programId limit 1].Processing_Status__c == 'Completed';
    }
    // update publish price book entry records
    // try five time if an attempt is failed due to ROW locking
    private static void updateRecords(List<Publish_PriceBook_Entry__c> pbes) {
        Integer attempts = 5;
        while(attempts > 0){
            try {
                attempts --; 
                update pbes; 
                attempts = 0;
            } catch (System.DmlException dmlEx) {
                if (!dmlEx.getMessage().contains('UNABLE_TO_LOCK_ROW')) {  attempts = 0;  }

                if(attempts == 0) { throw dmlEx; }
            } // end of catch
        } // end of while retry loop
    }
}