force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Display__c.field-meta.xml
<CustomField>
    <fullName>Filter_Display__c</fullName>
    <description>Field used to display filter criteria details on review products visualforce page.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Field used to display filter criteria details on review products visualforce page.</inlineHelpText>
    <label>Filter Display</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</description>
    <inlineHelpText>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</inlineHelpText>
    <label>Product Code</label>
    <length>25000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Results_Count__c.field-meta.xml
<CustomField>
    <fullName>Results_Count__c</fullName>
    <label>Results Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Program_Scheduler__c/Program_Scheduler__c.object-meta.xml
<CustomObject>
    <label>Program Scheduler</label>
    <nameField>
        <displayFormat>PS-{0000000}</displayFormat>
        <label>Program Scheduler Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Scheduler__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the record has been processed</description>
    <inlineHelpText>Identify if the record has been processed</inlineHelpText>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Scheduler__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identify the Program that is related to the Scheduler record.</description>
    <inlineHelpText>Identify the Program that is related to the Scheduler record.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Scheduler</relationshipLabel>
    <relationshipName>Program_Scheduler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Scheduler__c/fields/Program_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Template_Name__c</fullName>
    <description>Identify the Program Template name (if selecteD)</description>
    <inlineHelpText>Identify the Program Template name (if selecteD)</inlineHelpText>
    <label>Program Template Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book Entry. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book Entry. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Fixed_Price__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked (TRUE) it indicates the price for this product is fixed and will not be impacted by the price update batch job which runs for all Programs where Auto Update Prices = TRUE. Only applies to price book entries created for programs.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked (TRUE) it indicates the price for this product is fixed and will not be impacted by the price update batch job which runs for all Programs where Auto Update Prices = TRUE. Only applies to price book entries created for programs.</inlineHelpText>
    <label>Fixed Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number__c.field-meta.xml
<CustomField>
    <fullName>Style_Number__c</fullName>
    <description>Style Number (field is used to match against Product standard object). Used for outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number (field is used to match against Product standard object). Used for outbound messaging.</inlineHelpText>
    <label>Style Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_UseTemplate_Util.cls
/********************************************************************************
*   PURPOSE : Utility class to support program template selection/creation
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   			M360			        Initial version
*	03/08/18	Brandon Willard(M360)   Modified for RWCP-3449
********************************************************************************/
public with sharing class RWS_UseTemplate_Util {
	public static List<Filter_Criteria__c> newCriterias;
	public static Program_Scheduler__c scheduleProgram(Id programId, List<Filter_Criteria__c> criterias, List<Publish_PriceBook_Entry__c> ppbes, Boolean insertFCs) {

        Map<String, Decimal> customProductCodes = new Map<String, Decimal>();
        Set<String> customFPCs = new Set<String>();
        Map<Integer, Set<String>> productCodesMap = new Map<Integer, Set<String>>();
        Map<Integer, Set<String>> fpcsMap = new Map<Integer, Set<String>>();

        for(Publish_PriceBook_Entry__c ppbe : ppbes) {
          System.debug('ppbe: ' + ppbe);
          if(ppbe.Filter_Number__c == null) ppbe.Filter_Number__c = 0;

          if(ppbe.Discount__c == null) ppbe.Discount__c = 0;

          Integer filterNumber = ppbe.Filter_Number__c.intValue();

          if(filterNumber == 0) {
            customProductCodes.put(ppbe.Style_Number__c, ppbe.Discount__c);

            if(ppbe.Fixed_Price__c) customFPCs.add(ppbe.Style_Number__c);

          } else {
            Set<String> productCodes = productCodesMap.get(filterNumber);
            Set<String> fpcs = fpcsMap.get(filterNumber);

            if(productCodes == null) {
              productCodes = new Set<String>();
              fpcs = new Set<String>();

              productCodesMap.put(filterNumber, productCodes);
              fpcsMap.put(filterNumber, fpcs);
            }

            productCodes.add(ppbe.Style_Number__c);


            if(ppbe.Fixed_Price__c) fpcs.add(ppbe.Style_Number__c);
          }
        }

        newCriterias = new List<Filter_Criteria__c>();
        Boolean hasCustomList = !customProductCodes.isEmpty();
        Boolean foundCustomList = false;

        System.debug('productCodesMap: ' + productCodesMap);
        System.debug('fpcsMap: ' + fpcsMap);
        System.debug('customProductCodes: ' + customProductCodes);
        System.debug('customFPCs: ' + customFPCs);

        for(Filter_Criteria__c fc : criterias) {
        	System.debug('fc: ' + fc);
            if(fc.Filter_Number__c == null) fc.Filter_Number__c = 0;

            Integer filterNumber = fc.Filter_Number__c.intValue();

            if(fc.Filter_Number__c == 0) {
              foundCustomList = true;
              fc.Product_Code__c = JSON.serialize(customProductCodes) + '-FPC-' + JSON.serialize(customFPCs);
            } else {

              Set<String> productCodes = productCodesMap.get(filterNumber);
              Set<String> fpcs = fpcsMap.get(filterNumber);

              if(productCodes == null) {
                productCodes = new Set<String>();
                fpcs = new Set<String>();
              }
              fc.Product_Code__c = JSON.serialize(productCodes) + '-FPC-' + JSON.serialize(fpcs);
            }

            Filter_Criteria__c criteria = fc.clone(false, true);

            criteria.Program__c = programId;

            newCriterias.add(criteria);
        }

        System.debug(hasCustomList + ' - ' + foundCustomList);

        if(hasCustomList && !foundCustomList) {
          Filter_Criteria__c fc = new Filter_Criteria__c();

          fc.Program__c = programId;
          fc.Filter_Number__c = 0;
          fc.Filter_Display__c = 'CUSTOM LIST';
          fc.Product_Code__c = JSON.serialize(customProductCodes) + '-FPC-' + JSON.serialize(customFPCs);
          fc.Results_Count__c = customProductCodes.size();
          fc.Discount__c = 0;

          newCriterias.add(fc);
        }


		if(insertFCs) insert newCriterias;

        return new Program_Scheduler__c(Program__c = programId, 
          Program_Template_Name__c = null, 
          Processed__c = false);
	}
}