force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_BE_Details__c.field-meta.xml
<CustomField>
    <fullName>Filter_BE_Details__c</fullName>
    <description>Field used to display filter criteria details on review products visualforce page.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Field used to display filter criteria details on review products visualforce page.</inlineHelpText>
    <label>Filter BE Details</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</description>
    <inlineHelpText>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</inlineHelpText>
    <label>Product Code</label>
    <length>25000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Results_Count__c.field-meta.xml
<CustomField>
    <fullName>Results_Count__c</fullName>
    <label>Results Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Feature__c/fields/Filter_Logic__c.field-meta.xml
<CustomField>
    <fullName>Filter_Logic__c</fullName>
    <description>The filter logic for an IA Feature.  (AND, OR) Logic for each filter and how they related to one another when selecting multiple filters using the Product Selection Visualforce Page.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The filter logic for an IA Feature.  (AND, OR) Logic for each filter and how they related to one another when selecting multiple filters using the Product Selection Visualforce Page.</inlineHelpText>
    <label>Filter Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/Parent_IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>Parent_IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to associate an IA Feature with a Parent IA Feature.  Lookup within the same IA Feature object.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to associate an IA Feature with a Parent IA Feature.  Lookup within the same IA Feature object.</inlineHelpText>
    <label>Red Wing Parent ID</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>IA Feature</relationshipLabel>
    <relationshipName>IA_Feature</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>External Id for MuleSoft.
Field Type: IA
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id for MuleSoft.</inlineHelpText>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Used in apex to match to the style number unique id on the Product object.  Updated via apex.
Field Type: IA
Integrated: N</description>
    <externalId>true</externalId>
    <inlineHelpText>Used in apex to match to the style number unique id on the Product object. Updated via apex.</inlineHelpText>
    <label>Style Number Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/HasPricebook__c.field-meta.xml
<CustomField>
    <fullName>HasPricebook__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by APEX to flag Programs that have an active custom Pricebook.</description>
    <inlineHelpText>This field is used by APEX to flag Programs that have an active custom Pricebook.</inlineHelpText>
    <label>HasPricebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book Entry. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book Entry. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Price_Level__c.field-meta.xml
<CustomField>
    <fullName>Price_Level__c</fullName>
    <description>Identify the Price Level of the related Price Book Entry record. Used for outbound messaging.</description>
    <inlineHelpText>Identify the Price Level of the related Price Book Entry record.</inlineHelpText>
    <label>Price Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_RWS_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_RWS_ID__c</fullName>
    <description>Product RWS ID from the Product standard object.  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Product RWS ID from the Product standard object.  Used in outbound messaging.</inlineHelpText>
    <label>Product RWS ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Name__c.field-meta.xml
<CustomField>
    <fullName>Style_Name__c</fullName>
    <description>Style Name</description>
    <label>Style Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number__c.field-meta.xml
<CustomField>
    <fullName>Style_Number__c</fullName>
    <description>Style Number (field is used to match against Product standard object). Used for outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number (field is used to match against Product standard object). Used for outbound messaging.</inlineHelpText>
    <label>Style Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_Id__c</fullName>
    <description>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.</inlineHelpText>
    <label>Style Number Unique Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_InsertNewProducts_BatchHandler.cls
/********************************************************************************
*   PURPOSE : Handler class for RWS_InsertNewProducts_Batch
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   12/08/2016  Kotapati Keerthi/M360   Initial version
*   03/08/2018  Brandon Willard/M360    Modified for RWCP-3449
********************************************************************************/

public class RWS_InsertNewProducts_BatchHandler {
    
    public static void createProducts (Id programId) {

        // retrieve program with Pricebook, filter criterias (ordered by discount and records 
        // with NULL discount appearing at the end)
        Program__c program = [
                    select Id, CurrencyIsoCode, HasPricebook__c,
                    (select Id, CurrencyIsoCode, Program__c from Publish_PriceBooks__r),
                    (select IA_Feature__r.Name, 
                            Discount__c,
                            Filter_Number__c,
                            IA_Feature__r.Filter_Logic__c,
                            Filter_BE_Details__c,
                            Product_Code__c,
                            Results_Count__c
                        from Filter_Criteria__r
                        where Filter_Number__c != null and Filter_Number__c > 0 
                        order by Discount__c desc NULLS LAST)

                    from Program__c where id = :programId limit 1];
        

        // if no filter criterias found, exit
        if(program.Filter_Criteria__r == null || program.Filter_Criteria__r.isEmpty()) return;

        // if no pricebook found, exit
        if(program.Publish_PriceBooks__r == null 
                || program.Publish_PriceBooks__r.isEmpty() 
                || program.Publish_PriceBooks__r.size() > 1) return;

        // local variable for pricebook for easy reference in code
        Publish_PriceBook__c pbook = program.Publish_PriceBooks__r[0];
        
        // map that holds all style ids -> discount. 
        // Used to update discount on the pricebook entry and publish pricebook entry records
        Map<Id, Decimal> allStylesWithDiscount = new Map<Id, Decimal>();

        // map that holds all style ids -> filter number
        // Used to update discount on the pricebook entry records
        Map<Id, Decimal> allStylesWithFilterNumber = new Map<Id, Decimal>();

        // iterate over filter criteria and find highest discount for the product style and filter number
        for(Filter_Criteria__c fc : program.Filter_Criteria__r) {

            // if there no filter details on filter criteria, move to next record
            if(String.isBlank(fc.Filter_BE_Details__c)) continue;

            // if discount is not set, assume it as ZERO
            if(fc.Discount__c == null) fc.Discount__c = 0;

            // get styles that falls under the filter criteria
            Set<Id> filterStyles = RWS_FilterCriteria_Util.getProductStylesForFilter(fc);

            // if not style found, move to next filter criteria
            if(filterStyles.isEmpty()) continue;

            // iterate over product style ids 
            for(Id s : filterStyles) {
                // process the product style if already doesn't exists in the maps
                if(!allStylesWithDiscount.containsKey(s)) {

                    // add discount for the product style
                    allStylesWithDiscount.put(s, fc.Discount__c);

                    // add filter number for the product style
                    allStylesWithFilterNumber.put(s, fc.Filter_Number__c);
                }
            }
        }

        // get standard price book Id
        Id stdpbid;
        if(Test.isRunningTest()) // for test code
            stdpbid = Test.getStandardPricebookId();
        else // for actual run
            stdpbid = [select id, name from Pricebook2 where isStandard = true limit 1].id;


        // get active products related to all product styles relevant to all filter criterias
        List<Product2> products = [select Id from Product2 
                                        where Product_Style__c in :allStylesWithDiscount.keySet()
                                        and IsActive = true];
       
        // get products that are already there in Program Pricebook
        Set<String> existingProductIds = new Set<String>();

        for(Publish_PriceBook_Entry__c pd : [select Id, Style_Number__c, Product_ID__c
                    from Publish_PriceBook_Entry__c 
                    where Publish_PriceBook__c = :pbook.id]) {

            existingProductIds.add(pd.Product_ID__c);
        }


        // get active MSRP records using Standard Pricebook and Products relevant to all filter criterias
        List<PricebookEntry> product_lst = [select Id, CurrencyISOCode, 
                     Unitprice, Product2Id, Product2.Product_Style__c, Product2.Style_Number_Unique_ID__c, Product2.ProductCode, Product2.Name, 
                     ProductCode, Product2.RWS_ID__c, Product2.SKU__c, Product2.UPC__c, Price_Level__c
                 from PricebookEntry
                 where Pricebook2id = :stdpbid
                 and Product2Id in :products
                   and IsActive = true ];


        // List used to insert new PriceBookEntry records
        List<Publish_PriceBook_Entry__c> insertPublishPriceBookEntry_lst = new list<Publish_PriceBook_Entry__c>();

        Set<Id> productIds = new Set<Id>();        
        Set<String> prodCodeSet = new Set<String>(); //added by BW - RWCP-3600

        // iterate over MSRP records, find any missing products under program, 
        // and create pricebook entry recors for those missing products
        for(PricebookEntry pd : product_lst ) {


            // if MSRP currency is different than program pricebook currency, move to the next records
            if(pd.CurrencyIsoCode != pbook.CurrencyIsoCode) continue;

            // if product already exists under the program, move to next record
            if(existingProductIds.contains(pd.Product2Id)) continue;

            // keep track of new products added to the program
            productIds.add(pd.Product2Id);
            prodCodeSet.add(pd.Product2.ProductCode); //added by BW - RWCP-3600

            // initialize PricebookEntry object
            Publish_PriceBook_Entry__c ppbEntry = new Publish_PriceBook_Entry__c();
            ppbEntry.Product_Id__c = pd.Product2Id;
            ppbEntry.Publish_PriceBook__c = pbook.id;
            ppbEntry.Active__c = true;
            ppbEntry.CurrencyIsoCode = pbook.CurrencyIsoCode;
            ppbEntry.Style_Name__c = pd.Product2.Name;
            ppbEntry.Style_Number__c = pd.Product2.ProductCode;
            ppbEntry.Style_Number_Unique_Id__c = pd.Product2.Style_Number_Unique_ID__c;
            ppbEntry.Product_RWS_ID__c = pd.Product2.RWS_ID__c;
            ppbEntry.Product_SKU__c = pd.Product2.SKU__c;
            ppbEntry.Product_UPC__c = pd.Product2.UPC__c;
            ppbEntry.MSRP__c = pd.UnitPrice;
            ppbEntry.Price_Level__c = pd.Price_Level__c;    
            
            // assume max discount is zero for now
            Decimal maxDiscount = 0;

            Decimal discount = allStylesWithDiscount.get(pd.Product2.Product_Style__c );

            Decimal filterNumber = allStylesWithFilterNumber.get(pd.Product2.Product_Style__c);

            // if discount is found for the product style and is greater than zero, consider it as the maximum discount
            if(discount != null && discount > 0) {
                maxDiscount = discount;
            }

            // set discount
            ppbEntry.Discount__c = maxDiscount;

            // if filter is not found in allStylesWithFilterNumber, add that products to custom list
            if(filterNumber == null) filterNumber = 1;

            // set filter number
            ppbEntry.Filter_Number__c = filterNumber;

            Double stdUnitPrice = pd.UnitPrice;

            // set program product unit price using unit price of MSRP and discount
            ppbEntry.List_Price__c = stdUnitPrice == 0 ? 0 : (stdUnitPrice - (ppbEntry.Discount__c / 100) * stdUnitPrice);

            // add variable to the list
            insertPublishPriceBookEntry_lst.add(ppbEntry);

            // insert 200 records at a time to avoid row locking issue
            if(insertPublishPriceBookEntry_lst.size() == 200) {
                RWS_PriceBookEntry_Util.insertUpdateRecords(insertPublishPriceBookEntry_lst, true);

                insertPublishPriceBookEntry_lst = new List<Publish_PriceBook_Entry__c>();
            }

        }

        // if new records were initialized in the code above
        if(!insertPublishPriceBookEntry_lst.isEmpty()) {

            // insert those records
            RWS_PriceBookEntry_Util.insertUpdateRecords(insertPublishPriceBookEntry_lst, true); 
            
            // create publish pricebook records for those records
            //RWS_PriceBookEntry_Util.createPublishPriceBookEntries(pbook.Id, productIds);

            // find any products under programs that are not added from this batch job (productIds variable)
            // and belong to program filter criterias
            // and are no longer active (Product2.Parent_Product_Style__c set)
            List<Publish_PriceBook_Entry__c> entriesToDelete = [select Id, Product_Id__c, Style_Number__c from Publish_PriceBook_Entry__c where Publish_PriceBook__c in :program.Publish_PriceBooks__r 
                   // and Product2.Parent_Product_Style__c in :allStylesWithDiscount.keySet()
                   // and Style_Number__c not in :prodCodeSet
                   ];

            prodCodeSet.clear();
            for(Publish_PriceBook_Entry__c ppbe : entriesToDelete) {
                prodCodeSet.add(ppbe.Product_Id__c);
            }
            
            Set<String> prodCodes = new Set<String>(); 
            for (Product2 prod : [SELECT Id, Name, Category__c, ProductCode FROM Product2 WHERE Parent_Product_Style__c in :allStylesWithDiscount.keySet() AND Id IN :prodCodeSet]){
                prodCodes.add(prod.Id);
            }
            
            for(Integer i = 0; i < entriesToDelete.size(); i++){
                if (!prodCodes.contains(entriesToDelete[i].Product_Id__c)){
                    entriesToDelete.remove(i);
                    i--;    
                }
            }

            // deactivate publish pricebook entry records so the outbound message is sent to update extermal system
            if(!entriesToDelete.isEmpty())  RWS_PriceBookEntry_Util.deactivatePublicPriceBookEntries(entriesToDelete);
        }
    }
}