force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Display__c.field-meta.xml
<CustomField>
    <fullName>Filter_Display__c</fullName>
    <description>Field used to display filter criteria details on review products visualforce page.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Field used to display filter criteria details on review products visualforce page.</inlineHelpText>
    <label>Filter Display</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</description>
    <inlineHelpText>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</inlineHelpText>
    <label>Product Code</label>
    <length>25000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Results_Count__c.field-meta.xml
<CustomField>
    <fullName>Results_Count__c</fullName>
    <label>Results Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Feature__c/fields/Filter_Display__c.field-meta.xml
<CustomField>
    <fullName>Filter_Display__c</fullName>
    <description>If filter display is set to expanded it will be open on page load of Product Selection VF
If filter display is set to collapsed it will be closed on page load
NOTE:  Only applies to parent / header IA features.  Where &quot;selectable&quot; equals False.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If filter display is set to expanded it will be open on page load of Product Selection VF
If filter display is set to collapsed it will be closed on page load
NOTE:  Only applies to parent / header IA features.  Where &quot;selectable&quot; equals False.</inlineHelpText>
    <label>Filter Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expanded</fullName>
            </value>
            <value>
                <fullName>Collapsed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <description>The Processing status determine the status of the related Product record creation for this program. Program Activation is dependent on the Program processing.</description>
    <inlineHelpText>The Processing status determine the status of the related Product record creation for this program. Program Activation is dependent on the Program processing.</inlineHelpText>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/classes/RWS_ProgramProducts_Queue.cls
public with sharing class RWS_ProgramProducts_Queue  implements Queueable {
	private Id programId;
	private Boolean createTemplate;
	private String programName;
	public RWS_ProgramProducts_Queue(Id programId, Boolean createTemplate, String programName) {
		this.programId = programId;
		this.createTemplate = createTemplate;
		this.programName = programName;
    }

    public class Product {
    	public Decimal filterNumber {get; set;}
    	public Decimal discount {get; set;}
    	public Boolean isFixedPrice {get; set;}

    	public Product(Decimal f, Decimal d, Boolean fp) {
    		filterNumber = f;
    		discount = d;
    		isFixedPrice = fp;
    	}
    }

    public void execute(QueueableContext context) {
    	List<Pricebook2> pb = [select Id
                                from Pricebook2 
                                where  Program__c != null 
                                and Program__c = :programId 
                                and IsStandard = false 
                            limit 1];

        List<Filter_Criteria__c> fcs = [select Results_Count__c,
                    Filter_Number__c,
                    Discount__c,
                    Filter_Display__c,
                    Product_Code__c
                from Filter_Criteria__c
                where Program__c = :this.programId
                and IA_Feature__c = null
                and Filter_Number__c != null
                Order by Filter_Number__c desc];


        Map<String, Product> productsMap = new Map<String, Product>();

        for(Filter_Criteria__c fc : fcs) {

        	if( String.isBlank(fc.Product_Code__c) ) continue;

            if(fc.Discount__c == null) fc.Discount__c = 0;

            String codesSet = fc.Product_Code__c.split('-FPC-')[0];
            String fpcSet = fc.Product_Code__c.split('-FPC-')[1];

            Set<String> fpCodes =  (Set<String>) JSON.deserialize(fpcSet, Set<String>.class);

            if(fc.Filter_Number__c > 0 ) {
                Set<String> productCodes = (Set<String>) JSON.deserialize(codesSet, Set<String>.class);
                

                for(String code : productCodes) {
                	Boolean isFixedPrice = fpCodes.contains(code);

                	Product p = productsMap.get(code);

                	if(p == null) {
                		p = new Product(fc.Filter_Number__c, fc.Discount__c, isFixedPrice);
                		productsMap.put(code, p);
                	}

                	if(fc.Discount__c > p.discount) {
                		p.discount = fc.Discount__c;
                		p.filterNumber = fc.Filter_Number__c;
                		p.isFixedPrice = isFixedPrice;
                	}
                }
                
            } else {
                Map<String, Decimal> productCodes = (Map<String, Decimal>) JSON.deserialize(codesSet, Map<String, Decimal>.class);

                for(String code : productCodes.keySet()) {
                	Decimal discount = productCodes.get(code);

                	if(discount == null) discount = 0;

                	Boolean isFixedPrice = fpCodes.contains(code);

                	Product p = productsMap.get(code);

                	if(p == null) {
                		p = new Product(0, discount, isFixedPrice);
                		productsMap.put(code, p);
                	}

                	if(discount > p.discount) {
                		p.discount = discount;
                		p.filterNumber = 0;
                		p.isFixedPrice = isFixedPrice;
                	}
                }
            }
        }


        Id stdPriceBookId;
        if(Test.isRunningTest()) {
            stdPriceBookId = Test.getStandardPricebookId();
        }
        else if (stdPriceBookId == null) {
            stdPriceBookId    = [select id, name from Pricebook2 where isStandard = true limit 1].id;
        }

        List<PricebookEntry> stdPbes = [SELECT UnitPrice,
                                            ProductCode,
                                            Product2Id
                                        FROM PricebookEntry 
                                        WHERE Pricebook2Id = :stdPriceBookId 
                                        AND IsActive = true 
                                        AND ProductCode in :productsMap.keySet()
                                        AND Product2.Product_Style__c != null
                                        AND Product2.IsActive = true
                                        AND CurrencyISOCode = :UserInfo.getDefaultCurrency()];


        Map<Id, PriceBookEntry> pricebookentry_Map = new Map<Id,PriceBookEntry>();
    	Set<Id> productIds = new Set<Id>();
    	Set<String> productCodesProcessed = new Set<String>();

        for(PricebookEntry spbe : stdPbes) {
        	if(productCodesProcessed.contains(spbe.ProductCode)) continue;

        	Product p = productsMap.get(spbe.ProductCode);

        	if(p == null) continue;

        	productCodesProcessed.add(spbe.ProductCode);

        	PriceBookEntry pbe = new PriceBookEntry();
            pbe.Pricebook2id = pb[0].Id;
            pbe.IsActive = true;
            pbe.Product2Id = spbe.Product2Id;
            pbe.Discount__c = p.discount;

             // get standard price
        	Double stdUnitPrice = spbe.UnitPrice;

        	if(stdUnitPrice == null) stdUnitPrice = 0;

        	// set on program pricebook entry
        	pbe.UnitPrice = stdUnitPrice == 0 ? 0 : (stdUnitPrice - (pbe.Discount__c / 100) * stdUnitPrice).setScale(2);

            
            pbe.Fixed_Price__c = p.isFixedPrice;
            pbe.Filter_Number__c = p.filterNumber;

            pricebookentry_Map.put(pbe.Product2Id, pbe);
            productIds.add(pbe.Product2Id);
        }


        if(!pricebookentry_Map.isEmpty()) {

            //List<Product2> prods = [select Id from Product2 where Id in :productIds for update];

            // As upsert for pricebookentry is not possible, the below method is followed.
            List<PricebookEntry> pbe_check_Lst 
                = [select Id, Product2Id, Unitprice, Fixed_Price__c, Discount__c, IsActive
                        From PricebookEntry 
                        Where Pricebook2Id = :pb[0].Id 
                        and Product2Id in :pricebookentry_Map.keyset()
                        AND Product2.IsActive = true
                        AND CurrencyISOCode = :UserInfo.getDefaultCurrency()];
            
            List<pricebookentry> pricebookentry_updatelst = new List<pricebookentry>();
            if(!pbe_check_Lst.isEmpty()) {
                for(pricebookentry p : pbe_check_Lst ) {

                	PriceBookEntry otherPbe = pricebookentry_Map.get(p.Product2Id);

                    if(p.Discount__c > otherPbe.discount__c) {
                        pricebookentry_Map.remove(p.Product2Id);
                        continue;
                    }

                    PriceBookEntry pbe = new PriceBookEntry();
                    pbe.id = p.Id;
                    pbe.unitprice = otherPbe.Unitprice;
                    pbe.discount__c = otherPbe.Discount__c;
                    pbe.Fixed_Price__c = otherPbe.Fixed_Price__c;
                    pbe.Filter_Number__c = otherPbe.Filter_Number__c;

                    pbe.IsActive = true;

                    pricebookentry_updatelst.add(pbe);

                    /*                    
                    if(pricebookentry_updatelst.size() == 200) {
                        
                    	insertUpdateRecords(pricebookentry_updatelst, false);

                    	pricebookentry_updatelst = new List<PricebookEntry>();
                    }
                    */

                    pricebookentry_Map.remove(p.Product2Id);
                }
            }

            if(!pricebookentry_updatelst.isEmpty()) {
                insertUpdateRecords(pricebookentry_updatelst, false);
                //update pricebookentry_updatelst;
            }

            List<PricebookEntry> pricebookentry_insertlst = new List<PricebookEntry>();

            for(PricebookEntry p : pricebookentry_Map.values() ) {
            	pricebookentry_insertlst.add(p);

                /*
                if(pricebookentry_insertlst.size() == 200) {
                	insertUpdateRecords(pricebookentry_insertlst, true);

                	pricebookentry_insertlst = new List<PricebookEntry>();
                }
                */
            }

            if(!pricebookentry_insertlst.isEmpty()) {
                insertUpdateRecords(pricebookentry_insertlst, true);
                //insert pricebookentry_insertlst;
            }

            RWS_PriceBookEntry_Util.createPublishPriceBookEntries(pb[0].Id, productIds);
        }

        Program__c existingProgram = new Program__c(Id = programId,
                    Processing_Status__c = 'Completed'
        );   

        update existingProgram;

        for(Filter_Criteria__c fc : fcs) {
        	fc.Product_Code__c = null;
        }

        update fcs;

        if(createTemplate && !Test.isRunningTest()) {
        	System.enqueueJob(new RWS_ProgramTemplate_Queue(programId, programName));
        }
    }

    private void insertUpdateRecords(List<PricebookEntry> pbes, Boolean insertRecords) {
        Integer attempts = 5;
        while(attempts > 0){
            try {
                attempts --; 
                if(insertRecords) insert pbes; 
                if(!insertRecords) update pbes; 
                attempts = 0;
            } catch (System.DmlException dmlEx) {
                if (!dmlEx.getMessage().contains('UNABLE_TO_LOCK_ROW')) {  attempts = 0;  }

                if(attempts == 0) { throw dmlEx; }
            } // end of catch
        } // end of while retry loop
    }
}