force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_BE_Details__c.field-meta.xml
<CustomField>
    <fullName>Filter_BE_Details__c</fullName>
    <description>Field used to display filter criteria details on review products visualforce page.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Field used to display filter criteria details on review products visualforce page.</inlineHelpText>
    <label>Filter BE Details</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</description>
    <inlineHelpText>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</inlineHelpText>
    <label>Product Code</label>
    <length>25000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Results_Count__c.field-meta.xml
<CustomField>
    <fullName>Results_Count__c</fullName>
    <label>Results Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Feature__c/fields/Filter_Logic__c.field-meta.xml
<CustomField>
    <fullName>Filter_Logic__c</fullName>
    <description>The filter logic for an IA Feature.  (AND, OR) Logic for each filter and how they related to one another when selecting multiple filters using the Product Selection Visualforce Page.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The filter logic for an IA Feature.  (AND, OR) Logic for each filter and how they related to one another when selecting multiple filters using the Product Selection Visualforce Page.</inlineHelpText>
    <label>Filter Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/Parent_IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>Parent_IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to associate an IA Feature with a Parent IA Feature.  Lookup within the same IA Feature object.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to associate an IA Feature with a Parent IA Feature.  Lookup within the same IA Feature object.</inlineHelpText>
    <label>Red Wing Parent ID</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>IA Feature</relationshipLabel>
    <relationshipName>IA_Feature</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>External Id for MuleSoft.
Field Type: IA
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id for MuleSoft.</inlineHelpText>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Used in apex to match to the style number unique id on the Product object.  Updated via apex.
Field Type: IA
Integrated: N</description>
    <externalId>true</externalId>
    <inlineHelpText>Used in apex to match to the style number unique id on the Product object. Updated via apex.</inlineHelpText>
    <label>Style Number Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/Product_Style_Features__c.object-meta.xml
<CustomObject>
    <description>Junction object which manages the many to many relationship between unique styles (Product Style Object) and the Features object. Records are created / updated via apex. Does not need to be maintained via integration. 
Object Type: IA 
Integrated: N</description>
    <label>Product Style Features</label>
    <nameField>
        <displayFormat>PSF-{000000}</displayFormat>
        <label>Product Style Feature #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Style Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style_Features__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Product Style object. Used to associate a Product Style to a Feature. Maintained by apex. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup field to the Product Style object. Used to associate a Product Style to a Feature.</inlineHelpText>
    <label>Product Style</label>
    <referenceTo>Product_Style__c</referenceTo>
    <relationshipLabel>Product Style Features</relationshipLabel>
    <relationshipName>Product_Style_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Reference related Product Style Unique Style Id</description>
    <formula>Product_Style__r.Style_Number_Unique_ID__c</formula>
    <label>Style Number Unique ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Auto_Add_Products__c.field-meta.xml
<CustomField>
    <fullName>Auto_Add_Products__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If TRUE your price book is automatically updated with new products that meet stored filter criteria. EXAMPLE: a program for Red Wing &amp; Steel Toe and a new product product is manufactured that is Red Wing &amp; Steel Toe it will be added to your price book.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If TRUE your price book is automatically updated with new products that meet stored filter criteria. EXAMPLE: a program for Red Wing &amp; Steel Toe and a new product product is manufactured that is Red Wing &amp; Steel Toe it will be added to your price book.</inlineHelpText>
    <label>Auto Add Products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/HasPricebook__c.field-meta.xml
<CustomField>
    <fullName>HasPricebook__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by APEX to flag Programs that have an active custom Pricebook.</description>
    <inlineHelpText>This field is used by APEX to flag Programs that have an active custom Pricebook.</inlineHelpText>
    <label>HasPricebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book Entry. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book Entry. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_Id__c</fullName>
    <description>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.</inlineHelpText>
    <label>Style Number Unique Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_InsertPPBE_Batch.cls
global class RWS_InsertPPBE_Batch implements Database.Batchable<sObject>, Schedulable {
    
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new RWS_InsertPPBE_Batch(), 1);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Integer count = [select Id from Product2 where LastModifiedDate >= YESTERDAY 
                        and IsActive = true limit 1].size();

        Integer featureCount = [select Id from Product_Style_Features__c where LastModifiedDate >= YESTERDAY limit 1].size();

        return Database.getQueryLocator('Select Id From Program__c where Auto_Add_Products__c = true '
                                        + (featureCount == 0 && count == 0 && !Test.isRunningTest() ?  ' and Id = null ' : '') );
    }
    
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Id> programId= new List<Id>();
        //convert scope to actual segments
        for (sObject p : scope) {
            Program__c program = (Program__c) p;
            createProducts(program.Id);
        }
        
    }  

    private static void createProducts (Id programId) {

        Program__c program = [
                    select Id, CurrencyIsoCode, HasPricebook__c,
                    (select Id, CurrencyIsoCode from Price_Books__r),
                    (select IA_Feature__r.Name, 
                            Discount__c,
                            Filter_Number__c,
                            IA_Feature__r.Filter_Logic__c,
                            Filter_BE_Details__c,
                            Product_Code__c,
                            Results_Count__c
                        from Filter_Criteria__r
                        where Filter_Number__c != null and Filter_Number__c > 0 
                        order by Discount__c desc NULLS LAST)

                    from Program__c where id = :programId limit 1];

        if(program.Filter_Criteria__r == null || program.Filter_Criteria__r.isEmpty()) return;

        if(program.Price_Books__r == null || program.Price_Books__r.isEmpty() ) return;

        Pricebook2 pbook = program.Price_Books__r[0];

        Map<Id, Decimal> allStylesWithDiscount = new Map<Id, Decimal>();
        Map<Id, Decimal> allStylesWithFilterNumber = new Map<Id, Decimal>();

        for(Filter_Criteria__c fc : program.Filter_Criteria__r) {
            if(String.isBlank(fc.Filter_BE_Details__c)) continue;

            if(fc.Discount__c == null) fc.Discount__c = 0;

            Set<Id> filterStyles = RWS_FilterCriteria_Util.getProductStylesForFilter(fc);

            if(filterStyles.isEmpty()) continue;

            for(Id s : filterStyles) {
                if(!allStylesWithDiscount.containsKey(s)) {
                    allStylesWithDiscount.put(s, fc.Discount__c);
                    allStylesWithFilterNumber.put(s, fc.Filter_Number__c);
                }
            }
        }

        Id stdpbid;
        if(Test.isRunningTest()) 
            stdpbid = Test.getStandardPricebookId();
        else
            stdpbid = [select id, name from Pricebook2 where isStandard = true limit 1].id;


        Set<Id> validProducts = new Map<Id, Product2>([select Id from Product2 
                                        where Product_Style__c in :allStylesWithDiscount.keySet()
                                        and IsActive = true]).keySet();

        List<PricebookEntry> product_lst 
            = Database.query('select Id, CurrencyISOCode, ' + 
 '                    Unitprice, Product2Id, Product2.Product_Style__c, ' + 
 '                    Product2.SKU__c, ' + 
 '                    Product2.UPC__c, ' + 
 '                    Product2.RWS_Id__c, ' + 
 '                    Product2.ProductCode, ' + 
 '                    Product2.Style_Number_Unique_ID__c, ' + 
 '                    Product2.Name, ' +
 '                    Product2.Id ' +  
 '                from PricebookEntry ' + 
 '                where Pricebook2id = :stdpbid' +  
 '                and Product2Id in :validProducts' +
 '                  and IsActive = true ');


        // create PriceBook to Publish Price Book Id map
        Map<Id, Id> pbToPpbIdMap = new Map<Id, Id>();

        Id ppbId = [select Id, 
                            Price_Book__c
                    from Publish_PriceBook__c 
                    where Price_Book__c = :pbook.id].Id;

        Map<Id, Publish_PriceBook_Entry__c> ppbeMap = new Map<Id, Publish_PriceBook_Entry__c>();

        Set<Id> productIds = new Set<Id>();

        for(Publish_PriceBook_Entry__c ppbe : [select Id, Product_Id__c, 
        											Discount__c,
        											Product_SKU__c,
        											Product_UPC__c,
        											Product_RWS_ID__c,
        											Style_Number_Unique_Id__c,
        											Style_Name__c,
        											List_Price__c,
        											MSRP__c,
        											Active__c,
        											Publish_PriceBook__c
			        							from Publish_PriceBook_Entry__c 
			        						where Publish_PriceBook__c = :ppbId
			        						and Product_Id__c in :validProducts] ) {

        	ppbeMap.put(ppbe.Product_Id__c, ppbe);
        }

        List<Publish_PriceBook_Entry__c> ppbEntriesToInsert = new List<Publish_PriceBook_Entry__c>();

        for(PricebookEntry pd : product_lst ) {

            if(ppbId == null) continue;

            if(pd.CurrencyIsoCode != pbook.CurrencyIsoCode) continue;

            productIds.add(pd.Product2Id);

            Product2 p = pd.Product2;

            Publish_PriceBook_Entry__c existingPpbe = ppbeMap.get(pd.Product2Id);

            Decimal maxDiscount = 0;

            Decimal discount = allStylesWithDiscount.get(p.Product_Style__c );

            Decimal filterNumber = allStylesWithFilterNumber.get(p.Product_Style__c);

            if(filterNumber == null) filterNumber = 1;

            if(discount != null && discount > 0) {
                maxDiscount = discount;
            }

            if(existingPpbe != null && existingPpbe.Publish_PriceBook__c == ppbId &&
            	existingPpbe.Style_Number_Unique_Id__c == p.Style_Number_Unique_ID__c &&
            	existingPpbe.MSRP__c == pd.UnitPrice &&
				existingPpbe.Discount__c == maxDiscount &&
				existingPpbe.Filter_Number__c == filterNumber ) continue;

            Publish_PriceBook_Entry__c ppbe = new Publish_PriceBook_Entry__c( Id = existingPpbe == null ? null : existingPpbe.Id );

            ppbe.Price_Book__c = pbook.id;

            

            ppbe.Discount__c = maxDiscount;
            ppbe.Publish_PriceBook__c = ppbId;

            ppbe.Product_SKU__c = p.SKU__c;
            ppbe.Product_UPC__c = p.UPC__c;
            ppbe.Product_RWS_ID__c = p.RWS_Id__c;

            ppbe.Style_Number__c = p.ProductCode;
            ppbe.Style_Number_Unique_Id__c = p.Style_Number_Unique_ID__c;
            ppbe.Style_Name__c = p.Name;
            ppbe.Product_Id__c = p.Id;

            //ppbe.Pricebook_Entry_ID__c = ppbId + '-' + p.Id;

            

            ppbe.Filter_Number__c = filterNumber;

            Double stdUnitPrice = pd.UnitPrice;

            ppbe.List_Price__c = stdUnitPrice == 0 ? 0 : (stdUnitPrice - (ppbe.Discount__c / 100) * stdUnitPrice);

            ppbe.MSRP__c = pd.UnitPrice;

            ppbe.Active__c = true;

            // Add to List
            ppbEntriesToInsert.add(ppbe);

            if(ppbEntriesToInsert.size() == 200) {
            	insertUpdateRecord(ppbEntriesToInsert);

                ppbEntriesToInsert = new List<Publish_PriceBook_Entry__c>();
            }

        }

        if(!ppbEntriesToInsert.isempty())  insertUpdateRecord(ppbEntriesToInsert);

        if(!productIds.isEmpty()) deactivatePublicPriceBookEntries(ppbId, productIds);

    }

    private static void insertUpdateRecord(List<Publish_PriceBook_Entry__c> ppbEntriesToInsert) {
        Integer attempts = 5;
        while(attempts > 0){
            try {
                attempts --; 
                upsert ppbEntriesToInsert; 
                attempts = 0;
            } catch (System.DmlException dmlEx) {
                if (!dmlEx.getMessage().contains('UNABLE_TO_LOCK_ROW')) {  attempts = 0;  }

                if(attempts == 0) { throw dmlEx; }
            } // end of catch
        } // end of while retry loop
    }

    public static void deactivatePublicPriceBookEntries(Id ppbId, Set<Id> productIds) {

        List<Publish_PriceBook_Entry__c> ppbes = [select Id, Active__c,
                                                       // Pricebook_Entry_ID__c,
                                                        Expiration_Date__c 
                                                    from Publish_PriceBook_Entry__c
                                                    where Product_Id__c not in :productIds
                                                    and Publish_PriceBook__c = :ppbId];

        if(ppbes.isEmpty()) return;

        for(Publish_PriceBook_Entry__c ppbe : ppbes) {
            ppbe.Active__c = false;
            ppbe.Expiration_Date__c = DateTime.now();
        }

        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = true;        

        insertUpdateRecord(ppbes);

        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = Test.isRunningTest();

    }

    
    global void finish(Database.BatchableContext BC) {} 
}