force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>A formula field to bring in the category of the IA Feature.
Field Type: IA
Integrated: N</description>
    <formula>TEXT(IA_Feature__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A formula field to bring in the category of the IA Feature.</inlineHelpText>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_BE_Details__c.field-meta.xml
<CustomField>
    <fullName>Filter_BE_Details__c</fullName>
    <description>Field used to display filter criteria details on review products visualforce page.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Field used to display filter criteria details on review products visualforce page.</inlineHelpText>
    <label>Filter BE Details</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</description>
    <inlineHelpText>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</inlineHelpText>
    <label>Product Code</label>
    <length>25000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Results_Count__c.field-meta.xml
<CustomField>
    <fullName>Results_Count__c</fullName>
    <label>Results Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Feature__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Product Category for the IA Feature.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Product Category for the IA Feature.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Workwear</fullName>
            </value>
            <value>
                <fullName>Outside Lines</fullName>
            </value>
            <value>
                <fullName>Accessories Apparel and Gear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/Filter_Logic__c.field-meta.xml
<CustomField>
    <fullName>Filter_Logic__c</fullName>
    <description>The filter logic for an IA Feature.  (AND, OR) Logic for each filter and how they related to one another when selecting multiple filters using the Product Selection Visualforce Page.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The filter logic for an IA Feature.  (AND, OR) Logic for each filter and how they related to one another when selecting multiple filters using the Product Selection Visualforce Page.</inlineHelpText>
    <label>Filter Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/Parent_IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>Parent_IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to associate an IA Feature with a Parent IA Feature.  Lookup within the same IA Feature object.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to associate an IA Feature with a Parent IA Feature.  Lookup within the same IA Feature object.</inlineHelpText>
    <label>Red Wing Parent ID</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>IA Feature</relationshipLabel>
    <relationshipName>IA_Feature</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Used in apex to match to the category on the Product object. Updated via apex.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used in apex to match to the category on the Product object. Updated via apex.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Workwear</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Accessories Apparel and Gear</fullName>
            </value>
            <value>
                <fullName>Outside Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/HasPricebook__c.field-meta.xml
<CustomField>
    <fullName>HasPricebook__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by APEX to flag Programs that have an active custom Pricebook.</description>
    <inlineHelpText>This field is used by APEX to flag Programs that have an active custom Pricebook.</inlineHelpText>
    <label>HasPricebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book Entry. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book Entry. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>List Price</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number__c.field-meta.xml
<CustomField>
    <fullName>Style_Number__c</fullName>
    <description>Style Number (field is used to match against Product standard object). Used for outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number (field is used to match against Product standard object). Used for outbound messaging.</inlineHelpText>
    <label>Style Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_ProgramSync_Batch.cls
global class RWS_ProgramSync_Batch implements Database.Batchable<sObject>, Schedulable {

    global void execute(SchedulableContext sc) {
        Database.executeBatch(new RWS_ProgramSync_Batch(), 1);
    }

    global RWS_ProgramSync_Batch() { }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        Integer lastDays = -1 * Integer.valueOf(Label.Number_of_Days);
        Datetime dt = Datetime.now().addDays(lastDays);

        String programKeyPrefix = Program__c.SObjectType.getDescribe().getKeyPrefix();

        Set<String> programIds = new Set<String>();

        for(String prId : Label.Program_Test_Run_Id.split(',')) {
            if(String.isBlank(prId)) continue;

            if(prId.startsWith(programKeyPrefix) && (prId.length() == 15 || prId.length() == 18) ) {
                if(!Test.isRunningTest()) programIds.add(prId);
            }
        }

        return Database.getQueryLocator('select Id, Active__c, HasPricebook__c, ' + 
                                '(select Id, CurrencyIsoCode from Publish_PriceBooks__r), ' + 
                                '(select IA_Feature__r.Name, ' +
                                    'Discount__c, ' +
                                    'Filter_Number__c, ' +
                                    'IA_Feature__r.Filter_Logic__c, ' +
                                    'Filter_BE_Details__c, ' +
                                    'Product_Code__c, ' +
                                    'Results_Count__c ' +
                                'from Filter_Criteria__r where Filter_Number__c != null and Filter_Number__c > 0 ' +
                            'order by Discount__c desc NULLS LAST) ' + 
                            'from Program__c where CreatedDate >= :dt ' + 
                        (programIds.isEmpty() ? '' : ' AND Id in :programIds ')  );
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {

        Program__c program = (Program__c) scope[0];

        if(program.Filter_Criteria__r == null || program.Filter_Criteria__r.isEmpty()) return;

        if(program.Publish_PriceBooks__r == null || program.Publish_PriceBooks__r.isEmpty() ) return;

        Publish_PriceBook__c pbook = program.Publish_PriceBooks__r[0];

        List<Publish_PriceBook_Entry__c> existing_product_lst  
            = [select Id, CurrencyISOCode, 
                     List_Price__c, Product_Id__c, 
                     //Product2.Category__c,
                     //Product2.Product_Style__c,
                     Filter_Number__c,
                     Discount__c,
                     Active__c,
                     Style_Number__c
                from Publish_PriceBook_Entry__c
                where Publish_PriceBook__c = :pbook.Id
                //and Product2.Product_Style__c != null
                and CurrencyISOCode = :pbook.CurrencyIsoCode];
        
        Set<Id> prodIds = new Set<Id>();
            
        for(Publish_PriceBook_Entry__c ppbe : existing_product_lst) {
            prodIds.add(ppbe.Product_Id__c);
        }
        
        Set<Id> prodIdSet = new Set<Id>(); 
        for (Product2 prod : [SELECT Id, Name, Category__c, ProductCode FROM Product2 WHERE Product_Style__c != null AND Id IN : prodIds]){
            prodIdSet.add(prod.Id);
        }
        
        for(Integer i = 0; i < existing_product_lst.size(); i++){
            if (!prodIdSet.contains(existing_product_lst[i].Product_Id__c)){
                existing_product_lst.remove(i);    
            }
        }
        

        Map<String, Publish_PriceBook_Entry__c> productToPBEMap  = new Map<String, Publish_PriceBook_Entry__c>();
        for(Publish_PriceBook_Entry__c ppbe : existing_product_lst) {
            productToPBEMap.put(ppbe.Style_Number__c, ppbe);
        }

        Map<Id, Decimal> allStylesWithDiscount = new Map<Id, Decimal>();
        Map<Id, Decimal> allStylesWithFilterNumber = new Map<Id, Decimal>();

        for(Filter_Criteria__c fc : program.Filter_Criteria__r) {
            if(String.isBlank(fc.Filter_BE_Details__c)) continue;

            if(fc.Discount__c == null) fc.Discount__c = 0;

            Set<Id> filterStyles = RWS_FilterCriteria_Util.getProductStylesForFilter(fc);

            if(filterStyles.isEmpty()) continue;

            for(Id s : filterStyles) {
                if(!allStylesWithDiscount.containsKey(s)) {
                    allStylesWithDiscount.put(s, fc.Discount__c);
                    allStylesWithFilterNumber.put(s, fc.Filter_Number__c);
                }
            }
        }

        Id stdpbid;
        if(Test.isRunningTest()) 
            stdpbid = Test.getStandardPricebookId();
        else
            stdpbid = [select id, name from Pricebook2 where isStandard = true limit 1].id;


        List<Product2> products = [select Id from Product2 
                                        where Product_Style__c in :allStylesWithDiscount.keySet()
                                        and IsActive = true];
                                        
        List<PricebookEntry> product_lst  
            = [select Id, CurrencyISOCode, 
                     Unitprice, Product2Id, 
                     Product2.Product_Style__c,
                     Filter_Number__c,
                     Discount__c,
                     IsActive,
                     ProductCode
                from PricebookEntry
                where Pricebook2Id = :stdpbid
                and Product2Id in :products
                and IsActive = true
                and Product2.Product_Style__c != null
                and CurrencyISOCode = :pbook.CurrencyIsoCode];

        List<Publish_PriceBook_Entry__c> insertPriceBookEntry_lst = new list<Publish_PriceBook_Entry__c>();
        List<Publish_PriceBook_Entry__c> updatePriceBookEntry_lst = new list<Publish_PriceBook_Entry__c>();
        Set<Id> productIds = new Set<Id>();
        Set<String> processedCode = new Set<String>();

        for(PricebookEntry pd : product_lst ) {

            if(processedCode.contains(pd.ProductCode)) continue;

            processedCode.add(pd.ProductCode);
            
            Publish_PriceBook_Entry__c pbEntry = productToPBEMap.get(pd.ProductCode);

            Decimal maxDiscount = 0;

            Decimal discount = allStylesWithDiscount.get(pd.Product2.Product_Style__c );

            Decimal filterNumber = allStylesWithFilterNumber.get(pd.Product2.Product_Style__c);

            if(discount != null && discount > 0) {
                maxDiscount = discount;
            }

            if(filterNumber == null) filterNumber = 1;

            if(pbEntry == null)  {
                pbEntry = new Publish_PriceBook_Entry__c();
                pbEntry.Product_ID__c = pd.Product2Id;
                pbEntry.Publish_PriceBook__c = pbook.id;
                pbEntry.CurrencyIsoCode = pbook.CurrencyIsoCode;
            }
            

            pbEntry.Active__c = true;

            pbEntry.Discount__c = maxDiscount;

            pbEntry.Filter_Number__c = filterNumber;

            Double stdUnitPrice = pd.UnitPrice;

            pbEntry.List_Price__c = stdUnitPrice == 0 ? 0 : (stdUnitPrice - (pbEntry.Discount__c / 100) * stdUnitPrice);

            productIds.add(pbEntry.Product_ID__c);

            if(pbEntry.Id != null) {
                updatePriceBookEntry_lst.add(pbEntry);

                if(updatePriceBookEntry_lst.size() == 200) {
                    RWS_PriceBookEntry_Util.insertUpdateRecords(updatePriceBookEntry_lst, false);
                    updatePriceBookEntry_lst = new List<Publish_PriceBook_Entry__c>();
                }

            } else {
                insertPriceBookEntry_lst.add(pbEntry);

                if(insertPriceBookEntry_lst.size() == 200) {
                    RWS_PriceBookEntry_Util.insertUpdateRecords(insertPriceBookEntry_lst, true);
                    insertPriceBookEntry_lst = new List<Publish_PriceBook_Entry__c>();
                }
                
            }

            productToPBEMap.put(pd.ProductCode, pbEntry);
        }

        if(updatePriceBookEntry_lst.isempty() && insertPriceBookEntry_lst.isempty()) return;

        if(!updatePriceBookEntry_lst.isempty())  RWS_PriceBookEntry_Util.insertUpdateRecords(updatePriceBookEntry_lst, false);

        if(!insertPriceBookEntry_lst.isempty())  RWS_PriceBookEntry_Util.insertUpdateRecords(insertPriceBookEntry_lst, true);

        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = Test.isRunningTest();

        RWS_PriceBookEntry_Util.createPublishPriceBookEntries(pbook.Id, productIds);

        List<Publish_PriceBook_Entry__c> entriesToDelete = [select Id from Publish_PriceBook_Entry__c where Publish_PriceBook__c in :program.Publish_PriceBooks__r 
                    //and Product2.Parent_Product_Style__c in :allStylesWithDiscount.keySet()
                    and Product_ID__c not in :productIds];
        
        prodIds.clear();            
        for(Publish_PriceBook_Entry__c ppbe : entriesToDelete) {
            prodIds.add(ppbe.Product_Id__c);
        }
        
        prodIdSet.clear(); 
        for (Product2 prod : [SELECT Id, Name, Category__c, ProductCode FROM Product2 WHERE Product_Style__c != null AND Id IN : prodIds]){
            prodIdSet.add(prod.Id);
        }
        
        for(Integer i = 0; i < entriesToDelete.size(); i++){
            if (!prodIdSet.contains(entriesToDelete[i].Product_Id__c)){
                entriesToDelete.remove(i);    
            }
        }
        

        //if(!entriesToDelete.isEmpty())  RWS_PriceBookEntry_Util.deleteRecords(entriesToDelete);
        if(!entriesToDelete.isEmpty())  RWS_PriceBookEntry_Util.deactivatePublicPriceBookEntries(entriesToDelete);
        
    }

    global void finish(Database.BatchableContext BC) {}
}