force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Brand Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Sales Rep</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>BrandEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <inlineHelpText>Identify the brand(s) involved in this Case</inlineHelpText>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carhartt</fullName>
            </value>
            <value>
                <fullName>Irish Setter Brands (Work &amp; Hunt)</fullName>
            </value>
            <value>
                <fullName>Irish Setter Hunt</fullName>
            </value>
            <value>
                <fullName>Irish Setter Work</fullName>
            </value>
            <value>
                <fullName>Red Wing</fullName>
            </value>
            <value>
                <fullName>Red Wing Brand</fullName>
            </value>
            <value>
                <fullName>Red Wing Brand - Other</fullName>
            </value>
            <value>
                <fullName>Red Wing Garments</fullName>
            </value>
            <value>
                <fullName>Red Wing Heritage</fullName>
            </value>
            <value>
                <fullName>Vasque</fullName>
            </value>
            <value>
                <fullName>WORX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChatterGroupsAutoAssigned__c/ChatterGroupsAutoAssigned__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Chatter groups M3 contacts are added to automatically upon accepting Chatter.</description>
    <label>ChatterGroupsAutoAssigned</label>
</CustomObject>

force-app/main/default/objects/ChatterGroupsAutoAssigned__c/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <description>Chatter Group Id value</description>
    <inlineHelpText>Enter Id of the chatter group to be auto assigned</inlineHelpText>
    <label>GroupId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ECTestDataFactory.cls
@isTest
Global class ECTestDataFactory{

	public static Account createAccount(String name, boolean saveItems) {
		Account newAccount = new Account();
		newAccount.Name = name;
		
		if(saveItems) {
			insert newAccount;
		}
		return newAccount;
	}
	
    Public Static Contact CreateContact(String FirstName, String LastName, String Email, boolean saveItems){
        Contact newContact = new Contact();
    
        newContact.FirstName = FirstName;
        newContact.LastName = LastName;
        newContact.Email = Email; 
    
        if(saveItems){
            insert newContact;
        }
        return newContact;    
    }

    Public Static CollaborationGroup CreateCollaborationGroup(String Name, String CollaborationType, boolean saveItems){
        CollaborationGroup cg = new CollaborationGroup();
        
        cg.Name = Name;
        cg.CollaborationType = CollaborationType;
        
        if(saveItems){
            insert cg;
        }
        
        return cg;
    }
    
    public static Case createCase(String primaryCaseType, String status, String caseOrigin, Id businessHours, Id recordTypeId, Id accountId, Id contactId, boolean saveItems) {
    	Case newCase = new Case();
    	newCase.RecordTypeId = recordTypeId;
    	newCase.ContactId = contactId;
    	
    	if(saveItems) {
    		insert newCase;
    	}
    	return newCase;
    }
    
    public static Task createTask(Id whoId, string status, string priority, string subject, date activitydate, boolean saveItems) {
    	Task newTask = new Task();
    	newTask.whoId = whoId;
    	newTask.Status = status;
    	newTask.Priority = priority;
    	newTask.Subject = subject;
    	newTask.ActivityDate = activitydate;
    	
    	if(saveItems) {
    		insert newTask;
    	}
    	return newTask;
    }
    
    public static User createTestUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User testUser = new User();
        testUser.FirstName = 'Test';
        testUser.LastName = 'Tester';
        testUser.Alias = 'tester';
        testUser.Email = 'test@tester.com';
        testUser.EmailEncodingKey='UTF-8';
        testUser.LanguageLocaleKey='en_US';
        testUser.LocaleSidKey='en_US';
        testUser.ProfileId = p.Id;
        testUser.TimeZoneSidKey='America/Los_Angeles';
        testUser.UserName = 'tester@redwingshoestest.com';
        return testUser;
    }
    
    public static Brand__c createBrand(Id accountId, Id userId, boolean saveItems) {
    	Brand__c newBrand = new Brand__c();
    	newBrand.Account__c = accountId;
    	newBrand.User__c = userId;
    	newBrand.CurrencyIsoCode = 'USD';
    	return newBrand;
    }
    
  // Create Custom Settings Marketing Assisted
    Global Static void CreateCustomSettingsChatterGroups(Id groupId, boolean saveItems) {    
    
    list<ChatterGroupsAutoAssigned__c> lstChatterGroups=new list<ChatterGroupsAutoAssigned__c>();

    ChatterGroupsAutoAssigned__c chatterGroupCS=new ChatterGroupsAutoAssigned__c();
    chatterGroupCS.name='ectest';
    chatterGroupCS.Group_Id__c=groupId;
    lstChatterGroups.add(chatterGroupCS);
      
    if(saveItems){
        insert lstChatterGroups;
    	}    
    }    
}