force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Used in apex to match to the category on the Product object. Updated via apex.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used in apex to match to the category on the Product object. Updated via apex.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Workwear</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Accessories Apparel and Gear</fullName>
            </value>
            <value>
                <fullName>Outside Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Style__c/fields/Item_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Status_Code__c</fullName>
    <description>Rollup for the related Product Item Status Code (populated with the lowest possible value)</description>
    <inlineHelpText>Rollup for the related Product Item Status Code (populated with the lowest possible value)</inlineHelpText>
    <label>Item Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Used in apex to match to the style number unique id on the Product object.  Updated via apex.
Field Type: IA
Integrated: N</description>
    <externalId>true</externalId>
    <inlineHelpText>Used in apex to match to the style number unique id on the Product object. Updated via apex.</inlineHelpText>
    <label>Style Number Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Auto_Add_Products__c.field-meta.xml
<CustomField>
    <fullName>Auto_Add_Products__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If TRUE your price book is automatically updated with new products that meet stored filter criteria. EXAMPLE: a program for Red Wing &amp; Steel Toe and a new product product is manufactured that is Red Wing &amp; Steel Toe it will be added to your price book.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If TRUE your price book is automatically updated with new products that meet stored filter criteria. EXAMPLE: a program for Red Wing &amp; Steel Toe and a new product product is manufactured that is Red Wing &amp; Steel Toe it will be added to your price book.</inlineHelpText>
    <label>Auto Add Products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Auto_Update_Price__c.field-meta.xml
<CustomField>
    <fullName>Auto_Update_Price__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If TRUE your price books is automatically adjusted with MSRP changes.  EXAMPLE:  If you had 20% off Red Wing and the MSRP increases; your 20% remains but it is off the new MSRP.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If TRUE your price book is automatically adjusted with MSRP changes.  EXAMPLE:  If you had 20% off Red Wing and the MSRP increases; your 20% remains but it is off the new MSRP.</inlineHelpText>
    <label>Auto Update Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_Id__c</fullName>
    <description>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.</inlineHelpText>
    <label>Style Number Unique Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_Print_ProgramPricelistContTest.cls
@isTest
private class RWS_Print_ProgramPricelistContTest 
{
    static testMethod void printTess() 
    {
    	PageReference pageRef = Page.RWS_Print_ProgramPricelist;

        Program__c pr = [select Id, Name, Auto_Update_Price__c, Auto_Add_Products__c from Program__c limit 1];

        pageRef.getParameters().put('ProgramId', pr.Id);
        pageRef.getParameters().put('pn', '0');

        Test.setCurrentPageReference(pageRef);
        RWS_Print_ProgramPricelistCont con = new RWS_Print_ProgramPricelistCont();
        pageRef.getParameters().put('pn', '1');
        
        con = new RWS_Print_ProgramPricelistCont();
        con.getProgramDetails();

    }

    @TestSetup
    static void setupData() { 
        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');
        Account acc = RWS_TestUtil.createAccount(rtId, true);
        Program__c pr = RWS_TestUtil.createProgram(acc.Id, true);
        Id pricebookId = Test.getStandardPricebookId();

        Product_Style__c ps = new Product_Style__c(Category__c= 'Footwear', Style_Number_Unique_ID__c = '06001');
        insert ps;

        List<Product2> prod_lst = new List<Product2>();
        Product2 fw1 = RWS_TestUtil.createProductwithDetail('Footwear Prod 1','Footwear',false);
        fw1.ProductCode = '0001';
        fw1.Item_Status_Code__c = '20';
        fw1.Item_Status__c = 'Active';
        fw1.Product_Style__c = ps.Id ;

        Product2 fw2 = RWS_TestUtil.createProductwithDetail('Footwear Prod 1','Footwear',false);
        fw2.ProductCode = '0001';
        fw2.Item_Status_Code__c = '80';
        fw2.Item_Status__c = 'Active';
        fw2.Product_Style__c = ps.Id ;

        prod_lst.add(fw1);
        prod_lst.add(fw2);
        
        Publish_PriceBook__c customPB = RWS_TestUtil.createCustomPublishPricebook(pr.Id, true);
		Publish_PriceBook_Entry__c customPrice = RWS_TestUtil.createPublishPricebookEntry(customPB.Id, fw1.Id, true);
        Publish_PriceBook_Entry__c customPrice2 = RWS_TestUtil.createPublishPricebookEntry(customPB.Id, fw2.Id, true);

        prod_lst.add(RWS_TestUtil.createProductwithDetail('Accessories Prod 1','Accessories Apparel and Gear', false));
        prod_lst.add(RWS_TestUtil.createProductwithDetail('Workwear Prod 1','Workwear', false));
        prod_lst.add(RWS_TestUtil.createProductwithDetail('OL Prod 1','Outside Lines', false));
        insert prod_lst;

        List<PriceBookEntry> pricebookentry_lst = new List<Pricebookentry>();
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[0].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[1].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[2].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[3].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[4].Id, false));
        insert pricebookentry_lst;

    }

}