force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Features__c/Features__c.object-meta.xml
<CustomObject>
    <description>Features for Products in Salesforce.  Updated with Integration.
Object Type: IA
Integrated: Y</description>
    <label>Features</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Features__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to IA Feature Object.  IA Features are those displayed in the Community. This associates a feature with an IA Feature.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to IA Feature Object.  IA Features are those displayed in the Community.  This associates a feature with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Display__c.field-meta.xml
<CustomField>
    <fullName>Filter_Display__c</fullName>
    <description>Field used to display filter criteria details on review products visualforce page.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Field used to display filter criteria details on review products visualforce page.</inlineHelpText>
    <label>Filter Display</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</description>
    <inlineHelpText>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</inlineHelpText>
    <label>Product Code</label>
    <length>25000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Feature__c/fields/Filter_Display__c.field-meta.xml
<CustomField>
    <fullName>Filter_Display__c</fullName>
    <description>If filter display is set to expanded it will be open on page load of Product Selection VF
If filter display is set to collapsed it will be closed on page load
NOTE:  Only applies to parent / header IA features.  Where &quot;selectable&quot; equals False.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If filter display is set to expanded it will be open on page load of Product Selection VF
If filter display is set to collapsed it will be closed on page load
NOTE:  Only applies to parent / header IA features.  Where &quot;selectable&quot; equals False.</inlineHelpText>
    <label>Filter Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expanded</fullName>
            </value>
            <value>
                <fullName>Collapsed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Features__c/Product_Features__c.object-meta.xml
<CustomObject>
    <description>Junction object which manages the many to many relationship between Product object and the Features object. Maintained via integration. 
Object Type: IA 
Integrated: Y</description>
    <label>Product Features</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>Product Feature Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/RWS_ProgramTemplate_Queue_Test.cls
@isTest
private class RWS_ProgramTemplate_Queue_Test {
    static testMethod void testJob() {
        Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        Program__c pr = RWS_TestUtil.createProgram(acc.Id, true);   

        Product2 prod = RWS_TestUtil.createProduct(true);

        Id pricebookId = Test.getStandardPricebookId();

        PricebookEntry standardPrice = RWS_TestUtil.createPricebookEntry(pricebookId, prod.Id, true);

        Pricebook2 customPB = RWS_TestUtil.createCustomPricebook(pr.Id, true);

        PricebookEntry customPrice = RWS_TestUtil.createPricebookEntry(customPB.Id, prod.Id, true);

        List<IA_Feature__c> Iafeature_lst1 = new List<IA_Feature__c>();
        Iafeature_lst1.add(RWS_TestUtil.createIAFeature('Brand',null, 'Footwear', false, false));
        insert Iafeature_lst1;

        List<IA_Feature__c> Iafeature_lst2 = new List<IA_Feature__c>();
        Iafeature_lst2.add(RWS_TestUtil.createIAFeature('Red wing',Iafeature_lst1[0].id, 'Footwear', true, false));
        insert Iafeature_lst2;

        List<Features__c> features_lst1 = new List<Features__c>();
        features_lst1.add(RWS_TestUtil.createFeature('Red wing',Iafeature_lst2[0].id, false));
        insert features_lst1;

        List<Product_Features__c> Product_Features_lst = new List<Product_Features__c>();
        Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst1[0].id, prod.id, false));
        insert product_Features_lst;

        List<Filter_Criteria__c> filters = new List<Filter_Criteria__c>();
        Filter_Criteria__c fc = RWS_TestUtil.createFilterCriteria(pr.Id, Iafeature_lst2[0].id, false);
        fc.IA_Feature__c = null;
        fc.Product_Code__c = JSON.serialize(new Set<String>{prod.ProductCode}) + '-FPC-' + JSON.serialize(new Set<String>() );
        fc.Filter_Display__c = 'AND( ABC )';

        Filter_Criteria__c fc2 = RWS_TestUtil.createFilterCriteria(pr.Id, Iafeature_lst2[0].id, false);
        fc2.Filter_Number__c = 0;
        fc2.IA_Feature__c = null;
        fc2.Product_Code__c = JSON.serialize(new Map<String, Decimal>{prod.ProductCode => 40}) + '-FPC-' + JSON.serialize(new Set<String>() );
        fc2.Filter_Display__c = 'Custom List';

        filters.add(fc);
        filters.add(fc2);

        insert filters;

        Test.startTest();
        	System.enqueueJob(new RWS_ProgramTemplate_Queue(pr.Id, pr.Name));
        Test.stopTest();
    }
}