force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Features__c/Features__c.object-meta.xml
<CustomObject>
    <description>Features for Products in Salesforce.  Updated with Integration.
Object Type: IA
Integrated: Y</description>
    <label>Features</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Features__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to IA Feature Object.  IA Features are those displayed in the Community. This associates a feature with an IA Feature.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to IA Feature Object.  IA Features are those displayed in the Community.  This associates a feature with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Display__c.field-meta.xml
<CustomField>
    <fullName>Filter_Display__c</fullName>
    <description>Field used to display filter criteria details on review products visualforce page.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Field used to display filter criteria details on review products visualforce page.</inlineHelpText>
    <label>Filter Display</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</description>
    <inlineHelpText>The Styles that are returned based on the defined Filter Criteria. Used in the Product Search on the Product Review screen.</inlineHelpText>
    <label>Product Code</label>
    <length>25000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Feature__c/fields/Filter_Display__c.field-meta.xml
<CustomField>
    <fullName>Filter_Display__c</fullName>
    <description>If filter display is set to expanded it will be open on page load of Product Selection VF
If filter display is set to collapsed it will be closed on page load
NOTE:  Only applies to parent / header IA features.  Where &quot;selectable&quot; equals False.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If filter display is set to expanded it will be open on page load of Product Selection VF
If filter display is set to collapsed it will be closed on page load
NOTE:  Only applies to parent / header IA features.  Where &quot;selectable&quot; equals False.</inlineHelpText>
    <label>Filter Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expanded</fullName>
            </value>
            <value>
                <fullName>Collapsed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style_Features__c/Product_Style_Features__c.object-meta.xml
<CustomObject>
    <description>Junction object which manages the many to many relationship between unique styles (Product Style Object) and the Features object. Records are created / updated via apex. Does not need to be maintained via integration. 
Object Type: IA 
Integrated: N</description>
    <label>Product Style Features</label>
    <nameField>
        <displayFormat>PSF-{000000}</displayFormat>
        <label>Product Style Feature #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Style Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style_Features__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Product Style object. Used to associate a Product Style to a Feature. Maintained by apex. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup field to the Product Style object. Used to associate a Product Style to a Feature.</inlineHelpText>
    <label>Product Style</label>
    <referenceTo>Product_Style__c</referenceTo>
    <relationshipLabel>Product Style Features</relationshipLabel>
    <relationshipName>Product_Style_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <description>The Processing status determine the status of the related Product record creation for this program. Program Activation is dependent on the Program processing.</description>
    <inlineHelpText>The Processing status determine the status of the related Product record creation for this program. Program Activation is dependent on the Program processing.</inlineHelpText>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the program is a template</description>
    <inlineHelpText>Indicates if the program is a template</inlineHelpText>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_PriceList_Summary_Controller_Test.cls
@isTest
private class RWS_PriceList_Summary_Controller_Test {
    static testMethod void testController() {
        Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);

        insert con1;

        Id roleId = [select Id from UserRole where Name = 'System Administrators' limit 1].Id;

        User u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {

            User user = new User(Id = UserInfo.getUserId(), UserRoleId = roleId);
            update user;

            insert u1;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u1.UserRoleId = partnerRoleId;

            update u1;
        }

        Test.startTest();

        System.runAs(u1) {
            Program__c pr = RWS_TestUtil.createProgram(acc.Id, false);   
            pr.Processing_Status__c = 'Completed';
            insert pr;

            Product2 prod = RWS_TestUtil.createProduct(true);

            Id pricebookId = Test.getStandardPricebookId();

            PricebookEntry standardPrice = RWS_TestUtil.createPricebookEntry(pricebookId, prod.Id, true);

            Publish_PriceBook__c customPB = RWS_TestUtil.createCustomPublishPricebook(pr.Id, true);

            Publish_PriceBook_Entry__c customPrice = RWS_TestUtil.createPublishPricebookEntry(customPB.Id, prod.Id, true);
			System.debug('PPBE :'+customPrice);
            List<IA_Feature__c> Iafeature_lst1 = new List<IA_Feature__c>();
            Iafeature_lst1.add(RWS_TestUtil.createIAFeature('Brand',null, 'Footwear', false, false));
            insert Iafeature_lst1;

            List<IA_Feature__c> Iafeature_lst2 = new List<IA_Feature__c>();
            Iafeature_lst2.add(RWS_TestUtil.createIAFeature('Red wing',Iafeature_lst1[0].id, 'Footwear', true, false));
            insert Iafeature_lst2;

            List<Features__c> features_lst1 = new List<Features__c>();
            features_lst1.add(RWS_TestUtil.createFeature('Red wing',Iafeature_lst2[0].id, false));
            insert features_lst1;

            List<Product_Style__c> styles = [select Id from Product_Style__c];

            List<Product_Style_Features__c> Product_Features_lst = new List<Product_Style_Features__c>();
            Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst1[0].id, styles[0].id, false));

            insert product_Features_lst;

            List<Filter_Criteria__c> filters = new List<Filter_Criteria__c>();
            Filter_Criteria__c fc = RWS_TestUtil.createFilterCriteria(pr.Id, Iafeature_lst2[0].id, false);
            fc.IA_Feature__c = null;
            fc.Product_Code__c = JSON.serialize(new Set<String>{prod.ProductCode}) + '-FPC-' + JSON.serialize(new Set<String>() );
            fc.Filter_Display__c = 'AND( ABC )';

            Filter_Criteria__c fc2 = RWS_TestUtil.createFilterCriteria(pr.Id, Iafeature_lst2[0].id, false);
            fc2.Filter_Number__c = 0;
            fc2.IA_Feature__c = null;
            fc2.Product_Code__c = JSON.serialize(new Map<String, Decimal>{prod.ProductCode => 40}) + '-FPC-' + JSON.serialize(new Set<String>() );
            fc2.Filter_Display__c = 'Custom List';

            filters.add(fc);
            filters.add(fc2);

            insert filters;

            PageReference pg = Page.RWS_PriceList_Summary;
            pg.getParameters().put('id', customPB.Id);
            Test.setCurrentPageReference(pg);

            RWS_PriceList_Summary_Controller psc = new RWS_PriceList_Summary_Controller();
            psc.firstLoad = true;

            System.debug(psc.loadEntriesJSON);
            System.debug(psc.ProgramEffectiveDate);
            System.debug(psc.ExpirationDate);

            System.assert(psc.entries.size() == 1);

            psc.updateJson = JSON.serialize(psc.entries);

            psc.updateEntries();

            psc.program.Template__c = true;

            psc.updateProgram();

            psc.entryId = psc.entries[0].Id;

            //psc.removeEntry();

            psc.selectedFilter = '1';
            
            psc.removeAll();

            psc.searchTerm = prod.ProductCode;

            psc.searchProduct();
        }

        Test.stopTest();
    }
}