force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Features__c/Features__c.object-meta.xml
<CustomObject>
    <description>Features for Products in Salesforce.  Updated with Integration.
Object Type: IA
Integrated: Y</description>
    <label>Features</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Features__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to IA Feature Object.  IA Features are those displayed in the Community. This associates a feature with an IA Feature.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to IA Feature Object.  IA Features are those displayed in the Community.  This associates a feature with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>The discount % that was entered for a product filter on the product selection visualforce page.  Used to apply discounts to products which are auto added to a program.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_BE_Details__c.field-meta.xml
<CustomField>
    <fullName>Filter_BE_Details__c</fullName>
    <description>Field used to display filter criteria details on review products visualforce page.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Field used to display filter criteria details on review products visualforce page.</inlineHelpText>
    <label>Filter BE Details</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Used in apex to match to the style number unique id on the Product object.  Updated via apex.
Field Type: IA
Integrated: N</description>
    <externalId>true</externalId>
    <inlineHelpText>Used in apex to match to the style number unique id on the Product object. Updated via apex.</inlineHelpText>
    <label>Style Number Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/Product_Style_Features__c.object-meta.xml
<CustomObject>
    <description>Junction object which manages the many to many relationship between unique styles (Product Style Object) and the Features object. Records are created / updated via apex. Does not need to be maintained via integration. 
Object Type: IA 
Integrated: N</description>
    <label>Product Style Features</label>
    <nameField>
        <displayFormat>PSF-{000000}</displayFormat>
        <label>Product Style Feature #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Style Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style_Features__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Product Style object. Used to associate a Product Style to a Feature. Maintained by apex. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup field to the Product Style object. Used to associate a Product Style to a Feature.</inlineHelpText>
    <label>Product Style</label>
    <referenceTo>Product_Style__c</referenceTo>
    <relationshipLabel>Product Style Features</relationshipLabel>
    <relationshipName>Product_Style_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Reference related Product Style Unique Style Id</description>
    <formula>Product_Style__r.Style_Number_Unique_ID__c</formula>
    <label>Style Number Unique ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_ProgramSync_Batch_Test.cls
@isTest
private class RWS_ProgramSync_Batch_Test {
    static testMethod void testBatch() {

    	Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        Program__c pr = RWS_TestUtil.createProgram(acc.Id, true);

        Id pricebookId = Test.getStandardPricebookId();

        List<Product2> prod_lst = new List<Product2>();
        prod_lst.add(RWS_TestUtil.createProductwithDetail('Footwear Prod 1','Footwear',false));
        prod_lst.add(RWS_TestUtil.createProductwithDetail('Accessories Prod 1','Accessories Apparel and Gear', false));
        prod_lst.add(RWS_TestUtil.createProductwithDetail('Workwear Prod 1','Workwear', false));
        prod_lst[0].Style_Number_Unique_ID__c = '0010';
        prod_lst[1].Style_Number_Unique_ID__c = '0012';
        prod_lst[2].Style_Number_Unique_ID__c = '0011';
        insert prod_lst;

        List<Product_Style__c> styles = [select Id from Product_Style__c];

        List<PriceBookEntry> pricebookentry_lst = new List<Pricebookentry>();
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[0].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[1].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[2].Id, false));
        insert pricebookentry_lst;

        List<IA_Feature__c> Iafeature_lst1 = new List<IA_Feature__c>();
        Iafeature_lst1.add(RWS_TestUtil.createIAFeature('Brand',null, 'Footwear', false, false));
        Iafeature_lst1.add(RWS_TestUtil.createIAFeature('Color',null, 'Accessories Apparel and Gear', false, false));
        Iafeature_lst1.add(RWS_TestUtil.createIAFeature('Country Of Origin',null, 'Workwear', false, false));
        insert Iafeature_lst1;

        List<IA_Feature__c> Iafeature_lst2 = new List<IA_Feature__c>();
        Iafeature_lst2.add(RWS_TestUtil.createIAFeature('Red wing',Iafeature_lst1[0].id, 'Footwear', true, false));
        Iafeature_lst2.add(RWS_TestUtil.createIAFeature('Red',Iafeature_lst1[1].id, 'Accessories Apparel and Gear', true, false));
        Iafeature_lst2.add(RWS_TestUtil.createIAFeature('USA',Iafeature_lst1[2].id, 'Workwear', true, false));
        insert Iafeature_lst2;

        List<Features__c> features_lst1 = new List<Features__c>();
        features_lst1.add(RWS_TestUtil.createFeature('Red wing',Iafeature_lst2[0].id, false));
        features_lst1.add(RWS_TestUtil.createFeature('Red',Iafeature_lst2[0].id, false));
        features_lst1.add(RWS_TestUtil.createFeature('USA',Iafeature_lst2[0].id, false));
        insert features_lst1;

        List<Product_Style_Features__c> Product_Features_lst = new List<Product_Style_Features__c>();
        Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst1[0].id, styles[0].id, false));
        Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst1[1].id, styles[1].id, false));
        
        Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst1[2].id, styles[2].id, false));
        Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst1[1].id, styles[2].id, false));
        insert product_Features_lst;

		Publish_PriceBook__c customPB = RWS_TestUtil.createCustomPublishPricebook(pr.Id, true);

        Filter_Criteria__c fc = RWS_TestUtil.createFilterCriteria(pr.Id, Iafeature_lst2[0].id, false);
        fc.Filter_Number__c = 1;
        fc.Filter_BE_Details__c = JSON.serialize(new Map<String, String>{'Name = \'Red wing\'' => ' AND '}) + 'SEPARATOR[]';

        Filter_Criteria__c fc2 = RWS_TestUtil.createFilterCriteria(pr.Id, Iafeature_lst2[1].id, false);
        fc2.Filter_Number__c = 2;
        fc2.Filter_BE_Details__c = JSON.serialize(new Map<String, String>{'Name = \'Red\'' => ' AND '}) + 'SEPARATOR[]';

        Filter_Criteria__c fc3 = RWS_TestUtil.createFilterCriteria(pr.Id, Iafeature_lst2[2].id, false);
        fc3.Filter_Number__c = 3;
        fc3.Filter_BE_Details__c = JSON.serialize(new Map<String, String>{'Name = \'USA\'' => ' AND '}) + 'SEPARATOR[]';

        Filter_Criteria__c fc4 = RWS_TestUtil.createFilterCriteria(pr.Id, Iafeature_lst2[2].id, false);
        fc4.Filter_Number__c = 4;
        fc4.Filter_BE_Details__c = JSON.serialize(new Map<String, String>{'Name = \'USA\' AND Name = \'Red\'' => ' AND '}) + 'SEPARATOR[]';
        fc4.Discount__c = 20;

        insert new List<Filter_Criteria__c>{fc, fc2, fc3, fc4};

		Test.startTest();
			RWS_ProgramSync_Batch job = new RWS_ProgramSync_Batch();
			job.execute(null);
		Test.stopTest();
        
    }
}