force-app/main/default/objects/Store_IA_Account__c/Store_IA_Account__c.object-meta.xml
<CustomObject>
    <description>Object for Red Wing Store and IA Account relationships.  When a Red Wing Store creates a new IA account a record is inserted into this object via APEX.
Object Type: IA
Integrated: N</description>
    <label>Store IA Account</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Store IA Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store IA Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_IA_Account__c/fields/Store_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.</inlineHelpText>
    <label>Store Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store IA Account</relationshipLabel>
    <relationshipName>Store_IA_Account_del1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_EditAccounController_Test.cls
@isTest
public class RWS_EditAccounController_Test {
	@isTest
    public static void Constructor_Test(){

    	RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
 		System.runAs(dataFactory.TestRunner){
			//not sure if this is needs to be done per unit test method? I think so
			List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

			RWS_EditAccounController controller = new RWS_EditAccounController();
			System.assert(controller != null);
			System.assert(controller.editAccount.id == Industrial[0].Store_Account__c);
 		}
	} 

	@isTest
    public static void UpdateAcccount_Test(){

    	RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
 		System.runAs(dataFactory.TestRunner){
			//not sure if this is needs to be done per unit test method? I think so
			List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

			RWS_EditAccounController controller = new RWS_EditAccounController();
			controller.updateAcccountContact();
			//this code is weird. From the looks of it, the method will ALWAYS return the error message. 
			System.assert(controller.duplicationMessage.contains('We detected an account already established for') );
 		}
	} 

	@isTest
    public static void FinalUpdateAcccountContact_Test(){

    	RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
 		System.runAs(dataFactory.TestRunner){
			//not sure if this is needs to be done per unit test method? I think so
			List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

			RWS_EditAccounController controller = new RWS_EditAccounController();
			controller.finalUpdateAcccountContact();
			//this code is weird. From the looks of it, the method will ALWAYS return the error message.
			Id myType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('M3 Wholesale Accounts').getRecordTypeId(); 
			System.assert(myType != null );
 		}
	} 
}