force-app/main/default/objects/Store_IA_Account__c/Store_IA_Account__c.object-meta.xml
<CustomObject>
    <description>Object for Red Wing Store and IA Account relationships.  When a Red Wing Store creates a new IA account a record is inserted into this object via APEX.
Object Type: IA
Integrated: N</description>
    <label>Store IA Account</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Store IA Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store IA Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_IA_Account__c/fields/IA_Account__c.field-meta.xml
<CustomField>
    <fullName>IA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to an Industrial Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to an Industrial Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.</inlineHelpText>
    <label>IA Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store IA Account</relationshipLabel>
    <relationshipName>Store_IA_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_IA_Account__c/fields/Store_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.</inlineHelpText>
    <label>Store Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store IA Account</relationshipLabel>
    <relationshipName>Store_IA_Account_del1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_StoreIAAccount_Trigger_Handler.cls
public with sharing class RWS_StoreIAAccount_Trigger_Handler {
	public static void beforeDelete(List<Store_IA_Account__c> oldRecords) {
		Set<Id> storeAccountIds = new Set<Id>();
		Set<Id> iaAccountIds = new Set<Id>();

		for(Store_IA_Account__c s : oldRecords) {
			if(s.Store_Account__c == null) continue;

			storeAccountIds.add(s.Store_Account__c);

			if(s.IA_Account__c != null) iaAccountIds.add(s.IA_Account__c);
		}

		if(storeAccountIds.isEmpty()) return;

		Set<Id> userIds = new Map<Id, User>([select Id from User where AccountId in :storeAccountIds]).keySet();


		delete [select Id from AccountShare where AccountId in :iaAccountIds and UserOrGroupId in :userIds];
	}
}