force-app/main/default/objects/Account/fields/Account_Number_BPC__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_BPC__c</fullName>
    <formula>IF(  ISBLANK(AccountNumber) ,  Account_Number_Helper__c , AccountNumber  )</formula>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>Activation Date for an IA Account. (Set by Workflow)</description>
    <inlineHelpText>Activation Date for an IA Account  (Set by Workflow)</inlineHelpText>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Approval_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Credit_Approval_Indicator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Credit Dept has approved credit for this account. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates credit has been approved by the Credit Dept. Sent to Salesforce by IA.</inlineHelpText>
    <label>Credit Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Status__c</fullName>
    <inlineHelpText>Maintained by MultiService. Submitted Value only used for internal processes.</inlineHelpText>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved/Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Credit Hold</fullName>
            </value>
            <value>
                <fullName>Application Sent</fullName>
                <isActive>false</isActive>
                <label>Application Sent</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_City__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_City__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_State_Province__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_State_Province__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IA_Physical_Location_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>--Select--</fullName>
                <default>true</default>
                <label>--Select--</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Alabama</label>
            </value>
            <value>
                <fullName>AK</fullName>
                <label>Alaska</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Arizona</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Arkansas</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>California</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colorado</label>
            </value>
            <value>
                <fullName>CT</fullName>
                <label>Connecticut</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Delaware</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>Florida</label>
            </value>
            <value>
                <fullName>GA</fullName>
                <label>Georgia</label>
            </value>
            <value>
                <fullName>HI</fullName>
                <label>Hawaii</label>
            </value>
            <value>
                <fullName>ID</fullName>
                <label>Idaho</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>Illinois</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Indiana</label>
            </value>
            <value>
                <fullName>IA</fullName>
                <label>Iowa</label>
            </value>
            <value>
                <fullName>KS</fullName>
                <label>Kansas</label>
            </value>
            <value>
                <fullName>KY</fullName>
                <label>Kentucky</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <label>Louisiana</label>
            </value>
            <value>
                <fullName>ME</fullName>
                <label>Maine</label>
            </value>
            <value>
                <fullName>MD</fullName>
                <label>Maryland</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <label>Massachusetts</label>
            </value>
            <value>
                <fullName>MI</fullName>
                <label>Michigan</label>
            </value>
            <value>
                <fullName>MN</fullName>
                <label>Minnesota</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>Mississippi</label>
            </value>
            <value>
                <fullName>MO</fullName>
                <label>Missouri</label>
            </value>
            <value>
                <fullName>MT</fullName>
                <label>Montana</label>
            </value>
            <value>
                <fullName>NE</fullName>
                <label>Nebraska</label>
            </value>
            <value>
                <fullName>NV</fullName>
                <label>Nevada</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>New Hampshire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NA_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>NA_Account_Status__c</fullName>
    <description>The IA Account Status; Active or Inactive 
Type: IA
Integrated: Y</description>
    <inlineHelpText>The IA Account Status; Active or Inactive. Sent to Salesforce by IA.</inlineHelpText>
    <label>IA Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Owning_Store__c.field-meta.xml
<CustomField>
    <fullName>Owning_Store__c</fullName>
    <description>The owning store comes from the company name field on the user record.</description>
    <formula>Owner.CompanyName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Red Wing Store that owns the account.</inlineHelpText>
    <label>Owning Store</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recourse_Customer__c.field-meta.xml
<CustomField>
    <fullName>Recourse_Customer__c</fullName>
    <description>Identifies if the Account is on recourse.</description>
    <inlineHelpText>Identifies if the Account is on recourse.</inlineHelpText>
    <label>Recourse Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>TemporaryCorporate</fullName>
                <label>Temporary Corporate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NA_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>NA_Account_Status__c</fullName>
    <description>For National Accounts Only; from R-00880</description>
    <formula>TEXT(Account.NA_Account_Status__c)</formula>
    <label>NA Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Industrial Account (Account Standard Object) for the program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to Industrial Account (Account Standard Object) for the program.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>The activation (effective) date of an Industrial Account Program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The activation (effective) date of an Industrial Account Program.</inlineHelpText>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/RWBAA_AR_Data__c.object-meta.xml
<CustomObject>
    <label>RWBAA AR Data</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>RWBAA AR Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWBAA AR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/Accounts_Receivable_Alert__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Receivable_Alert__c</fullName>
    <formula>IF(
OR( MSTS_AR_8_to_14__c &gt; 0,
    MSTS_AR_15_to_30__c &gt; 0,
    MSTS_AR_31_to_45__c &gt; 0,
    MSTS_AR_46_to_60__c &gt; 0,
    MSTS_AR_61_to_90__c  &gt; 0,
    MSTS_AR_91_to_120__c &gt; 0,
    MSTS_AR_121_to_150__c  &gt; 0,
    MSTS_AR_Over_150__c &gt; 0), &quot;AR&quot;,
    NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts Receivable Alert</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/Accounts_Receivable_Alert_Color__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Receivable_Alert_Color__c</fullName>
    <formula>IF(
AND(
OR( MSTS_AR_8_to_14__c &gt; 0,
MSTS_AR_15_to_30__c &gt; 0,
MSTS_AR_31_to_45__c &gt; 0),


MSTS_AR_46_to_60__c &lt;= 0,
MSTS_AR_61_to_90__c &lt;= 0,
MSTS_AR_91_to_120__c &lt;= 0,
MSTS_AR_121_to_150__c &lt;= 0,
MSTS_AR_Over_150__c &lt;= 0), &quot;Yellow&quot;,

IF(
OR(MSTS_AR_46_to_60__c &gt; 0,
MSTS_AR_61_to_90__c &gt; 0,
MSTS_AR_91_to_120__c &gt; 0,
MSTS_AR_121_to_150__c &gt; 0,
MSTS_AR_Over_150__c &gt; 0), &quot;Red&quot;,
NULL
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts Receivable Alert Color</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/Credit_Hold_Alert__c.field-meta.xml
<CustomField>
    <fullName>Credit_Hold_Alert__c</fullName>
    <formula>IF( TEXT(Account__r.Credit_Status__c) = &quot;Credit Hold&quot;, &quot;CH&quot;,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Hold Alert</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/Credit_Hold_Alert_Color__c.field-meta.xml
<CustomField>
    <fullName>Credit_Hold_Alert_Color__c</fullName>
    <formula>IF( TEXT(Account__r.Credit_Status__c) = &quot;Credit Hold&quot;,&quot;Red&quot;,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Hold Alert Color</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/Credit_Limit_Alert__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Alert__c</fullName>
    <formula>IF( 
MSTS_Credit_Limit__c = 0 &amp;&amp; MSTS_Available_Credit__c &lt;&gt; 0, &quot;CL&quot;,
IF(MSTS_Credit_Limit__c = 0 &amp;&amp; MSTS_Available_Credit__c = 0,NULL,
IF(
MSTS_Available_Credit__c / MSTS_Credit_Limit__c &lt;= 0.4,&quot;CL&quot;
,NULL)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Limit Alert</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_AccountHomeController.cls
Public with sharing class RWS_AccountHomeController{

   
    // UA: 05-Oct: added transient keyword to avoid view state limit
    public transient String jsonResult     {set;get;}
    public transient List<AccountWrap> accListWrap {get;set;}
    
    //added by Joey
    public Boolean isFullAccessUser {get;set;}
    
    //added by BW for accountList search
    public String searchBoxFilter { get; set; }
    
    public List<SelectOption> accountViews
    {
        get
        {
            if(accountViews == null )
            {
                accountViews = new List<SelectOption>();
                accountViews.add(new SelectOption('National Accounts', 'National Accounts'));
                accountViews.add(new SelectOption('Active Store Accounts', 'Active Store Accounts'));
                accountViews.add(new SelectOption('Inactive Store Accounts', 'Inactive Store Accounts'));
            }
            return accountViews ;
        }
        set; 
    }
    
    public String selectedAccountView {get; set; }
   
    //query variables
    public String searchTerm {get; set;}
    public String query {get; set;}
    Id currentUserId {get; set;}        
    String recordtypeid {get; set;}
    String programSubQuery {get; set;}
    set<id> editableAccts {get; set;}
        
            
    //Constructor
    public RWS_AccountHomeController()
    {
        //initialize and assign values to query variables
        currentUserId = UserInfo.getUserId();        
        recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Partner Community').getRecordTypeId();
        programSubQuery = '';
        editableAccts = new set<Id>();
        searchTerm = '';
        searchBoxFilter = 'active';
        
        // added by Joey
        isFullAccessUser = RWS_UtilityClass.isFullAccessUser();      
        
       
        
        //sets the correct list view for user based on limited user custom setting - BW 7/7/17
        if (isFullAccessUser){
            selectedAccountView = 'Active Store Accounts';
        } else {
            selectedAccountView = 'National Accounts';
        }
        
        setQueryListView();        
        getAccounts();
        
    }
    
    //method to set query for list views
    //RW: (Rajani on 9/13/2019) --- Adding RWBAA AR Data on Account Screen
    public void setQueryListView(){
        system.debug('1*****==>' +selectedAccountView);
        
        query = 'SELECT Credit_Approval_Indicator__c, Id, Name, Active__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, NA_Account_Status__c, Activation_Date__c, Account_Number_BPC__c, ' +
                    'Credit_Status__c, IA_Physical_Location_City__c, IA_Physical_Location_State_Province__c, AccountNumber, Owning_Store__c, Recourse_Customer__c, (SELECT Id, Name FROM Programs__r ' + programSubQuery + ') , ' +
					'(SELECT Accounts_Receivable_Alert__c, Accounts_Receivable_Alert_Color__c, '+ 
					'Credit_Hold_Alert__c, Credit_Hold_Alert_Color__c, '+
					'Credit_Limit_Alert__c, Credit_Limit_Alert_Color__c FROM RWBAA_AR_Data__r)' +
					'FROM Account ' +
                    'WHERE RecordTypeId = :recordtypeid ';
        
        
       
        
            if(selectedAccountView == 'National Accounts') query += ' AND Organization_Type__c =\'National\' and Active__c = true ' ;
            if(selectedAccountView == 'Active Store Accounts') query += ' AND (Owner.Contact.Account.RecordType.Name = \'M3 Store Parent Account\' OR Owner.Contact.Account.RecordType.Name = \'M3 Store Child Account\')  and Active__c = true ' ;
            if(selectedAccountView == 'Inactive Store Accounts') query += ' AND (Owner.Contact.Account.RecordType.Name = \'M3 Store Parent Account\' OR Owner.Contact.Account.RecordType.Name = \'M3 Store Child Account\')  and Active__c = false ' ;
        
        
        query += ' limit 1000 ';


    }
    
    //method to set query for search box
    public void setQuerySearch(){
        system.debug('2*****==>'+searchTerm+'----'+searchBoxFilter);        
        query = 'SELECT Credit_Approval_Indicator__c, Id, Name, Active__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, NA_Account_Status__c, Activation_Date__c, Account_Number_BPC__c, ' +
                    'Credit_Status__c, IA_Physical_Location_City__c, IA_Physical_Location_State_Province__c, Recourse_Customer__c, AccountNumber, Owning_Store__c, (SELECT Id, Name FROM Programs__r ' + programSubQuery + ') , ' +
					'(SELECT Accounts_Receivable_Alert__c, Accounts_Receivable_Alert_Color__c, '+ 
					'Credit_Hold_Alert__c, Credit_Hold_Alert_Color__c, '+
					'Credit_Limit_Alert__c, Credit_Limit_Alert_Color__c FROM RWBAA_AR_Data__r)' +
                    'FROM Account ' +
                    'WHERE RecordTypeId = :recordtypeid ';//Id =\'001W000000Xrnsn\' and 
        
        
         //Sets query for Active Accounts Only search box option
        if (searchBoxFilter == 'active'){
            query += 'AND Active__c = true';
        }

       
        
        //Sets query for My Store Accounts search box option
        if (searchBoxFilter == 'myStore'){
            
            for(AccountShare acs : [select AccountAccessLevel, AccountId from AccountShare where UserOrGroupId =: UserInfo.getUserId() and (AccountAccessLevel = 'Edit' or AccountAccessLevel = 'All') ]){
                editableAccts.add(acs.AccountId);
            }
            query += 'AND Id in: editableAccts';
        }
        
         if(!String.isBlank(searchTerm)) {
            searchTerm = String.escapeSingleQuotes(searchTerm);
            query += ' AND (Name like \'%' + searchTerm + '%\' OR AccountNumber like \'%' + searchTerm + '%\') ' ;
         }
         
        query += ' limit 1000 ';


    }
        
    public void getAccounts()
    {
        accListWrap = new List<AccountWrap>();
       
        //Id currentUserId = UserInfo.getUserId() ;
        
        /*
        User currentUser = [select Id, Contact.Account.Store_Ownership_Type__c, Contact.Account.Dealer__c, 
                                    Contact.Account.Region_Code__c, Contact.AccountId, AccountId
                            from User 
                            where Id = :UserInfo.getUserId()];

        Set<Id> allAccountIds = new Set<Id>();
        
        if(currentUser.Contact.AccountId != null)
            allAccountIds.add(currentUser.Contact.AccountId);
        
        if(currentUser.Contact.Account.Dealer__c != null) {
            for(Account a : [select Id, Dealer__c from Account 
                             where Dealer__c = :currentUser.Contact.Account.Dealer__c]) {
                                 
                allAccountIds.add(a.Id);
            }
        }
        
        Set<Id> userIds = new Set<Id>();
        for(User u : [select Id from User where Contact.AccountId in :allAccountIds]) {
            userIds.add(u.Id);
        }
        
        userIds.add(currentUser.Id);
        */

        
        // if(selectedAccountView == 'Store Accounts' || selectedAccountView == 'Pending Accounts') 
        //    programSubQuery = ' where Active__c = true ';

      /*  
      
        String recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Partner Community').getRecordTypeId();
        String programSubQuery = '';
      
        query = 'SELECT Credit_Approval_Indicator__c, Id, Name, Active__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, NA_Account_Status__c, Activation_Date__c, Account_Number_BPC__c, ' +
                    'Credit_Status__c, IA_Physical_Location_City__c, IA_Physical_Location_State_Province__c, AccountNumber, Owning_Store__c, (SELECT Id, Name FROM Programs__r ' + programSubQuery + ') ' +
                    'FROM Account ' +
                    'WHERE RecordTypeId = :recordtypeid ';//' AND Id IN :industrialAccountSet ';
        


        //Sets query for Active Accounts Only search box option
        if (searchBoxFilter == 'active'){
            query += 'AND Active__c = true';
        }

        set<id> editableAccts = new set<Id>();
        
        //Sets query for My Store Accounts search box option
        if (searchBoxFilter == 'myStore'){
            
            for(AccountShare acs : [select AccountAccessLevel, AccountId from AccountShare where UserOrGroupId =: UserInfo.getUserId() and (AccountAccessLevel = 'Edit' or AccountAccessLevel = 'All') ]){
                editableAccts.add(acs.AccountId);
            }
            query += 'AND Id in: editableAccts';
        }
        
        System.debug('Find Me: ' + query);

        if(!String.isBlank(searchTerm)) {
            searchTerm = String.escapeSingleQuotes(searchTerm);
            query += ' AND (Name like \'%' + searchTerm + '%\' OR AccountNumber like \'%' + searchTerm + '%\') ' ;
        } else {
            if(selectedAccountView == 'National Accounts') query += ' AND Organization_Type__c =\'National\' and Active__c = true ' ;
            if(selectedAccountView == 'Store Accounts') query += ' AND (Owner.Account.RecordType.Name = \'M3 Store Parent Account\' OR Owner.Account.RecordType.Name = \'M3 Store Child Account\')  and Active__c = true ' ;
            if(selectedAccountView == 'Pending Accounts') query += ' AND (Owner.Account.RecordType.Name = \'M3 Store Parent Account\' OR Owner.Account.RecordType.Name = \'M3 Store Child Account\')  and Active__c = false ' ;
        }
        
        query += ' limit 1000 ';
        */
        
        System.debug('Query to be run: ' + query);
        
        List<Account> accountList = Database.query(query);
        
        System.debug('Returned Account List: ' + accountList);
        
        User currentUser = [select Id, CompanyName
                            from User 
                            where Id = :currentUserId];
        System.debug('User Info: ' + currentUser);
                           
        for(Account obj : accountList)
        {            
            AccountWrap wrapObj = new AccountWrap();            
            wrapObj.AccountAlerts = new Map<string,string>();
            wrapObj.NoOfPrograms = obj.Programs__r.size();                    
            if(currentUser.CompanyName == obj.Owning_Store__c)
            {
	 			if(obj.RWBAA_AR_Data__r.size() != 0)
	            {
	                List<RWBAA_AR_Data__c> rwbaaList = obj.RWBAA_AR_Data__r;
	                for(RWBAA_AR_Data__c rwbaa : rwbaaList)
	                {    
	                    System.debug('Company Name: ' + currentUser.CompanyName + ' ' + ' ' + obj.Owning_Store__c);                    
	
	                        if(rwbaa.Accounts_Receivable_Alert__c != null){        		            		
	                            wrapObj.AccountAlerts.Put(rwbaa.Accounts_Receivable_Alert__c, rwbaa.Accounts_Receivable_Alert_Color__c);
	                        }  
	                        if(rwbaa.Credit_Hold_Alert__c != null)    
	                        {      		
	                            wrapObj.AccountAlerts.Put(rwbaa.Credit_Hold_Alert__c, rwbaa.Credit_Hold_Alert_Color__c);     
	                        }     
	                        if(rwbaa.Credit_Limit_Alert__c != null){   		
	                            wrapObj.AccountAlerts.Put(rwbaa.Credit_Limit_Alert__c, rwbaa.Credit_Limit_Alert_Color__c);            		
	                        }
	                         System.debug('RWBAA to Map: ' + wrapObj.AccountAlerts);
	                }
	            }
	            else if (obj.Credit_Status__c == 'Credit Hold'){
	            	wrapObj.AccountAlerts.Put('CH','RED');
	            }
            }
            wrapObj.AccountAlertSize = wrapObj.AccountAlerts.size();
            wrapObj.URLEdit = 'RWS_Account_CreationV2?tab=account&link=edit&id='+obj.id;
            wrapObj.URLSummary = 'AccountSummary?tab=account&id='+obj.id;
            wrapObj.URLAccountAlert = 'RWS_AccountRwbaaSummary?id='+obj.id;
            wrapObj.accObj = obj;
            
            if(obj.Active__c == False){
                wrapObj.Active = 'Inactive';
            }
            else{
                wrapObj.Active = 'Active';
            }
            
            //Sets Location column for Accounts list datatable - BW 7/7/17
            if  (obj.IA_Physical_Location_City__c == null && obj.IA_Physical_Location_City__c == null){
                 wrapObj.Location = 'Not Available';
            } else if (obj.IA_Physical_Location_City__c == null && obj.IA_Physical_Location_City__c != null){
                 wrapObj.Location = obj.IA_Physical_Location_State_Province__c ;
            } else if (obj.IA_Physical_Location_City__c != null && obj.IA_Physical_Location_City__c == null){
                 wrapObj.Location =  obj.IA_Physical_Location_City__c;
            } else {
                wrapObj.Location =  obj.IA_Physical_Location_City__c + ', ' + obj.IA_Physical_Location_State_Province__c ;
            }
            accListWrap.Add(wrapObj);
        }
        
        searchTerm = '';
        
        System.debug('Account List Wrapper: ' + accListWrap);
        
        jsonAccountList();

    }
    public void jsonAccountList(){
        jsonResult = JSON.serialize(AccListWrap);
        jsonResult = String.escapeSingleQuotes(jsonResult);
        
        System.debug('JSON account list: '+ jsonResult);
    }
    
    public PageReference RedirectToEdit(String Id){
        return null;
    }

    public class AccountWrap{
        String URLEdit {get;set;}
        String URLSummary {get;set;}
        String URLAccountAlert {get;set;}
        Integer NoOfPrograms {get;set;}        
        String Active {get;set;}
        String Location {get;set;}
        Map<string,string> AccountAlerts {get;set;}
        Integer AccountAlertSize {get;set;}
        Account AccObj {get;set;}
    }
}