force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Atributes_Required__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Atributes_Required__c</fullName>
    <description>Select up to 4 Invoice Attributes Required for the Account. This information is also copied to the Account&apos;s Programs where Type is not Cash and Carry. These are related directly to the Account_Invoice_Attributes_Up_to_4 validation rule. Both must be in sync.</description>
    <inlineHelpText>Select up to 4 Invoice Attributes Required for the Account. This information is also copied to the Account&apos;s Programs where Type is not Cash and Carry.</inlineHelpText>
    <label>Invoice Attributes Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Authform</fullName>
                <label>Auth form #</label>
            </value>
            <value>
                <fullName>AuthorizerManager</fullName>
                <label>Authorizer / Manager</label>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>BusinessUnit</fullName>
                <label>Business Unit</label>
            </value>
            <value>
                <fullName>Certificate</fullName>
                <label>Certificate #</label>
            </value>
            <value>
                <fullName>ChargeCode</fullName>
                <label>Charge Code</label>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>CostCenter</fullName>
                <label>Cost Center</label>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Division</fullName>
            </value>
            <value>
                <fullName>EmployeeID</fullName>
                <label>Employee ID</label>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>GL</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
                <label>Project #</label>
            </value>
            <value>
                <fullName>Purchaseorder</fullName>
                <label>Purchase order</label>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>TicketReceipt</fullName>
                <label>Ticket/Receipt</label>
            </value>
            <value>
                <fullName>VendorNumber</fullName>
                <label>Vendor Number</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>UDF</fullName>
                <isActive>false</isActive>
                <label>UDF</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RWS_UserAccess_Controller_Test.cls
@isTest
private class RWS_UserAccess_Controller_Test {
	static testMethod void testController() {

		Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');
		
        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, false);
        acc.Invoice_Atributes_Required__c = 'Branch';
        insert acc;

        Program__c pr = RWS_TestUtil.createProgram(acc.Id, false);
        pr.Active__c = false;
        insert pr;

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        insert con1;

        Id roleId = [select Id from UserRole where Name = 'System Administrators' limit 1].Id;

        User u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {

            User user = new User(Id = UserInfo.getUserId(), UserRoleId = roleId);
            update user;

            insert u1;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u1.UserRoleId = partnerRoleId;

            update u1;
        }

        PageReference pg = Page.RWS_UserAccess;

        Test.setCurrentPageReference(pg);

        ApexPages.StandardController sc = new ApexPages.StandardController(con1);

        RWS_UserAccess_Controller cont = new RWS_UserAccess_Controller(sc);

        System.assertNotEquals(null, cont.updateSharing());
	}
}