force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NA_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>NA_Account_Status__c</fullName>
    <description>The IA Account Status; Active or Inactive 
Type: IA
Integrated: Y</description>
    <inlineHelpText>The IA Account Status; Active or Inactive. Sent to Salesforce by IA.</inlineHelpText>
    <label>IA Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Preference__c.field-meta.xml
<CustomField>
    <fullName>Contact_Preference__c</fullName>
    <inlineHelpText>Inidicate the method by which this Contact prefers to be contacted</inlineHelpText>
    <label>Contact Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <color>#0B6FCE</color>
                <label>Email</label>
            </value>
            <value>
                <fullName>Phone - Office</fullName>
                <color>#78C953</color>
                <label>Phone - Office</label>
            </value>
            <value>
                <fullName>Phone - Mobile</fullName>
                <color>#E27001</color>
                <label>Phone - Mobile</label>
            </value>
            <value>
                <fullName>USPS</fullName>
                <color>#A845DC</color>
                <label>USPS</label>
            </value>
            <value>
                <fullName>Fax</fullName>
                <color>#F3D904</color>
                <label>Fax</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NA_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>NA_Account_Status__c</fullName>
    <description>For National Accounts Only; from R-00880</description>
    <formula>TEXT(Account.NA_Account_Status__c)</formula>
    <label>NA Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Identify the role(s) this contact plays</inlineHelpText>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Assistant</fullName>
            </value>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Company Executive</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>EH&amp;S (Environmental, Health, Safety)</fullName>
            </value>
            <value>
                <fullName>Facility/Operations Manager</fullName>
            </value>
            <value>
                <fullName>Human Resource Management</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Purchasing Management</fullName>
            </value>
            <value>
                <fullName>Safety Director</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>Store Manager</fullName>
            </value>
            <value>
                <fullName>Truck Run Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_EditAccounController.cls
public class RWS_EditAccounController {

    public String duplicationMessage { get; set; }
    public Account editAccount { get; set; }
    public Contact editContact { get; set; }
    public List<Account> accList;
    public Account createAccount;
    public Contact createContact;
    public String accountId;
    
    
    // Controller 
    public RWS_EditAccounController(){
        string Id= Apexpages.currentpage().getparameters().get('id');
        //accountId = Apexpages.currentpage().getparameters().get('id');
        createAccount = new Account();
        createContact = new Contact();
        accList = new List<Account>();
        duplicationMessage = '';
        editAccount = [select id,Name,BillingStreet,BillingCity,BillingState,BillingPostalCode from Account where id =: Id];//accountId
        editContact = [select id,FirstName,LastName,Email,Phone,Title,Fax,AccountId from Contact where AccountId =:editAccount.id limit 1];
        
    }
    
    // Save Account,Contact
    public void updateAcccountContact(){
            System.debug('*********Update Account Contact method');
        //Check duplication of Account based on Account Details 
        accList = [select Id,Name from Account where Name =:editAccount.Name]; 
        //AND BillingStreet = :accountStreet
        //AND BillingCity = :accountCity 
        //AND BillingState = :accountState
        //AND BillingPostalCode = :accountZipCode];
        system.debug('accList ===: ' + accList.size());
        if(accList.size()>0){
            duplicationMessage = 'We detected an account already established for : ' + editAccount.Name;
            //throw error message for duplication account 
        }
        else{
            finalUpdateAcccountContact();  // Method to update Account and contact records.
        }
        system.debug('duplicationMessage ===: ' + duplicationMessage);
        
    }
    
    public void finalUpdateAcccountContact(){
        createAccount.Id = editAccount.Id;
        createAccount.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('M3 Wholesale Accounts').getRecordTypeId();
        createAccount.Name = editAccount.Name;
        if (editAccount.BillingStreet!= null){
            createAccount.BillingStreet =  editAccount.BillingStreet;
        }
        createAccount.BillingCity = editAccount.BillingCity;
        createAccount.BillingState = editAccount.BillingState;
        createAccount.BillingPostalCode = editAccount.BillingPostalCode;
        createAccount.NA_Account_Status__c = 'Inactive';
        try{
            update createAccount;
            if(createAccount.id!=Null){
                createContact.Id = editContact.Id;
                createContact.recordtypeid = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('General Contact').getRecordTypeId();
                createContact.AccountId = createAccount.id;
                createContact.FirstName = editContact.FirstName;
                createContact.LastName = editContact.LastName;
                createContact.Email = editContact.Email;
                createContact.Phone = editContact.Phone;
                //createContact.Active__c = isActive;
                createContact.Title = editContact.Title;
                createContact.Fax = editContact.Fax;
                //createContact.MobilePhone = contactmobilePhone;
                //createContact.Role__c = contactRole;
                //createContact.Contact_Preference__c = contactPreference;
                update createContact;
            }
        }
        catch(Exception e){
            //TODO: implement something here?
        }
    }
}