force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Account Publish Status</description>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Program Publish Status</description>
    <inlineHelpText>Program Publish Status</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_ppbButtonTest.cls
@isTest
private class RWS_ppbButtonTest {
  
    //test
    @isTest
    static void testppbButton() {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Partner Community').getRecordTypeId();
        Account acc = RWS_TestUtil.createAccount(recordTypeId, true);
        Program__c prgm = RWS_TestUtil.createProgram(acc.Id, false);
        prgm.Publish_Status__c = 'Published';
        insert prgm;
        
        Publish_Pricebook__c ppb = RWS_TestUtil.createCustomPublishPricebook(prgm.Id, true);
        
        Product2 p1 = RWS_TestUtil.createProduct('1', true);
        Product2 p2 = RWS_TestUtil.createProduct('2', true);
        Product2 p3 = RWS_TestUtil.createProduct('3', true);
        Product2 p4 = RWS_TestUtil.createProduct('4', true);
        
        Publish_Pricebook_Entry__c ppbe1 = RWS_TestUtil.createPublishPricebookEntry(ppb.Id, p1.Id, true);
        Publish_Pricebook_Entry__c ppbe2 = RWS_TestUtil.createPublishPricebookEntry(ppb.Id, p2.Id, true);
        Publish_Pricebook_Entry__c ppbe3 = RWS_TestUtil.createPublishPricebookEntry(ppb.Id, p3.Id, true);
        Publish_Pricebook_Entry__c ppbe4 = RWS_TestUtil.createPublishPricebookEntry(ppb.Id, p4.Id, true);
        
        ppbe1.Active__c = true;
        ppbe1.Publish_Status__c = 'Waiting';
        update ppbe1;
        ppbe2.Active__c = true;
        ppbe2.Publish_Status__c = 'Deactivated';
        update ppbe2;
        ppbe3.Active__c = false;
        ppbe3.Publish_Status__c = 'Deactivated';
        update ppbe3;
        ppbe4.Active__c = true;
        ppbe4.Publish_Status__c = 'Published';
        update ppbe4;
        
        System.debug('ppbe1: '+ppbe1.Publish_Status__c);
        System.debug('ppbe2: '+ppbe2.Publish_Status__c);
        System.debug('ppbe3: '+ppbe3.Publish_Status__c);
        System.debug('ppbe4: '+ppbe4.Publish_Status__c);
                        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(ppb);
        RWS_ppbButtonController testPpbButton = new RWS_ppbButtonController(sc);
        
        PageReference pageRef = Page.RWS_ppbButtonPage; 
        
        pageRef.getParameters().put('id', String.valueOf(ppb.Id));
        
        Test.setCurrentPage(pageRef);
        
        testPpbButton.autoRun();
       
        Test.stopTest();
        
        Publish_Pricebook_Entry__c updatedPPBE1 = [SELECT Publish_Status__c FROM Publish_Pricebook_Entry__c WHERE Id =: ppbe1.Id];
        Publish_Pricebook_Entry__c updatedPPBE2 = [SELECT Publish_Status__c FROM Publish_Pricebook_Entry__c WHERE Id =: ppbe2.Id];
        Publish_Pricebook_Entry__c updatedPPBE3 = [SELECT Publish_Status__c FROM Publish_Pricebook_Entry__c WHERE Id =: ppbe3.Id];
        Publish_Pricebook_Entry__c updatedPPBE4 = [SELECT Publish_Status__c FROM Publish_Pricebook_Entry__c WHERE Id =: ppbe4.Id];
        
        System.debug('updatedPPBE1: '+updatedPPBE1.Publish_Status__c);
        System.debug('updatedPPBE2: '+updatedPPBE2.Publish_Status__c);
        System.debug('updatedPPBE3: '+updatedPPBE3.Publish_Status__c);
        System.debug('updatedPPBE4: '+updatedPPBE4.Publish_Status__c);
        
        System.assertEquals('Published', updatedPPBE1.Publish_Status__c);
        System.assertEquals('Published', updatedPPBE2.Publish_Status__c); 
        System.assertEquals('Deactivated', updatedPPBE3.Publish_Status__c);
        System.assertEquals('Published', updatedPPBE4.Publish_Status__c);        

    }
  
    
    
    
}