force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RWS_ProgramActivationJob_Test.cls
@isTest
private class RWS_ProgramActivationJob_Test {
    static testMethod void testJob() {
        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

    	Account acc = RWS_TestUtil.createAccount(rtId, true);

    	Program__c pr = RWS_TestUtil.createProgram(acc.Id, true);

    	System.assert([select Active__c from Program__c where Id = :pr.Id].Active__c);

    	Test.startTest();
    		RWS_ProgramActivationJob job = new RWS_ProgramActivationJob();
			job.execute(null);
		Test.stopTest();

		System.assert(![select Active__c from Program__c where Id = :pr.Id].Active__c);
    }
}