force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Account Publish Status</description>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Published_Date__c.field-meta.xml
<CustomField>
    <fullName>Published_Date__c</fullName>
    <description>Date when account was published to subscribers</description>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>The Industrial Account Program&apos;s expiration date.  A program will become inactive if the expiration date is less than today.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Industrial Account Program&apos;s expiration date.  A program will become inactive if the expiration date is less than today.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Program Publish Status</description>
    <inlineHelpText>Program Publish Status</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Published_Date__c.field-meta.xml
<CustomField>
    <fullName>Published_Date__c</fullName>
    <description>Program Published Date</description>
    <inlineHelpText>Program Published Date</inlineHelpText>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Published_Date__c.field-meta.xml
<CustomField>
    <fullName>Published_Date__c</fullName>
    <description>The Published Date of the outbound message.  Updated by workflow field update, when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Published Date of the outbound message.  Updated by workflow field update, when outbound message is triggered.</inlineHelpText>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</description>
    <inlineHelpText>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</inlineHelpText>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Published_Date__c.field-meta.xml
<CustomField>
    <fullName>Published_Date__c</fullName>
    <description>Outbound Message Published Date
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Outbound Message Published Date</inlineHelpText>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/Servicing_Store__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Object created to share programs based on servicing level with downstream systems via outbound message</description>
    <label>Servicing Store</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Servicing Store #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Servicing Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicing_Store__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Date/Time that is populated when the Servicing Store record is no longer Active.</description>
    <inlineHelpText>Date/Time that is populated when the Servicing Store record is no longer Active.</inlineHelpText>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Servicing Stores</relationshipLabel>
    <relationshipName>Servicing_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/fields/Program_Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Service_Level__c</fullName>
    <label>Program Service Level</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_ppbeAndServicingStoreDeleteBatchTest.cls
/************************************************************************
* Test class for the following Apex classes:
*
* RWS_ServicingStoreDeleteBatch
* RWS_PPBEDeleteBatch
* RWS_BatchDeleteSchedulable
*
* @Author: Brandon Willard
* @Date: 10/22/18
************************************************************************/ 
@isTest 
public class RWS_ppbeAndServicingStoreDeleteBatchTest {
    
    //Test Data Creation
    @testSetup 
    static void setup() {  
        //Get record type for Account
        Id accRecTypeId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');
        //Create and insert Account for Program creation
        Account acc = RWS_TestUtil.createAccount(accRecTypeId, true);
        //Create and insert Program for Publish Pricebook and Servicing Store creation
        Program__c prog = RWS_TestUtil.createProgram(acc.Id, true);
        //Create and insert Publish Pricebook for Publish Pricebook Entry creation
        Publish_PriceBook__c ppb = RWS_TestUtil.createCustomPublishPricebook(prog.Id, true);
        
        //Create 50 Servicing Stores for testing
        List<Servicing_Store__c> ssList = new List<Servicing_Store__c>();        
        for(Integer i=0 ;i <50;i++){
            Servicing_Store__c ss = RWS_TestUtil.createServicingStore(acc.Id, prog.Id, false);
            ss.Active__c = false;
            ss.Expiration_Date__c = Date.today()-8;
            ss.Published_Date__c = Date.today()-8;
            ss.Program_Service_Level__c = 'Dealer';       
            ssList.add(ss);
        }
        
        //Set the first 10 to Active__c = true 
        for(Integer i=0 ;i <10;i++){
            ssList[i].Active__c = true;
        }
        
        //Insert Servicing Store records
        insert ssList; 
        
        //Create 50 Product records for PPBE creation        
        List<Product2> prodList = new List<Product2>();        
        for(Integer i=0 ;i <50;i++){
            prodList.add(RWS_TestUtil.createProduct('prod'+i, false));
        }
        //Insert products
        insert prodList;
        
        //Create 50 Publish Pricebook Entry records for testing
        List<Publish_PriceBook_Entry__c> ppbeList = new List<Publish_PriceBook_Entry__c>();        
        for(Integer i=0 ;i <50;i++){            
            Publish_PriceBook_Entry__c ppbe = RWS_TestUtil.createPublishPricebookEntry(ppb.Id, prodList[i].Id, false);
            ppbe.Filter_Number__c = null;
            ppbe.Active__c = false;
            ppbe.Published_Date__c = Date.today()-8;                          
            ppbeList.add(ppbe);
        }
        
        //Set the first 10 with Filter_Number__c values
        for(Integer i=0 ;i <10;i++){
            ppbeList[i].Filter_Number__c = i;
        }
        //Insert PPBE records
        insert ppbeList;
        
        //Make sure publish status is changed from 'waiting' to 'deactivated'
        for (Publish_PriceBook_Entry__c ppbe : ppbeList){
            ppbe.Publish_Status__c = 'Deactivated';
        }
        //Update PPBE records
        update ppbeList;
        
    }
    
    //This method tests the deletion of Servicing_Store__c records
    @isTest
    static void testServicingStoreDelete() {
        
        //Assert that 50 Servicing_Store__c records exist
        List<Servicing_Store__c> ssListAll = [SELECT Id FROM Servicing_Store__c];    
        System.assertEquals(50, ssListAll.size());
        
        Test.startTest();
            //Execute Servicing Store batch job
            RWS_ServicingStoreDeleteBatch obj = new RWS_ServicingStoreDeleteBatch();
            DataBase.executeBatch(obj);            
        Test.stopTest();
        
        //Assert that there are only 10 Servicing_Store__c records from the original 50 after batch runs
        List<Servicing_Store__c> ssList = [SELECT Id, Active__c FROM Servicing_Store__c];       
        System.assertEquals(10, ssList.size());
        
    }
    
    //This method tests the deletion of Publish_PriceBook_Entry__c records
    @isTest
    static void testPublishPricebookEntryDelete() {
        
        //Assert that 50 Publish_PriceBook_Entry__c records exist
        List<Publish_PriceBook_Entry__c> ppbeListAll = [SELECT Id FROM Publish_PriceBook_Entry__c]; 
        System.assertEquals(50, ppbeListAll.size());
        
        Test.startTest();
            //Execute PPBE batch job
            RWS_PPBEDeleteBatch obj = new RWS_PPBEDeleteBatch();
            DataBase.executeBatch(obj);            
        Test.stopTest();
        
        //Assert that there are only 10 Publish_PriceBook_Entry__c records from the original 50 after batch runs
        List<Publish_PriceBook_Entry__c> ppbeList = [SELECT Id, Publish_Status__c, Active__c, Filter_Number__c FROM Publish_PriceBook_Entry__c];       
        System.assertEquals(10, ppbeList.size());
        
    }
    
    //This method tests the scheduler class for code coverage
    @isTest
    static void testSchedulerClass() {
        String jobId  = RWS_BatchDeleteSchedulable.scheduleDeleteBatchJob();  
              
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same
        System.assertEquals(RWS_BatchDeleteSchedulable.CRON_EXPR, ct.CronExpression);
        
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
    }
    
}