force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_City__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_City__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_City__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_City__c</fullName>
    <description>M3 Physical Location Address - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: Y</description>
    <label>Physical Location City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RWS_ID__c.field-meta.xml
<CustomField>
    <fullName>RWS_ID__c</fullName>
    <description>M3 Account Unique External ID field. The same value is used for the M3 Account Number. DO NOT TOUCH.
Type: M3
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the M3 Account unique ID.</inlineHelpText>
    <label>RWS_ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Store_Number__c.field-meta.xml
<CustomField>
    <fullName>Store_Number__c</fullName>
    <description>This is the three digit store number in M3.
Field Type: M3
Integrated: Y -  M3&gt;SF&gt;Xstore pricing portal</description>
    <inlineHelpText>This is the three digit store number in M3.</inlineHelpText>
    <label>Store Number</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Login__c.field-meta.xml
<CustomField>
    <fullName>EMS_Login__c</fullName>
    <description>The alpha character EMS User Login name provided in the EMS
To SFDC integration</description>
    <inlineHelpText>The alpha character EMS User Login name provided in the EMS
To SFDC integration</inlineHelpText>
    <label>EMS Login</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>Entity_ID__c</fullName>
    <description>Entity ID provided in the EMS to SFDC integration</description>
    <inlineHelpText>Entity ID provided in the EMS to SFDC integration</inlineHelpText>
    <label>Entity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Identify the role(s) this contact plays</inlineHelpText>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Assistant</fullName>
            </value>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Company Executive</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>EH&amp;S (Environmental, Health, Safety)</fullName>
            </value>
            <value>
                <fullName>Facility/Operations Manager</fullName>
            </value>
            <value>
                <fullName>Human Resource Management</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Purchasing Management</fullName>
            </value>
            <value>
                <fullName>Safety Director</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>Store Manager</fullName>
            </value>
            <value>
                <fullName>Truck Run Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>For integration with M3</description>
    <externalId>true</externalId>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner_Community_Users.recordType-meta.xml
<RecordType>
    <fullName>Partner_Community_Users</fullName>
    <active>true</active>
    <description>Partner Community Contacts connected to Community User License</description>
    <label>Partner Community Users</label>
</RecordType>

force-app/main/default/classes/RWS_Contacts_Tests.cls
@isTest
public class RWS_Contacts_Tests {
    static testMethod void createContactTest() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
            Account a = new Account(
                Name = 'First Avenue', 
                Phone = '952-867-5309', 
                Store_Number__c = '137', 
                M3_Location_City__c = 'Minneapolis',
                AccountNumber = '7654321',
                IA_Physical_Location_City__c = 'Minneapolis'
            );
            insert a;
            RecordType r = [SELECT Id FROM RecordType WHERE DeveloperName = 'Partner_Community_Users' LIMIT 1];
            String body = '{"contacts" : [{"accountId":"' + a.Id + '", "firstName":"Andy", "lastName":"Hall", "jobTitle":"Store Manager", "emailAddress":"andy.hall@fake.com", "login":"andhall", "accountPhone":"' + a.Phone + 
    					  '", "recordId":"' + r.Id + '", "id":"1112223", "accountNumber":"' + a.AccountNumber + '", "active":"true"}]}';
            
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
        
            req.requestURI = '/services/apexrest/users';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(body);
            RestContext.request = req;
            RestContext.response = res;
            
            RWS_Contacts.createContacts();
            System.assertEquals(201, res.statusCode);
            Contact c = [SELECT AccountId, Firstname, Lastname, Role__c, Title, RWS_Id__c, Phone, RecordTypeId, Entity_ID__c, EMS_Login__c, Active__c FROM Contact WHERE Email = 'andy.hall@fake.com'];
            System.assertEquals(a.Id, c.AccountId);
            System.assertEquals('Andy', c.FirstName);
            System.assertEquals('Hall', c.Lastname);
            System.assertEquals('Store Manager', c.Title);
            System.assertEquals('andhall_' + a.AccountNumber, c.RWS_Id__c);
            System.assertEquals(a.Phone, c.Phone);
            System.assertEquals(r.Id, c.RecordTypeId);
            System.assertEquals('1112223', c.Entity_ID__c);
            System.assertEquals('andhall', c.EMS_Login__c);
            System.assertEquals(true, c.Active__c);
        }
    }
    
    static testMethod void createContactTestMultiple() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
            Account a = new Account(
                Name = 'First Avenue', 
                Phone = '952-867-5309', 
                Store_Number__c = '137', 
                M3_Location_City__c = 'Minneapolis',
                AccountNumber = '7654321',
                IA_Physical_Location_City__c = 'Minneapolis'
            );
            insert a;
            Account a2 = new Account(
                Name = 'Second Avenue', 
                Phone = '952-867-5308', 
                Store_Number__c = '138', 
                M3_Location_City__c = 'St. Paul',
                AccountNumber = '7654320',
                IA_Physical_Location_City__c = 'St. Paul'
            );
            insert a2;
            
            RecordType r = [SELECT Id FROM RecordType WHERE DeveloperName = 'Partner_Community_Users' LIMIT 1];
            String body = '{"contacts" : [{"accountId":"' + a.Id + '", "firstName":"Andy", "lastName":"Hall", "jobTitle":"Store Manager", "emailAddress":"andy.hall@fake.com", "login":"andhall", "accountPhone":"' + a.Phone + 
    					  '", "recordId":"' + r.Id + '", "id":"1112223", "accountNumber":"' + a.AccountNumber + '", "active":"true"},' +
                		  '{"accountId":"' + a2.Id + '", "firstName":"Frank", "lastName":"Sinatra", "jobTitle":"Store Manager", "emailAddress":"frank.sinatra@fake.com", "login":"frasina", "accountPhone":"' + a2.Phone + 
    					  '", "recordId":"' + r.Id + '", "id":"1112224", "accountNumber":"' + a2.AccountNumber + '", "active":"true"}]}';
            
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
        
            req.requestURI = '/services/apexrest/users';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(body);
            RestContext.request = req;
            RestContext.response = res;
            
            RWS_Contacts.createContacts();
            System.assertEquals(201, res.statusCode);
            Contact c = [SELECT AccountId, Firstname, Lastname, Role__c, Title, RWS_Id__c, Phone, RecordTypeId, Entity_ID__c, EMS_Login__c, Active__c FROM Contact WHERE Email = 'andy.hall@fake.com'];
            System.assertEquals(a.Id, c.AccountId);
            System.assertEquals('Andy', c.FirstName);
            System.assertEquals('Hall', c.Lastname);
            System.assertEquals('Store Manager', c.Title);
            System.assertEquals('andhall_' + a.AccountNumber, c.RWS_Id__c);
            System.assertEquals(a.Phone, c.Phone);
            System.assertEquals(r.Id, c.RecordTypeId);
            System.assertEquals('1112223', c.Entity_ID__c);
            System.assertEquals('andhall', c.EMS_Login__c);
            System.assertEquals(true, c.Active__c);
            
            Contact c2 = [SELECT AccountId, Firstname, Lastname, Role__c, Title, RWS_Id__c, Phone, RecordTypeId, Entity_ID__c, EMS_Login__c, Active__c FROM Contact WHERE Email = 'frank.sinatra@fake.com'];
            System.assertEquals(a2.Id, c2.AccountId);
            System.assertEquals('Frank', c2.FirstName);
            System.assertEquals('Sinatra', c2.Lastname);
            System.assertEquals('Store Manager', c2.Title);
            System.assertEquals('frasina_' + a2.AccountNumber, c2.RWS_Id__c);
            System.assertEquals(a2.Phone, c2.Phone);
            System.assertEquals(r.Id, c2.RecordTypeId);
            System.assertEquals('1112224', c2.Entity_ID__c);
            System.assertEquals('frasina', c2.EMS_Login__c);
            System.assertEquals(true, c2.Active__c);
        }
    }
}