force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Industrial Account (Account Standard Object) for the program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to Industrial Account (Account Standard Object) for the program.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <description>The Processing status determine the status of the related Product record creation for this program. Program Activation is dependent on the Program processing.</description>
    <inlineHelpText>The Processing status determine the status of the related Product record creation for this program. Program Activation is dependent on the Program processing.</inlineHelpText>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the program is a template</description>
    <inlineHelpText>Indicates if the program is a template</inlineHelpText>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Store_IA_Account__c/Store_IA_Account__c.object-meta.xml
<CustomObject>
    <description>Object for Red Wing Store and IA Account relationships.  When a Red Wing Store creates a new IA account a record is inserted into this object via APEX.
Object Type: IA
Integrated: N</description>
    <label>Store IA Account</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Store IA Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store IA Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_IA_Account__c/fields/Store_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.</inlineHelpText>
    <label>Store Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store IA Account</relationshipLabel>
    <relationshipName>Store_IA_Account_del1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_AccountSetupController_Test.cls
@isTest
public class RWS_AccountSetupController_Test {

    @isTest
    public static void InsertAccount_NoData_NoAccountId_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            //not sure if this is needs to be done per unit test method? I think so
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();

            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            System.assert(controller != null);
            //try to save an account without setting member variables in the controller
            controller.accountName = null;
            controller.accountLine1 = null;
            controller.accountCity = null;
            controller.accountstate = null;
            controller.accountZipCode = null;
            controller.accountCountry = null;
            controller.accountPhone = null;
            controller.SelectTaxExempt = null;
            controller.SelectTaxName = dataFactory.TaxExemptionReasons[0].Name;
            controller.TaxCertificateNumber = null;
            controller.TaxExpiryDate = date.newInstance(2017,12,31);
            
            Test.startTest();
            controller.insertAccount();
            controller.ListOfProgramWrap[0].Selected = true;
            controller.AddProgramToAccount(); 

            //if there isn't any data, there sure should be some error messages
            System.assert(ApexPages.getMessages() != null && ApexPages.getMessages().size() > 0);
            
            Test.stopTest();
        }
    }

    @isTest
    public static void AddProgramToAccount_Test(){
        Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, true);

        Id roleId = [select Id from UserRole where Name = 'System Administrators' limit 1].Id;

        User u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {

            User user = new User(Id = UserInfo.getUserId(), UserRoleId = roleId);
            update user;

            insert u1;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u1.UserRoleId = partnerRoleId;
            update u1;
        }


        System.runAs(u1) {

            Program__c pr = RWS_TestUtil.createProgram(null, false);
            pr.Active__c = false;
            pr.Template__c = true;
            pr.Processing_Status__c = 'Completed';
            insert pr;

            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', acc.Id);
            
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            //set a template as selected
            controller.listOfProgramWrap[0].Selected = true;
            //after the constructor is ran, there should be a list of contacts
            Integer numPrograms = [SELECT count()  
                                            FROM Program__c  
                                            WHERE Account__c = :acc.Id];
            
            Test.startTest();
            controller.AddProgramToAccount();

            Integer numPrograms2 = [SELECT count()  
                                            FROM Program__c  
                                            WHERE Account__c = :acc.Id];

            //in this case controller action should return null
            System.assert(numPrograms2 > numPrograms);
            Test.stopTest();
        }
    } 

    @isTest
    public static void AccountActivate_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();

            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
            RWS_AccountSetupController controller = new RWS_AccountSetupController();

            Test.startTest();
            controller.AccountActivate();
            //in this case controller action should return null
            System.assert(controller.AccountStatusMessage == 'Store One account is activated');
            Test.stopTest();

        }   
    }

    @isTest
    public static void ViewContact_Test(){
        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();

            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

            Test.startTest();
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            //set the contact id
            controller.deletedContactId = dataFactory.AccountContacts[0].Id;

            controller.ViewContact();
            //in this case controller action should return null
            System.assert(dataFactory.AccountContacts[0].FirstName == controller.contactFirstName);
            Test.stopTest();

        }
    } 
    
    @isTest
    public static void InsertAccount_WithData_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            //not sure if this is needs to be done per unit test method? I think so
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
            
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            System.assert(controller != null);
            //try to save an account without setting member variables in the controller
            controller.accountName = 'My Test Account';
            controller.accountLine1 = '123 East First St';
            controller.accountCity = 'Sartell';
            controller.accountstate = 'MN';
            controller.accountZIPCODE = '56377';
            controller.accountCountry = 'US';
            controller.accountPhone = '(541) 754-3010';
            controller.SelectTaxExempt = 'NO';
            controller.SelectTaxName = dataFactory.TaxExemptionReasons[0].Name;
            controller.TaxCertificateNumber = 'ABC123';
            controller.TaxExpiryDate = date.newInstance(2017,12,31);
            Test.startTest();
            controller.insertAccount();
            Test.stopTest();
            //System.assert(ApexPages.getMessages() == null || ApexPages.getMessages().size() == 0, ApexPages.getMessages());
        }
    } 

    
    @isTest
    public static void UpsertAccount_WithData_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            //not sure if this is needs to be done per unit test method? I think so
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
            Test.startTest();
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            System.assert(controller != null);
            //try to save an account without setting member variables in the controller
            controller.accountName = 'My Test Account';
            controller.accountLine1 = '123 East First St';
            controller.accountCity = 'Sartell';
            controller.accountstate = 'MN';
            controller.accountZIPCODE = '56377';
            controller.accountCountry = 'US';
            controller.accountPhone = '(541) 754-3010';
            controller.SelectTaxExempt = 'NO';
            controller.SelectTaxName = dataFactory.TaxExemptionReasons[0].Name;
            controller.TaxCertificateNumber = 'ABC123';
            controller.TaxExpiryDate = date.newInstance(2017,12,31);
            controller.saveeditAccount();
            Test.stopTest();

            //System.assert(ApexPages.getMessages() == null || ApexPages.getMessages().size() == 0);
        }
    } 

    @isTest
    public static void InsertAccount_NoData_Test(){
        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();

        System.runAs(dataFactory.TestRunner){
            //not sure if this is needs to be done per unit test method? I think so
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
           
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            System.assert(controller != null);
            //try to save an account without setting member variables in the controller
            controller.accountName = null;
            controller.accountCountry = null;
            controller.SelectTaxExempt = 'Yes';
            controller.TaxCertificateNumber = null; 
            
            Test.startTest();
            controller.insertAccount();
            System.assert(ApexPages.getMessages() != null && ApexPages.getMessages().size() > 0);
            Test.stopTest();
        } 
    }

     

    @isTest
    public static void InsertAccountContact_NoData_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            //not sure if this is needs to be done per unit test method? I think so
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            //ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            System.assert(controller != null);

            controller.accountName = null;
            controller.accountCountry = null;
            controller.SelectTaxExempt = 'Yes';
            controller.TaxCertificateNumber = null;
            
            Test.startTest();
            controller.createContact();

            System.assert(ApexPages.getMessages() != null && ApexPages.getMessages().size() > 0);
            Test.stopTest();
        }
    }

    @isTest
    public static void InsertAccountContact_WithData_DifferentAddress_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            //not sure if this is needs to be done per unit test method? I think so
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts(false);
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            System.assert(controller != null);
            //set up data for a new primary contact, and expect the contract address info to pull from account
            controller.SelectedRoles = new List<String>{'Associate'};
            controller.SelectContactAddressOptions = null;
            controller.contactFirstName = 'John';
            controller.contactLastName = 'Doe';
            controller.contactEmail ='John@test.com';
            controller.contactPhoneNo = '2065242223';
            controller.contactTitle = 'Owner';
            //the code should recognize not to use account address and use the info below.
            controller.contactStreetAddress = '1234 Easy Street South';
            controller.contactCity = 'Sartell';
            controller.contactState = 'MN';
            controller.contactZipCode = '56377';
            controller.contactCountry = 'US';

            Test.startTest();
            //create contact does an upsert?
            controller.createContact();

            System.assert(ApexPages.getMessages() == null || ApexPages.getMessages().size() == 0);
            System.assert(controller.contactList != null);
            Test.stopTest();
        }
    } 
    @isTest
    public static void InsertAccountContact_WithData_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            //not sure if this is needs to be done per unit test method? I think so
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts(false);
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

            RWS_AccountSetupController controller = new RWS_AccountSetupController();

            //set up data for a new primary contact, and expect the contract address info to pull from account
            controller.SelectedRoles = new List<String>{'Owner'};
            controller.SelectContactAddressOptions = 'Same as Physical';
            controller.contactFirstName = 'John';
            controller.contactLastName = 'Doe';
            controller.contactEmail ='John@test.com';
            controller.contactPhoneNo = '(541) 754-3010';
            controller.contactTitle = 'Owner';
            //while this information is set, it will be ignored since the "Same as Account is set"
            controller.contactStreetAddress = '1234 Easy Street South';
            controller.contactCity = 'Sartell';
            controller.contactState = 'MN';
            controller.contactZipCode = '56377';
            controller.contactCountry = 'US';

            Test.startTest();
            //create contact does an upsert?
            controller.createContact();
            System.assert(ApexPages.getMessages() == null || ApexPages.getMessages().size() == 0);
            System.assert(controller.contactList != null);
            Test.stopTest();
        }
    } 


    @isTest
    public static void IsValidUser_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            Test.startTest();
            RWS_AccountSetupController controller = new RWS_AccountSetupController();

            System.assert(controller.isValidUser(Userinfo.getProfileId()) == true);
            Test.stopTest();

        }
    }   

    @isTest
    public static void RedirectToNewProgram_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            //not sure if this is needs to be done per unit test method? I think so
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

            Test.startTest();
            pagereference reference = controller.RedirectToNewProgram();
            System.assert(reference != null);
            Test.stopTest();
        }
    } 

    @isTest
    public static void CreateAccountContact_EditModeFalse_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            //set up account information same as what is in data factory
            controller.accountName = 'Store One';
            controller.accountLine1 = '123 East First Street';
            controller.accountCity = 'Sartell';
            controller.accountstate = 'MN';
            controller.accountZIPCODE = '56377';
            controller.accountCountry = 'US';
            controller.accountPhone = '(541) 754-3010';
            controller.EditMode = false;

            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
            
            Test.startTest();
            pagereference reference = controller.createAccountContact();
            //in this case controller action should return null
            System.assert(reference == null);
            Test.stopTest();
        }
    } 

    @isTest
    public static void CreateAccountContact_EditModeTrue_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            
            RWS_AccountSetupController controller = new RWS_AccountSetupController();

            //set up account information same as what is in data factory
            controller.accountName = 'Store One';
            controller.accountLine1 = '123 East First Street';
            controller.accountCity = 'Sartell';
            controller.accountstate = 'MN';
            controller.accountZIPCODE = '56377';
            controller.accountCountry = 'US';
            controller.accountPhone = '(541) 754-3010';
            controller.EditMode = true;

            Test.startTest();
            pagereference reference = controller.createAccountContact();
            //in this case controller action should return null
            System.assert(reference == null);
            Test.stopTest();
        }
    }  

    @isTest
    public static void AccountDeactivate_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts(false);


            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            
            Test.startTest();
            controller.AccountDeactivate();
            //in this case controller action should return null
            System.assert(controller.AccountStatusMessage != null);
            Test.stopTest();
        }
    }

    @isTest
    public static void UpdateCreditInfo_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();

            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            controller.SelectinvoiceOptions = 'Yes';
            controller.SelectbillingcontactOptions = 'Yes';
            controller.creditappFlag = true;
            
            Test.startTest();
            controller.updateCreditInfo();
            //in this case controller action should return null
            System.assert(controller.AccountStatusMessage == null);
            Test.stopTest();
        }
    }  

    @isTest
    public static void UpdateCreditInfo2_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();

            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
            
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            controller.SelectinvoiceOptions = 'Yes';
            controller.SelectbillingcontactOptions = 'No';
            controller.creditappFlag = true;
            
            Test.startTest();
            controller.updateCreditInfo();
            //in this case controller action should return null
            System.assert(controller.AccountStatusMessage == null);
            Test.stopTest();
        }
    }
    @isTest
    public static void UpdateCreditInfo3_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();


            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
            
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            controller.SelectinvoiceOptions = 'Yes';
            controller.SelectbillingcontactOptions = 'No';
            controller.SelectContactAddrBillOptions = 'Same as Physical';
            controller.creditappFlag = true;
            
            Test.startTest();
            controller.updateCreditInfo();
            //in this case controller action should return null
            System.assert(controller.AccountStatusMessage == null);
            Test.stopTest();

        }   
    } 

     @isTest
    public static void AssignTaxExempt_ExemptYes_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
            
            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            controller.selecttaxName = dataFactory.TaxExemptionReasons[0].Id;
            
            Test.startTest();
            controller.AssignTaxExempt();
            //in this case controller action should return null
            System.assert(controller.AccountStatusMessage == null);
            Test.stopTest();
        }   
    }
    @isTest
    public static void AssignTaxExempt_ExemptNo_Test(){

        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();
            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

            RWS_AccountSetupController controller = new RWS_AccountSetupController();
            controller.selecttaxName = dataFactory.TaxExemptionReasons[1].Id;
            
            Test.startTest();
            controller.AssignTaxExempt();
            //in this case controller action should return null
            System.assert(controller.AccountStatusMessage == null);
            Test.stopTest();
        }   
    } 

    @isTest
    public static void DeleteContact_Test(){
        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();

            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);
            
            RWS_AccountSetupController controller = new RWS_AccountSetupController();

            //after the constructor is ran, there should be a list of contacts
            Integer numContacts = controller.contactList.size();

            //set the contact id
            controller.deletedContactId = dataFactory.AccountContacts[0].Id;
            
            Test.startTest();
            controller.deleteContact();

            Integer numContacts2 = controller.contactList.size();

            //in this case controller action should return null
            System.assert(numContacts > numContacts2);
            Test.stopTest();

        }
    }

    @isTest
    public static void UploadAttachment_Test(){
        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();

            //set the id of the page
            ApexPages.CurrentPage().getparameters().put('id', Industrial[0].Store_Account__c);

            //after the constructor is ran, there should be a list of contacts
            Integer firstCount = [SELECT count()  FROM Attachment 
                                  WHERE parentid = :Industrial[0].Store_Account__c];

            Test.startTest();
            RWS_AccountSetupController.doUploadAttachment(Industrial[0].Store_Account__c, 'This is a test body', 'FakeName', 'FakeAttachmentId', 'FakePageName');

            Integer secondCount = [SELECT count()  FROM Attachment 
                                  WHERE parentid = :Industrial[0].Store_Account__c];

            //in this case controller action should return null
            System.assert(firstCount < secondCount);
            
            Test.stopTest();

        }
    } 

    @isTest
    public static void FormSubmit_Test(){
        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){

            //here we create a couple accounts, one account has full address info
            List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();

            Test.startTest();
            String retval = RWS_AccountSetupController.doSubmitForm(Industrial[0].Store_Account__c, 'TestDescription', 'http://www.fakesite.com', '(541) 754-3010');

            //in this case controller action should return null
            System.assert('Success' == retval);
            Test.stopTest();

        }
    } 

    @isTest
    public static void statementCoverage(){
        RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();
        System.runAs(dataFactory.TestRunner){
            Test.startTest();
            RWS_AccountSetupController cont = new RWS_AccountSetupController();
            system.debug(cont.hasErrors);
            system.debug(cont.SaveProgramDetails());
            system.debug(cont.creditApplicationMessage);
            system.debug(cont.payrollAccessories);
            system.debug(cont.annualOption);
            system.debug(cont.voucherDistro);
            system.debug(cont.eligibilityOption);
            system.debug(cont.subTax);
            system.debug(cont.allowedPairs);
            system.debug(cont.accessoriesAllowed);
            system.debug(cont.maxAmount);
            system.debug(cont.subsidyPercent);
            system.debug(cont.subsidyFrequency);
            system.debug(cont.subsidyAmount);
            system.debug(cont.subsidyType);
            system.debug(cont.notes);
            system.debug(cont.expiration);
            system.debug(cont.activation);
            system.debug(cont.programName);
            system.debug(cont.type);
            system.debug(cont.emailTo);
            system.debug(cont.Terms);
            system.debug(cont.Frequency);
            system.debug(cont.paymentBy);
            system.debug(cont.deliveryBy);
            system.debug(cont.contactRole);
            system.debug(cont.parentId);
            system.debug(cont.attid);
            system.debug(cont.SendCreditApplicationErrors);
            system.debug(cont.searchStateString);
            system.debug(cont.taxexemptReasonList);
            system.debug(cont.contactPhone);
            system.debug(cont.contactName);
            system.debug(cont.billingStatus);
            system.debug(cont.billingStreet);
            system.debug(cont.billingName);
            system.debug(cont.mailingzipCode);
            system.debug(cont.mailingState);
            system.debug(cont.mailingCity);
            system.debug(cont.mailingStreet);
            system.debug(cont.billingCountry);
            system.debug(cont.StreetAddress);
            system.debug(cont.accountAddress);
            system.debug(cont.dupliactionMessage);
            system.debug(cont.selectedserviceMethods);
            system.debug(cont.displayTaxExpiryDate);
            system.debug(cont.exemptReason);
            system.debug(cont.nationalAccount);
            system.debug(cont.cityExempt);
            system.debug(cont.stateExempt);
            system.debug(cont.countyExempt);
            system.debug(cont.countryExempt);
            system.debug(cont.billingDifferentCountry);
            system.debug(cont.requestedCreditLimit);
            system.debug(cont.creditApplicationSentDate);
            system.debug(cont.creditApplicationApprovedDate);
            system.debug(cont.SendCreditApplicationPopUp);
            system.debug(cont.PrimaryContactEmail);
            system.debug(cont.contactFax);
            system.debug(cont.contactMobilePhone);
            system.debug(cont.SelectContactPreference);
            system.debug(cont.editContact);
            system.debug(cont.showSection);
            system.debug(cont.issetupAccount);
            system.debug(cont.isalternatePayment);
            system.debug(cont.isnewProgram);
            system.debug(cont.isassignexistProgram);
            system.debug(cont.isnotReady);
            system.debug(cont.SelectedPrograms);
            system.debug(cont.deleteChildAccountId);
            system.debug(cont.contactPrimaryEmail);
            system.debug(cont.createdProgramId);
            cont.populateProgramId();
            system.debug(cont.attachment);
            //system.debug(cont.decContactId); 02/24 commented out temp, Uncomment after Tory has finished updating RWS_AccountSetupController
            system.debug(cont.decFirst);
            system.debug(cont.decLast);
            system.debug(cont.decEmail);
            system.debug(cont.decPhone);
            system.debug(cont.decStreet);
            system.debug(cont.decCity);
            system.debug(cont.decState);
            system.debug(cont.decZipCode);
            system.debug(cont.decCountry);
            system.debug(cont.parentContactId);
            system.debug(cont.isCentralizedBilling);
            system.debug(cont.isDecentralizedBilling);
            system.debug(cont.hasParent);
            
            Test.stopTest();
        }
            
    } 
   
}