force-app/main/default/objects/Account/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>Activation Date for an IA Account. (Set by Workflow)</description>
    <inlineHelpText>Activation Date for an IA Account  (Set by Workflow)</inlineHelpText>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Industrial Account (Account Standard Object) for the program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to Industrial Account (Account Standard Object) for the program.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>The activation (effective) date of an Industrial Account Program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The activation (effective) date of an Industrial Account Program.</inlineHelpText>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>The Industrial Account Program&apos;s expiration date.  A program will become inactive if the expiration date is less than today.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Industrial Account Program&apos;s expiration date.  A program will become inactive if the expiration date is less than today.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Notes_Trimmed__c.field-meta.xml
<CustomField>
    <fullName>Program_Notes_Trimmed__c</fullName>
    <description>A short (trimmed) version of Purchase Program Notes used in Community list views. Formula Field
Field Type: IA
Integrated: N</description>
    <formula>IF(NOT(ISBLANK(Purchase_Program_Notes__c)), LEFT(Purchase_Program_Notes__c, 55) + &quot;...&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A short (trimmed) version of Purchase Program Notes used in Community list views. Formula Field</inlineHelpText>
    <label>Program Notes Trimmed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the program is a template</description>
    <inlineHelpText>Indicates if the program is a template</inlineHelpText>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of Industrial Account Program.  The type of program determines options for Subsidy, Eligibility, and Payroll Deduction.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The type of Industrial Account Program.  The type of program determines options for Subsidy, Eligibility, and Payroll Deduction.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CashandCarry</fullName>
                <label>Cash and Carry</label>
            </value>
            <value>
                <fullName>PayrollDeduction</fullName>
                <label>Payroll Deduction</label>
            </value>
            <value>
                <fullName>Subsidy</fullName>
            </value>
            <value>
                <fullName>SubsidyandPayrollDeduction</fullName>
                <label>Subsidy and Payroll Deduction</label>
            </value>
            <value>
                <fullName>SubsidywithPcard</fullName>
                <label>Subsidy with Pcard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Store_IA_Account__c/Store_IA_Account__c.object-meta.xml
<CustomObject>
    <description>Object for Red Wing Store and IA Account relationships.  When a Red Wing Store creates a new IA account a record is inserted into this object via APEX.
Object Type: IA
Integrated: N</description>
    <label>Store IA Account</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Store IA Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store IA Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_IA_Account__c/fields/IA_Account__c.field-meta.xml
<CustomField>
    <fullName>IA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to an Industrial Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to an Industrial Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.</inlineHelpText>
    <label>IA Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store IA Account</relationshipLabel>
    <relationshipName>Store_IA_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_IA_Account__c/fields/Store_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.</inlineHelpText>
    <label>Store Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store IA Account</relationshipLabel>
    <relationshipName>Store_IA_Account_del1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_ProgramHomeController.cls
Public  with sharing class RWS_ProgramHomeController{

    public Program__c ProObj {get;set;}
    public List<Program__c> ProgramList {get;set;}
    public String jsonResult     {set;get;}
    public List<ProgramWrap> ProListWrap {get;set;}
    public Boolean isFullAccessUser {get; set;}
    
    
    /*public List<SelectOption> programViews
    {
        get
        {
            if(programViews == null )
            {
                programViews = new List<SelectOption>();
                programViews.add(new SelectOption('1', 'Program Templates'));
                programViews.add(new SelectOption('0', 'Account Templates'));
            }
            return programViews ;
        }
        set; 
    }
    public String selectedProgramViews {get; set; }*/

    public Set<Id> industrialAccountSet ;

    //Controller
    public RWS_ProgramHomeController(){
        isFullAccessUser = RWS_UtilityClass.isFullAccessUser();
        ProObj = new Program__c();
        ProgramList = new List<Program__c>();
        ProListWrap = new List<ProgramWrap>();
        //selectedProgramViews = '0';
        User storeUser = [Select Id,contactid,accountId from User where id =: Userinfo.getUserid()];
        List<Store_IA_Account__c> storeAccountList = [select Id,IA_Account__c,Store_Account__c from Store_IA_Account__c 
                            where Store_Account__c = :storeUser.accountId
                            and IA_Account__c != null];

        industrialAccountSet = new Set<Id>();
        if(!storeAccountList.isEmpty()){
            for(Store_IA_Account__c storeId: storeAccountList){
                industrialAccountSet.add(storeId.IA_Account__c);
            } 
        } 

        getPrograms();
    }
    
    public void getPrograms()
    {
        System.debug('UAC: industrialAccountSet ' + industrialAccountSet );
        proListWrap = new List<ProgramWrap>();
        jsonResult = '';
        //Boolean isTemplate = selectedProgramViews == '1' ? true : false ;
        //System.debug('UAC: isTemplate ' + isTemplate );

        programList =  [SELECT Id,Name,Active__c, Account__r.Name, Template__c, toLabel(Type__c), Program_Notes_Trimmed__c, Activation_Date__c, Expiration_Date__c  FROM Program__c 
                        WHERE //( Account__c IN :industrialAccountSet OR 
                         (Account__c = null AND OwnerId = :UserInfo.getUserId())  //) 
                        AND Template__c = TRUE ];
        
        System.debug('UAC: programList size ' + programList.size() );

        for(Program__c obj : programList)
        {
            ProgramWrap wrapObj = new ProgramWrap();
            
            wrapObj.URLEdit = 'RWS_NewProgramSetup?tab=program&task=clone&proid='+obj.Id;
            wrapObj.URLSummary = 'ProgramSummary?tab=program&proid='+obj.Id;
            wrapObj.ProObj = obj;
            System.debug(obj.Expiration_Date__c);
            if(obj.Active__c == false)
            {
                wrapObj.Status = 'InActive';
            }
            else
            {
                wrapObj.Status = 'Active';
            }
            
            proListWrap.add(wrapObj);
        }
        
        System.debug('UAC: programList ' + programList );
        jsonProgramList();
    }

    public String jsonProgramList(){
        jsonResult = JSON.serialize(proListWrap);
        jsonResult = String.escapeSingleQuotes(jsonResult);
        System.debug('jsonResult****'+jsonResult);
            return jsonResult; 
    }
    
    public PageReference RedirectToEdit(String Id){
    
        system.debug('-=-=- Need to redirect'+Id);
        return null;
    }

    public class ProgramWrap{
        String URLEdit {get;set;}
        String URLSummary {get;set;}
        String Status {get;set;}
        Program__c ProObj {get;set;}
        
    }
}