force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Approval_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Credit_Approval_Indicator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Credit Dept has approved credit for this account. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates credit has been approved by the Credit Dept. Sent to Salesforce by IA.</inlineHelpText>
    <label>Credit Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Status__c</fullName>
    <inlineHelpText>Maintained by MultiService. Submitted Value only used for internal processes.</inlineHelpText>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved/Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Credit Hold</fullName>
            </value>
            <value>
                <fullName>Application Sent</fullName>
                <isActive>false</isActive>
                <label>Application Sent</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HasActiveProgram__c.field-meta.xml
<CustomField>
    <fullName>HasActiveProgram__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the Account has a related Active Program. This is to be used for Active Account validation rules.</description>
    <inlineHelpText>This field is used to determine if the Account has a related Active Program. This is to be used for Active Account validation rules.</inlineHelpText>
    <label>HasActiveProgram</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_Address_Line_1__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location Address Line 1</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_City__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_City__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_Country__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_State_Province__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_State_Province__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IA_Physical_Location_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>--Select--</fullName>
                <default>true</default>
                <label>--Select--</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Alabama</label>
            </value>
            <value>
                <fullName>AK</fullName>
                <label>Alaska</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Arizona</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Arkansas</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>California</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colorado</label>
            </value>
            <value>
                <fullName>CT</fullName>
                <label>Connecticut</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Delaware</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>Florida</label>
            </value>
            <value>
                <fullName>GA</fullName>
                <label>Georgia</label>
            </value>
            <value>
                <fullName>HI</fullName>
                <label>Hawaii</label>
            </value>
            <value>
                <fullName>ID</fullName>
                <label>Idaho</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>Illinois</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Indiana</label>
            </value>
            <value>
                <fullName>IA</fullName>
                <label>Iowa</label>
            </value>
            <value>
                <fullName>KS</fullName>
                <label>Kansas</label>
            </value>
            <value>
                <fullName>KY</fullName>
                <label>Kentucky</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <label>Louisiana</label>
            </value>
            <value>
                <fullName>ME</fullName>
                <label>Maine</label>
            </value>
            <value>
                <fullName>MD</fullName>
                <label>Maryland</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <label>Massachusetts</label>
            </value>
            <value>
                <fullName>MI</fullName>
                <label>Michigan</label>
            </value>
            <value>
                <fullName>MN</fullName>
                <label>Minnesota</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>Mississippi</label>
            </value>
            <value>
                <fullName>MO</fullName>
                <label>Missouri</label>
            </value>
            <value>
                <fullName>MT</fullName>
                <label>Montana</label>
            </value>
            <value>
                <fullName>NE</fullName>
                <label>Nebraska</label>
            </value>
            <value>
                <fullName>NV</fullName>
                <label>Nevada</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>New Hampshire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_ZIP_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_ZIP_Postal_Code__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location ZIP/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Email__c</fullName>
    <label>Primary Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Requires_Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Requires_Invoicing__c</fullName>
    <label>Requires Invoicing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Exemption_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exemption_Reason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Available in Business Partner Community</description>
    <inlineHelpText>Select Tax Exemption Reason if the Account is Tax Exempt.</inlineHelpText>
    <label>Tax Exemption Reason</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tax_Exemption_Reason__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Exemption_Reason__c</referenceTo>
    <relationshipLabel>Accounts claiming Exemption</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Industrial Account (Account Standard Object) for the program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to Industrial Account (Account Standard Object) for the program.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the program is a template</description>
    <inlineHelpText>Indicates if the program is a template</inlineHelpText>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Store_IA_Account__c/Store_IA_Account__c.object-meta.xml
<CustomObject>
    <description>Object for Red Wing Store and IA Account relationships.  When a Red Wing Store creates a new IA account a record is inserted into this object via APEX.
Object Type: IA
Integrated: N</description>
    <label>Store IA Account</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Store IA Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store IA Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_IA_Account__c/fields/IA_Account__c.field-meta.xml
<CustomField>
    <fullName>IA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to an Industrial Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to an Industrial Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.</inlineHelpText>
    <label>IA Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store IA Account</relationshipLabel>
    <relationshipName>Store_IA_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_IA_Account__c/fields/Store_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to a Red Wing Store Account (Account Object).  Used to associate an IA Account with a Red Wing Store Account. Populated via APEX.</inlineHelpText>
    <label>Store Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store IA Account</relationshipLabel>
    <relationshipName>Store_IA_Account_del1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax_Exemption_Reason__c/Tax_Exemption_Reason__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the Tax Exempt reasons that can be applied to Industrial Accounts.
Object Type: IA
Integrated: N</description>
    <label>Tax Exemption Reason</label>
    <nameField>
        <label>Tax Exemption Reason</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Exemption Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Exemption_Reason__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicator for the Tax Exemption Reason.  If checked (TRUE) the Tax Exemption Reason is active.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Indicator for the Tax Exemption Reason.  If checked (TRUE) the Tax Exemption Reason is active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RWS_TestDataFactory.cls
public class RWS_TestDataFactory {

    /*
    Salesforce records that are created in 
    test methods aren’t committed to the database. 
    They’re rolled back when the test finishes execution. 
    This rollback behavior is handy for testing because 
    you don’t have to clean up your test data after the test executes.
    */
    public User TestRunner {get; set;}
    public List<Tax_Exemption_Reason__c> TaxExemptionReasons {get; set;}
    public List<Contact> AccountContacts {get; set;}
    public List<Program__c> AccountPrograms {get; set;}
    public List<Pricebook2> ProgramPriceBooks {get; set;}

    public RWS_TestDataFactory(){
        //will set a user member level variable
        HandleTestUserSetup();
    }

    public void HandleTestUserSetup(){
        UserRole r = new UserRole(name = 'TEST ROLE');
        Database.insert(r);

        User userWithRole = new User(
            alias = 'hasrole', 
            email='userwithrole@roletest1.com', 
            userroleid = r.id, 
            emailencodingkey='UTF-8', 
            lastname='Testing', 
            languagelocalekey='en_US',
            localesidkey='en_US', 
            profileid = UserInfo.getProfileId(),
            timezonesidkey='America/Los_Angeles', 
            username='userwithrole@testorg.com');
        Database.insert(userWithRole);
        //member variable use System.RunAs() with this user
        TestRunner = userWithRole;

    }

    public List<Store_IA_Account__c> createIndustrialAccounts() {
        return createIndustrialAccount(true);
    }

    public List<Store_IA_Account__c> createIndustrialAccounts(Boolean createPrograms) {
        return createIndustrialAccount(createPrograms);
    }

    private List<Store_IA_Account__c> createIndustrialAccount(Boolean createPrograms)
    {
        //assume the test runner user will be the user
        Id BPC = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Partner Community').getRecordTypeId();
        Id BP = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Partner').getRecordTypeId();
        String PrimaryContact = 'Primary Contact';
        String BillingContact = 'Billing Contact';

        //create two industrial accounts
        List<Account> industrialAccounts = new List<Account>();
        List<Account> storeAccounts = new List<Account>();
        List<Store_IA_Account__c> lookups = new List<Store_IA_Account__c>();
        List<Program__c> programs = new List<Program__c>();
        List<Contact> contacts = new List<Contact>();
        List<Tax_Exemption_Reason__c> taxExemptReasons = new List<Tax_Exemption_Reason__c>();
        List<Pricebook2> priceBooks = new List<Pricebook2>();


        Account industrialAccount1 = new Account();
        industrialAccount1.Name = 'IA One';

        Account industrialAccount2 = new Account();
        industrialAccount2.Name = 'IA Two';

        industrialAccounts.add(industrialAccount1);
        industrialAccounts.add(industrialAccount2);

        insert industrialAccounts;

        //create four store accounts
        Account acct = new Account();
        acct.Name = 'Store One';
        acct.RecordTypeId = BPC;
        acct.IA_Physical_Location_Address_Line_1__c = '123 East First Street';
        acct.IA_Physical_Location_City__c = 'Sartell';
        acct.IA_Physical_Location_State_Province__c = 'MN';
        acct.IA_Physical_Location_ZIP_Postal_Code__c = '56377';
        acct.IA_Physical_Location_Country__c = 'US';
        acct.Credit_Approval_Indicator__c = true;
        acct.Credit_Status__c = 'Approved/Active';
        acct.Active__c = true;
        acct.HasActiveProgram__c = true;
        acct.Requires_Invoicing__c = 'No';
        acct.Primary_Contact_Email__c = 'bob@test.com';
        acct.Primary_Contact_First_Name__c = 'Bob';
        acct.Primary_Contact_Last_Name__c = 'Test';

        Account acct2 = new Account();
        acct2.Name = 'Store Two';
        acct2.RecordTypeId = BPC;
        acct2.IA_Physical_Location_Address_Line_1__c = '1234 East First Street';
        acct2.IA_Physical_Location_City__c = 'Sartelll';
        acct2.IA_Physical_Location_State_Province__c = 'MN';
        acct2.IA_Physical_Location_ZIP_Postal_Code__c = '56378';
        acct2.IA_Physical_Location_Country__c = 'US';
        acct2.Credit_Approval_Indicator__c = true;
        acct2.Credit_Status__c = 'Approved/Active';
        acct2.Active__c = true;
        acct2.HasActiveProgram__c = true;
        acct2.Requires_Invoicing__c = 'No';
        acct2.Primary_Contact_Email__c = 'bob@test.com';
        acct2.Primary_Contact_First_Name__c = 'Bob';
        acct2.Primary_Contact_Last_Name__c = 'Test';

        Account acct3 = new Account();
        acct3.Name = 'Store Three';
        acct3.RecordTypeId = BPC;
        acct3.HasActiveProgram__c = true;
        acct3.Requires_Invoicing__c = 'No';

        Account acct4 = new Account();
        acct4.Name = 'Store Four';
        acct4.RecordTypeId = BPC;
        acct4.HasActiveProgram__c = true;
        acct4.Requires_Invoicing__c = 'No';

        storeAccounts.add(acct);
        storeAccounts.add(acct2);
        storeAccounts.add(acct3);
        storeAccounts.add(acct4);

        insert storeAccounts;

        system.debug('The store accounts are... ' + storeAccounts);

        //now join or relate the IA -> store
        Store_IA_Account__c lookup = new Store_IA_Account__c();
        lookup.IA_Account__c = industrialAccount1.id;
        lookup.Store_Account__c = acct.id;

        Store_IA_Account__c lookup2 = new Store_IA_Account__c();
        lookup2.IA_Account__c = industrialAccount1.id;
        lookup2.Store_Account__c = acct2.id;

        Store_IA_Account__c lookup3 = new Store_IA_Account__c();
        lookup3.IA_Account__c = industrialAccount2.id;
        lookup3.Store_Account__c = acct3.id;

        Store_IA_Account__c lookup4 = new Store_IA_Account__c();
        lookup4.IA_Account__c = industrialAccount2.id;
        lookup4.Store_Account__c = acct4.id;

        lookups.add(lookup);
        lookups.add(lookup2);
        lookups.add(lookup3);
        lookups.add(lookup4);

        insert lookups;

        if(createPrograms) {
            //now we are going to add programs to the mix
            Program__c program1 = new Program__c();
            program1.Name = 'Program One';
            program1.Account__c = lookups[0].Store_Account__c;
            program1.Template__c = false;
            program1.Active__c = true;
            program1.Type__c = 'CashandCarry';
            program1.Auto_Update_Price__c = true;
            program1.Activation_Date__c = Date.today().addDays(-1);
            program1.Expiration_Date__c = Date.today().addDays(5);
            program1.Eligibility_Option__c = 'False';
            program1.Subsidy_Tax__c = 'SubsidyTaxed';
            program1.HasPricebook__c = true;
            program1.Processing_Status__c = 'Completed';

            Program__c program2 = new Program__c();
            program2.Name = 'Program Two';
            program2.Account__c = lookups[1].Store_Account__c;
            program2.Template__c = false;
            program2.Active__c = true;
            program2.Type__c = 'CashandCarry';
            program2.Auto_Update_Price__c = true;
            program2.Activation_Date__c = Date.today().addDays(-1);
            program2.Expiration_Date__c = Date.today().addDays(5);
            program2.Eligibility_Option__c = 'False';
            program2.Subsidy_Tax__c = 'SubsidyTaxed';
            program2.HasPricebook__c = true;
            
            Program__c program3 = new Program__c();
            program3.Name = 'Program Three';
            program3.Type__c = 'CashandCarry';
            program3.Template__c = true;
            program3.Processing_Status__c = 'Completed';

            Program__c program4 = new Program__c();
            program4.Name = 'Program Four';
            program4.Type__c = 'CashandCarry';
            program4.Template__c = true;
            program4.Processing_Status__c = 'Completed';

            programs.add(program1);
            programs.add(program2);
            programs.add(program3);
            programs.add(program4);

            insert programs;

            system.debug('The account programs are... ' + programs);

            //set up a couple price books
            Pricebook2 priceBook = new Pricebook2();
            priceBook.Name = 'Price Book 1';
            priceBook.IsActive = true;
            priceBook.Program__c = program1.Id;

            priceBooks.add(priceBook);
            insert priceBooks;
        }

        AccountPrograms = programs;
        ProgramPriceBooks = priceBooks;

        //need contacts linked to accounts, use first account
        Contact contact1 = new Contact();
        contact1.RecordTypeId = BP;
        contact1.AccountId = acct.id;
        contact1.Contact_Identifier__c = 'Primary';
        contact1.FirstName = 'Bill';
        contact1.LastName = 'Test';
        contact1.Email = 'bill@test.com';

        Contact contact2 = new Contact();
        contact2.RecordTypeId = BP;
        contact2.AccountId = acct.id;
        contact2.Contact_Identifier__c = 'Primary';
        contact2.FirstName = 'Bob';
        contact2.LastName = 'Test';
        contact2.Email = 'bob@test.com';

        Contact contact3 = new Contact();
        contact3.RecordTypeId = BP;
        contact3.AccountId = acct.id;
        contact3.Contact_Identifier__c = 'Primary';
        contact3.FirstName = 'Brent';
        contact3.LastName = 'Test';
        contact3.Email = 'brent@test.com';

        contacts.add(contact1);
        contacts.add(contact2);
        contacts.add(contact3);

        insert contacts;

        AccountContacts = contacts;

        system.debug('The test contacts list is... ' + Contacts);

        Tax_Exemption_Reason__c taxExemption = new Tax_Exemption_Reason__c();
        taxExemption.Name = 'TCN GOVT-PST EXMPT';
        taxExemption.Active__c = true;
        taxExemption.State_Exempt__c = 'TRUE'; 
        taxExemption.Applicable_to__c = 'All State/Provinces';
        taxExemption.Industrial_Account_Allowed__c = 'Y';
        taxExemption.National_Account_Allowed__c = 'Y';     
        taxExemption.City_Exempt__c = 'TRUE';
        taxExemption.State_Exempt__c = 'TRUE';
        taxExemption.County_Exempt__c = 'TRUE';
        taxExemption.Country_Exempt__c = 'TRUE';

        Tax_Exemption_Reason__c taxExemption2 = new Tax_Exemption_Reason__c();
        taxExemption2.Name = 'IL-EQUIP EXEMPT';
        taxExemption2.Active__c = true;
        taxExemption2.State_Exempt__c = 'FALSE'; 
        taxExemption2.Applicable_to__c = 'All State/Provinces';
        taxExemption2.Industrial_Account_Allowed__c = 'N';
        taxExemption2.National_Account_Allowed__c = 'N';        
        taxExemption2.City_Exempt__c = 'FALSE';
        taxExemption2.State_Exempt__c = 'FALSE';
        taxExemption2.County_Exempt__c = 'FALSE';
        taxExemption2.Country_Exempt__c = 'FALSE';

        taxExemptReasons.add(taxExemption);
        taxExemptReasons.add(taxExemption2);

        insert taxExemptReasons;

        TaxExemptionReasons = taxExemptReasons;

        return lookups;

    }


}