force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Type_Detail__c.field-meta.xml
<CustomField>
    <fullName>Case_Type_Detail__c</fullName>
    <label>Case Type Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>2 to 3</fullName>
                <color>#0B6FCE</color>
                <label>2 to 3</label>
            </value>
            <value>
                <fullName>30-Day Comfort</fullName>
                <color>#993300</color>
                <label>30-Day Comfort</label>
            </value>
            <value>
                <fullName>3rd Party AP Vendor</fullName>
                <color>#78C953</color>
                <label>3rd Party AP Vendor</label>
            </value>
            <value>
                <fullName>3 to 2</fullName>
                <color>#E27001</color>
                <label>3 to 2</label>
            </value>
            <value>
                <fullName>3 to 4</fullName>
                <color>#A845DC</color>
                <label>3 to 4</label>
            </value>
            <value>
                <fullName>4 to 3</fullName>
                <color>#F3D904</color>
                <label>4 to 3</label>
            </value>
            <value>
                <fullName>Account</fullName>
                <color>#A53711</color>
                <label>Account</label>
            </value>
            <value>
                <fullName>Account Setup</fullName>
                <color>#66E9BD</color>
                <label>Account Setup</label>
            </value>
            <value>
                <fullName>Account Status</fullName>
                <color>#0B24BE</color>
                <label>Account Status</label>
            </value>
            <value>
                <fullName>ACH</fullName>
                <color>#419249</color>
                <label>ACH</label>
            </value>
            <value>
                <fullName>Administrative for Sales</fullName>
                <color>#B6E32E</color>
                <label>Administrative for Sales</label>
            </value>
            <value>
                <fullName>Advertising</fullName>
                <color>#641CCF</color>
                <label>Advertising</label>
            </value>
            <value>
                <fullName>Allowance</fullName>
                <color>#2F5D85</color>
                <label>Allowance</label>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
            <value>
                <fullName>ARIBA Invoice</fullName>
                <color>#F96FB7</color>
                <label>ARIBA Invoice</label>
            </value>
            <value>
                <fullName>Auth Form #</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
                <color>#2F5D85</color>
                <label>Availability</label>
            </value>
            <value>
                <fullName>Backorder</fullName>
                <color>#AFCADF</color>
                <label>Backorder</label>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Both New and Worn</fullName>
                <color>#8F6429</color>
                <label>Both New and Worn</label>
            </value>
            <value>
                <fullName>Bounce Back</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Business Cards</fullName>
                <color>#EFAE73</color>
                <label>Business Cards</label>
            </value>
            <value>
                <fullName>Buying Programs</fullName>
                <color>#57F17C</color>
                <label>Buying Programs</label>
            </value>
            <value>
                <fullName>Cage Code (SAM)</fullName>
                <color>#0B6FCE</color>
                <label>Cage Code (SAM)</label>
            </value>
            <value>
                <fullName>Call Tags</fullName>
                <color>#78C953</color>
                <label>Call Tags</label>
            </value>
            <value>
                <fullName>Card Charged Incorrectly</fullName>
                <color>#E27001</color>
                <label>Card Charged Incorrectly</label>
            </value>
            <value>
                <fullName>Change Account Address</fullName>
                <color>#A845DC</color>
                <label>Change Account Address</label>
            </value>
            <value>
                <fullName>Change Account Fax</fullName>
                <color>#F3D904</color>
                <label>Change Account Fax</label>
            </value>
            <value>
                <fullName>Change Account Phone</fullName>
                <color>#A53711</color>
                <label>Change Account Phone</label>
            </value>
            <value>
                <fullName>New</fullName>
                <color>#E27001</color>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Entry Error</fullName>
                <color>#2F5D85</color>
                <label>Order Entry Error</label>
            </value>
            <value>
                <fullName>Order Revision</fullName>
                <color>#EFAE73</color>
                <label>Order Revision</label>
            </value>
            <value>
                <fullName>Wrong Label</fullName>
                <color>#FF6666</color>
                <label>Wrong Label</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Do_Not_Send_Surveys__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Surveys__c</fullName>
    <description>Do NOT Delete - used for Case - Closed Send Survey workflow to check if Contact does not want to receive surveys</description>
    <formula>Contact.Do_Not_Send_Surveys__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Do Not Send Surveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Do_Not_Send_Surveys__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Surveys__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to flag contacts that do not want to receive surveys.</description>
    <label>Do Not Send Surveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_Threshold_Reached__c.field-meta.xml
<CustomField>
    <fullName>Survey_Threshold_Reached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field gets checked to TRUE when the survey threshold value has been reached for the number of surveys sent out in a 12 month period.</description>
    <label>Survey Threshold Reached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Built for Timba Survey</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/classes/CaseSetCreateSurveyTaskFlagTest.cls
@isTest
private class CaseSetCreateSurveyTaskFlagTest {

    static Case testCase;
    static Contact testContact;
    static Account testAccount;
    static TriggerSettings__c settings;
    
    static void initialize() {    	
    	settings = TriggerSettings__c.getInstance();
    	
        testAccount = ECTestDataFactory.createAccount('Acme', true);
        system.assertNotEquals(null, testAccount.Id);
        
        testContact = ECTestDataFactory.CreateContact('Fred', 'Flintstone', 'fflintstone@test.com', false);
        testContact.Active__c = true;
        testContact.Do_Not_Send_Surveys__c = false;
        testContact.HasOptedOutOfEmail = false;
        testContact.Survey_Threshold_Reached__c = false;
        insert testContact;
        system.assertNotEquals(null, testContact.Id);
        
        BusinessHours bh = [select id from BusinessHours where IsDefault=true];
        Id recordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Support').getRecordTypeId();
        testCase = ECTestDataFactory.createCase('Order', 'New', 'Phone', bh.Id ,recordTypeId , testAccount.Id, testContact.Id, false);
        insert testCase;
        system.assertNotEquals(null, testCase.Id);
        
    }
    
    static testMethod void testSendSurveyWhenCaseClosedTypeOrder() {
        initialize();
        
        testCase.Status = 'Closed';
        testCase.Type = 'Order';
        testCase.Case_Type_Detail__c = 'Order Entry Error';
        
        test.startTest();
            update testCase;
        test.stopTest();
    }
    
    static testMethod void testSendSurveyWhenCaseClosedTypeSalesSupport() {
        initialize();
        
        testCase.Status = 'Closed';
        testCase.Type = 'Sales Support';
        testCase.Case_Type_Detail__c = 'Order Revision';
        
        test.startTest();
            update testCase;
        test.stopTest();
    }
    
    static testMethod void testDoNotSendSurveyWhenCaseClosed() {
        initialize();
        
        testCase.Status = 'Closed';
        testCase.Type = 'Shipping';
        testCase.Case_Type_Detail__c = 'Wrong Label';
        
        test.startTest();
            update testCase;
        test.stopTest();
    }
}