force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Status__c</fullName>
    <inlineHelpText>Maintained by MultiService. Submitted Value only used for internal processes.</inlineHelpText>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved/Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Credit Hold</fullName>
            </value>
            <value>
                <fullName>Application Sent</fullName>
                <isActive>false</isActive>
                <label>Application Sent</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the related Dealer. 
Field Type: Store Data
Integrated: N</description>
    <inlineHelpText>This is a lookup to the related Dealer.

Responsible Owner: Dealer Operations and Store Operations</inlineHelpText>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Account Publish Status</description>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <description>The Region code defined in M3 associated to a person (Region Director) and a geographical area within a brand. Theoretically, the region director would be the same in all brands. 
Type: M3
Integrated: Y</description>
    <inlineHelpText>The Region code defined in M3 that is associated to a Sales Region.</inlineHelpText>
    <label>Region Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Requires_Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Requires_Invoicing__c</fullName>
    <label>Requires Invoicing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Store_Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Store_Ownership_Type__c</fullName>
    <description>Type of store; Dealership, Company Owned, or Branded
Field Type: Store Data - Automatically populated based on M3 Customer Group
Integrated: Y - SF&gt;Xstore pricing portal</description>
    <inlineHelpText>Please select the type of store - used in reporting &amp; list views to separate Company Owned, Dealer, and Branded stores.

Responsible Owner: M3</inlineHelpText>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Branded</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/M3_Store_Parent_Account.recordType-meta.xml
<RecordType>
    <fullName>M3_Store_Parent_Account</fullName>
    <active>true</active>
    <description>Designed for M3 Store Parent Accounts</description>
    <label>M3 Store Parent Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Publishing Status for subscriber systems.  Set as part of Contact Outbound Message.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Publishing Status for subscriber systems.  Set as part of Contact Outbound Message.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <description>Referenced by Stores.</description>
    <label>Dealer</label>
    <nameField>
        <label>Dealership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Program Publish Status</description>
    <inlineHelpText>Program Publish Status</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Servicing_Level__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Level__c</fullName>
    <description>Controls the sharing (servicing stores) for an Industrial Account Program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Controls the sharing (servicing stores) for an Industrial Account Program.
Dealer Only and Dealer Market Area Program are allowed for Dealer Stores. 
RWSS is allowed for Corporate Stores.</inlineHelpText>
    <label>Servicing Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RWSS</fullName>
            </value>
            <value>
                <fullName>RWSSPlus</fullName>
                <default>true</default>
                <label>RWSS +</label>
            </value>
            <value>
                <fullName>DealerMarketAreaProgram</fullName>
                <label>Dealer Market Area Program</label>
            </value>
            <value>
                <fullName>DealerOnly</fullName>
                <label>Dealer Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_AccountProgramAccess_Batch_Test.cls
@isTest
private class RWS_AccountProgramAccess_Batch_Test {
    static testMethod void testBatch() {

    	Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');
        
        Id m3RtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('M3_Store_Parent_Account', 'Account');
        
        Dealer__c d = RWS_TestUtil.createDealer(true);
        
        Account acc = RWS_TestUtil.createAccount(m3RtId, false);
        acc.Credit_Status__c = null;
        acc.Publish_Status__c = null;
        acc.Requires_Invoicing__c = null;
        acc.Active__c = false;
        acc.Store_Ownership_Type__c = 'Dealer';
        acc.Dealer__c = d.Id;
        acc.Region_Code__c = '01';
        
        Account acc2 = RWS_TestUtil.createAccount(rtId, false);
        acc2.Store_Ownership_Type__c = 'Corporate';
        acc2.Dealer__c = d.Id;
        acc2.Region_Code__c = '01';
        
        Account acc3 = RWS_TestUtil.createAccount(rtId, false);
        acc3.Store_Ownership_Type__c = 'Corporate';
        acc3.Dealer__c = d.Id;
        acc3.Region_Code__c = '01';
        
        Account acc5 = RWS_TestUtil.createAccount(rtId, false);
        acc5.Store_Ownership_Type__c = 'Dealer';
        acc5.Region_Code__c = '01';
        
        List<Account> accList = new List<Account>{acc, acc2, acc3, acc5};
            
        insert accList;

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        Contact con2 = RWS_TestUtil.createContact(acc.Id, 1, false);

        List<Contact> contacts = new List<Contact>{con2, con1};

        insert contacts;

        Id roleId = [select Id from UserRole where Name = 'System Administrators' limit 1].Id;

        User u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {

            User user = new User(Id = UserInfo.getUserId(), UserRoleId = roleId);
            update user;
            
            insert u1;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u1.UserRoleId = partnerRoleId;

            update u1;
        }

        Test.startTest();

        System.runAs(u1) {
            Program__c pr = RWS_TestUtil.createProgram(acc.Id, false);  
            pr.Servicing_Level__c = 'DealerOnly';
            
            
            Program__c pr2 = RWS_TestUtil.createProgram(acc.Id, false);  
            pr2.Servicing_Level__c = 'DealerMarketAreaProgram';
            
            insert new List<Program__c>{pr, pr2};
        }
        
        User u2 = RWS_TestUtil.createCommunityUser(con2.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {
            
            insert u2;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u2.UserRoleId = partnerRoleId;

            update u2;
        }
        
        RWS_AccountProgramAccess_Batch b = new RWS_AccountProgramAccess_Batch();
        
        b.execute(null);
        
        acc.Region_Code__c = '02';
        update acc;
        
        b.execute(null);

        Test.stopTest();
    }
}