force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Atributes_Required__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Atributes_Required__c</fullName>
    <description>Select up to 4 Invoice Attributes Required for the Account. This information is also copied to the Account&apos;s Programs where Type is not Cash and Carry. These are related directly to the Account_Invoice_Attributes_Up_to_4 validation rule. Both must be in sync.</description>
    <inlineHelpText>Select up to 4 Invoice Attributes Required for the Account. This information is also copied to the Account&apos;s Programs where Type is not Cash and Carry.</inlineHelpText>
    <label>Invoice Attributes Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Authform</fullName>
                <label>Auth form #</label>
            </value>
            <value>
                <fullName>AuthorizerManager</fullName>
                <label>Authorizer / Manager</label>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>BusinessUnit</fullName>
                <label>Business Unit</label>
            </value>
            <value>
                <fullName>Certificate</fullName>
                <label>Certificate #</label>
            </value>
            <value>
                <fullName>ChargeCode</fullName>
                <label>Charge Code</label>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>CostCenter</fullName>
                <label>Cost Center</label>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Division</fullName>
            </value>
            <value>
                <fullName>EmployeeID</fullName>
                <label>Employee ID</label>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>GL</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
                <label>Project #</label>
            </value>
            <value>
                <fullName>Purchaseorder</fullName>
                <label>Purchase order</label>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>TicketReceipt</fullName>
                <label>Ticket/Receipt</label>
            </value>
            <value>
                <fullName>VendorNumber</fullName>
                <label>Vendor Number</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>UDF</fullName>
                <isActive>false</isActive>
                <label>UDF</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Accessories_Allowed_on_Payroll_Deduction__c.field-meta.xml
<CustomField>
    <fullName>Accessories_Allowed_on_Payroll_Deduction__c</fullName>
    <description>Indicates whether the employee is allowed to purchase accessories on payroll deduction.  
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates whether the employee is allowed to purchase accessories on payroll deduction.</inlineHelpText>
    <label>Accessories Allowed on Payroll Deduction</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Ecomm_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Ecomm_Enabled__c</fullName>
    <description>Designates a digital voucher program to be used for ecommerce purchases</description>
    <inlineHelpText>Designates a digital voucher program to be used for ecommerce purchases</inlineHelpText>
    <label>Ecomm Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Eligibility_Option__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Eligibility_Option__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Option__c</fullName>
    <description>Indicates whom the eligibility is tied / not tied with.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates whom the eligibility is tied / not tied with.</inlineHelpText>
    <label>Use Eligibility Tool</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>False</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>True</fullName>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Invoice_Attributes_Required__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Attributes_Required__c</fullName>
    <description>Text field to be populated by the related Account Invoice Attributes Required value when Type is not Cash and Carry.</description>
    <inlineHelpText>This field is controlled by the Account and populated when Type is not Cash and Carry</inlineHelpText>
    <label>Invoice Attributes Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <description>Indicates if employees are required to use payroll deduct for their portion of the transaction
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Are employees required to use payroll deduct for their portion of the transaction?</inlineHelpText>
    <label>Mandatory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Require_Upload_of_Company_Voucher__c.field-meta.xml
<CustomField>
    <fullName>Require_Upload_of_Company_Voucher__c</fullName>
    <description>Identify if Upload of Company Voucher is required.</description>
    <inlineHelpText>Identify if Upload of Company Voucher is required.</inlineHelpText>
    <label>Require Upload of Company Voucher</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Eligibility_Option__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Servicing_Level__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Level__c</fullName>
    <description>Controls the sharing (servicing stores) for an Industrial Account Program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Controls the sharing (servicing stores) for an Industrial Account Program.
Dealer Only and Dealer Market Area Program are allowed for Dealer Stores. 
RWSS is allowed for Corporate Stores.</inlineHelpText>
    <label>Servicing Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RWSS</fullName>
            </value>
            <value>
                <fullName>RWSSPlus</fullName>
                <default>true</default>
                <label>RWSS +</label>
            </value>
            <value>
                <fullName>DealerMarketAreaProgram</fullName>
                <label>Dealer Market Area Program</label>
            </value>
            <value>
                <fullName>DealerOnly</fullName>
                <label>Dealer Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of Industrial Account Program.  The type of program determines options for Subsidy, Eligibility, and Payroll Deduction.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The type of Industrial Account Program.  The type of program determines options for Subsidy, Eligibility, and Payroll Deduction.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CashandCarry</fullName>
                <label>Cash and Carry</label>
            </value>
            <value>
                <fullName>PayrollDeduction</fullName>
                <label>Payroll Deduction</label>
            </value>
            <value>
                <fullName>Subsidy</fullName>
            </value>
            <value>
                <fullName>SubsidyandPayrollDeduction</fullName>
                <label>Subsidy and Payroll Deduction</label>
            </value>
            <value>
                <fullName>SubsidywithPcard</fullName>
                <label>Subsidy with Pcard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/Servicing_Store__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Object created to share programs based on servicing level with downstream systems via outbound message</description>
    <label>Servicing Store</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Servicing Store #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Servicing Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicing_Store__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Servicing Stores</relationshipLabel>
    <relationshipName>Servicing_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_ProgramTrigger_Test.cls
@isTest
private class RWS_ProgramTrigger_Test {

    static testMethod void testSetInvoiceAttributes() {
        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');
		
        Account acc = RWS_TestUtil.createAccount(rtId, false);
        acc.Invoice_Atributes_Required__c = 'Branch';
        insert acc;

        Program__c pr = RWS_TestUtil.createProgram(acc.Id, false);
        pr.Active__c = false;
        insert pr;

       System.assertEquals(null, 
                        [select Invoice_Attributes_Required__c from Program__c where Id = :pr.Id].Invoice_Attributes_Required__c);

        pr.Type__c = 'PayrollDeduction';
        pr.Mandatory__c = 'No';
        pr.Accessories_Allowed_on_Payroll_Deduction__c = 'No';
        pr.Servicing_Level__c = 'RWSS';
        pr.Require_Upload_of_Company_Voucher__c = 'No';
        //test changing ecomm/digital values too.
        pr.Ecomm_Enabled__c = 'Yes';
        pr.Eligibility_Option__c = 'True';
        pr.Allow_Expedited_Shipping__c  = 'No';
        pr.Annual_Reset_or_Rollover__c = 'Single-use';
        //If Active__c is true; and "Processing_Status__c" is not completed
        //we need "hasBeenActive__c" to be true
        pr.HasBeenActive__c = false;

        update pr;

        System.assertEquals(acc.Invoice_Atributes_Required__c, 
                        [select Invoice_Attributes_Required__c from Program__c where Id = :pr.Id].Invoice_Attributes_Required__c);

    }

    static testMethod void testPublish() {
        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        Program__c pr = RWS_TestUtil.createProgram(acc.Id, true);

        Product2 prod = RWS_TestUtil.createProduct(true);

        Id pricebookId = Test.getStandardPricebookId();

        PricebookEntry standardPrice = RWS_TestUtil.createPricebookEntry(pricebookId, prod.Id, true);

        Publish_PriceBook__c customPB = RWS_TestUtil.createCustomPublishPricebook(pr.Id, true);

        Publish_PriceBook_Entry__c	 customPrice = RWS_TestUtil.createPublishPricebookEntry(customPB.Id, prod.Id, true);

        RWS_PriceBookEntry_Util.createPublicPriceBookEntries(new List<Publish_PriceBook_Entry__c>{customPrice});

        Servicing_Store__c ss = RWS_TestUtil.createServicingStore(acc.Id, pr.Id, true);

        pr.Publish_Status__c = '';

        pr.Servicing_Level__c = 'RWSS';
        Test.startTest();
        update pr;
        Test.stopTest();

    }
    static testMethod void testSetExpiration() {
        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        Program__c pr = RWS_TestUtil.createProgram(acc.Id, true);   

        pr.Active__c = false;

        update pr;


        Program__c prog = [select Id, Expiration_Date__c from Program__c where Id = :pr.Id];
        System.assert(prog.Expiration_Date__c == date.today());
    }
    
    static testMethod void testTriggerDealer() {

        Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');
		
        Account csAcc = RWS_TestUtil.createAccount(rtId, false);
        csAcc.Invoice_Atributes_Required__c = 'Branch';
        insert csAcc;
        
        insert new Region_Exception__c(Name = '01', Accounts_CSV__c = String.valueOf(csAcc.Id));        
        
        Dealer__c d = RWS_TestUtil.createDealer(true);
        
        Account acc = RWS_TestUtil.createAccount(rtId, false);
        acc.Store_Ownership_Type__c = 'Dealer';
        acc.Dealer__c = d.Id;
        acc.Region_Code__c = '01';
        
        Account acc2 = RWS_TestUtil.createAccount(rtId, false);
        acc2.Store_Ownership_Type__c = 'Corporate';
        acc2.Dealer__c = d.Id;
        acc2.Region_Code__c = '01';
        
        Account acc3 = RWS_TestUtil.createAccount(rtId, false);
        acc3.Store_Ownership_Type__c = 'Corporate';
        acc3.Dealer__c = d.Id;
        acc3.Region_Code__c = '01';
        
        Account acc5 = RWS_TestUtil.createAccount(rtId, false);
        acc5.Store_Ownership_Type__c = 'Dealer';
        acc5.Region_Code__c = '01';
        
        List<Account> accList = new List<Account>{acc, acc2, acc3, acc5};
            
        insert accList;

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        Contact con2 = RWS_TestUtil.createContact(acc.Id, 1, false);

        List<Contact> contacts = new List<Contact>{con2, con1};

        insert contacts;

        Id roleId = [select Id from UserRole where Name = 'System Administrators' limit 1].Id;

        User u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, false);
        User u2 = RWS_TestUtil.createCommunityUser(con2.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {

            User user = new User(Id = UserInfo.getUserId(), UserRoleId = roleId);
            update user;



            List<User> users = new List<User>{u2, u1};  
            insert users;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u1.UserRoleId = partnerRoleId;
            u2.UserRoleId = partnerRoleId;

            update users;
        }

        Test.startTest();
        User userTest = [SELECT Id, Contact.Account.Region_Code__c FROM User WHERE Id =: u1.Id];
        System.debug(userTest);

        System.runAs(u1) {
            Program__c pr = RWS_TestUtil.createProgram(acc.Id, false);  
            pr.Servicing_Level__c = 'DealerOnly';
            insert pr;
        }


        System.runAs(u2) {
            Program__c pr = RWS_TestUtil.createProgram(acc.Id, false);  
            pr.Servicing_Level__c = 'DealerMarketAreaProgram';
            insert pr;
        }

        Test.stopTest();

    }

    static testMethod void testTriggerCorporate() {

        Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Dealer__c d = RWS_TestUtil.createDealer(true);
        
        Account acc = RWS_TestUtil.createAccount(rtId, false);
        acc.Store_Ownership_Type__c = 'Corporate';
        acc.Dealer__c = d.Id;
        acc.Region_Code__c = '01';
        
        Account acc2 = RWS_TestUtil.createAccount(rtId, false);
        acc2.Store_Ownership_Type__c = 'Corporate';
        acc2.Dealer__c = d.Id;
        acc2.Region_Code__c = '01';
        
        Account acc3 = RWS_TestUtil.createAccount(rtId, false);
        acc3.Store_Ownership_Type__c = 'Corporate';
        acc3.Dealer__c = d.Id;
        acc3.Region_Code__c = '01';
        
        Account acc5 = RWS_TestUtil.createAccount(rtId, false);
        acc5.Store_Ownership_Type__c = 'Dealer';
        acc5.Region_Code__c = '01';
        
        List<Account> accList = new List<Account>{acc, acc2, acc3, acc5};
            
        insert accList;

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        Contact con2 = RWS_TestUtil.createContact(acc.Id, 1, false);

        List<Contact> contacts = new List<Contact>{con2, con1};

        insert contacts;

        Id roleId = [select Id from UserRole where Name = 'System Administrators' limit 1].Id;

        User u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, false);
        User u2 = RWS_TestUtil.createCommunityUser(con2.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {

            User user = new User(Id = UserInfo.getUserId(), UserRoleId = roleId);
            update user;



            List<User> users = new List<User>{u2, u1};  
            insert users;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u1.UserRoleId = partnerRoleId;
            u2.UserRoleId = partnerRoleId;

            update users;
        }

        Test.startTest();
        
        System.runAs(u1) {
            Program__c pr = RWS_TestUtil.createProgram(acc.Id, false);  
            pr.Servicing_Level__c = 'RWSS';
            insert pr;
        }

        Test.stopTest();

    }
}