force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Outbound_Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Message_Type__c</fullName>
    <description>Outbound Message Type</description>
    <label>Outbound Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Application</fullName>
            </value>
            <value>
                <fullName>Active Account</fullName>
            </value>
            <value>
                <fullName>Update Account</fullName>
            </value>
            <value>
                <fullName>Deactivate</fullName>
                <label>Deactivate Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Account Publish Status</description>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Industrial Account (Account Standard Object) for the program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to Industrial Account (Account Standard Object) for the program.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/HasPricebook__c.field-meta.xml
<CustomField>
    <fullName>HasPricebook__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by APEX to flag Programs that have an active custom Pricebook.</description>
    <inlineHelpText>This field is used by APEX to flag Programs that have an active custom Pricebook.</inlineHelpText>
    <label>HasPricebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Outbound_Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Message_Type__c</fullName>
    <description>Outbound Message Type
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Outbound Message Type</inlineHelpText>
    <label>Outbound Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <description>Indicates the related Price Book (ID).
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the related Price Book.</inlineHelpText>
    <label>Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Program Publish Status</description>
    <inlineHelpText>Program Publish Status</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Active_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Active_PriceBook__c</fullName>
    <description>Formula Field to return the status (Active / Inactive) of a Program&apos;s Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <formula>Program__r.Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula Field to return the status (Active / Inactive) of a Program&apos;s Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Active PriceBook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the Publish Pricebook is Active</description>
    <inlineHelpText>Identify if the Publish Pricebook is Active</inlineHelpText>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Outbound_Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Message_Type__c</fullName>
    <description>Indicates the Outbound Message Type
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the Outbound Message Type</inlineHelpText>
    <label>Outbound Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update PriceBook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <description>Formula field which returns the ID from a Price Book (standard object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <formula>IF( Historic_Pricebook_ID__c != NULL, Historic_Pricebook_ID__c, CASESAFEID(Id))</formula>
    <inlineHelpText>Formula field which returns the ID from a Price Book (standard object)  Used in outbound messaging.</inlineHelpText>
    <label>Price Book ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_PublishPriceBookTrigger_Handler.cls
/********************************************************************************
*   PURPOSE : Validate publishing criteria for Publish_PriceBook__c and set ReadyToPublish
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   12/07/2016  Usman Aslam/M360        Initial version
*   03/01/2018  Brandon Willard/M360    Removed standard pricebook references and added in
*										functionality to copy publish pricebook Id to the program
*										instead of pricebook Id - RWCP-3449
********************************************************************************/

public with sharing class RWS_PublishPriceBookTrigger_Handler {
    
    //Is the below needed for Publish Pricebooks? 
    //--Start--    
    public static void beforeInsert(List<Publish_PriceBook__c> newList) {
        for(Publish_PriceBook__c ppb : newList) {
            if(ppb.Name != null && ppb.Name.length() > 80) ppb.Name = ppb.Name.left(80);
        }
    }

    public static void beforeUpdate(List<Publish_PriceBook__c> newList, Map<Id, Publish_PriceBook__c> oldMap) {
        for(Publish_PriceBook__c ppb : newList) {
            if(ppb.Name != null && ppb.Name.length() > 80) ppb.Name = ppb.Name.left(80);
        }
    }
    //--End--
    

    public static void afterInsert(List<Publish_PriceBook__c> newList) {
        // get publish price book information with program details
    	List<Publish_PriceBook__c> publishPricebooksWithProgramInfo = getPublishPricebooksWithProgramInfo(newList);

    	List<Publish_PriceBook__c> publishPricebooksToUpdate = new List<Publish_PriceBook__c>();


    	for(Publish_PriceBook__c ppb : publishPricebooksWithProgramInfo) {

            // if status is ReadyToPublish move to next iteration
    		if(ppb.Publish_Status__c == 'ReadyToPublish') continue;

            // validate records and set new values
    		if(validatePublishPriceBook(ppb)) {
    			setNewValues(ppb,true);
       		}
            else {
                setNewValues(ppb,false);
            }
            publishPricebooksToUpdate.add(ppb);
    	}

        // update records
        if(!publishPricebooksToUpdate.isEmpty()) {
            update publishPricebooksToUpdate;
        }
        
        setPublishPricebookIdOnProgram(newList, false);
    }

    private static Boolean RUN_UPDATE_ONCE = true;
    public static void afterUpdate(List<Publish_PriceBook__c> newList, Map<Id, Publish_PriceBook__c> oldMap) {
    	if(!RUN_UPDATE_ONCE) return;

        // get publish price book information with program details
    	List<Publish_PriceBook__c> publishPricebooksWithProgramInfo = getPublishPricebooksWithProgramInfo(newList);

    	List<Publish_PriceBook__c> publishPricebooksToUpdate = new List<Publish_PriceBook__c>();

    	for(Publish_PriceBook__c ppb : publishPricebooksWithProgramInfo) {

            // if status is ReadyToPublis,  Waiting , Deactivated or just changed to published, move to next iteration
    		if((ppb.Publish_Status__c == 'ReadyToPublish') || (ppb.Publish_Status__c == 'Waiting') || (ppb.Publish_Status__c == 'Deactivated') ||
    			(ppb.Publish_Status__c == 'Published' && 
    				ppb.Publish_Status__c != oldMap.get(ppb.id).Publish_Status__c)) continue;

            // validate records and set new values
            //if(ppb.Active_PriceBook__c != oldMap.get(ppb.id).Active_PriceBook__c) {
            if(ppb.Active_PriceBook__c != oldMap.get(ppb.id).Active_PriceBook__c && !ppb.Active_PriceBook__c) {
                //No need to set here: When Pricebook is deactivated, it is already set in RWS_ProgramTrigger_Handler               
                //ppb.Outbound_Message_Type__c = 'Update PriceBook';
                //ppb.Publish_Status__c = 'ReadyToPublish';
            } else if(validatePublishPriceBook(ppb)) {
    			setNewValues(ppb,true);
    		}
            else {
                setNewValues(ppb,false);
            }
            publishPricebooksToUpdate.add(ppb);

    	}

        // update records
        if(!publishPricebooksToUpdate.isEmpty()) {
        	RUN_UPDATE_ONCE = Test.isRunningTest();
            update publishPricebooksToUpdate;
        }
        
        setPublishPricebookIdOnProgram(newList, oldMap);
    	
    }
    
    // handles before delete event
    public static void beforeDelete(List<Publish_PriceBook__c> newList) {
        setPublishPricebookIdOnProgram(newList, true);
    }
    
    // handles after undelete event
    public static void afterUndelete(List<Publish_PriceBook__c> newList) {
        setPublishPricebookIdOnProgram(newList, false);
    }

    // get publish price book information with program details
    private static List<Publish_PriceBook__c> getPublishPricebooksWithProgramInfo(List<Publish_PriceBook__c> newList) {
    	Set<Id> ppbIds = new Map<Id, Publish_PriceBook__c>(newList).keySet();

    	List<Publish_PriceBook__c> ppbs 
    		= [select Id, Publish_Status__c,
    	 			Outbound_Message_Type__c,
    	 			IsActive__c,
    	 			Program__r.Active__c,
    	 			Program__r.Publish_Status__c,
    	 			Program__r.Account__r.Active__c,
    	 			Program__r.Account__r.Publish_Status__c,
                    Active_PriceBook__c
    	 			from Publish_PriceBook__c 
    	 		where Id in :ppbIds];

    	return ppbs;
    }

    // validate record
    private static Boolean validatePublishPriceBook(Publish_PriceBook__c ppb) {

    	return (ppb.IsActive__c &&
    			ppb.Program__r.Active__c &&
                ppb.Program__r.Publish_Status__c == 'Published' && //Jas- added Program Publish_status
    			ppb.Program__r.Account__r.Active__c &&
    			ppb.Program__r.Account__r.Publish_Status__c == 'Published');
    }

    // set new values on the record
    private static void setNewValues(Publish_PriceBook__c ppb, Boolean publish) {
        if(publish){
    	    ppb.Outbound_Message_Type__c = 'Update PriceBook';
            ppb.Publish_Status__c = 'ReadyToPublish';  
        }
        else
            ppb.Publish_Status__c = 'Waiting';  
    }
	
    private static void setPublishPricebookIdOnProgram(List<Publish_PriceBook__c> newList, Map<Id, Publish_PriceBook__c> oldMap) {
        List<Publish_PriceBook__c> relatedRecords = new List<Publish_PriceBook__c>();

        for(Publish_PriceBook__c ppb : newList) {
            //if(pb.IsActive == oldMap.get(pb.Id).IsActive)  continue;

            relatedRecords.add(ppb);
        }

        if(relatedRecords.isEmpty()) return;

        setPublishPricebookIdOnProgram(relatedRecords, false);
    }

    private static void setPublishPricebookIdOnProgram(List<Publish_PriceBook__c> newList, Boolean isDelete) {
        Map<Id, Program__c> programsToUpdate = new Map<Id, Program__c>();

        Set<Id> programIds = new Set<Id>();

        for(Publish_PriceBook__c ppb : newList) {
            if(ppb.Program__c == null) continue;

            programIds.add(ppb.Program__c);
        }

        if(programIds.isEmpty()) return;

        List<Publish_PriceBook__c> otherPriceBooks = [select Id, Program__c from Publish_PriceBook__c 
            where Program__c != null and Program__c in :programIds and Id not in :newList];

        Set<Id> programAlreadyHavingPricebook = new Set<Id>();

        for(Publish_PriceBook__c pb : otherPriceBooks) {
            programAlreadyHavingPricebook.add(pb.Program__c);
        }

        for(Publish_PriceBook__c pb : newList) {
            if(pb.Program__c == null) continue;

            if(programAlreadyHavingPricebook.contains(pb.Program__c) && (!isDelete) ) pb.addError('Program already has a Pricebook.');

            programsToUpdate.put(pb.Program__c, new Program__c(Id = pb.Program__c, 
                                                    Price_Book_ID__c = isDelete ? null : pb.Id ,
                                                    HasPricebook__c = isDelete ? false : pb.IsActive__c ));
        }

        if(!programsToUpdate.isEmpty()) update programsToUpdate.values();
    }

}