force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MSTS_ID__c.field-meta.xml
<CustomField>
    <fullName>MSTS_ID__c</fullName>
    <description>Sample IA 2.0 Field - Multi Service Technology Solutions Account Record Unique ID 
Field Type: MSTS
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>Multi Service record identifier</inlineHelpText>
    <label>RWBAA Customer ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Contact_Identifier__c</fullName>
    <description>This field was requested by Jeff G to identify the primary contact.</description>
    <inlineHelpText>Please identify this contact as Primary or Billing.</inlineHelpText>
    <label>Contact Identifier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Primary &amp; Billing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Invoice Payment Portal Admin</label>
            </value>
            <value>
                <fullName>Truck Run</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/RWBAA_AR_Data__c.object-meta.xml
<CustomObject>
    <label>RWBAA AR Data</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>RWBAA AR Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWBAA AR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Partner Community</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RWBAA AR Data</relationshipLabel>
    <relationshipName>RWBAA_AR_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_121_to_150__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_121_to_150__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>MSTS AR 121 to 150</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_15_to_30__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_15_to_30__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>MSTS AR 15 to 30</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_1_to_7__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_1_to_7__c</fullName>
    <label>MSTS AR 1 to 7</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_31_to_45__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_31_to_45__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>MSTS AR 31 to 45</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_46_to_60__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_46_to_60__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>MSTS AR 46 to 60</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_61_to_90__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_61_to_90__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>MSTS AR 61 to 90</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_8_to_14__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_8_to_14__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>MSTS AR 8 to 14</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_91_to_120__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_91_to_120__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>MSTS AR 91 to 120</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_Current__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_Current__c</fullName>
    <label>MSTS AR Current</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_AR_Over_150__c.field-meta.xml
<CustomField>
    <fullName>MSTS_AR_Over_150__c</fullName>
    <label>MSTS AR Over 150</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_Available_Credit__c.field-meta.xml
<CustomField>
    <fullName>MSTS_Available_Credit__c</fullName>
    <label>MSTS Available Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>MSTS_Credit_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MSTS Credit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_AR_Data__c/fields/MSTS_Unapplied_Payment__c.field-meta.xml
<CustomField>
    <fullName>MSTS_Unapplied_Payment__c</fullName>
    <label>MSTS Unapplied Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RWBAA_Contacts__c/RWBAA_Contacts__c.object-meta.xml
<CustomObject>
    <description>Multiservice RWBAA Contacts - Read Only</description>
    <label>RWBAA Contact</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>RWBAA Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWBAA Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RWBAA_Contacts__c/fields/RWBAA_Active__c.field-meta.xml
<CustomField>
    <fullName>RWBAA_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Designates that the Contact is Active or Inactive for this account</description>
    <inlineHelpText>Contact is Active or Inactive for this account</inlineHelpText>
    <label>RWBAA Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RWBAA_Contacts__c/fields/RWBAA_Bill_Send_Type__c.field-meta.xml
<CustomField>
    <fullName>RWBAA_Bill_Send_Type__c</fullName>
    <description>Multiservice RWBAA Contact Bill Send Type</description>
    <inlineHelpText>Multiservice RWBAA Contact Bill Send Type</inlineHelpText>
    <label>RWBAA Bill Send Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RWBAA_Contacts__c/fields/RWBAA_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>RWBAA_Contact_Type__c</fullName>
    <description>Multiservice RWBAA Contact Types used to classify contacts in their system</description>
    <inlineHelpText>Multiservice RWBAA Contact Types used to classify contacts in their system</inlineHelpText>
    <label>RWBAA Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Physical Location</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RWBAA_Contacts__c/fields/RWBAA_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>RWBAA_Email_Address__c</fullName>
    <description>Multiservice RWBAA Contact Email Address</description>
    <inlineHelpText>Multiservice RWBAA Contact Email Address</inlineHelpText>
    <label>RWBAA Email Address</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RWBAA_Contacts__c/fields/RWBAA_First_Name__c.field-meta.xml
<CustomField>
    <fullName>RWBAA_First_Name__c</fullName>
    <description>Multiservice RWBAA Contact First name</description>
    <inlineHelpText>Multiservice RWBAA Contact First name</inlineHelpText>
    <label>RWBAA First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RWBAA_Contacts__c/fields/RWBAA_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>RWBAA_Last_Name__c</fullName>
    <description>Multiservice RWBAA Last Name</description>
    <inlineHelpText>Multiservice RWBAA Last Name</inlineHelpText>
    <label>RWBAA Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RWBAA_Contacts__c/fields/RWBAA_Phone__c.field-meta.xml
<CustomField>
    <fullName>RWBAA_Phone__c</fullName>
    <description>Multiservice RWBAA Contact Phone Number</description>
    <inlineHelpText>Multiservice RWBAA Contact Phone Number</inlineHelpText>
    <label>RWBAA Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RWBAA_Contacts__c/fields/RWfB_Account__c.field-meta.xml
<CustomField>
    <fullName>RWfB_Account__c</fullName>
    <description>RWfB Account in Salesforce for the RWBAA Contact in Multiservice</description>
    <inlineHelpText>RWfB Account in Salesforce for the RWBAA Contact in Multiservice</inlineHelpText>
    <label>RWfB Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RWBAA Contacts</relationshipLabel>
    <relationshipName>RWBAA_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RWS_RwbaaARSummaryController.cls
public with sharing class RWS_RwbaaARSummaryController {
	
	public string accountId {get;set;}
	public string query {get;set;}
	Id currentUserId {get; set;} 
	
	public String AccountName {get;set;}
    public String AccountNumber {get;set;}
	public String ARLastModifiedDate {get;set;}
	public String RwbaaId {get;set;}
	public String CurrentAmount {get;set;}
	public String UnappliedPayment {get;set;}	
	public String TotalCreditLine {get;set;}
	public String RemainingCredit {get;set;}
	public String DaysLate1to7 {get;set;}    
	public String DaysLate8to14 {get;set;}
	public String DaysLate15to30 {get;set;}
	public String DaysLate31to45 {get;set;}
	public String DaysLate46to60 {get;set;}    
	public String DaysLateOver60 {get;set;} 
	public List<Contact> RWFBContacts {get;set;}
	public List<RWBAA_Contacts__c> RWBAAContacts {get;set;}
	
	//Constructor
	public RWS_RwbaaARSummaryController(){
		currentUserId = UserInfo.getUserId(); 
		accountId = Apexpages.currentpage().getparameters().get('id');
		setQuery();
        getRwbaaARData();
	}
    
    public void setQuery(){
    	query = 'select id,Name, MSTS_ID__c, AccountNumber, ' +
	    			'(select id,LastModifiedDate, MSTS_AR_Current__c,MSTS_Unapplied_Payment__c,MSTS_Credit_Limit__c,MSTS_Available_Credit__c,' +
            			'MSTS_AR_1_to_7__c, MSTS_AR_8_to_14__c, MSTS_AR_15_to_30__c,MSTS_AR_31_to_45__c,' +
						'MSTS_AR_46_to_60__c,MSTS_AR_61_to_90__c,MSTS_AR_91_to_120__c,MSTS_AR_121_to_150__c,MSTS_AR_Over_150__c from RWBAA_AR_Data__r),' +
					'(select id, RWBAA_First_Name__c, RWBAA_Last_Name__c, RWBAA_Contact_Type__c,RWBAA_Phone__c,RWBAA_Email_Address__c,RWBAA_Bill_Send_Type__c,' +
						'RWBAA_Active__c from RWBAA_Contacts__r Order by RWBAA_Active__c DESC, RWBAA_Bill_Send_Type__c DESC),' + 
					'(select id, FirstName, LastName,Contact_Identifier__c,Phone,Title,Email,Active__c from Contacts Order by Active__c DESC, Contact_Identifier__c DESC)' + 
				'from account where id = :accountId limit 1000';
        System.debug('Query: ' + accountId + query);
    }
    
    public void getRwbaaARData(){
    	List<Account> account = Database.query(query);
    	User  myUser = [select id,TimeZoneSidKey from user where id = :currentUserId ];
    	System.debug('Returned Account: ' + myUser + account);
    	
    	for(Account acctObj : account){ 		
    		AccountName = acctObj.Name;
    		RwbaaId = acctObj.MSTS_ID__c;
            AccountNumber = acctObj.AccountNumber;
            RWBAAContacts = new List<RWBAA_Contacts__c>();
    			RWBAAContacts = acctObj.RWBAA_Contacts__r;
            RWFBContacts = new List<Contact>();
    			RWFBContacts = acctObj.Contacts;
    		if(acctObj.RWBAA_AR_Data__r.size() != 0)
            {
            	List<RWBAA_AR_Data__c> rwbaaARData = acctObj.RWBAA_AR_Data__r;
            	for(RWBAA_AR_Data__c arData : rwbaaARData)
            	{
    				CurrentAmount = checkNull('$' + arData.MSTS_AR_Current__c);
    				ARLastModifiedDate = checkNull(arData.LastModifiedDate.format('MM/dd/yyyy hh:mm a z', myUser.TimeZoneSidKey));
    				UnappliedPayment = checkNull('$' + arData.MSTS_Unapplied_Payment__c);
    				TotalCreditLine = checkNull('$' + arData.MSTS_Credit_Limit__c);
    				RemainingCredit = checkNull('$' + arData.MSTS_Available_Credit__c);
    				DaysLate1to7 = checkNull('$' + arData.MSTS_AR_1_to_7__c);                    
    				DaysLate8to14 = checkNull('$' + arData.MSTS_AR_8_to_14__c);
    				DaysLate15to30 = checkNull('$' +  arData.MSTS_AR_15_to_30__c);
    				DaysLate31to45 = checkNull('$' + arData.MSTS_AR_31_to_45__c);
    				DaysLate46to60 = checkNull('$' + arData.MSTS_AR_46_to_60__c);
    				DaysLateOver60 = checkNull('$' + (arData.MSTS_AR_61_to_90__c + arData.MSTS_AR_91_to_120__c 
    											+ arData.MSTS_AR_121_to_150__c + arData.MSTS_AR_Over_150__c));
            	}
            }
    		System.debug('RWFB Contacts: ' + RWFBContacts);
    		System.debug('RWBAA Contacts: ' + RWBAAContacts); 
    		System.debug('CurrentAmount: ' + CurrentAmount);
    		    		
    	}
    }
    
    private String checkNull(string data){
    	if(data.contains('null'))
    	{
    		return '-';
    	}
    	return data;
    }
}