force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked = Active, UnChecked = InActive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Account Publish Status</description>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <description>Indicates the related Price Book (ID).
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the related Price Book.</inlineHelpText>
    <label>Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Program Publish Status</description>
    <inlineHelpText>Program Publish Status</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <description>Formula field which returns the ID from a Price Book (standard object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <formula>IF( Historic_Pricebook_ID__c != NULL, Historic_Pricebook_ID__c, CASESAFEID(Id))</formula>
    <inlineHelpText>Formula field which returns the ID from a Price Book (standard object)  Used in outbound messaging.</inlineHelpText>
    <label>Price Book ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_PriceBookTrigger_Test.cls
@isTest
private class RWS_PriceBookTrigger_Test {
    static testMethod void testTrigger() {
        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

    	Account acc = RWS_TestUtil.createAccount(rtId, true);

    	Program__c pr = RWS_TestUtil.createProgram(acc.Id, false);
        pr.Active__c = false;
        insert pr;

    	Product2 prod = RWS_TestUtil.createProduct(true);

		Pricebook2 priceBook = RWS_TestUtil.createCustomPricebook(pr.Id, false);
		priceBook.Discount__c = 20;
		insert priceBook;

        /*
        System.assertEquals([select Id, Price_Book_ID__c from Program__c where Id = :pr.Id].Price_Book_ID__c, 
                            priceBook.Id);

		List<Publish_PriceBook__c> ppbs = [
    		select Id, Discount__c, Publish_Status__c, Name
    		from Publish_PriceBook__c 
    		where Price_Book__c = :customPB.Id
    	];*/

		//System.assertEquals(1, ppbs.size(), 'Issue with public price book');
		//System.assertEquals(customPB.Discount__c, ppbs[0].Discount__c, 'Incorrect discount');
		System.assertEquals(priceBook.Name.length() < 80, true, 'Incorrect Name');
        
        priceBook.Discount__c = 10;
		update priceBook;

        delete priceBook;

        undelete priceBook;

        priceBook.IsActive = false;

        update priceBook;
    }
}