force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Updated automatically in the New Account Approval process.
Field Type: GBL
Integrated: N
New Account process has not deployed and approval process is not in use.</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
                <color>#78C953</color>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>In Vendor Compliance</fullName>
                <color>#E27001</color>
                <label>In Vendor Compliance</label>
            </value>
            <value>
                <fullName>In Credit</fullName>
                <color>#A845DC</color>
                <label>In Credit</label>
            </value>
            <value>
                <fullName>Scheduled for M3</fullName>
                <color>#F3D904</color>
                <label>Scheduled for M3</label>
            </value>
            <value>
                <fullName>Added to M3</fullName>
                <color>#A53711</color>
                <label>Added to M3</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#66E9BD</color>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#0B24BE</color>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Notes on the account
Type:GBL
Integrated: N</description>
    <inlineHelpText>Notes on the account. Data is only in Salesforce.</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Store_Number__c.field-meta.xml
<CustomField>
    <fullName>Store_Number__c</fullName>
    <description>This is the three digit store number in M3.
Field Type: M3
Integrated: Y -  M3&gt;SF&gt;Xstore pricing portal</description>
    <inlineHelpText>This is the three digit store number in M3.</inlineHelpText>
    <label>Store Number</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Additional notes about the contact 
Type:GBL 
Integrated: N</description>
    <inlineHelpText>Notes about this contact</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Truck_for_Store__c/Truck_for_Store__c.object-meta.xml
<CustomObject>
    <label>Truck for Store</label>
    <nameField>
        <displayFormat>TFS-{0000000}</displayFormat>
        <label>TFS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trucks for Store</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck_for_Store__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Trucks_for_Store</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Truck_Run__c/Truck_Run__c.object-meta.xml
<CustomObject>
    <description>Object used to schedule and maintain mobile truck appointments and results.</description>
    <label>Truck Run</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Truck Run</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truck Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck_Run__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The driver assigned to the truck run.</description>
    <inlineHelpText>Select the name of the driver assigned to the truck run.</inlineHelpText>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Truck Runs</relationshipLabel>
    <relationshipName>Truck_Runs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Truck_Run__c/fields/Forecast_Amount__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Amount__c</fullName>
    <description>Amount of revenue expected to be achieved on the truck run.</description>
    <inlineHelpText>Enter the amount of revenue you expect to achieve during the truck run.</inlineHelpText>
    <label>Forecast Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Truck_Run__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Used to capture any pre or post run notes or comments related to the truck run.</description>
    <inlineHelpText>Enter any notes or comments related to the truck run.</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Truck_Run__c/fields/Run_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Run_End_Time__c</fullName>
    <description>Used to capture the scheduled ending time of the truck run.</description>
    <inlineHelpText>Enter the ending time for the truck run.</inlineHelpText>
    <label>Run End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Truck_Run__c/fields/Run_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Run_Start_Time__c</fullName>
    <description>The time at which the truck run is scheduled to start.</description>
    <inlineHelpText>Enter the start time for the truck run.</inlineHelpText>
    <label>Run Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Truck_Run__c/fields/RWfB_Account__c.field-meta.xml
<CustomField>
    <fullName>RWfB_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identified the Red Wing for Business account where the truck run will be scheduled.</description>
    <inlineHelpText>Select the Red Wing for Business Account tied to the truck run.</inlineHelpText>
    <label>RWfB Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Partner Community</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Truck Runs</relationshipLabel>
    <relationshipName>Truck_Runs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Truck_Run__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The store that will be servicing the account on the truck run.</description>
    <inlineHelpText>Select the store associated with the truck run.</inlineHelpText>
    <label>Store</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>M3 Store Parent Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Truck Runs (Store)</relationshipLabel>
    <relationshipName>Truck_Runs_Store</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Truck_Run__c/fields/Truck_for_Run__c.field-meta.xml
<CustomField>
    <fullName>Truck_for_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The truck that will be servicing the account on the truck run.</description>
    <inlineHelpText>Select the truck assigned to the run.</inlineHelpText>
    <label>Truck for Run</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Truck_for_Store__c.Truck_Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Truck_for_Store__c</referenceTo>
    <relationshipLabel>Truck Runs</relationshipLabel>
    <relationshipName>Truck_Runs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TravelCalendars_Controller.cls
public class TravelCalendars_Controller {
    
    private final Account acct;
    public TravelCalendars_Controller(ApexPages.StandardController stdcontroller) {
     this.acct = (Account)stdController.getRecord();
     system.debug('Store Id in Cal Contr:' + this.acct);
     pageload();
    }
    
    public Boolean includeMyEvents {get;set;}
    public list<calEvent> events {get;set;}

    //The calendar plugin is expecting dates is a certain format. We can use this string to get it formated correctly
    String dtFormat = 'EEE, d MMM yyyy HH:mm:ss z';

    //constructor
   /* public TravelCalendars_Controller() {

        //Default showing my events to on
		system.debug('loading');
        includeMyEvents = true;

    }*/
    public PageReference pageLoad() {
        events = new list<calEvent>();
 		system.debug('Pageload');
        //Get My Travel

        for(Truck_Run__c mytruck : [select Id, Forecast_Amount__c , Notes__c, Run_Start_Time__c, Run_End_Time__c , Driver__r.Name, Rwfb_Account__r.Name,Truck_for_Run__r.Store__r.Store_Number__c from Truck_Run__c ])//where IsDeleted  = 'Approved' and OwnerID = :UserInfo.getUserId() ])
        {
            TimeZone tz = UserInfo.getTimeZone();
            if(mytruck.Run_Start_Time__c != null)
            {
            DateTime startDT = mytruck.Run_Start_Time__c.AddSeconds(tz.getOffset(mytruck.Run_Start_Time__c)/1000);
            DateTime endDT = mytruck.Run_End_Time__c.AddSeconds(tz.getOffset(mytruck.Run_End_Time__c)/1000);
            DateTime nowDT = DateTime.now().AddSeconds(tz.getOffset(DateTime.now())/1000);
            string DriName = mytruck.Driver__r.Name;
            string AcctName = mytruck.Rwfb_Account__r.Name;
			string StoreNumber = mytruck.Truck_for_Run__r.Store__r.Store_Number__c ;
            string notes = '';
            if (mytruck.Notes__c != null)
            {
                notes = '; Notes - ' + mytruck.Notes__c;
             } 
            calEvent mytravEvent = new calEvent();             
            mytravEvent.title = 'Trip: Account - '+ AcctName + '; Driver - ' + DriName + '; Store# - ' + StoreNumber + notes; //+ ' ' + myTrav.Owner.FirstName+ ' ' + myTrav.Owner.LastName;
            mytravEvent.allDay = false;
            mytravEvent.startString = startDT.format(dtFormat);
            mytravEvent.endString = endDT.format(dtFormat);
            mytravEvent.url = '/' + mytruck.Id;
            
            system.debug(startDt + '- ' + nowDT + '- ' +  endDT);
            if(startDt < nowDT && endDT < nowDT)
            {
            	mytravEvent.className = 'event-mytravel';
            }
            else if ((startDt == nowDT || startDt < nowDT) && endDT >= nowDT)
            {
                mytravEvent.className = 'event-sbtravel';
            }
            else if(startDt > nowDT)
            {
                mytravEvent.className = 'event-trtravel';
            }
            //mytravEvent.className.style = '.event-mytravel {background:#00447b;border-color:#00447b;}';
            events.add(mytravEvent);
            }
        }
         //Get School Bus Travel

 /*       for(Travel__c sbtrav : [select Id, Owner.FirstName, Owner.LastName, Name, Departure_Date__c, Return_Date__c, Owner_Territory__c from Travel__c where Approval_Status__c = 'Approved' and  Owner_Division__c = 'School Bus' and OwnerID != :UserInfo.getUserId() ]){

            DateTime startDT = sbTrav.Departure_Date__c;

            DateTime endDT = sbTrav.Return_Date__c;

            calEvent sbtravEvent = new calEvent();

            

            sbtravEvent.title = 'Trip:'+ ' ' + sbTrav.Name+ ' ' + sbTrav.Owner.FirstName+ ' ' + sbTrav.Owner.LastName;

            sbtravEvent.allDay = true;

            sbtravEvent.startString = startDT.format(dtFormat);

            sbtravEvent.endString = endDT.format(dtFormat);

            sbtravEvent.url = '/' + sbTrav.Id;

            sbtravEvent.className = 'event-sbtravel';

            events.add(sbtravEvent);

        }
 
         //Get Transit Travel

        for(Travel__c trtrav : [select Id, Owner.FirstName, Owner.LastName, Name, Departure_Date__c, Return_Date__c, Owner_Territory__c from Travel__c where Approval_Status__c = 'Approved' and  Owner_Division__c = 'Transit' and  OwnerID != :UserInfo.getUserId() ]){

            DateTime startDT = trTrav.Departure_Date__c;

            DateTime endDT = trTrav.Return_Date__c;

            calEvent trtravEvent = new calEvent();

            

            trtravEvent.title = 'Trip:'+ ' ' + trTrav.Name+ ' ' + trTrav.Owner.FirstName+ ' ' + trTrav.Owner.LastName;

            trtravEvent.allDay = true;

            trtravEvent.startString = startDT.format(dtFormat);

            trtravEvent.endString = endDT.format(dtFormat);

            trtravEvent.url = '/' + trTrav.Id;

            trtravEvent.className = 'event-trtravel';

            events.add(trtravEvent);

        }
        



//Get Other Travel

        for(Travel__c ottrav : [select Id, Owner.FirstName, Owner.LastName, Name, Departure_Date__c, Return_Date__c, Owner_Territory__c from Travel__c where Approval_Status__c = 'Approved' and  Owner_Division__c != 'School Bus' and  Owner_Division__c != 'Transit'and OwnerID != :UserInfo.getUserId() ]){

            DateTime startDT = otTrav.Departure_Date__c;

            DateTime endDT = otTrav.Return_Date__c;

            calEvent ottravEvent = new calEvent();

            

            ottravEvent.title = 'Trip:'+ ' ' + otTrav.Name+ ' ' + otTrav.Owner.FirstName+ ' ' + otTrav.Owner.LastName;

            ottravEvent.allDay = true;

            ottravEvent.startString = startDT.format(dtFormat);

            ottravEvent.endString = endDT.format(dtFormat);

            ottravEvent.url = '/' + otTrav.Id;

            ottravEvent.className = 'event-ottravel';

            events.add(ottravEvent);

        }

//Get my Events if we have selected the correct option

        if(includeMyEvents){

            for(Event evnt: [select Id, Subject, isAllDayEvent, StartDateTime, EndDateTime from Event where OwnerID = :UserInfo.getUserId()]){

                DateTime startDT = evnt.StartDateTime;

                DateTime endDT = evnt.EndDateTime;

                calEvent myEvent = new calEvent();

                

                myEvent.title = evnt.Subject;

                myEvent.allDay = evnt.isAllDayEvent;

                myEvent.startString = startDT.format(dtFormat);

                myEvent.endString = endDT.format(dtFormat);

                myEvent.url = '/' + evnt.Id;

                myEvent.className = 'event-personal';

                events.add(myEvent);

            }

        }*/

        return null;

    }

    public PageReference toggleMyEvents() {
        if(includeMyEvents){
            includeMyEvents = false;
        }
        else{
            includeMyEvents = true;
        }

        pageload();

        return null;

    }


    //Class to hold calendar event data

    public class calEvent{

        public String title {get;set;}

        public Boolean allDay {get;set;}

        public String startString {get;private set;}

        public String endString {get;private set;}

        public String url {get;set;}

        public String className {get;set;}
    }

}