force-app/main/default/objects/Account/fields/Billing_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Last_Name__c</fullName>
    <label>Billing Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingContactID__c.field-meta.xml
<CustomField>
    <fullName>BillingContactID__c</fullName>
    <label>BillingContactID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/HasBillingContact_BPC__c.field-meta.xml
<CustomField>
    <fullName>HasBillingContact_BPC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for Submit Credit Application data check. Not on Layout</description>
    <label>HasBillingContact_BPC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_Address_Line_1__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location Address Line 1</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_City__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_City__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_Country__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_State_Province__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_State_Province__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IA_Physical_Location_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>--Select--</fullName>
                <default>true</default>
                <label>--Select--</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Alabama</label>
            </value>
            <value>
                <fullName>AK</fullName>
                <label>Alaska</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Arizona</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Arkansas</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>California</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colorado</label>
            </value>
            <value>
                <fullName>CT</fullName>
                <label>Connecticut</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Delaware</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>Florida</label>
            </value>
            <value>
                <fullName>GA</fullName>
                <label>Georgia</label>
            </value>
            <value>
                <fullName>HI</fullName>
                <label>Hawaii</label>
            </value>
            <value>
                <fullName>ID</fullName>
                <label>Idaho</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>Illinois</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Indiana</label>
            </value>
            <value>
                <fullName>IA</fullName>
                <label>Iowa</label>
            </value>
            <value>
                <fullName>KS</fullName>
                <label>Kansas</label>
            </value>
            <value>
                <fullName>KY</fullName>
                <label>Kentucky</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <label>Louisiana</label>
            </value>
            <value>
                <fullName>ME</fullName>
                <label>Maine</label>
            </value>
            <value>
                <fullName>MD</fullName>
                <label>Maryland</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <label>Massachusetts</label>
            </value>
            <value>
                <fullName>MI</fullName>
                <label>Michigan</label>
            </value>
            <value>
                <fullName>MN</fullName>
                <label>Minnesota</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>Mississippi</label>
            </value>
            <value>
                <fullName>MO</fullName>
                <label>Missouri</label>
            </value>
            <value>
                <fullName>MT</fullName>
                <label>Montana</label>
            </value>
            <value>
                <fullName>NE</fullName>
                <label>Nebraska</label>
            </value>
            <value>
                <fullName>NV</fullName>
                <label>Nevada</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>New Hampshire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_ZIP_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_ZIP_Postal_Code__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location ZIP/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RWfB_Billing_Address_City__c.field-meta.xml
<CustomField>
    <fullName>RWfB_Billing_Address_City__c</fullName>
    <description>Identification of the RWfB Billing Address City for MSTS, Credit Application process for Community and &apos;Same as Physical Address&apos; logic.</description>
    <inlineHelpText>Identification of the RWfB Billing Address City for MSTS, Credit Application process</inlineHelpText>
    <label>RWfB Billing Address City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RWfB_same_as_Physical_Address__c.field-meta.xml
<CustomField>
    <fullName>RWfB_same_as_Physical_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify if the RWfB Address is the same (true) or different (false) than the IA Physical Location fields.</description>
    <inlineHelpText>Used to identify if the RWfB Address is the same (true) or different (false) than the IA Physical Location fields.</inlineHelpText>
    <label>RWfB same as Physical Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Address_same_as_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Address_same_as_Accounts__c</fullName>
    <description>Picklist to indicate if the contacts address is the same as the account in which they are associated with.  Values are Same as Account or Different
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Picklist to indicate if the contacts address is the same as the account in which they are associated with.  Values are Same as Account or Different</inlineHelpText>
    <label>Address same as Accounts</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Same as Physical</fullName>
            </value>
            <value>
                <fullName>Same as Billing</fullName>
            </value>
            <value>
                <fullName>Different</fullName>
            </value>
            <value>
                <fullName>Same as Account</fullName>
                <isActive>false</isActive>
                <label>Same as Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Contact_Identifier__c</fullName>
    <description>This field was requested by Jeff G to identify the primary contact.</description>
    <inlineHelpText>Please identify this contact as Primary or Billing.</inlineHelpText>
    <label>Contact Identifier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Primary &amp; Billing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Invoice Payment Portal Admin</label>
            </value>
            <value>
                <fullName>Truck Run</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_ContactTrigger_Test.cls
@isTest
private class RWS_ContactTrigger_Test {

    static testMethod void testPhysicalLocation() {

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, false);
        acc.IA_Physical_Location_City__c = 'MN';
        acc.IA_Physical_Location_Country__c = 'US';
        acc.IA_Physical_Location_State_Province__c = 'MN';
        acc.IA_Physical_Location_Address_Line_1__c = '24-A';
        acc.IA_Physical_Location_ZIP_Postal_Code__c = '55213';
        acc.RWfB_same_as_Physical_Address__c = true;
        
        Test.startTest();
        insert acc;
        Test.stopTest();

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        con1.Address_same_as_Accounts__c = 'Same as Physical';
        con1.Phone = '111-222-3333';
        insert con1;

        System.assert([select MailingCity from Contact where Id = :con1.Id].MailingCity == acc.IA_Physical_Location_City__c);

    }

    static testMethod void testBillingLocation() {

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, false);
        acc.IA_Physical_Location_City__c = 'MN';
        acc.IA_Physical_Location_Country__c = 'US';
        acc.IA_Physical_Location_State_Province__c = 'MN';
        acc.IA_Physical_Location_Address_Line_1__c = '24-A';
        acc.IA_Physical_Location_ZIP_Postal_Code__c = '55213';
        acc.RWfB_same_as_Physical_Address__c = false;
        acc.RWfB_Billing_Address_City__c = 'ISB';

        Test.startTest();
        insert acc;
		Test.stopTest();
        
        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        con1.Address_same_as_Accounts__c = 'Same as Billing';
        con1.Phone = '111-222-3333';
        insert con1;

        System.assert([select MailingCity from Contact where Id = :con1.Id].MailingCity == acc.RWfB_Billing_Address_City__c);

    }

    static testMethod void testBPCUpdate() {

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Test.startTest();
        Account acc = RWS_TestUtil.createAccount(rtId, true);
        
        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        con1.Contact_Identifier__c = 'Billing';
        con1.FirstName = 'Bill';
        con1.LastName = 'Test';
        con1.Email = 'bill@test.com';
        con1.MailingCity = 'MN';
        con1.MailingCountry = 'US';
        con1.MailingState = 'MN';
        con1.MailingStreet = '24-A';
        con1.MailingPostalCode = '55213';
        con1.Phone = '111-222-3333';
        insert con1;
        Test.stopTest();

        System.assert([select HasBillingContact_BPC__c from Account where Id = :acc.Id].HasBillingContact_BPC__c);
        System.assertEquals([select BillingContactID__c from Account where Id = :acc.Id].BillingContactID__c, con1.Id);

        con1.Contact_Identifier__c = 'Primary';
        update con1;

        System.assert(![select HasBillingContact_BPC__c from Account where Id = :acc.Id].HasBillingContact_BPC__c);
    }

    static testMethod void testCopyData() {

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Test.startTest();
        Account acc = RWS_TestUtil.createAccount(rtId, true);
		Test.stopTest();
        
        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        con1.Contact_Identifier__c = 'Billing';
        con1.FirstName = 'Bill';
        con1.LastName = 'Test';
        con1.Email = 'bill@test.com';
        con1.MailingCity = 'MN';
        con1.MailingCountry = 'US';
        con1.MailingState = 'MN';
        con1.MailingStreet = '24-A';
        con1.MailingPostalCode = '55213';
        con1.Phone = '111-222-3333';
        insert con1;

        System.assert([select Billing_Contact_Last_Name__c from Account where Id = :acc.Id].Billing_Contact_Last_Name__c == con1.LastName);

        delete con1;
    }


    static testMethod void testPublishTrigger() {
        Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        Contact con2 = RWS_TestUtil.createContact(acc.Id, 1, false);
        con1.Phone = '111-222-3333';
        con2.Phone = '222-222-3333';

        List<Contact> contacts = new List<Contact>{con2, con1};

        insert contacts;

        Id roleId = [select Id from UserRole where Name = 'System Administrators' limit 1].Id;

        User u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, false);
        User u2 = RWS_TestUtil.createCommunityUser(con2.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {

            User user = new User(Id = UserInfo.getUserId(), UserRoleId = roleId);
            update user;

            List<User> users = new List<User>{u2, u1};  
            insert users;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u1.UserRoleId = partnerRoleId;
            u2.UserRoleId = partnerRoleId;

            update users;
        }

        Test.startTest();

        System.runAs(u1) {
            Contact con3 = RWS_TestUtil.createContact(acc.Id, 2, false);
            Contact con4 = RWS_TestUtil.createContact(acc.Id, 3, false);

            List<Contact> otherContacts = new List<Contact>{con3, con4};

            insert otherContacts;
        }

        Test.stopTest();
    }

    static testMethod void testUserUpdate() {
        Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        Contact con2 = RWS_TestUtil.createContact(acc.Id, 1, false);
		con1.Phone = '111-222-3333';
        con2.Phone = '222-222-3333';
        
        List<Contact> contacts = new List<Contact>{con2, con1};


        insert contacts;

        User u1;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, true);
            User u2 = RWS_TestUtil.createCommunityUser(con2.Id, profileId, true);
        }

        Test.startTest();
        System.runAs(u1) {
            con1.Contact_Identifier__c = null;
            con1.FirstName = 'UserUpdate';

            update con1;
        }
        Test.stopTest();

    }
}