force-app/main/default/objects/Account/fields/Brands__c.field-meta.xml
<CustomField>
    <fullName>Brands__c</fullName>
    <label>Brands</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Brand Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Sales Rep</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>BrandEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <inlineHelpText>Identify the brand(s) involved in this Case</inlineHelpText>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carhartt</fullName>
            </value>
            <value>
                <fullName>Irish Setter Brands (Work &amp; Hunt)</fullName>
            </value>
            <value>
                <fullName>Irish Setter Hunt</fullName>
            </value>
            <value>
                <fullName>Irish Setter Work</fullName>
            </value>
            <value>
                <fullName>Red Wing</fullName>
            </value>
            <value>
                <fullName>Red Wing Brand</fullName>
            </value>
            <value>
                <fullName>Red Wing Brand - Other</fullName>
            </value>
            <value>
                <fullName>Red Wing Garments</fullName>
            </value>
            <value>
                <fullName>Red Wing Heritage</fullName>
            </value>
            <value>
                <fullName>Vasque</fullName>
            </value>
            <value>
                <fullName>WORX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrandCopyToAccount.cls
global class BrandCopyToAccount /*implements ITriggers.HandlerInterface*/ {

    public BrandCopyToAccount(){
    //Do Nothing
    }
/* 2020-07-10 Chris Mollet Commented out - DC Case 8433
    List<Brand__c> newCollection = trigger.new;
    Map<Id, Brand__c> oldCollection = (Map<Id, Brand__c>)trigger.oldMap;
    Boolean isInsert = trigger.isInsert;
    Boolean isUpdate = trigger.isUpdate;
    Boolean isDelete = trigger.isDelete;
    
    global void handle() {
        copyBrandsToAccount(getAccountIds());
    }
    
    private Set<Id> getAccountIds() {
        Set<Id> accountIds = new Set<Id>();
        if(isInsert || isUpdate) {
            for(Brand__c b : newCollection) {
                if(isInsert || b.Brand__c != oldCollection.get(b.Id).Brand__c) accountIds.add(b.Account__c);
            }
        }
        if(isDelete) {
            for(Brand__c b : oldCollection.values()) {
                accountIds.add(b.Account__c);
            }
        }
        return accountIds;
    }
    
    private void copyBrandsToAccount(Set<Id> accountIds) {
        String brand = '';
        Map<Id, Account> accountsToUpdate = new Map<Id, Account>();
        if(!accountIds.isEmpty()) { 
            for(Account a : [select Id, Brands__c, (select Brand__c from BrandEntries__r) from Account where Id in :accountIds])
            {
                a.Brands__c = '';
                for (Brand__c b : a.BrandEntries__r)
                {
                    a.Brands__c += b.Brand__c + ';';
                }
                if(a.Brands__c.length() > 0) a.Brands__c = a.Brands__c.substring(0,a.Brands__c.length()-1);
                    accountsToUpdate.put(a.Id, a);
            }       
            if(!accountsToUpdate.isEmpty() && accountsToUpdate.size() > 0) {
                update accountsToUpdate.values();
            }
        }
    }*/
}