force-app/main/default/objects/Account/fields/Brands__c.field-meta.xml
<CustomField>
    <fullName>Brands__c</fullName>
    <label>Brands</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Brand Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Sales Rep</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BrandCopyToAccountTest.cls
@isTest
private class BrandCopyToAccountTest {

    static testMethod void myContoller(){
       BrandCopyToAccount comment = new BrandCopyToAccount();
   }
    
/*    static User testUser;
    static Account testAccount;
    static Brand__c testBrand;
    
    static void initialize() {
        testUser = ECTestDataFactory.createTestUser();
        insert testUser;
        system.assertNotEquals(null, testUser.Id);
        
        testAccount = ECTestDataFactory.createAccount('Acme', true);    
        system.assertNotEquals(null, testAccount.Id);   
        
        testBrand = ECTestDataFactory.createBrand(testAccount.Id, testUser.Id, false);
    }   
    
    static testMethod void testCopyBrandToAccount() {
        initialize();
        
        testBrand.Brand__c = 'WROX';
        
        test.startTest();
            insert testBrand;
        test.stopTest();
    
        Account result = [select Brands__c from Account where Id =: testAccount.Id];
        system.assertEquals(testBrand.Brand__c, result.Brands__c);  
    }
    
    static testMethod void testCopyBrandToAccountOnDelete() {
        initialize();
        
        testBrand.Brand__c = 'WROX';
        insert testBrand;
        
        system.assertNotEquals(null, testBrand.Id);
        
        test.startTest();
            delete testBrand;
        test.stopTest();
    
        Account result = [select Brands__c from Account where Id =: testAccount.Id];
        system.assertEquals(null, result.Brands__c);    
    }*/
    
}