force-app/main/default/objects/Account/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <description>The date that that the store officially closed.
Field Type: Store Data
Integrated: N</description>
    <inlineHelpText>The date that the store was closed.

Responsible Owner: Store Operations</inlineHelpText>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status_Description__c</fullName>
    <description>What status is this account in, active or inactive?
Field Type: M3
Integrated: Y - M3&gt;SF&gt;&quot;Xstore Pricing Portal</description>
    <inlineHelpText>M3 status of this account; active or inactive.

Responsible Owner: M3 Integration</inlineHelpText>
    <label>Account Status Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <color>#419249</color>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#FF0000</color>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <color>#3333FF</color>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the related Dealer. 
Field Type: Store Data
Integrated: N</description>
    <inlineHelpText>This is a lookup to the related Dealer.

Responsible Owner: Dealer Operations and Store Operations</inlineHelpText>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <description>This holds the account open date.
Field Type: GLBL
Integrated: N</description>
    <inlineHelpText>This is the date the Account was opened. This could be a retail store or an industrial account.

Responsible for maintenance on Stores: Store Operations 
Responsible for maintenance on Industrial Accounts: Account Owner</inlineHelpText>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Store_Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Store_Ownership_Type__c</fullName>
    <description>Type of store; Dealership, Company Owned, or Branded
Field Type: Store Data - Automatically populated based on M3 Customer Group
Integrated: Y - SF&gt;Xstore pricing portal</description>
    <inlineHelpText>Please select the type of store - used in reporting &amp; list views to separate Company Owned, Dealer, and Branded stores.

Responsible Owner: M3</inlineHelpText>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Branded</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <description>Referenced by Stores.</description>
    <label>Dealer</label>
    <nameField>
        <label>Dealership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Scorecard__c/Dealer_Scorecard__c.object-meta.xml
<CustomObject>
    <label>Dealer Scorecard</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Dealer Scorecard</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Scorecard__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Store_Ownership_Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>90</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Scorecards</relationshipLabel>
    <relationshipName>Dealer_Scorecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Dealer_Scorecard__c/fields/Scorecard_Type__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Type__c</fullName>
    <description>Indicates the type of scorecard being completed.</description>
    <inlineHelpText>Select the appropriate type of scorecard.</inlineHelpText>
    <label>Scorecard Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Review</fullName>
            </value>
            <value>
                <fullName>Store Build-out</fullName>
            </value>
            <value>
                <fullName>Store Remodel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Daily_DealerScorecardCreation.cls
global class Daily_DealerScorecardCreation implements Schedulable 
{
   global void execute(SchedulableContext SC) 
   {
       Date today = System.Today();
       integer month = today.month();
       integer day = today.day();
       integer year = today.year();
       Id recordTypeId = [SELECT Id FROM RecordType Where Name = 'M3 Store Parent Account' LIMIT 1].Id;
       List<String> roles = new List<String>{'Regional Retail Director', 'Sales Rep', 'Industrial Sales Manager', 'Retail Operations Manager'};//, 'Credit Analyst'};
       List<Dealer_Scorecard__c> scorecards = new List<Dealer_Scorecard__c>();
       RecordType taskRecordType = [SELECT Id FROM RecordType WHERE Name = 'Sales ROM\'s and TSM\'s' LIMIT 1];
       Map<Id, List<Task>> accountTasks = new Map<Id, List<Task>>();
       User marketingUser = [SELECT Id FROM User WHERE email like 'michael.rudquist%' AND Firstname = 'Michael' AND Lastname = 'Rudquist' LIMIT 1];
       
       for(Account a : [SELECT Id, 
                        	   Name, 
                               (SELECT UserId, TeamMemberRole FROM AccountTeamMembers WHERE IsDeleted = false AND TeamMemberRole IN :roles)
                        FROM Account
                        WHERE Customer_Status_Description__c = 'Active'
                        AND Close_Date__c = null
                        AND RecordType.Id = :recordTypeId
                        AND Store_Ownership_Type__c = 'Dealer'
                        AND CALENDAR_YEAR(Open_Date__c) < :year
                        AND CALENDAR_MONTH(Open_Date__c) = :month 
                        AND DAY_IN_MONTH(Open_Date__c) = :day])
       {
           //Create Dealer scorecards and Tasks for any Accounts that match the criteria
           Dealer_Scorecard__c scorecard = new Dealer_Scorecard__c(
               Dealer__c = a.Id,
               Scorecard_Type__c = 'Annual Review'
           );
           scorecards.add(scorecard);
           Date dueDate = System.today().addDays(5);
           
           //Create tasks for each team member
           List<Task> tasks = new List<Task>();
           for(AccountTeamMember atm : a.AccountTeamMembers)
           {
               Task t = new Task(
                   OwnerId = atm.UserId,
                   RecordTypeId = taskRecordType.Id,
                   Type = 'Dealer Review',
                   Priority = 'Normal',
                   ActivityDate = dueDate,
                   Subject = 'An annual Dealer Scorecard is ready for you to complete',
                   Description = 'Please complete your evaluation of dealer ' + a.Name + '.'
               );
               tasks.add(t);
           }
           
           //Add marketing task
           if(string.isNotEmpty(marketingUser.Id))
           {
               Task marketingTask = new Task(
                       OwnerId = marketingUser.Id,
                       RecordType = taskRecordType,
                       Type = 'Dealer Review',
                       Priority = 'Normal',
                       ActivityDate = dueDate,
                       Subject = 'An annual Dealer Scorecard is ready for you to complete',
                       Description = 'Please complete your evaluation of dealer ' + a.Name + '.'
               );
               tasks.add(marketingTask);
           }
           
           accountTasks.put(a.Id, tasks);
       }
       
       Database.Insert(scorecards, false);
       
       //Loop through scorecards and add their id to the tasks
       List<Task> tasksToInsert = new List<Task>();
       for(Dealer_Scorecard__c s : scorecards)
       {
           List<Task> tasks = accountTasks.get(s.Dealer__c);
           for(Task t : tasks)
           {
               t.whatId = s.Id;
               tasksToInsert.add(t);
           }
       }
       
       //Insert tasks
       Database.DMLOptions dmlOptions = new Database.DMLOptions(); 
	   dmlOptions.EmailHeader.TriggerUserEmail = TRUE; 
	   Database.Insert(tasksToInsert, dmlOptions);
	}
}