force-app/main/default/objects/Account/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <description>The date that that the store officially closed.
Field Type: Store Data
Integrated: N</description>
    <inlineHelpText>The date that the store was closed.

Responsible Owner: Store Operations</inlineHelpText>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status_Description__c</fullName>
    <description>What status is this account in, active or inactive?
Field Type: M3
Integrated: Y - M3&gt;SF&gt;&quot;Xstore Pricing Portal</description>
    <inlineHelpText>M3 status of this account; active or inactive.

Responsible Owner: M3 Integration</inlineHelpText>
    <label>Account Status Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <color>#419249</color>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#FF0000</color>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <color>#3333FF</color>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the related Dealer. 
Field Type: Store Data
Integrated: N</description>
    <inlineHelpText>This is a lookup to the related Dealer.

Responsible Owner: Dealer Operations and Store Operations</inlineHelpText>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <description>This holds the account open date.
Field Type: GLBL
Integrated: N</description>
    <inlineHelpText>This is the date the Account was opened. This could be a retail store or an industrial account.

Responsible for maintenance on Stores: Store Operations 
Responsible for maintenance on Industrial Accounts: Account Owner</inlineHelpText>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Store_Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Store_Ownership_Type__c</fullName>
    <description>Type of store; Dealership, Company Owned, or Branded
Field Type: Store Data - Automatically populated based on M3 Customer Group
Integrated: Y - SF&gt;Xstore pricing portal</description>
    <inlineHelpText>Please select the type of store - used in reporting &amp; list views to separate Company Owned, Dealer, and Branded stores.

Responsible Owner: M3</inlineHelpText>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Branded</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <description>Referenced by Stores.</description>
    <label>Dealer</label>
    <nameField>
        <label>Dealership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Scorecard__c/Dealer_Scorecard__c.object-meta.xml
<CustomObject>
    <label>Dealer Scorecard</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Dealer Scorecard</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Scorecard__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Store_Ownership_Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>90</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Scorecards</relationshipLabel>
    <relationshipName>Dealer_Scorecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Dealer_Scorecard__c/fields/Scorecard_Type__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Type__c</fullName>
    <description>Indicates the type of scorecard being completed.</description>
    <inlineHelpText>Select the appropriate type of scorecard.</inlineHelpText>
    <label>Scorecard Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Review</fullName>
            </value>
            <value>
                <fullName>Store Build-out</fullName>
            </value>
            <value>
                <fullName>Store Remodel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Daily_DealerScorecardCreation_Tests.cls
@isTest
private class Daily_DealerScorecardCreation_Tests {
    
	static List<Account> SetupAccounts(Id recordTypeId) {
        List<Account> accounts = new List<Account>();
        // insert 2 accounts
        for (Integer i=0;i<2;i++) {
            accounts.add(new Account(name='Account'+i, 
                                     Customer_Status_Description__c = 'Active',
                                     Close_Date__c = null,
                                     RecordTypeId = recordTypeId,
                                     Store_Ownership_Type__c = 'Dealer',
            						 Open_Date__c = Date.today().addYears(-1)));
        }
        // insert accounts that will be unaffected by batch job
        accounts.add(new Account(name='Account3', 
                                     Customer_Status_Description__c = 'Active',
                                     Close_Date__c = null,
                                     RecordTypeId = recordTypeId,
                                     Store_Ownership_Type__c = 'Dealer',
            						 Open_Date__c = Date.today().addDays(-1)));
        accounts.add(new Account(name='Account4', 
                                     Customer_Status_Description__c = 'Inactive',
                                     Close_Date__c = null,
                                     RecordTypeId = recordTypeId,
                                     Store_Ownership_Type__c = 'Dealer',
            						 Open_Date__c = Date.today().addYears(-1)));
        accounts.add(new Account(name='Account5', 
                                     Customer_Status_Description__c = 'Active',
                                     Close_Date__c = Date.today(),
                                     RecordTypeId = recordTypeId,
                                     Store_Ownership_Type__c = 'Dealer',
            						 Open_Date__c = Date.today().addYears(-1)));
        accounts.add(new Account(name='Account6', 
                                     Customer_Status_Description__c = 'Active',
                                     Close_Date__c = null,
                                     RecordTypeId = recordTypeId,
                                     Store_Ownership_Type__c = 'Dealer',
            						 Open_Date__c = Date.today().addYears(1)));
        insert accounts;
        return accounts;
    }
        
    static List<User> SetupUsers(List<Account> accounts, List<string> roles) {
        // create the Users
        List<User> userList = new List<User>();
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        
        for (Integer i = 0; i < roles.size(); i++) {
            // observe the same name for Opp and TSG
            userList.add(
                new User(
                    FirstName = roles[i], 
                    LastName = 'Test',
                    Alias = 'Test',
                    TimeZoneSidKey = 'GMT',
            		EmailEncodingKey = 'UTF-8',
                    ProfileId = p.Id,
            		LocaleSidKey = 'eu_ES',
                    LanguageLocaleKey = 'en_US',
                    Username='test' + i + Datetime.now().getTime() + '@blah.com',
                    Email='test'+ i + '@blah.com'
                )
            );
        }
        
        // insert marketing user
        userList.add(
            new User(
                FirstName='Michael',
                LastName='Rudquist',
                Alias = 'Test',
                TimeZoneSidKey = 'GMT',
                EmailEncodingKey = 'UTF-8',
                ProfileId = p.Id,
                LocaleSidKey = 'eu_ES',
                LanguageLocaleKey = 'en_US',
                Email='michael.rudquist@redwingshoes.com.test',
                Username='michael.rudquisttest' + Datetime.now().getTime() + '@redwingshoes.com.test'
            )
        );
        insert userList;
        return userList;
    }
    
    static List<AccountTeamMember> SetupAccountTeamMembers(List<Account> accounts, List<User> userList, List<string> roles) {
        //Create the AccountTeam
        List<AccountTeamMember> teamList = new List<AccountTeamMember>();
        for (Integer i = 0; i < roles.size(); i++) {
            for(Integer j = 0; j < accounts.size(); j++)
            {
                AccountTeamMember member = new AccountTeamMember(AccountId = accounts[j].Id, TeamMemberRole = roles[i], UserId = userList[i].ID);
        		teamList.add(member);
            }
        }
        insert teamList;
        return teamList;
    }
    
    static testmethod void test() {        
        Test.startTest();
        List<String> roles = new List<String>{'Regional Retail Director', 'Sales Rep', 'Industrial Sales Manager', 'Retail Operations Manager', 'Blah'};
        Id recordTypeId = [SELECT Id FROM RecordType Where Name = 'M3 Store Parent Account' LIMIT 1].Id;
        List<Account> accounts = SetupAccounts(recordTypeId);
        List<User> users = SetupUsers(accounts, roles);
        List<AccountTeamMember> atms = SetupAccountTeamMembers(accounts, users, roles);
        Daily_DealerScorecardCreation ddsc = new Daily_DealerScorecardCreation();      
        String sch = '0 0 0 1 1 ? 2050';
        System.schedule('Test check', sch, ddsc);
        Test.stopTest();
        
        // after the testing stops, assert records were updated properly
        List<Dealer_Scorecard__c> scorecards = [SELECT Id, Scorecard_Type__c From Dealer_Scorecard__c WHERE Dealer__c in :accounts];
        System.assertEquals(2, scorecards.size());
        for(Dealer_Scorecard__c scorecard : scorecards)
        {
            System.assertEquals('Annual Review', scorecard.Scorecard_Type__c);
        }
        Id taskRecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Sales ROM\'s and TSM\'s' LIMIT 1].Id;
        List<Task> tasks = [SELECT Id, RecordTypeId, Type, Priority, ActivityDate, Subject, Description FROM Task WHERE WhatId in :scorecards];
        System.assertEquals(10, tasks.size());
        Date dueDate = Date.today().AddDays(5);
        for(Task t : tasks)
        {
            System.assertEquals(taskRecordTypeId, t.RecordTypeId);
            System.assertEquals('Dealer Review', t.Type);
            System.assertEquals('Normal', t.Priority);
            System.assertEquals(dueDate, t.ActivityDate);
            System.assertEquals('An annual Dealer Scorecard is ready for you to complete', t.Subject);
        }
    }
}