force-app/main/default/objects/Account/fields/Data_com_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Data_com_Latitude__c</fullName>
    <description>Latitude retrieved from free Data.com Geocoding functionality</description>
    <inlineHelpText>Latitude retrieved from free Data.com Geocoding feature</inlineHelpText>
    <label>Data.com Latitude</label>
    <precision>10</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Data_com_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Data_com_Longitude__c</fullName>
    <description>Latitude retrieved from free Data.com Geocoding functionality</description>
    <inlineHelpText>Latitude retrieved from free Data.com Geocoding feature</inlineHelpText>
    <label>Data.com Longitude</label>
    <precision>10</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>This is the latitude values based off physical location. 
Field Type: GBL
Integrated: Y - SF&gt;Shoe Search</description>
    <inlineHelpText>This is the latitude values based off physical location.

Responsible Owner: M3 Integration</inlineHelpText>
    <label>Latitude</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>This is the longitude value base off the physical location.
Field Type: Store Data
Integrated: Y - SF&gt;Xstore</description>
    <inlineHelpText>This is the longitude value base off the physical location.

Responsible Owner: M3 Integration</inlineHelpText>
    <label>Longitude</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_City__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_City__c</fullName>
    <description>M3 Physical Location Address - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: Y</description>
    <label>Physical Location City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_Country__c</fullName>
    <description>M3 Physical Location Country - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: Y</description>
    <label>Physical Location Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_State_Province__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_State_Province__c</fullName>
    <description>M3 Location State or Province - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: Y</description>
    <label>Physical Location State/Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_Street__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_Street__c</fullName>
    <description>M3 Location Street - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: Y</description>
    <label>Physical Location Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_ZIP_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_ZIP_Postal_Code__c</fullName>
    <description>M3 Location Postal Code - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: N</description>
    <label>Physical Location ZIP/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APEX_Trigger_Settings__c/APEX_Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS consists of a list of triggers and true/false settings to enable/disable functionality without having to disable triggers or edit code.</description>
    <label>APEX Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/APEX_Trigger_Settings__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked - the code is enabled and will run.
Unchecked - the code will be DISABLED and will not run.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/M3_Account_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>M3_Account_Ext_Id__c</fullName>
    <description>Used explicitly for the M3 Mock Contact Geocoding Trigger(s)</description>
    <externalId>true</externalId>
    <inlineHelpText>Used explicity for the M3 Mock Contact Geocoding Trigger(s)</inlineHelpText>
    <label>M3 Account Ext Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/M3_Contact.recordType-meta.xml
<RecordType>
    <fullName>M3_Contact</fullName>
    <active>true</active>
    <description>For Contacts integrated with M3; most fields are read/only</description>
    <label>M3 Contact</label>
</RecordType>

force-app/main/default/classes/Test_TriggerControllerAccount.cls
@isTest
private class Test_TriggerControllerAccount {
/*
  static testmethod void testAutoGeocodingWithInsert() {
    List<APEX_Trigger_Settings__c> settings = new List<Apex_Trigger_Settings__c>{
      new Apex_Trigger_Settings__c(Name='geoLocationAccount',IsActive__c=true)
      ,new Apex_Trigger_Settings__c(Name='geoLocationContact',IsActive__c=true)
    };
    insert settings;


    Test.startTest();
    Account a = new Account(
      Name='Test'
      ,M3_Location_City__c = 'Red Wing'
      ,M3_Location_Street__c = '314 MAIN ST'
      ,M3_Location_State_Province__c = 'MN'
      ,M3_Location_Zip_Postal_Code__c = '55066'
      ,M3_Location_Country__c = 'US');
    insert a;
    Test.stopTest();

    //Data.com isn't working with unit tests. Instead, the contact test below will mock the lat and long geocoding up to the account.
    //Account result = [Select Longitude__c,Latitude__c From Account];
    //System.assertNotEquals(null,result.Longitude__c);
    //System.assertNotEquals(null,result.Latitude__c);
  }

  static testmethod void testAutoGeocodingWithUpdate() {
    List<APEX_Trigger_Settings__c> settings = new List<Apex_Trigger_Settings__c>{
      new Apex_Trigger_Settings__c(Name='geoLocationAccount',IsActive__c=true)
      ,new Apex_Trigger_Settings__c(Name='geoLocationContact',IsActive__c=true)
    };
    insert settings;

    Account a = new Account(
      Name='Test'
    );
    insert a;

    Test.startTest();
    a.M3_Location_City__c = 'Red Wing';
    a.M3_Location_Street__c = '314 MAIN ST';
    a.M3_Location_State_Province__c = 'MN';
    a.M3_Location_Zip_Postal_Code__c = '55066';
    a.M3_Location_Country__c = 'US';
    update a;
    Test.stopTest();

    //Data.com isn't working with unit tests. Instead, the contact test below will mock the lat and long geocoding up to the account.
    //Account result = [Select Longitude__c,Latitude__c From Account];
    //System.assertNotEquals(null,result.Longitude__c);
    //System.assertNotEquals(null,result.Latitude__c);
  }

  static testmethod void testAutoGeocodingContactWithUpdate() {
    List<APEX_Trigger_Settings__c> settings = new List<Apex_Trigger_Settings__c>{
      new Apex_Trigger_Settings__c(Name='geoLocationAccount',IsActive__c=true)
      ,new Apex_Trigger_Settings__c(Name='geoLocationContact',IsActive__c=true)
    };
    insert settings;

    RecordType rt = [Select Id From RecordType Where DeveloperName = 'M3_Contact'];

    Account a = new Account(
      Name='Test'
      ,M3_Location_City__c = 'Red Wing'
      ,M3_Location_Street__c = '314 MAIN ST'
      ,M3_Location_State_Province__c = 'MN'
      ,M3_Location_Zip_Postal_Code__c = '55066'
      ,M3_Location_Country__c = 'US'
    );
    insert a;

    Contact c = new Contact(
      AccountId = a.Id
            ,M3_Account_Ext_Id__c = a.Id
            ,Firstname='M3'
            ,Lastname='Address'
            ,MailingStreet = a.M3_Location_Street__c
            ,MailingCity = a.M3_Location_City__c
            ,MailingState = a.M3_Location_State_Province__c
            ,MailingCountry = a.M3_Location_Country__c
            ,MailingPostalCode = a.M3_Location_ZIP_Postal_Code__c
            ,RecordTypeId = rt.Id
        );
        insert c;

    Test.startTest();
    c.MailingLatitude = 44.566353;
        c.MailingLongitude = -92.534672;
        update c;
    Test.stopTest();

    Account result = [Select Data_com_Longitude__c,Data_com_Latitude__c From Account];
    System.assertEquals(-92.534672,result.Data_com_Longitude__c);
    System.assertEquals(44.566353,result.Data_com_Latitude__c);
  }

  static testmethod void testAutoGeocodingContactInsert() {
    List<APEX_Trigger_Settings__c> settings = new List<Apex_Trigger_Settings__c>{
      new Apex_Trigger_Settings__c(Name='geoLocationAccount',IsActive__c=true)
      ,new Apex_Trigger_Settings__c(Name='geoLocationContact',IsActive__c=true)
    };
    insert settings;

    RecordType rt = [Select Id From RecordType Where DeveloperName = 'M3_Contact'];

    Account a = new Account(
      Name='Test'
      ,M3_Location_City__c = 'Red Wing'
      ,M3_Location_Street__c = '314 MAIN ST'
      ,M3_Location_State_Province__c = 'MN'
      ,M3_Location_Zip_Postal_Code__c = '55066'
      ,M3_Location_Country__c = 'US'
    );
    insert a;

    Test.startTest();
    Contact c = new Contact(
      AccountId = a.Id
            ,M3_Account_Ext_Id__c = a.Id
            ,Firstname='M3'
            ,Lastname='Address'
            ,MailingStreet = a.M3_Location_Street__c
            ,MailingCity = a.M3_Location_City__c
            ,MailingState = a.M3_Location_State_Province__c
            ,MailingCountry = a.M3_Location_Country__c
            ,MailingPostalCode = a.M3_Location_ZIP_Postal_Code__c
            ,RecordTypeId = rt.Id
            ,MailingLatitude = 44.566353
          ,MailingLongitude = -92.534672
        );
        insert c;
    Test.stopTest();

    Account result = [Select Data_com_Longitude__c,Data_com_Latitude__c From Account];
    System.assertEquals(-92.534672,result.Data_com_Longitude__c);
    System.assertEquals(44.566353,result.Data_com_Latitude__c);
    System.assertEquals(0,[Select Id From Contact].size());
  }

*/}