force-app/main/default/objects/Account/fields/Days_Since_Last_Truck_Run__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Last_Truck_Run__c</fullName>
    <formula>If(Today()&gt;Last_Truck_Run__c, Today()-Last_Truck_Run__c, Null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Truck Run</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Service_Method__c.field-meta.xml
<CustomField>
    <fullName>IA_Service_Method__c</fullName>
    <description>The service method selected in IA. 
Type: IA
Integrated: Y</description>
    <inlineHelpText>The service method selected in IA. Sent to Salesforce by IA.</inlineHelpText>
    <label>IA Service Method</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>MicroSite</fullName>
            </value>
            <value>
                <fullName>DTI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Truck_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Truck_Run__c</fullName>
    <description>Date last truck run occurred.  Populated by a trigger.</description>
    <inlineHelpText>Date last truck run occurred.</inlineHelpText>
    <label>Last Truck Run</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>This is the latitude values based off physical location. 
Field Type: GBL
Integrated: Y - SF&gt;Shoe Search</description>
    <inlineHelpText>This is the latitude values based off physical location.

Responsible Owner: M3 Integration</inlineHelpText>
    <label>Latitude</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>This is the longitude value base off the physical location.
Field Type: Store Data
Integrated: Y - SF&gt;Xstore</description>
    <inlineHelpText>This is the longitude value base off the physical location.

Responsible Owner: M3 Integration</inlineHelpText>
    <label>Longitude</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Store_Number__c.field-meta.xml
<CustomField>
    <fullName>Store_Number__c</fullName>
    <description>This is the three digit store number in M3.
Field Type: M3
Integrated: Y -  M3&gt;SF&gt;Xstore pricing portal</description>
    <inlineHelpText>This is the three digit store number in M3.</inlineHelpText>
    <label>Store Number</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Truck_Qty__c.field-meta.xml
<CustomField>
    <fullName>Truck_Qty__c</fullName>
    <description>The total number of trucks for the store.
Field Type: Store Data
Integrated: N</description>
    <inlineHelpText>This field show the total number of trucks for the store.

Responsible Owner: Dealer Operations and Store Operations</inlineHelpText>
    <label>Truck Qty</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Truck__c/Truck__c.object-meta.xml
<CustomObject>
    <label>Truck</label>
    <nameField>
        <label>Mobile Customer Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trucks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck__c/fields/Truck_Description__c.field-meta.xml
<CustomField>
    <fullName>Truck_Description__c</fullName>
    <description>Description of Truck
Field Type: Store Data
Integrated: N</description>
    <inlineHelpText>Description of Truck</inlineHelpText>
    <label>Truck Description</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Truck_for_Store__c/Truck_for_Store__c.object-meta.xml
<CustomObject>
    <label>Truck for Store</label>
    <nameField>
        <displayFormat>TFS-{0000000}</displayFormat>
        <label>TFS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trucks for Store</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck_for_Store__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Trucks_for_Store</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Truck_for_Store__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <label>Truck</label>
    <referenceTo>Truck__c</referenceTo>
    <relationshipLabel>Stores for Trucks</relationshipLabel>
    <relationshipName>Stores_for_Trucks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Truck_for_Store__c/fields/Truck_Description__c.field-meta.xml
<CustomField>
    <fullName>Truck_Description__c</fullName>
    <formula>Truck__r.Truck_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Truck Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Truck_for_Store__c/fields/Truck_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Truck_Is_Active__c</fullName>
    <formula>Truck__r.IsActive__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Truck Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Truck_for_Store__c/fields/Truck_Unit_Nbr__c.field-meta.xml
<CustomField>
    <fullName>Truck_Unit_Nbr__c</fullName>
    <description>Truck Unit Number needed for lookups</description>
    <formula>Truck__r.Unit_Number__c</formula>
    <inlineHelpText>Truck Unit Number</inlineHelpText>
    <label>Truck Unit Nbr</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TruckController.cls
public with sharing class TruckController
{
    private List<Account> AccountTemp;
	private List<Truck_for_Store__c> TruckTemp;
	private List<User> UserTemp;
	private List<Account> Locations;
    private Account ParentAccount;
    //public Truck_for_Store__c SelectedTruck;
    public List<Account> ServicedAccounts {get; set;}
    public Id SelectedAccountId {get; set;}
    public Id SelectedTruckId {get; set;}
    public boolean MapVisible;
    public boolean IgnoreServicedByTruck {get; set;}
    public String BaseUrl {get; set;}

    public TruckController()
    {
        BaseUrl = URL.getSalesforceBaseUrl().toExternalForm() + '';
        MapVisible = false;
        IgnoreServicedByTruck = false;
        AccountTemp = new List<Account>();
        TruckTemp = new List<Truck_for_Store__c>();
        UserTemp = new List<User>();
        Locations = new List<Account>();
        ServicedAccounts = new List<Account>();
    }
    
    public Integer getServicedAccountsLength()
    {
        return ServicedAccounts.size();
    }
    
    public Account getServicedAccount(Integer index)
    {
        if(index >= getServicedAccountsLength())
        {
            //error            
        }
        return ServicedAccounts.get(index);
    }
    
    public boolean getMapVisible()
    {
        return MapVisible;
    }    
    
    public Account getParentAccount() 
    {
        return ParentAccount;
    }
     
    public List<SelectOption> getAccounts()
    {
        AccountTemp = [Select a.Store_Number__c, a.Id, a.Truck_Qty__c, a.ParentId From Account a Where a.Truck_Qty__c > 0];
        List<SelectOption> accounts = new List<SelectOption>();
        accounts.add(new SelectOption('','-Select-'));
        for(Account temp : AccountTemp)
        {
            accounts.add(new SelectOption(temp.Id, temp.Store_Number__c));
        }
        return accounts;
    }
	
	public List<SelectOption> TruckList
    {
        get
        {
            List<Truck_for_Store__c> TruckTemp = [Select t.Store__r.Id, t.Truck__r.Id, t.Truck_Unit_Nbr__c, t.Truck_Description__c  From Truck_for_Store__c t Where t.Truck_Is_Active__c = true];
            TruckList = new List<SelectOption>();
            TruckList.add(new SelectOption('','-Select-'));
            for(Truck_for_Store__c temp : TruckTemp)
            {
                String truckInfo = temp.Truck_Unit_Nbr__c + ' ' + temp.Truck_Description__c;
                TruckList.add(new SelectOption(temp.Store__r.Id, truckInfo));
            }
            return TruckList;
        }
        set;
    }
	
	/*public List<SelectOption> UserList
	{
		get
		{
			//correct role name? driver?
			List<User> UserTemp = [Select u.Id, u.Name, u.UserRole From User u Where u.IsActive = true AND u.UserRole.Name = 'Industrial_Store_Truck'];
			UserList = new List<SelectOption>();
			for(User temp : UserTemp)
			{
				UserList.add(new SelectOption(temp.Id, temp.Name);
			}
			return UserList;
		}
		set;
	}*/
    
    public void PopulateMapForAccount() 
    {
        List<Account> selectAccount = [Select Name, Latitude__c, Longitude__c From Account Where Id = :SelectedAccountId];
        if(selectAccount.size() > 0)
        {
            ParentAccount = selectAccount.get(0);
            PopulateIndustrialAccounts(ParentAccount.Id);
        	MapVisible = true;
        }
        else
        {
            MapVisible = false;
        }        
    }
    
    public void ToggleIgnoreNonTruck()
    {
        IgnoreServicedByTruck = !IgnoreServicedByTruck;
    }
    
    public void PopulateMapForTruck() 
    {
        List<Account> selectAccount = [Select Name, Latitude__c, Longitude__c From Account Where Id = :SelectedTruckId];
        if(selectAccount.size() > 0)
        {
            ParentAccount = selectAccount.get(0);
            PopulateIndustrialAccounts(ParentAccount.Id);
        	MapVisible = true;
        }
        else
        {
            MapVisible = false;
        }        
    }
    
    private void PopulateIndustrialAccounts(Id selectedId)
    {
        ServicedAccounts = [Select Id, Name, Latitude__c, Longitude__c, IA_Service_Method__c, Last_Truck_Run__c, Days_Since_Last_Truck_Run__c
                            FROM Account 
                            WHERE Id != :selectedId];
    }
    
    public PageReference openCal()
    {
        PageReference pageRef= new PageReference('/apex/TruckControllerCal');
        pageRef.setredirect(true);       
        pageRef.getParameters().put('storeId', ParentAccount.Id);
        return pageRef;
    }
}