force-app/main/default/objects/Account/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the related Dealer. 
Field Type: Store Data
Integrated: N</description>
    <inlineHelpText>This is a lookup to the related Dealer.

Responsible Owner: Dealer Operations and Store Operations</inlineHelpText>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <description>The Region code defined in M3 associated to a person (Region Director) and a geographical area within a brand. Theoretically, the region director would be the same in all brands. 
Type: M3
Integrated: Y</description>
    <inlineHelpText>The Region code defined in M3 that is associated to a Sales Region.</inlineHelpText>
    <label>Region Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sharing_Old_Values__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Old_Values__c</fullName>
    <description>This field is used by AccountProgramAccess_Batch to generate Account / Program Sharing for Users when Store Ownership Type or Region Code is changed</description>
    <inlineHelpText>This field is used by AccountProgramAccess_Batch to generate Account / Program Sharing for Users when Store Ownership Type or Region Code is changed</inlineHelpText>
    <label>Sharing Old Values</label>
    <length>63</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sharing_Status__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Status__c</fullName>
    <defaultValue>&quot;Created&quot;</defaultValue>
    <description>This field is used by AccountProgramAccess_Batch to generate Account / Program Sharing for Users.</description>
    <inlineHelpText>This field is used by AccountProgramAccess_Batch to generate Account / Program Sharing for Users.</inlineHelpText>
    <label>Sharing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/M3_Store_Child_Account.recordType-meta.xml
<RecordType>
    <fullName>M3_Store_Child_Account</fullName>
    <active>true</active>
    <description>Designed for M3 Store Child Accounts</description>
    <label>M3 Store Child Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/M3_Store_Parent_Account.recordType-meta.xml
<RecordType>
    <fullName>M3_Store_Parent_Account</fullName>
    <active>true</active>
    <description>Designed for M3 Store Parent Accounts</description>
    <label>M3 Store Parent Account</label>
</RecordType>

force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <description>Referenced by Stores.</description>
    <label>Dealer</label>
    <nameField>
        <label>Dealership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Industrial Account (Account Standard Object) for the program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to Industrial Account (Account Standard Object) for the program.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Servicing_Level__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Level__c</fullName>
    <description>Controls the sharing (servicing stores) for an Industrial Account Program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Controls the sharing (servicing stores) for an Industrial Account Program.
Dealer Only and Dealer Market Area Program are allowed for Dealer Stores. 
RWSS is allowed for Corporate Stores.</inlineHelpText>
    <label>Servicing Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RWSS</fullName>
            </value>
            <value>
                <fullName>RWSSPlus</fullName>
                <default>true</default>
                <label>RWSS +</label>
            </value>
            <value>
                <fullName>DealerMarketAreaProgram</fullName>
                <label>Dealer Market Area Program</label>
            </value>
            <value>
                <fullName>DealerOnly</fullName>
                <label>Dealer Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/classes/RWS_AccountProgramAccess_Batch_Debug.cls
global class RWS_AccountProgramAccess_Batch_Debug implements Database.Batchable<sObject> , Schedulable, Database.Stateful {

    global RWS_AccountProgramAccess_Batch_Debug() { }

    private Set<Id> updatedAccountIds;
    private List<Account> accounts;
    private Set<Id> usersToRemove;

    // initialize batch job
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new RWS_AccountProgramAccess_Batch_Debug(), 10);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {

        updatedAccountIds = new Set<Id>();
        accounts = new List<Account>();
        usersToRemove = new Set<Id>();

        // created accounts after the last run
        Set<Id> accountCreatedIds = new Set<Id>();
        Set<String> accountCreatedWithRegionIds = new Set<String>();

        // updated accounts after the last run
        Set<Id> accountDealerUpdatedIds = new Set<Id>();
        Set<String> accountUpdatedWithRegionIds = new Set<String>();

        Set<Id> accountIds = new Set<Id>();

        for( User u : [select Id, Contact.AccountId, AccountId
                            from User
                            where IsActive = true
                            and CreatedDate >= YESTERDAY
                            and Contact.AccountId != null] ) {

            accountIds.add(u.Contact.AccountId);
        }

        accountIds.remove(null);
		
        System.debug('***accountIds: '+accountIds);
        
        accounts =  
                [select Id, Sharing_Status__c, Dealer__c, Sharing_Old_Values__c, Region_Code__c
                    from Account 
                where IsPartner = true and RecordType.DeveloperName in ('M3_Store_Parent_Account', 
                        'M3_Store_Child_Account')
                and Sharing_Status__c in ('Created', 'Updated')];
        
       System.debug('***accounts: '+accounts);


        for(Account a : accounts) {
            if(a.Dealer__c != null) {
                accountDealerUpdatedIds.add(a.Dealer__c);
            }
            
            if(a.Region_Code__c != null) {
                accountCreatedWithRegionIds.add(a.Region_Code__c);
            }

            if(a.Sharing_Status__c == 'Updated') {

                updatedAccountIds.add(a.Id);

                List<String> values = a.Sharing_Old_Values__c.split(',');
                
                try {
                    if(!String.isBlank(values.get(0)))
                        accountDealerUpdatedIds.add((Id) values.get(0));
                    
                    
                    if(!String.isBlank(values.get(2)))
                        accountUpdatedWithRegionIds.add(values.get(2));

                } catch(Exception ex) {}
            }
            
            accountIds.add(a.Id);
        }
        System.debug('***updatedAccountIds: '+updatedAccountIds);               
        System.debug('***accountCreatedIds: '+accountCreatedIds);        
        System.debug('***accountDealerUpdatedIds: '+accountDealerUpdatedIds);        
 		System.debug('***accountCreatedWithRegionIds: '+accountCreatedWithRegionIds);        
        System.debug('***accountUpdatedWithRegionIds: '+accountUpdatedWithRegionIds);
		System.debug('***accountIds: '+accountIds);         


        if( (!accountCreatedIds.isEmpty()) || (!accountDealerUpdatedIds.isEmpty())) {

            for(Account a : [select Id, Dealer__c from Account 
                                where Dealer__c in :accountCreatedIds 
                                or Dealer__c in :accountDealerUpdatedIds]) {

                accountIds.add(a.Id);
            }
        }

        if( (!accountCreatedWithRegionIds.isEmpty()) || (!accountUpdatedWithRegionIds.isEmpty())) {

            for(Account a : [select Id, Region_Code__c from Account 
                                where Region_Code__c in :accountCreatedWithRegionIds 
                                or Region_Code__c in :accountUpdatedWithRegionIds]) {
                accountIds.add(a.Id);
            }
        }
        
        System.debug('***accountIds: '+accountIds);        


        Set<Id> userIds = new Set<Id>();


        for(User u : [select Id, Name, Contact.AccountId from User where Contact.AccountId in :accountIds]) {
            if(updatedAccountIds.contains(u.Contact.AccountId) ) usersToRemove.add(u.Id);
            userIds.add(u.Id);
        }
        
        System.debug('***userIds: '+userIds);        

        
        return Database.getQueryLocator('select Id, OwnerId, Servicing_Level__c, Account__c ' +
                                        ' from Program__c where OwnerId in :userIds '
                                        + (accountIds.isEmpty() && !Test.isRunningTest() ?  ' and Id = null ' : '') );
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        List<Program__c> programs = (List<Program__c>) scope;
		
        System.debug('***Programs: '+programs);

        if(!updatedAccountIds.isEmpty()) {

            Set<Id> programIds = new Set<Id>();
            Set<Id> accountIds = new Set<Id>();

            for(Program__c p : programs) {
                programIds.add(p.Id);

                if(p.Account__c != null) accountIds.add(p.Account__c);
            }
            
            System.debug('***programIds: '+programIds);
            System.debug('***accountIds: '+accountIds);


            // delete program share records
            delete [select Id from Program__Share 
                        where ParentId in :programIds 
                            and UserorGroupId in :usersToRemove
                            and RowCause = 'Manual'];

            // delete account share records
            if(!accountIds.isEmpty())
                    delete [select Id from AccountShare 
                        where AccountId in :accountIds 
                            and UserorGroupId in :usersToRemove
                            and RowCause = 'Manual'];

            RWS_ProgramTrigger_Handler.setExpirationDateOnServicingStores(programs);
        }

        RWS_ProgramTrigger_Handler.shareProgramAndAccount(programs);
    }

    global void finish(Database.BatchableContext BC) { 
        for(Account a : accounts) {
            a.Sharing_Status__c = 'Completed';
        }
        System.debug('***accounts: '+accounts);
        update accounts;
    }

}