force-app/main/default/objects/Account/fields/Documents_for_Credit_Application__c.field-meta.xml
<CustomField>
    <fullName>Documents_for_Credit_Application__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>SCSV of the related RWfB Attachments that are identified as Documents for Credit Application</description>
    <inlineHelpText>SCSV of the related RWfB Attachments that are identified as Documents for Credit Application</inlineHelpText>
    <label>Documents for Credit Application</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/RWfB_Attachment__c/RWfB_Attachment__c.object-meta.xml
<CustomObject>
    <description>Object to house Business Partner Community Attachments for Accounts</description>
    <label>RWfB Attachment</label>
    <nameField>
        <displayFormat>RWFBA-{00000000}</displayFormat>
        <label>RWfB Attachments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWfB Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RWfB_Attachment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account which the RWfB Attachment is related to.</description>
    <inlineHelpText>Account which the RWfB Attachment is related to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RWfB Attachments</relationshipLabel>
    <relationshipName>RWfB_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/fields/Document_for_Credit_Application__c.field-meta.xml
<CustomField>
    <fullName>Document_for_Credit_Application__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the Document should be used in non-RWBAA Credit Application</description>
    <inlineHelpText>Identify if the Document should be used in non-RWBAA Credit Application</inlineHelpText>
    <label>Document for Credit Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if the RWfB Attachment should be public facing. The default is FALSE, not public.</description>
    <inlineHelpText>Determines if the RWfB Attachment should be public facing. The default is FALSE, not public.</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Define the Type of the Attachment.</description>
    <inlineHelpText>Define the Type of the Attachment.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_for_Credit_Application__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company Voucher</fullName>
            </value>
            <value>
                <fullName>Customer Bid Document</fullName>
            </value>
            <value>
                <fullName>Customer Master Service Agreement</fullName>
            </value>
            <value>
                <fullName>Customer Purchase Order</fullName>
            </value>
            <value>
                <fullName>Customer Trade Reference</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Red Wing Program Agreement</fullName>
            </value>
            <value>
                <fullName>Signed Contract</fullName>
            </value>
            <value>
                <fullName>Tax Exempt Certificate</fullName>
            </value>
            <value>
                <fullName>W-9</fullName>
            </value>
            <value>
                <fullName>Customer Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_RWfB_AttachmentTrigger_Test.cls
@isTest
private class RWS_RWfB_AttachmentTrigger_Test {
    static testMethod void testTrigger() {
        Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');
        
        Account acc = RWS_TestUtil.createAccount(rtId, true);

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);

        List<Contact> contacts = new List<Contact>{con1};

        insert contacts;

        Id roleId = [select Id from UserRole where Name = 'System Administrators' limit 1].Id;

        User u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {

            User user = new User(Id = UserInfo.getUserId(), UserRoleId = roleId);
            update user;

            List<User> users = new List<User>{u1};  
            insert users;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u1.UserRoleId = partnerRoleId;

            update users;
        }

        Test.startTest();

        RWfB_Attachment__c rwfb = new RWfB_Attachment__c();
        rwfb.Type__c = 'Customer Master Service Agreement';
        rwfb.Public__c = true;
        rwfb.Account__c = acc.Id;
        rwfb.Document_for_Credit_Application__c = true;
        insert rwfb;

        System.assert([select Id, Documents_for_Credit_Application__c from Account where Id = :acc.Id].Documents_for_Credit_Application__c == 'None');

        Attachment attach = new Attachment();
        attach.ParentId = rwfb.Id;
        attach.Name = 'Test Attachment';
        attach.Body = Blob.valueOf('Test Attachment');

        insert attach;

        System.assert([select Id, Documents_for_Credit_Application__c from Account where Id = :acc.Id].Documents_for_Credit_Application__c == 'Customer Master Service Agreement');

        rwfb.Type__c = 'Customer Purchase Order';

        update rwfb;

        System.assert([select Id, Documents_for_Credit_Application__c from Account where Id = :acc.Id].Documents_for_Credit_Application__c == 'Customer Purchase Order');

        delete rwfb;

        System.assert([select Id, Documents_for_Credit_Application__c from Account where Id = :acc.Id].Documents_for_Credit_Application__c == 'None');

        undelete rwfb;

        System.assert([select Id, Documents_for_Credit_Application__c from Account where Id = :acc.Id].Documents_for_Credit_Application__c == 'Customer Purchase Order');

        System.runAs(u1) {
            rwfb.Type__c = 'Customer Purchase Order';

            try {
                update rwfb;    
            } catch(Exception e) {}

            try {
                delete rwfb;
            } catch(Exception e) {}
            
        }

        Test.stopTest();
    }   
}