force-app/main/default/objects/Account/fields/Documents_for_Credit_Application__c.field-meta.xml
<CustomField>
    <fullName>Documents_for_Credit_Application__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>SCSV of the related RWfB Attachments that are identified as Documents for Credit Application</description>
    <inlineHelpText>SCSV of the related RWfB Attachments that are identified as Documents for Credit Application</inlineHelpText>
    <label>Documents for Credit Application</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/RWfB_Attachment__c.object-meta.xml
<CustomObject>
    <description>Object to house Business Partner Community Attachments for Accounts</description>
    <label>RWfB Attachment</label>
    <nameField>
        <displayFormat>RWFBA-{00000000}</displayFormat>
        <label>RWfB Attachments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWfB Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RWfB_Attachment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account which the RWfB Attachment is related to.</description>
    <inlineHelpText>Account which the RWfB Attachment is related to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RWfB Attachments</relationshipLabel>
    <relationshipName>RWfB_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/fields/Document_for_Credit_Application__c.field-meta.xml
<CustomField>
    <fullName>Document_for_Credit_Application__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the Document should be used in non-RWBAA Credit Application</description>
    <inlineHelpText>Identify if the Document should be used in non-RWBAA Credit Application</inlineHelpText>
    <label>Document for Credit Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if the RWfB Attachment should be public facing. The default is FALSE, not public.</description>
    <inlineHelpText>Determines if the RWfB Attachment should be public facing. The default is FALSE, not public.</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Define the Type of the Attachment.</description>
    <inlineHelpText>Define the Type of the Attachment.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_for_Credit_Application__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company Voucher</fullName>
            </value>
            <value>
                <fullName>Customer Bid Document</fullName>
            </value>
            <value>
                <fullName>Customer Master Service Agreement</fullName>
            </value>
            <value>
                <fullName>Customer Purchase Order</fullName>
            </value>
            <value>
                <fullName>Customer Trade Reference</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Red Wing Program Agreement</fullName>
            </value>
            <value>
                <fullName>Signed Contract</fullName>
            </value>
            <value>
                <fullName>Tax Exempt Certificate</fullName>
            </value>
            <value>
                <fullName>W-9</fullName>
            </value>
            <value>
                <fullName>Customer Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_RWfB_AttachmentTrigger_Handler.cls
public with sharing class RWS_RWfB_AttachmentTrigger_Handler {

	private static Id SYS_ADMIN_PROFILE_ID = [select Id from Profile where Name = 'System Administrator'].Id;

	public static void beforeUpdate(List<RWfB_Attachment__c> newRecords, Map<Id, RWfB_Attachment__c> oldMap) { 
		if(UserInfo.getProfileId() == SYS_ADMIN_PROFILE_ID )  return;

		for(RWfB_Attachment__c att : newRecords ) {
			if(oldMap.get(att.Id).Document_for_Credit_Application__c && 
				(att.Type__c != oldMap.get(att.Id).Type__c || 
					att.Public__c != oldMap.get(att.Id).Public__c  || 
					att.Document_for_Credit_Application__c != oldMap.get(att.Id).Document_for_Credit_Application__c ||
					att.CurrencyIsoCode != oldMap.get(att.Id).CurrencyIsoCode )) {
				//att.addError('System Administrators can update RWfB Attachments that are flagged as Document for Credit Application');
				}
		}
	}

	public static void beforeDelete(List<RWfB_Attachment__c> oldRecords) { 
		if(UserInfo.getProfileId() == SYS_ADMIN_PROFILE_ID )  return;

		for(RWfB_Attachment__c att : oldRecords ) {
			if(att.Document_for_Credit_Application__c)
				att.addError('System Administrators can delete RWfB Attachments that are flagged as Document for Credit Application');
		}
	}

	/*
	public static void afterInsert(List<RWfB_Attachment__c> newRecords) { 
		updateAccount(newRecords);
	}
	*/

	public static void afterUpdate(List<RWfB_Attachment__c> newRecords, Map<Id, RWfB_Attachment__c> oldMap) { 
		List<RWfB_Attachment__c> relevantRecords = new List<RWfB_Attachment__c> ();

		for(RWfB_Attachment__c att : newRecords) {
			if(att.Type__c != oldMap.get(att.Id).Type__c) {
				relevantRecords.add(att);
			}
		}

		updateAccount(relevantRecords);
	}

	public static void afterDelete(List<RWfB_Attachment__c> oldRecords) { 
		updateAccount(oldRecords);
	}

	public static void afterUndelete(List<RWfB_Attachment__c> newRecords) { 
		updateAccount(newRecords);
	}

	public static void updateAccount(List<RWfB_Attachment__c> newRecords) {
		Set<Id> accountIds = getAccountIds(newRecords);

		if(accountIds.isEmpty()) return;

		Map<Id, List<RWfB_Attachment__c>> accountIdToAttsMap = getRecordsWithAttachment(accountIds);

		List<Account> accountsToUpdate = new List<Account>();

		if(accountIdToAttsMap.isEmpty()) {

			for(Id accId : accountIds) {
				Account accToUpdate = new Account(Id = accId);

				accToUpdate.Documents_for_Credit_Application__c = 'None';

				accountsToUpdate.add(accToUpdate);
			}

			update accountsToUpdate;

			return;
		}

		for(Id accId : accountIdToAttsMap.keySet()) {

			List<RWfB_Attachment__c> atts = accountIdToAttsMap.get(accId);

			Account accToUpdate = new Account(Id = accId);

			if(atts == null || atts.isEmpty()) {
				accToUpdate.Documents_for_Credit_Application__c = 'None';
			} else {
				Set<String> types = new Set<String>();

				for(RWfB_Attachment__c att : atts) {
					types.add(att.Type__c);
				}

				List<String> typeList = new List<String>();
				typeList.addAll(types);

				typeList.sort();

				String docs = '';
				for(String t : typeList) {
					if(docs != '') docs += ',';

					docs += t;
				}

				accToUpdate.Documents_for_Credit_Application__c = docs;
			}

			accountsToUpdate.add(accToUpdate);
		}
		
		update accountsToUpdate;
	}

	private static Map<Id, List<RWfB_Attachment__c>> getRecordsWithAttachment(Set<Id> accountIds) {
		
        Map<Id, List<RWfB_Attachment__c>> returnMe = new Map<Id, List<RWfB_Attachment__c>>();

        List<RWfB_Attachment__c> rwfbList = [Select Id, Type__c, Public__c,
	            Document_for_Credit_Application__c, Account__c,
	            (Select Id from Attachments limit 1) 
            from RWfB_Attachment__c where Document_for_Credit_Application__c = true 
            and Account__c in :accountIds];

        
        for(RWfB_Attachment__c r : rwfbList){
        	List<RWfB_Attachment__c> atts = returnMe.get(r.Account__c);

        	if(atts == null) {
        		atts = new List<RWfB_Attachment__c>();
				returnMe.put(r.Account__c, atts);            		
        	}

            if(r.Attachments != null && !r.Attachments.isEmpty() ) atts.add(r);
        }

        return returnMe;
	}

	private static Set<Id> getAccountIds(List<RWfB_Attachment__c> attRecords) {
		Set<Id> accountIds = new Set<Id>();

		for(RWfB_Attachment__c att : attRecords) {
			if(!att.Document_for_Credit_Application__c) continue;

			accountIds.add(att.Account__c);
		}

		return accountIds;
	}

	/*
	private static List<Account> getAccounts(Set<Id> accountIds) {

		return [select Id, Documents_for_Credit_Application__c,
				(select Id, Type__c, Document_for_Credit_Application__c from 
					RWfB_Attachments__r where Type__c != null
					and Document_for_Credit_Application__c = true) 
				from Account where Id in :accountIds];

	}
	*/
}