force-app/main/default/objects/Account/fields/Freeze_Area_Assigment__c.field-meta.xml
<CustomField>
    <fullName>Freeze_Area_Assigment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Freeze Area Assigment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APEX_Trigger_Settings__c/APEX_Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS consists of a list of triggers and true/false settings to enable/disable functionality without having to disable triggers or edit code.</description>
    <label>APEX Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/APEX_Trigger_Settings__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked - the code is enabled and will run.
Unchecked - the code will be DISABLED and will not run.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/Zip_Code_Area_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is a lookup table for Area Assignment. - ZIp Code assignment of Reps to Zips</description>
    <label>Zip Code Area Assignment</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Area Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zip Code Area Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This a a lookup to the user.</description>
    <inlineHelpText>This a a lookup to the user.</inlineHelpText>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Area_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/Assignment_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Effective_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>This is the Assignment Effective Date.</description>
    <inlineHelpText>This is the Assignment Effective Date.</inlineHelpText>
    <label>Assignment Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Territory Mapper City</description>
    <inlineHelpText>Territory Mapper City</inlineHelpText>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>Territory Mapper County Name</description>
    <inlineHelpText>Territory Mapper County Name</inlineHelpText>
    <label>County Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is an active checkbox</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/IsIncluded__c.field-meta.xml
<CustomField>
    <fullName>IsIncluded__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is an Isincluded checkbox.</description>
    <label>IsIncluded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Area_Assignment__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>This is the role.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ISM</fullName>
            </value>
            <value>
                <fullName>NAM</fullName>
            </value>
            <value>
                <fullName>RD</fullName>
            </value>
            <value>
                <fullName>ROM</fullName>
            </value>
            <value>
                <fullName>TSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code_Assignment__c/Zip_Code_Assignment__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in conjunction with the Lead/Account record assignment logic.</description>
    <label>Zip Code Assignment</label>
</CustomObject>

force-app/main/default/objects/ZipCodeLatAndLong__c/ZipCodeLatAndLong__c.object-meta.xml
<CustomObject>
    <description>This is the base table of zip codes that is loaded from a purchased file from USPS</description>
    <label>ZipCodeLatAndLong</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZipCodeLatAndLong</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCodeLatAndLong__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This stored the City.</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeLatAndLong__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>This stored the County</description>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeLatAndLong__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This stores the state.</description>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZipAssignManagerController_UT.cls
@isTest
private class ZipAssignManagerController_UT {
	
	/*@isTest static void testManager() {
		User uTest = createTestData();

		test.startTest();

		ZipAssignManagerController clsZip = new ZipAssignManagerController();

		// False Search
		clsZip.validateCriteria();
		clsZip.getlstAssign();

		// True Search
		clsZip.clsSearch.zcSearch.City__c = 'City';
		clsZip.clsSearch.zcSearch.State__c = 'State';
		clsZip.clsSearch.zaSearch.OwnerId = uTest.Id;
		clsZip.clsSearch.zaSearch.Role__c = 'TSM';
		clsZip.clsSearch.zcSearch.County__c = 'County';
		clsZip.clsSearch.strZipCode = '12345';
		clsZip.validateCriteria();
		clsZip.getlstAssign();

		clsZip.getLstUnassigned();

		insert new Account(Name='test account', Freeze_Area_Assigment__c=true);
		insert new Lead(Lastname='test', email='me@you.com',PostalCode='12345',Freeze_Area_Assignment__c=true);
		clsZip.getLstFrozenRecords();

		// Page Buttons
		clsZip.newAssignment();

		test.stopTest();
	}
	
	@isTest static void testTriggerAction_Account() {
		User uTest = createTestData();
		test.startTest();
		Account acct = new Account(Name='Test Account', BillingPostalCode='12345');insert acct;
		Account acctCheck = [SELECT Id, OwnerId FROM Account WHERE Id = :acct.Id];
		//System.Assert(acctCheck.OwnerId == uTest.Id, 'Ownership did not change!');
		test.stopTest();
	}

	@isTest static void testTriggerAction_Lead() {
		User uTest = createTestData();
		test.startTest();
		Lead ld = new Lead(Lastname='Test Lead', Email='test@rws.com',PostalCode='12345');insert ld;
		Lead ldCheck = [SELECT Id, OwnerId FROM Lead WHERE Id = :ld.Id];
		//System.Assert(ldCheck.OwnerId == uTest.Id, 'Ownership did not change!');
		test.stopTest();
	}
	
	private static User createTestData() {

		List<Zip_Code_Assignment__c> lstCSAccountZips = new List<Zip_Code_Assignment__c>();
		List<Zip_Code_Assignment__c> lstCSLeadZips = new List<Zip_Code_Assignment__c>();
		for(RecordType rt : [SELECT Id, SObjectType FROM RecordType WHERE SObjectType IN ('Account', 'Lead')]) {
			if(rt.SObjectType == 'Account') {
				lstCSAccountZips.add(new Zip_Code_Assignment__c(Name=rt.Id, IsActive__c=true));
			}
			if(rt.SObjectType == 'Lead') {
				lstCSLeadZips.add(new Zip_Code_Assignment__c(Name=rt.Id, IsActive__c=true));
			}
		}
		insert lstCSAccountZips; insert lstCSLeadZips;

		APEX_Trigger_Settings__c csAPEXAccount = new APEX_Trigger_Settings__c(Name='ownerAssignmentAccount',IsActive__c=true);
		APEX_Trigger_Settings__c csAPEXLead = new APEX_Trigger_Settings__c(Name='ownerAssignmentLead',IsActive__c=true);
		insert csAPEXAccount;
		insert csAPEXLead;

		Profile p = [select id from profile where name='System Administrator'];
        User u = new User(alias = 'RWSTEST1', email='standarduser@rwstestorg.com',
        	emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        	localesidkey='en_US', profileid = p.Id,
        	timezonesidkey='America/Los_Angeles', username='standarduserTEST@testorgRWS.com');
        insert u;

       	List<ZipCodeLatAndLong__c> lstZips = new List<ZipCodeLatAndLong__c>();
       	lstZips.add(new ZipCodeLatAndLong__c(Name='12345'));
       	lstZips.add(new ZipCodeLatAndLong__c(Name='12346'));
       	lstZips.add(new ZipCodeLatAndLong__c(Name='12347'));
       	lstZips.add(new ZipCodeLatAndLong__c(Name='12348'));
       	insert lstZips;

       	List<String> lstRoles = new List<String>();
       	lstRoles.add('TSM');
       	lstRoles.add('ISM');
       	lstRoles.add('NAM');
       	lstRoles.add('ROM');

       	List<Zip_Code_Area_Assignment__c> lstZipAssign = new List<Zip_Code_Area_Assignment__c>();
       	Integer i = 0;
       	for(ZipCodeLatAndLong__c zip : lstZips) {
       		Zip_Code_Area_Assignment__c zca = new Zip_Code_Area_Assignment__c();
       		zca.Zip_Code_Lookup__c = zip.Id;
       		zca.Role__c = lstRoles[i];
       		zca.IsIncluded__c = true;
       		zca.IsActive__c = true;
       		zca.Assignment_Effective_Date__c = System.Today().addDays(-7);
       		zca.OwnerId = u.Id;
       		zca.Account_Owner__c = u.Id;
       		lstZipAssign.add(zca);
       		i += 1;
       	}

       	i = i-1;
       	for(ZipCodeLatAndLong__c zip : lstZips) {
       		Zip_Code_Area_Assignment__c zca = new Zip_Code_Area_Assignment__c();
       		zca.Zip_Code_Lookup__c = zip.Id;
       		zca.Role__c = lstRoles[i];
       		zca.IsIncluded__c = true;
       		zca.IsActive__c = true;
       		zca.Assignment_Effective_Date__c = System.Today().addDays(-7);
       		zca.OwnerId = u.Id;
       		zca.Account_Owner__c = u.Id;
       		lstZipAssign.add(zca);
       		i = i-1;
       	}

       	insert lstZipAssign;

       	return u;

	}*/
}