force-app/main/default/objects/Account/fields/Geocode_Status__c.field-meta.xml
<CustomField>
    <fullName>Geocode_Status__c</fullName>
    <description>This is the Geocode status regarding the &quot;GET&quot; of the latitude and longitude fields by the service. 
Field Type: M3
Integrated: Y</description>
    <inlineHelpText>This is the Geocode Status corresponding to the latitude and longitude fields. 

Responsible Owner: M3 Integration</inlineHelpText>
    <label>Geocode Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ignore</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>This is the latitude values based off physical location. 
Field Type: GBL
Integrated: Y - SF&gt;Shoe Search</description>
    <inlineHelpText>This is the latitude values based off physical location.

Responsible Owner: M3 Integration</inlineHelpText>
    <label>Latitude</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>This is the longitude value base off the physical location.
Field Type: Store Data
Integrated: Y - SF&gt;Xstore</description>
    <inlineHelpText>This is the longitude value base off the physical location.

Responsible Owner: M3 Integration</inlineHelpText>
    <label>Longitude</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_City__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_City__c</fullName>
    <description>M3 Physical Location Address - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: Y</description>
    <label>Physical Location City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_Country__c</fullName>
    <description>M3 Physical Location Country - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: Y</description>
    <label>Physical Location Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_State_Province__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_State_Province__c</fullName>
    <description>M3 Location State or Province - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: Y</description>
    <label>Physical Location State/Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_Street__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_Street__c</fullName>
    <description>M3 Location Street - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: Y</description>
    <label>Physical Location Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/M3_Location_ZIP_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>M3_Location_ZIP_Postal_Code__c</fullName>
    <description>M3 Location Postal Code - used for calculating latitude and longitude -DO NOT TOUCH
Type: M3
Integrated: N</description>
    <label>Physical Location ZIP/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mapquest_City__c.field-meta.xml
<CustomField>
    <fullName>Mapquest_City__c</fullName>
    <label>Mapquest City</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MapQuest_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>MapQuest_Country_Code__c</fullName>
    <label>MapQuest Country Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MapQuest_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>MapQuest_Postal_Code__c</fullName>
    <label>MapQuest Postal Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MapQuest_Response__c.field-meta.xml
<CustomField>
    <fullName>MapQuest_Response__c</fullName>
    <label>MapQuest Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MapQuest_State_Province__c.field-meta.xml
<CustomField>
    <fullName>MapQuest_State_Province__c</fullName>
    <label>MapQuest State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mapquest_Street__c.field-meta.xml
<CustomField>
    <fullName>Mapquest_Street__c</fullName>
    <label>Mapquest Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Utility_GeolocationSchedule.cls
global class Utility_GeolocationSchedule implements Schedulable {

	global void execute(SchedulableContext sc) {
		
		// Find all records in 'Pending' status
		Map<Id, Account> mapPendingGeo = new Map<Id, Account>([
			SELECT Id FROM Account WHERE Geocode_Status__c = 'Pending'
		]);

		Utility_Geolocation.hClsGeocodeTarget clsTarget = new Utility_Geolocation.hClsGeocodeTarget();
        clsTarget.strObject = 'Account';
        clsTarget.strResultStatusField = 'Geocode_Status__c';
        clsTarget.strResultMessageField = 'MapQuest_Response__c';
        clsTarget.strStreetSourceField = 'M3_Location_Street__c';
        clsTarget.strCitySourceField = 'M3_Location_City__c';
        clsTarget.strStateSourceField = 'M3_Location_State_Province__c';
        clsTarget.strPostalCodeSourceField = 'M3_Location_ZIP_Postal_Code__c';
        clsTarget.strCountrySourceField = 'M3_Location_Country__c';
        clsTarget.strStreetTargetField = 'MapQuest_Street__c';
        clsTarget.strCityTargetField = 'MapQuest_City__c';
        clsTarget.strStateTargetField = 'MapQuest_State_Province__c';
        clsTarget.strPostalCodeTargetField = 'MapQuest_Postal_Code__c';
        clsTarget.strCountryTargetField = 'MapQuest_Country_Code__c';
        clsTarget.strLatField = 'Latitude__c';
        clsTarget.strLngField = 'Longitude__c';
        
        Utility_GeolocationBatchProcessor clsBatch = 
            new Utility_GeolocationBatchProcessor();
        clsBatch.clsTarget = clsTarget;
        clsBatch.setScopeIds = mapPendingGeo.keySet();
        clsBatch.strObject = 'Account';

        Id idBatchprocess = Database.executeBatch(clsBatch,150);

	}

}