force-app/main/default/objects/Account/fields/IA_Physical_Location_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_Address_Line_1__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location Address Line 1</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_City__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_City__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_Country__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_State_Province__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_State_Province__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IA_Physical_Location_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>--Select--</fullName>
                <default>true</default>
                <label>--Select--</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Alabama</label>
            </value>
            <value>
                <fullName>AK</fullName>
                <label>Alaska</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Arizona</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Arkansas</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>California</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colorado</label>
            </value>
            <value>
                <fullName>CT</fullName>
                <label>Connecticut</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Delaware</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>Florida</label>
            </value>
            <value>
                <fullName>GA</fullName>
                <label>Georgia</label>
            </value>
            <value>
                <fullName>HI</fullName>
                <label>Hawaii</label>
            </value>
            <value>
                <fullName>ID</fullName>
                <label>Idaho</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>Illinois</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Indiana</label>
            </value>
            <value>
                <fullName>IA</fullName>
                <label>Iowa</label>
            </value>
            <value>
                <fullName>KS</fullName>
                <label>Kansas</label>
            </value>
            <value>
                <fullName>KY</fullName>
                <label>Kentucky</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <label>Louisiana</label>
            </value>
            <value>
                <fullName>ME</fullName>
                <label>Maine</label>
            </value>
            <value>
                <fullName>MD</fullName>
                <label>Maryland</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <label>Massachusetts</label>
            </value>
            <value>
                <fullName>MI</fullName>
                <label>Michigan</label>
            </value>
            <value>
                <fullName>MN</fullName>
                <label>Minnesota</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>Mississippi</label>
            </value>
            <value>
                <fullName>MO</fullName>
                <label>Missouri</label>
            </value>
            <value>
                <fullName>MT</fullName>
                <label>Montana</label>
            </value>
            <value>
                <fullName>NE</fullName>
                <label>Nebraska</label>
            </value>
            <value>
                <fullName>NV</fullName>
                <label>Nevada</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>New Hampshire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IA_Physical_Location_ZIP_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>IA_Physical_Location_ZIP_Postal_Code__c</fullName>
    <description>Community field. Referenced in Duplicate &amp; Matching Rules</description>
    <label>IA Physical Location ZIP/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Parent_Account__c</fullName>
    <inlineHelpText>Centralized - Account invoice(s) will be sent to the parent account utilizing the same terms and billing frequency.  
Decentralized - Account invoice(s) sent to a new address and will bill independent from the parent. Still uses Parent&apos;s Credit Line.</inlineHelpText>
    <label>Invoice Parent Account</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Centralized</fullName>
                <label>Yes - Centralized Billing</label>
            </value>
            <value>
                <fullName>Decentralized</fullName>
                <label>Yes - Decentralized Billing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Requested_Credit_Limi__c.field-meta.xml
<CustomField>
    <fullName>Requested_Credit_Limi__c</fullName>
    <label>Requested Credit Limit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5000</fullName>
                <label>$5,000</label>
            </value>
            <value>
                <fullName>10000</fullName>
                <label>$10,000</label>
            </value>
            <value>
                <fullName>15000</fullName>
                <label>$15,000</label>
            </value>
            <value>
                <fullName>25000</fullName>
                <label>$25,000</label>
            </value>
            <value>
                <fullName>50000</fullName>
                <label>$50,000</label>
            </value>
            <value>
                <fullName>100000</fullName>
                <label>$100,000</label>
            </value>
            <value>
                <fullName>150000</fullName>
                <label>$150,000</label>
            </value>
            <value>
                <fullName>200000</fullName>
                <label>$200,000</label>
            </value>
            <value>
                <fullName>225000</fullName>
                <label>$225,000+</label>
            </value>
            <value>
                <fullName>100</fullName>
                <isActive>false</isActive>
                <label>100</label>
            </value>
            <value>
                <fullName>1122.33</fullName>
                <isActive>false</isActive>
                <label>1122.33</label>
            </value>
            <value>
                <fullName>123</fullName>
                <isActive>false</isActive>
                <label>123</label>
            </value>
            <value>
                <fullName>1465.32</fullName>
                <isActive>false</isActive>
                <label>1465.32</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Requires_Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Requires_Invoicing__c</fullName>
    <label>Requires Invoicing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RWfB_same_as_Physical_Address__c.field-meta.xml
<CustomField>
    <fullName>RWfB_same_as_Physical_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify if the RWfB Address is the same (true) or different (false) than the IA Physical Location fields.</description>
    <inlineHelpText>Used to identify if the RWfB Address is the same (true) or different (false) than the IA Physical Location fields.</inlineHelpText>
    <label>RWfB same as Physical Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Contact_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Contact_Identifier__c</fullName>
    <description>This field was requested by Jeff G to identify the primary contact.</description>
    <inlineHelpText>Please identify this contact as Primary or Billing.</inlineHelpText>
    <label>Contact Identifier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Primary &amp; Billing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Invoice Payment Portal Admin</label>
            </value>
            <value>
                <fullName>Truck Run</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/RWfB_Attachment__c.object-meta.xml
<CustomObject>
    <description>Object to house Business Partner Community Attachments for Accounts</description>
    <label>RWfB Attachment</label>
    <nameField>
        <displayFormat>RWFBA-{00000000}</displayFormat>
        <label>RWfB Attachments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWfB Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/RWS_CreditBillingController_Test.cls
@isTest
private class RWS_CreditBillingController_Test {

    static testMethod void testInsertRWFB(){
        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        RWfB_Attachment__c att = RWS_CreditBillingController.insertRWFB(acc.Id, 'Company Voucher', false);


        System.assert(att.Id != null);
    }

    static testMethod void testYesCentralized(){

        //RWS_AccountTrigger_Handler.RUN

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        Account childAcc = RWS_TestUtil.createAccount(rtId, false);
        childAcc.ParentId = acc.Id;
        childAcc.Requires_Invoicing__c = 'Yes';
        childAcc.Invoice_Parent_Account__c = 'Centralized';
        childAcc.Requested_Credit_Limi__c = '5000';
        childAcc.IA_Physical_Location_City__c = 'MN';
        childAcc.IA_Physical_Location_Country__c = 'US';
        childAcc.IA_Physical_Location_State_Province__c = 'MN';
        childAcc.IA_Physical_Location_Address_Line_1__c = '24-11';
        childAcc.IA_Physical_Location_ZIP_Postal_Code__c = '55211';
        childAcc.RWfB_same_as_Physical_Address__c = true;
        insert childAcc;

        Contact con = RWS_TestUtil.createContact(childAcc.Id, 1, false);
        con.Contact_Identifier__c = 'Primary';
        con.FirstName = 'Charles';
        con.LastName = 'Test';
        con.Email = 'charles@test.com';
        con.MailingCity = 'MN';
        con.MailingCountry = 'US';
        con.MailingState = 'MN';
        con.MailingStreet = '24-A';
        con.MailingPostalCode = '55213';

        Contact con0 = RWS_TestUtil.createContact(acc.Id, 2, false);
        con0.Contact_Identifier__c = 'Primary';
        con0.FirstName = 'Dave';
        con0.LastName = 'Test';
        con0.Email = 'dave@test.com';
        con0.MailingCity = 'MN';
        con0.MailingCountry = 'US';
        con0.MailingState = 'MN';
        con0.MailingStreet = '24-0';
        con0.MailingPostalCode = '55210';

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        con1.Contact_Identifier__c = 'Billing';
        con1.FirstName = 'Bill';
        con1.LastName = 'Test';
        con1.Email = 'bill@test.com';
        con1.MailingCity = 'MN';
        con1.MailingCountry = 'US';
        con1.MailingState = 'MN';
        con1.MailingStreet = '24-B';
        con1.MailingPostalCode = '55214';

        insert new List<Contact>{con, con0, con1};


        Test.startTest();

            PageReference pr = Page.RWS_Account_CreationV2;

            pr.getParameters().put('id', childAcc.Id);

            Test.setCurrentPage(pr);

            RWS_CreditBillingController cc = new RWS_CreditBillingController();
            cc.creditappFlag = true;
            cc.selectInvoiceAttributes = new List<String>();
            cc.selectedBillingRole = new List<String>();

            cc.updateCreditInfo();
            
            System.debug(cc.errors);
            System.debug(cc.haserrors);
            System.debug(cc.isCentralizedBilling);
            System.debug(cc.isDecentralizedBilling);
            System.debug(cc.hasParent);
            System.debug(cc.hasParent);
            System.debug(cc.isInvoiceParentAccount);
            System.debug(cc.outputBillingContact);
            System.debug(cc.hasParent);
            System.debug(cc.contactPrimaryEmail);
            System.debug(cc.decContactId);
            System.debug(cc.invoiceAttributes);

        Test.stopTest();

    } 

    static testMethod void testYesDecentralizedDifferentSameAcc(){

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        Account childAcc = RWS_TestUtil.createAccount(rtId, false);
        childAcc.ParentId = acc.Id;
        childAcc.Requires_Invoicing__c = 'Yes';
        childAcc.Invoice_Parent_Account__c = 'Decentralized';
        childAcc.Requested_Credit_Limi__c = '5000';
        insert childAcc;

        Contact con = RWS_TestUtil.createContact(childAcc.Id, 1, false);
        con.Contact_Identifier__c = 'Primary';
        con.FirstName = 'Dave';
        con.LastName = 'Test';
        con.Email = 'dave@test.com';
        con.MailingCity = 'MN';
        con.MailingCountry = 'US';
        con.MailingState = 'MN';
        con.MailingStreet = '24-A';
        con.MailingPostalCode = '55213';
        
        Contact con2 = RWS_TestUtil.createContact(childAcc.Id, 3, false);
        
        con2.Contact_Identifier__c = 'Billing';
        con2.FirstName = 'Bill';
        con2.LastName = 'Test';
        con2.Email = 'bill@test.com';
        con2.MailingCity = 'MN';
        con2.MailingCountry = 'US';
        con2.MailingState = 'MN';
        con2.MailingStreet = '24-C';
        con2.MailingPostalCode = '55218';

        insert new List<Contact>{con, con2};

        PageReference pr = Page.RWS_Account_CreationV2;

        pr.getParameters().put('id', childAcc.Id);

        Test.setCurrentPage(pr);

        Test.startTest();

        System.runAs(new User(Id = UserInfo.getUserId())) {
            RWS_CreditBillingController cc = new RWS_CreditBillingController();

            cc.creditappFlag = true;

            cc.selectbillingcontactOptions = 'Different';

            cc.decLast = 'Last';
            cc.decFirst = 'First';

            cc.decPhone = '310-745-0000';
            cc.decEmail = 'test@cbc.com';
            
            cc.decRoles = 'DEV';
            
            cc.decSelectedBillingRole = new List<String>();
            
            cc.decTitle = 'TEST';

            cc.selectContactAddrBillOptions = 'Same as Account';
            cc.selectInvoiceAttributes = new List<String>();
            cc.selectedBillingRole = new List<String>();

            cc.selectInvoiceParent = 'Yes';
            cc.selectBillingParent = 'Decentralized';
            cc.selectbillingcontactOptions = 'Yes';
            //cc.updateCreditInfo();

            cc.selectContactAddrBillOptions = 'Different';
            cc.selectbillingcontactOptions = 'Different';
            //cc.updateCreditInfo();
            ////Commented  out on 3/30/2020 because of too many soql queries - James Loghry

            cc.selectInvoiceParent = 'No';
            //Commented  out on 3/30/2020 because of too many soql queries - James Loghry
            //cc.updateCreditInfo();

            cc.accountId = null;
            cc.updateCreditInfo();

        }
        Test.stopTest();
        
    } 

    static testMethod void testYesDecentralizedDifferentDifferentAcc(){

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');

        Account acc = RWS_TestUtil.createAccount(rtId, true);

        Account childAcc = RWS_TestUtil.createAccount(rtId, false);
        childAcc.ParentId = acc.Id;
        childAcc.Requires_Invoicing__c = 'Yes';
        childAcc.Invoice_Parent_Account__c = 'Decentralized';
        childAcc.Requested_Credit_Limi__c = '5000';
        insert childAcc;

        Contact con = RWS_TestUtil.createContact(childAcc.Id, 1, false);
        con.Contact_Identifier__c = 'Primary';
        con.FirstName = 'Bill';
        con.LastName = 'Test';
        con.Email = 'bill@test.com';
        con.MailingCity = 'MN';
        con.MailingCountry = 'US';
        con.MailingState = 'MN';
        con.MailingStreet = '24-A';
        con.MailingPostalCode = '55213';

        Contact con0 = RWS_TestUtil.createContact(acc.Id, 2, false);
        con0.Contact_Identifier__c = 'Primary';
        con0.FirstName = 'Charles';
        con0.LastName = 'Test';
        con0.Email = 'charles@test.com';
        con0.MailingCity = 'MN';
        con0.MailingCountry = 'US';
        con0.MailingState = 'MN';
        con0.MailingStreet = '24-0';
        con0.MailingPostalCode = '55210';

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);
        con1.Contact_Identifier__c = 'Billing';
        con1.FirstName = 'Bill';
        con1.LastName = 'Test';
        con1.Email = 'bill@test.com';
        con1.MailingCity = 'MN';
        con1.MailingCountry = 'US';
        con1.MailingState = 'MN';
        con1.MailingStreet = '24-B';
        con1.MailingPostalCode = '55214';
        
        Contact con2 = RWS_TestUtil.createContact(childAcc.Id, 3, false);
        
        con2.Contact_Identifier__c = 'Billing';
        con2.FirstName = 'Bill';
        con2.LastName = 'Test';
        con2.Email = 'bill@test.com';
        con2.MailingCity = 'MN';
        con2.MailingCountry = 'US';
        con2.MailingState = 'MN';
        con2.MailingStreet = '24-C';
        con2.MailingPostalCode = '55218';

        insert new List<Contact>{con, con0, con1, con2};

        Test.startTest();

            PageReference pr = Page.RWS_Account_CreationV2;

            pr.getParameters().put('id', childAcc.Id);

            Test.setCurrentPage(pr);

            RWS_CreditBillingController cc = new RWS_CreditBillingController();
            cc.creditappFlag = true;
            cc.selectbillingcontactOptions = 'Different';

            cc.decLast = 'Last';
            cc.decFirst = 'First';

            cc.decPhone = '310-745-0000';
            cc.decEmail = 'test@cbc.com';

            cc.selectContactAddrBillOptions = 'Different';

            cc.decCity = 'MN';
            cc.decCountry = 'US';
            cc.decEmail = 'test@cc.com';
            cc.decState = 'MN';
            cc.decZipCode = '55250';
            cc.selectInvoiceAttributes = new List<String>();
            cc.selectedBillingRole = new List<String>();

            cc.updateCreditInfo();

        Test.stopTest();
    }
}