force-app/main/default/objects/Account/fields/ROM_Last_Visit__c.field-meta.xml
<CustomField>
    <fullName>ROM_Last_Visit__c</fullName>
    <label>ROM Last Visit</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APEX_Trigger_Settings__c/APEX_Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS consists of a list of triggers and true/false settings to enable/disable functionality without having to disable triggers or edit code.</description>
    <label>APEX Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/APEX_Trigger_Settings__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked - the code is enabled and will run.
Unchecked - the code will be DISABLED and will not run.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ROM_Store_Visit_Report__c/ROM_Store_Visit_Report__c.object-meta.xml
<CustomObject>
    <description>This is the object for the ROM store visit updates.</description>
    <label>ROM Store Visit Report</label>
    <nameField>
        <displayFormat>ROM - {000000}</displayFormat>
        <label>ROM Visit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ROM Store Visit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ROM_Store_Visit_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account.</description>
    <inlineHelpText>Please lookup the related Account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Rom_Store_Visit_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ROM_Store_Visit_Report__c/fields/ROM_Last_Visit__c.field-meta.xml
<CustomField>
    <fullName>ROM_Last_Visit__c</fullName>
    <formula>Account__r.ROM_Last_Visit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROM Last Visit</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ROM_Store_Visit_Report__c/fields/Store_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Store_Manager_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is the store manager name.</description>
    <inlineHelpText>Please enter the store manager name.</inlineHelpText>
    <label>Store Manager Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Rom_Store_Visit_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Utility_ROMStoreVisit_UnitTest.cls
@isTest
private class Utility_ROMStoreVisit_UnitTest {
	
	@isTest static void testTrigger() {
		
		// Set Test Data
		APEX_Trigger_Settings__c csAPEX = new APEX_Trigger_Settings__c(Name='ROMReportRollupToAccount',IsActive__c=true);
        insert csAPEX;

		Account acct = new Account(Name='Test Account');
		insert acct;

		Contact cont = new Contact(AccountId=acct.Id, LastName='Test', Email='test@me.com');
		insert cont;

		test.startTest();

		insert new ROM_Store_Visit_Report__c(Account__c=acct.Id, Store_Manager_Name__c=cont.Id);
		insert new ROM_Store_Visit_Report__c(Account__c=acct.Id, Store_Manager_Name__c=cont.Id);

		test.stopTest();

		Account acctVerify = [SELECT Id, ROM_Last_Visit__c FROM Account WHERE Id = :acct.Id];

		System.Assert(acctVerify.ROM_Last_Visit__c != null, 'Trigger did not fire right!');

	}
	
}