force-app/main/default/objects/Account/fields/RWS_ID__c.field-meta.xml
<CustomField>
    <fullName>RWS_ID__c</fullName>
    <description>M3 Account Unique External ID field. The same value is used for the M3 Account Number. DO NOT TOUCH.
Type: M3
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the M3 Account unique ID.</inlineHelpText>
    <label>RWS_ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Price_Check__c/Price_Check__c.object-meta.xml
<CustomObject>
    <description>Object used to display results for real-time call for customer-specific Price Check response from Cast Iron.</description>
    <label>Price Check</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Price Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Check__c/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>For integration with M3</description>
    <externalId>true</externalId>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_PriceCheckSolution.cls
@isTest
private class Test_PriceCheckSolution {

    static testMethod void myUnitTest() {
        Account oAccount = new Account(name = 'Bootleggers', RWS_ID__c = '1256102');
        
       	insert oAccount;
       	
       	PageReference result = new PageReference('/apex/PriceCheck?id=' + oAccount.Id);

		Test.setCurrentPage(result);
        
        PriceCheckController oPriceCheckController = new PriceCheckController();

		PriceCheckController.ProductSearchResult oProductSearchResult = new PriceCheckController.ProductSearchResult();
        
        Price_Check__c oPriceCheck = oPriceCheckController.formatPriceCheck(false);
        oPriceCheck = oPriceCheckController.formatPriceCheck(true);
		Http oHttp = new Http();
		HttpRequest oRequest = oPriceCheckController.formatHttpRequest(oPriceCheck);

		HttpResponse oResponse = new HttpResponse();
		
		oResponse.setStatus('200');
		oResponse.setStatusCode(200);
		
		string sString = '<dog>';
		sString += '<h:GetSFDCPriceCheckDataResult xmlns:h="http://tempuri.org/"></h:GetSFDCPriceCheckDataResult>';
		sString += '<h:faultData xmlns:h="http://tempuri.org/"></h:faultData>';
		sString += '</dog>';
		
		oResponse.setBody(sString);
	    oPriceCheck = oPriceCheckController.handleResponse(oResponse, oPriceCheck);

		oPriceCheckController.insertPriceCheck(oPriceCheck);
		
		oPriceCheckController.sProductString = '1';
		oPriceCheckController.sProductBrand = 'Wrox';
		oPriceCheckController.searchProducts();
    }
}