force-app/main/default/objects/Account/fields/Store_Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Store_Ownership_Type__c</fullName>
    <description>Type of store; Dealership, Company Owned, or Branded
Field Type: Store Data - Automatically populated based on M3 Customer Group
Integrated: Y - SF&gt;Xstore pricing portal</description>
    <inlineHelpText>Please select the type of store - used in reporting &amp; list views to separate Company Owned, Dealer, and Branded stores.

Responsible Owner: M3</inlineHelpText>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Branded</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Partner_Community.recordType-meta.xml
<RecordType>
    <fullName>Business_Partner_Community</fullName>
    <active>true</active>
    <description>Used in the Business Partner Community</description>
    <label>Business Partner Community</label>
</RecordType>

force-app/main/default/objects/Store_IA_Account__c/Store_IA_Account__c.object-meta.xml
<CustomObject>
    <description>Object for Red Wing Store and IA Account relationships.  When a Red Wing Store creates a new IA account a record is inserted into this object via APEX.
Object Type: IA
Integrated: N</description>
    <label>Store IA Account</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Store IA Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store IA Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RWS_HeaderController_Test.cls
@isTest
public class RWS_HeaderController_Test {
	@isTest
    public static void Constructor_Test(){
    	RWS_TestDataFactory dataFactory = new RWS_TestDataFactory();

 		System.runAs(dataFactory.TestRunner){
			//not sure if this is needs to be done per unit test method? I think so
			List<Store_IA_Account__c> Industrial = dataFactory.createIndustrialAccounts();

			//test that when we do not set the program id, there is no object returned from SOQL
			RWS_HeaderController controller = new RWS_HeaderController();
			String name = controller.LoggedInUserName;

			System.assert(name != null);
		} 
	}
    
    static testMethod void testController() {
        Id profileId = RWS_TestUtil.getProfileIdByName('RWS Business Partner Community');

        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');
        
        Account acc = RWS_TestUtil.createAccount(rtId, false);
        acc.Store_Ownership_Type__c = 'Dealer';
            
        insert acc;

        acc.IsPartner = true;
        update acc;

        Contact con1 = RWS_TestUtil.createContact(acc.Id, 0, false);

        insert con1;

        Id roleId = [select Id from UserRole where Name = 'System Administrators' limit 1].Id;

        User u1 = RWS_TestUtil.createCommunityUser(con1.Id, profileId, false);

        System.runAs(new User(Id = UserInfo.getUserId())) {

            User user = new User(Id = UserInfo.getUserId(), UserRoleId = roleId);
            update user;
            
            insert u1;

            Id partnerRoleId = [select Name from UserRole where PortalAccountId = :acc.Id].Id;

            u1.UserRoleId = partnerRoleId;

            update u1;
        }

        Test.startTest();

        System.runAs(u1) {
            RWS_HeaderController pr = new RWS_HeaderController();  
            System.assertEquals(0, pr.recourseNumber);
        }

        Test.stopTest();
    }
}