force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book Entry. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book Entry. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>List Price</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/MSRP_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>MSRP_Effective_Date__c</fullName>
    <description>MSRP Effective Date</description>
    <label>MSRP Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/MSRP_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>MSRP_Expiration_Date__c</fullName>
    <description>MSRP Expiration Date</description>
    <label>MSRP Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number__c.field-meta.xml
<CustomField>
    <fullName>Style_Number__c</fullName>
    <description>Style Number (field is used to match against Product standard object). Used for outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number (field is used to match against Product standard object). Used for outbound messaging.</inlineHelpText>
    <label>Style Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_PublishPricebookController.cls
/********************************************************************************
*   PURPOSE :   Generate Publish Pricebook Entries from Pricebook native layout .
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   12/09/2016  Usman Aslam/M360        Initial version
********************************************************************************/
public with sharing class RWS_PublishPricebookController {
	private Id pricebookId;
    public RWS_PublishPricebookController() {
        // get price book id
        pricebookId = ApexPages.currentPage().getParameters().get('id');
    }

    public PageReference publishPricebookEntries() {

        // get price book entries
    	List<Publish_PriceBook_Entry__c> entries = [SELECT Id, Name, Publish_PriceBook__c, Product_ID__c, 
    										CurrencyIsoCode, List_Price__c, Active__c, 
    										/*UseStandardPrice,*/ CreatedDate, CreatedById, 
    										LastModifiedDate, LastModifiedById, SystemModstamp, 
    										Style_Number__c, IsDeleted, Discount__c, 
    										MSRP_Effective_Date__c, MSRP_Expiration_Date__c 
    									FROM Publish_PriceBook_Entry__c	
    									WHERE Publish_PriceBook__c = :pricebookId
                                        /*AND Product2.IsActive = true*/];
        
        Set<Id> prodIds = new Set<Id>();
            
        for(Publish_PriceBook_Entry__c ppbe : entries) {
            prodIds.add(ppbe.Product_Id__c);
        }
        
        Set<Id> prodIdSet = new Set<Id>(); 
        for (Product2 prod : [SELECT Id, Name, Category__c, ProductCode FROM Product2 WHERE IsActive = true AND Id IN : prodIds]){
            prodIdSet.add(prod.Id);
        }
        
        for(Integer i = 0; i < entries.size(); i++){
            if (!prodIdSet.contains(entries[i].Product_Id__c)){
                entries.remove(i);    
            }
        }
        
        
        

    	if(!entries.isEmpty()) {
    		try {

                // generate Publish Pricebook Entries
    			RWS_PriceBookEntry_Util.createPublicPriceBookEntries(entries);
    		} catch (DmlException ex) {
    			ApexPages.addMessages(ex);
    		}
    	}

        // return to price book
    	return new PageReference('/' + pricebookId);
    }
}