force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</description>
    <inlineHelpText>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</inlineHelpText>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_ppbButtonController.cls
public class RWS_ppbButtonController {
    // Constructor - only matters if the autoRun function doesn't work right
    private final Publish_Pricebook__c ppb;
    public RWS_ppbButtonController(ApexPages.StandardController stdController) {
        this.ppb = (Publish_PriceBook__c)stdController.getRecord();
    }
     
    // Code invoked on page load.
    public PageReference autoRun() {
 
        String recordId = ApexPages.currentPage().getParameters().get('id');
 
        if (recordId == null) {
            // Display the Visualforce page's content if no Id is passed over
            return null;
        }
 
        List<Publish_PriceBook_Entry__c> ppbeList = [SELECT Id, Active__c, Publish_Status__c, Publish_PriceBook__c, Expiration_Date__c 
                                                    FROM Publish_PriceBook_Entry__c 
                                                    WHERE Publish_PriceBook__c =: recordId 
                                                    AND Active__c = true 
                                                    AND (Publish_Status__c = 'Waiting' OR Publish_Status__c = 'Deactivated')];
        
        for (Publish_Pricebook_Entry__c ppbe : ppbeList){
            if (ppbe.Publish_Status__c == 'Deactivated')
                ppbe.Expiration_Date__c = null;
            
            ppbe.Publish_Status__c = 'ReadyToPublish';
        }
        
        try{
            update ppbeList;  
            
            // Redirect the user back to the original page
            PageReference pageRef = new PageReference('/' + recordId);
            pageRef.setRedirect(true);
            return pageRef;
            
        } catch (DMLException e){
            System.debug('Exception: '+e);
            
            // Display the Visualforce page's content if DML error
            return null;
        }
        
    }
}