force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the Publish Pricebook is Active</description>
    <inlineHelpText>Identify if the Publish Pricebook is Active</inlineHelpText>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Historic_Pricebook_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Historic_Pricebook_Entry_ID__c</fullName>
    <description>Captured the previous PBE Case Safe ID to leverage in the PPBE Pricebook Entry ID</description>
    <inlineHelpText>Captured the previous PBE Case Safe ID to leverage in the PPBE Pricebook Entry ID</inlineHelpText>
    <label>Historic Pricebook Entry ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>List Price</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/MSRP_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>MSRP_Effective_Date__c</fullName>
    <description>MSRP Effective Date</description>
    <label>MSRP Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Price Book standard object.  Associates the Publish Pricebook Entry Records with the Price Book record.  Used for outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to Price Book standard object.  Associates the Publish Pricebook Entry Records with the Price Book record.  Used for outbound messaging.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Pricebook_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Entry_ID__c</fullName>
    <description>Contains the ID for the PPBE record for downstream systems, includes Historic record ID if present.</description>
    <formula>IF( Historic_Pricebook_Entry_ID__c != NULL,  Historic_Pricebook_Entry_ID__c ,  CASESAFEID(Id))</formula>
    <inlineHelpText>Contains the ID for the PPBE record for downstream systems, includes Historic record ID if present.</inlineHelpText>
    <label>Pricebook_Entry_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number__c.field-meta.xml
<CustomField>
    <fullName>Style_Number__c</fullName>
    <description>Style Number (field is used to match against Product standard object). Used for outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number (field is used to match against Product standard object). Used for outbound messaging.</inlineHelpText>
    <label>Style Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_Id__c</fullName>
    <description>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.</inlineHelpText>
    <label>Style Number Unique Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_MigrateProductsFromPBE_Batch_Test.cls
/********************************************************************************
*   PURPOSE :   Test Class for RWS_MigrateProductsFromPBE_Batch
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   03/08/2018  Brandon Willard/M360    Initial version
********************************************************************************/
@isTest
public class RWS_MigrateProductsFromPBE_Batch_Test {

/* begin comment out class
    
    @testSetup 
    static void setup() {
        List<PriceBook2> pbs = new List<PriceBook2>();
        List<Publish_PriceBook__c> ppbs = new List<Publish_PriceBook__c>();
        List<PriceBookEntry> pbes = new List<PriceBookEntry>();
        List<Publish_PriceBook_Entry__c> ppbes = new List<Publish_PriceBook_Entry__c>();
        List<Product2> prods = new List<Product2>();
        
        //Set standard pricebook Id for test
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create products
        for (Integer i=0;i<5;i++) {            
            prods.add(new Product2( Name = 'RW Shoes' + i, 
                                     Family = 'Hardware',
                                     IsActive = true,
                                     Category__c = 'Footwear',
                                     Style_Number_Unique_Id__c = '00110' + i,
                                     Item_Status__c = 'Active' ,
                                     Item_Status_Code__c = '20',
                                     ProductCode = 'PC00110' + i));
        }        
        insert prods;
        
        //Create standard pricebook
        List<PricebookEntry> standardPbe = new List<PricebookEntry>();       
        
        //Create standard pricebooke entries for standard pricebook
        for (Integer i=0;i<5;i++) {           
           standardPbe.add(new PricebookEntry(Pricebook2Id = pricebookId, 
                                              Product2Id = prods[i].Id,
                                              UnitPrice = 1000, 
                                              IsActive = true));            
        }
        insert standardPbe;
        
        //Create custom standard pricebooks to simulate historical pricebook
        for (Integer i=0; i<5; i++) {
            pbs.add(new PriceBook2(name='PB '+i, isActive=true));
        }
        insert pbs;
        
        //For each custom standard pricebook, create a related publish pricebook and pricebookEntries for each product
        for (Pricebook2 pb : [select id from Pricebook2]) {
            Integer i = 0;
            ppbs.add(new Publish_PriceBook__c(Name='PPB '+i, IsActive__c=true, Price_Book__c=pb.Id));                        
            i++;  
            for (Integer j=0; j<prods.size(); j++){
                pbes.add(new PricebookEntry(Pricebook2Id = pb.Id, 
                                            Product2Id = prods[j].Id,
                                            UnitPrice = 900,
                                            Filter_Number__c = 1,
                                            IsActive = true));              
            }
        }
        insert ppbs;
        insert pbes;
        
        //For each publish pricebook create publish pricebook entries with fields to be populated set to null
        for (Publish_Pricebook__c ppb: [Select Id from Publish_Pricebook__c]){
            for (Integer i=0; i<prods.size(); i++){ 
                ppbes.add(new Publish_Pricebook_Entry__c(Publish_PriceBook__c = ppb.Id, 
                                                         Style_Number__c = prods[i].ProductCode,
                                                         List_Price__c = 900, 
                                                         Active__c = true,
                                                         Historic_Pricebook_Entry_ID__c = null,
                                                         Pricebook_Entry_ID__c = pbes[i].Id,                                                        
                                                         Product_ID__c = null,
                                                         MSRP_Effective_Date__c = Date.today()));
            }
            
        }
       
        insert ppbes;
        
        for (Integer i=0; i<ppbes.size(); i++){ 
        }
       
    }

    static testmethod void testBatchClass() {        
        Test.startTest();
        //Run batch job
        RWS_MigrateProductsFromPBE_Batch batchClass = new RWS_MigrateProductsFromPBE_Batch();
        Id batchId = Database.executeBatch(batchClass);
        Test.stopTest();
        
        
        //asserts that product Id and Historic Pricebook Entry Id fields are populated by the batch job
        System.assertEquals(25, [select count() from Publish_Pricebook_Entry__c where Product_ID__c != null]);
        System.assertEquals(25, [select count() from Publish_Pricebook_Entry__c where Historic_Pricebook_Entry_ID__c != null]); 
        System.assertEquals(25, [select count() from Publish_Pricebook_Entry__c where Filter_Number__c = 1]); 

    }
    
  */
    
}