force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Historic_Pricebook_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Historic_Pricebook_Entry_ID__c</fullName>
    <description>Captured the previous PBE Case Safe ID to leverage in the PPBE Pricebook Entry ID</description>
    <inlineHelpText>Captured the previous PBE Case Safe ID to leverage in the PPBE Pricebook Entry ID</inlineHelpText>
    <label>Historic Pricebook Entry ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Price Book standard object.  Associates the Publish Pricebook Entry Records with the Price Book record.  Used for outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to Price Book standard object.  Associates the Publish Pricebook Entry Records with the Price Book record.  Used for outbound messaging.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Pricebook_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Entry_ID__c</fullName>
    <description>Contains the ID for the PPBE record for downstream systems, includes Historic record ID if present.</description>
    <formula>IF( Historic_Pricebook_Entry_ID__c != NULL,  Historic_Pricebook_Entry_ID__c ,  CASESAFEID(Id))</formula>
    <inlineHelpText>Contains the ID for the PPBE record for downstream systems, includes Historic record ID if present.</inlineHelpText>
    <label>Pricebook_Entry_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number__c.field-meta.xml
<CustomField>
    <fullName>Style_Number__c</fullName>
    <description>Style Number (field is used to match against Product standard object). Used for outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number (field is used to match against Product standard object). Used for outbound messaging.</inlineHelpText>
    <label>Style Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_MigrateProductsFromPBE_Batch.cls
/********************************************************************************
*   PURPOSE :   Migrate data from historical PricebookEntry records to related 
*               Published Pricebook Entry records.
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   03/08/2018  Brandon Willard/M360    Initial version
********************************************************************************/
global class RWS_MigrateProductsFromPBE_Batch implements 
    Database.Batchable<sObject>, Database.Stateful {
  
        

    global Integer pricebookRecordsProcessed = 0;
    global Integer pricebookEntryRecordsProcessed = 0;


    //get all standard Pricebooks and related PricebookEntry records that currently contain the data to be migrated
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, IsStandard FROM PriceBook2 Where IsStandard = false'
        );
    }

    // intialize the batch job
    global void execute(Database.BatchableContext bc, List<PriceBook2> scope){
       
/* begin comment out method
        
        //Set of pricebook Ids        
        Set<Id> pbIds = new Set<Id>();
        //Map of product style to product Id
        Map<String, Id> styleProductIdMap = new Map<String, Id>();
        //Map of product Id to filter number
        Map<Id, Decimal> productIdFilterNumMap = new Map<Id, Decimal>();
        
        
        //Iterate standard pricebook records
        for (PriceBook2 pb : scope) {
            pbIds.add(pb.Id);
            pricebookRecordsProcessed = pricebookRecordsProcessed + 1;
        } 
        
        Set<Id> pbeIds = new Set<Id>();
        if (!pbIds.isEmpty()){            
            for (PriceBookEntry pbe : [SELECT Id, ProductCode, Product2Id, Filter_Number__c FROM PricebookEntry WHERE Pricebook2Id IN :pbIds]) {
                    //Fill maps
                    styleProductIdMap.put(pbe.ProductCode, pbe.Product2Id); 
                    productIdFilterNumMap.put(pbe.Product2Id, pbe.Filter_Number__c);
                    pbeIds.add(pbe.Id);
                    pricebookEntryRecordsProcessed = pricebookEntryRecordsProcessed + 1;
            }
        }
        
       
        Set<Id> ppbIds = new Set<Id>();
        
        if (!pbIds.isEmpty()){
            //Get all publish pricebooks that are related to standard pricebooks (related during creation of published pricebooks from standard pricebooks)
            //and add Ids to set
            for (Publish_Pricebook__c ppb : [SELECT Id, Price_Book__c FROM Publish_PriceBook__c WHERE Price_Book__c IN : pbIds]){
                ppbIds.add(ppb.Id);
            }
        }
       
        if (!ppbIds.isEmpty()){
            //Get all publish pricebook entry records for all relevant publish pricebooks
            List<Publish_PriceBook_Entry__c> ppbes = [SELECT Id, Product_ID__c, Style_Number__c, Publish_PriceBook__c, Publish_PriceBook__r.Price_Book__c, Filter_Number__c, Pricebook_Entry_ID__c FROM Publish_PriceBook_Entry__c WHERE Publish_PriceBook__c IN : ppbIds];
            
            List<Publish_Pricebook_Entry__c> PPBEsToUpdate = new List<Publish_Pricebook_Entry__c>();
            //Populate publish pricebook entry fields with migrated data
            for (Publish_Pricebook_Entry__c ppbe : ppbes){
                Id productId = styleProductIdMap.get(ppbe.Style_Number__c); 
                Decimal filterNum = productIdFilterNumMap.get(productId);
                System.debug('*************filterNum :'+filterNum);
                ppbe.Product_ID__c = productId;
                ppbe.Filter_Number__c =  filterNum;
                if(ppbe.Pricebook_Entry_ID__c != null)
                    ppbe.Historic_Pricebook_Entry_ID__c = ppbe.Pricebook_Entry_ID__c;
                
                PPBEsToUpdate.add(ppbe);
            }
            
            //Update list of modified publish pricebook entries
            update PPBEsToUpdate;
        }

  */ 
    }    

    global void finish(Database.BatchableContext bc){
        
/* begin comment out method                  

        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        
        System.debug('Number of errors: '+job.NumberOfErrors);
        System.debug(job.JobItemsProcessed+' job(s) processed of '+job.TotalJobItems+' total job(s)');
        System.debug(pricebookRecordsProcessed + ' pricebook records processed');
        System.debug(pricebookEntryRecordsProcessed + ' pricebook entry records processed');
        // call some utility to send email
       // EmailUtils.sendMessage(a, recordsProcessed);
       
*/ 
       
    } 
        
 
   
}