force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Outbound_Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Message_Type__c</fullName>
    <description>Outbound Message Type
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Outbound Message Type</inlineHelpText>
    <label>Outbound Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Program Publish Status</description>
    <inlineHelpText>Program Publish Status</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/Servicing_Store__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Object created to share programs based on servicing level with downstream systems via outbound message</description>
    <label>Servicing Store</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Servicing Store #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Servicing Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicing_Store__c/fields/Outbound_Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Message_Type__c</fullName>
    <label>Outbound Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update Servicing Store</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Servicing Stores</relationshipLabel>
    <relationshipName>Servicing_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/fields/Servicing_Status__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Status__c</fullName>
    <label>Servicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_ServicingStore_Handler.cls
public with sharing class RWS_ServicingStore_Handler {

	public static void afterInsert(List<Servicing_Store__c> newRecords) {
		publishServicingStores(newRecords, null, false);
	}

	public static void afterUpdate(List<Servicing_Store__c> newRecords, Map<Id, Servicing_Store__c> oldRecords) {
		publishServicingStores(newRecords, oldRecords, true);
	}

    private static void publishServicingStores(List<Servicing_Store__c> newRecords, Map<Id, Servicing_Store__c> oldRecords, Boolean isUpdate) {
        Set<Id> proIdSet = new Set<Id>();
        List<Servicing_Store__c> progList = new List<Servicing_Store__c>();
        List<Servicing_Store__c> progupdateList = new List<Servicing_Store__c>();
        

        for(Servicing_Store__c pro : newRecords){
            proIdSet.add(pro.Id);
        }       

        progList = [select id, Publish_Status__c,
                                Outbound_Message_Type__c,
                                Servicing_Status__c,
                                Program__r.Publish_Status__c,
                                Program__r.Active__c
                    from Servicing_Store__c where Id in :proIdSet];

                    
        Set<String> programsProcessedIds = new Set<String>();

        for(Servicing_Store__c ssObj : progList){
            
            // if status is ReadyToPublish or  Waiting or just changed to published, do nothing
            if((ssObj.Publish_Status__c == 'ReadyToPublish') || (ssObj.Publish_Status__c == 'Waiting') ||
                (isUpdate && ssObj.Publish_Status__c == 'Published' && 
                    ssObj.Publish_Status__c != oldRecords.get(ssObj.id).Publish_Status__c))
                continue;

            if (ssObj.Program__r.Active__c 
            	&& ssObj.Program__r.Publish_Status__c == 'Published' 
            	&& ssObj.Servicing_Status__c == 'Active'){

                ssObj.Outbound_Message_Type__c = 'Update Servicing Store';
                ssObj.Publish_Status__c = 'ReadyToPublish';  
                progupdateList.add(ssObj);

            } else if ((ssObj.Program__r.Active__c == false || ssObj.Program__r.Publish_Status__c == 'Published') 
            	&& ssObj.Servicing_Status__c == 'Active' 
                && ssObj.Publish_Status__c != 'Waiting' ){
                ssObj.Publish_Status__c = 'Waiting';  
                progupdateList.add(ssObj);
            }    
        }

        if(!progupdateList.isEmpty()){
            update progupdateList;
        }
    }
}