force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Scheduler__c/Program_Scheduler__c.object-meta.xml
<CustomObject>
    <label>Program Scheduler</label>
    <nameField>
        <displayFormat>PS-{0000000}</displayFormat>
        <label>Program Scheduler Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Scheduler__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the record has been processed</description>
    <inlineHelpText>Identify if the record has been processed</inlineHelpText>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Scheduler__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identify the Program that is related to the Scheduler record.</description>
    <inlineHelpText>Identify the Program that is related to the Scheduler record.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Scheduler</relationshipLabel>
    <relationshipName>Program_Scheduler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Scheduler__c/fields/Program_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Template_Name__c</fullName>
    <description>Identify the Program Template name (if selecteD)</description>
    <inlineHelpText>Identify the Program Template name (if selecteD)</inlineHelpText>
    <label>Program Template Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_ProgramProducts_Batch.cls
global class RWS_ProgramProducts_Batch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {

    global Boolean hasData = false;

    global void execute(SchedulableContext sc) {
        Database.executeBatch(new RWS_ProgramProducts_Batch(), 1);
    }

    

    global Database.QueryLocator start(Database.BatchableContext bc) {

        hasData = ![SELECT Processed__c, Program__c, Program_Template_Name__c 
                                            FROM Program_Scheduler__c where Processed__c = false limit 1].isEmpty();

        return Database.getQueryLocator([SELECT Processed__c, Program__c, Program_Template_Name__c 
                                            FROM Program_Scheduler__c where Processed__c = false
                                            order by CreatedDate asc]);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        Program_Scheduler__c scheduler = (Program_Scheduler__c) scope[0];

        Boolean createTemplate = !String.isBlank(scheduler.Program_Template_Name__c);

        

        RWS_ProgramProducts_BatchHandler h = new RWS_ProgramProducts_BatchHandler(scheduler.Program__c, 
                            createTemplate,
                            scheduler.Program_Template_Name__c);

        h.execute();

        scheduler.Processed__c = true;

        update scheduler;


    }

    global void finish(Database.BatchableContext BC) {
        Integer minutes = 5;
        if(hasData) minutes = 1;

       RWS_ProgramProducts_Batch sc = new RWS_ProgramProducts_Batch();
       Datetime dt = Datetime.now().addMinutes(minutes);
       String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
       Id schedId = System.Schedule('ProgramProducts' + timeForScheduler, timeForScheduler, sc);

    }
}