force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/HasPricebook__c.field-meta.xml
<CustomField>
    <fullName>HasPricebook__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by APEX to flag Programs that have an active custom Pricebook.</description>
    <inlineHelpText>This field is used by APEX to flag Programs that have an active custom Pricebook.</inlineHelpText>
    <label>HasPricebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <description>Indicates the related Price Book (ID).
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the related Price Book.</inlineHelpText>
    <label>Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Program Publish Status</description>
    <inlineHelpText>Program Publish Status</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <description>Formula field which returns the ID from a Price Book (standard object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <formula>IF( Historic_Pricebook_ID__c != NULL, Historic_Pricebook_ID__c, CASESAFEID(Id))</formula>
    <inlineHelpText>Formula field which returns the ID from a Price Book (standard object)  Used in outbound messaging.</inlineHelpText>
    <label>Price Book ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_PriceBookTrigger_Handler.cls
/********************************************************************************
*   PURPOSE : To stage Pricebook records into Publish_PriceBook__c for outbound publishing.
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   			M360			        Initial version
*	03/08/18	Brandon Willard(M360)   Modified for RWCP-3449
********************************************************************************/
public with sharing class RWS_PriceBookTrigger_Handler {

    public static Boolean RUN_UPDATE = true;

    public static void beforeInsert(List<Pricebook2> newList) {
        for(Pricebook2 pb : newList) {
            if(pb.Name != null && pb.Name.length() > 80) pb.Name = pb.Name.left(80);
        }
    }

    public static void beforeUpdate(List<Pricebook2> newList, Map<Id, Pricebook2> oldMap) {
        for(Pricebook2 pb : newList) {
            if(pb.Name != null && pb.Name.length() > 80) pb.Name = pb.Name.left(80);
        }
    }

    /* commented out by BW
    // method to handle after insert event of the trigger
    public static void afterInsert(List<Pricebook2> newList) {
        insertPublishPricebook(newList);

        setPricebookIdOnProgram(newList, false);
    }

    // method to handle after update event of the trigger
    public static void afterUpdate(List<Pricebook2> newList, Map<Id, Pricebook2> oldMap) {
        updatePublishPricebook(newList, oldMap);
        setPricebookIdOnProgram(newList, oldMap);
    }

    // handles before delete event
    public static void beforeDelete(List<Pricebook2> newList) {
        setPricebookIdOnProgram(newList, true);
    }
    
    // handles after undelete event
    public static void afterUndelete(List<Pricebook2> newList) {
        setPricebookIdOnProgram(newList, false);
    }
	
    private static void insertPublishPricebook(List<Pricebook2> newList) {
         // Create Publish Pricebook records
        List<Publish_PriceBook__c> recordsToInsert = new List<Publish_PriceBook__c>();
        for(Pricebook2 pb : newList) {
            recordsToInsert.add(
                new Publish_PriceBook__c(
                    Price_Book__c = pb.Id,
                    Discount__c = pb.Discount__c,
                    Name = (pb.Name != null && pb.Name.length() > 80 ? pb.Name.left(80) : pb.Name)
                )
            );
        }

        insert recordsToInsert;
    }

    private static void setPricebookIdOnProgram(List<Pricebook2> newList, Map<Id, Pricebook2> oldMap) {
        List<Pricebook2> relatedRecords = new List<Pricebook2>();

        for(Pricebook2 pb : newList) {
            //if(pb.IsActive == oldMap.get(pb.Id).IsActive)  continue;

            relatedRecords.add(pb);
        }

        if(relatedRecords.isEmpty()) return;

        setPricebookIdOnProgram(relatedRecords, false);
    }

    private static void setPricebookIdOnProgram(List<Pricebook2> newList, Boolean isDelete) {
        Map<Id, Program__c> programsToUpdate = new Map<Id, Program__c>();

        Set<Id> programIds = new Set<Id>();

        for(Pricebook2 pb : newList) {
            if(pb.Program__c == null) continue;

            programIds.add(pb.Program__c);
        }

        if(programIds.isEmpty()) return;

        List<Pricebook2> otherPriceBooks = [select Id, Program__c from Pricebook2 
            where Program__c != null and Program__c in :programIds and Id not in :newList];

        Set<Id> programAlreadyHavingPricebook = new Set<Id>();

        for(Pricebook2 pb : otherPriceBooks) {
            programAlreadyHavingPricebook.add(pb.Program__c);
        }

        for(Pricebook2 pb : newList) {
            if(pb.Program__c == null) continue;

            if(programAlreadyHavingPricebook.contains(pb.Program__c) && (!isDelete) ) pb.addError('Program already have a Pricebook.');

            programsToUpdate.put(pb.Program__c, new Program__c(Id = pb.Program__c, 
                                                    Price_Book_ID__c = isDelete ? null : pb.Id //,
                                                    //HasPricebook__c = isDelete ? false : pb.IsActive
    												));
        }

        if(!programsToUpdate.isEmpty()) update programsToUpdate.values();
    }

    private static void updatePublishPricebook(List<Pricebook2> newList, Map<Id, Pricebook2> oldMap) {
        if(!RUN_UPDATE) return;
        
        Set<Id> pbIds = new Set<Id>();

        // process records if name or discount is changed
        for(Pricebook2 pb : newList) {
            if(pb.Name != oldMap.get(pb.Id).Name ||
                pb.Discount__c != oldMap.get(pb.Id).Discount__c ||
                pb.IsActive != oldMap.get(pb.Id).IsActive) {

                pbIds.add(pb.Id);
            }
        }

        if(pbIds.isEmpty()) return;


        Map<Id, Pricebook2> newMap = new Map<Id, Pricebook2>(newList);

        // get existing records
        List<Publish_PriceBook__c> recordsToUpdate = [
            select Id, Discount__c, Publish_Status__c, Name,
                    Price_Book__c
            from Publish_PriceBook__c 
            where Price_Book__c in :pbIds
        ];


        // update information
        for(Publish_PriceBook__c ppb : recordsToUpdate) {
            Pricebook2 pb = newMap.get(ppb.Price_Book__c);

            ppb.Name = pb.Name;
            ppb.Discount__c = pb.Discount__c;
        }

        // update records
        update recordsToUpdate;
    }*/


}