force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>The activation (effective) date of an Industrial Account Program.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The activation (effective) date of an Industrial Account Program.</inlineHelpText>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the Industrial Account program is active.  If unchecked the program is inactive.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked the Industrial Account program is active.  If unchecked the program is inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>The Industrial Account Program&apos;s expiration date.  A program will become inactive if the expiration date is less than today.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Industrial Account Program&apos;s expiration date.  A program will become inactive if the expiration date is less than today.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the program is a template</description>
    <inlineHelpText>Indicates if the program is a template</inlineHelpText>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/classes/RWS_ProgramActivationJob.cls
/********************************************************************************
*   PURPOSE :   Activate/Deactivate Program on Activation/Expiration date.
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   12/09/2016  Usman Aslam/M360        Initial version
********************************************************************************/
global class RWS_ProgramActivationJob implements Database.Batchable<sObject>, Schedulable {

    // initialize batch job
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new RWS_ProgramActivationJob());
    }

    global Database.QueryLocator start(Database.BatchableContext bc) { 
        // get programs that needs to be updated
        return Database.getQueryLocator('SELECT Id, Active__c, Expiration_Date__c, Activation_Date__c ' +
                                'FROM Program__c ' +
                                'WHERE Template__c = false ' +
                                'AND Active__c = true ' + (Test.isRunningTest() ? '' : 'AND Expiration_Date__c < TODAY ')
                            ); 
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        List<Program__c> programs = (List<Program__c>) scope;

        for(Program__c p : programs) {
            p.Active__c = false;
        }

        // update programs
        update programs;
    }

    global void finish(Database.BatchableContext BC) {}
}