force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book Entry. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book Entry. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Fixed_Price__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked (TRUE) it indicates the price for this product is fixed and will not be impacted by the price update batch job which runs for all Programs where Auto Update Prices = TRUE. Only applies to price book entries created for programs.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked (TRUE) it indicates the price for this product is fixed and will not be impacted by the price update batch job which runs for all Programs where Auto Update Prices = TRUE. Only applies to price book entries created for programs.</inlineHelpText>
    <label>Fixed Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>List Price</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_PriceUpdateJob.cls
/********************************************************************************
*   PURPOSE :   Update PriceBook Entries relate to a Program where Auto Update is checked 
                when Standard Entries are changed.
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   12/01/2016  Usman Aslam/M360        Initial version
*	03/08/2018	Brandon Willard/M360    Modified for RWCP-3449
********************************************************************************/
global class RWS_PriceUpdateJob implements Database.Batchable<sObject>, Schedulable, Database.Stateful {

    // map to hold MSRP price
    global Map<String, Double> prodIdToUnitPriceMap;
    global Set<Id> productIds;
    global Set<Id> activeProductIds;
    global RWS_PriceUpdateJob() {
        // populate a map that is related Standard PB Entries that got modified yesterday.
        // this job maintains state between batches executation, so populated the map onece
        if(prodIdToUnitPriceMap == null) {

            // get the standard pricebook id
            Id stdPriceBookId = getStandardPricebookId();
            prodIdToUnitPriceMap = new Map<String, Double>();
            productIds = new Set<Id>();
            //activeProductIds = new Set<Id>();
            List<PricebookEntry> pbes = Database.query(
                    'SELECT Product2Id, ' +
                                'UnitPrice, CurrencyIsoCode ' +
                                'FROM PricebookEntry ' +
                                'WHERE Pricebook2Id = :stdPriceBookId ' +
                                'AND IsActive = true ' +
                                'AND LastModifiedDate >= ' + (Test.isRunningTest() ? ' TODAY ' : ' YESTERDAY ')
                );

            // fill the map
            for(PricebookEntry pbe : pbes) {
                prodIdToUnitPriceMap.put(String.valueOf(pbe.Product2Id) + pbe.CurrencyIsoCode, 
                            pbe.UnitPrice);

                productIds.add(pbe.Product2Id);
            }
            
           /* for (Product2 prod: [Select Id FROM Product2 WHERE IsActive=true AND Id IN :productIds]){
                activeProductIds.add(prod.Id);
            }*/
            
            
        }
    }

    // intialize the batch job
    global void execute(SchedulableContext sc) {
        // execute batch job and process 200 records in a batch
        Database.executeBatch(new RWS_PriceUpdateJob(), 200);
    }

    // get the records that needs to be updated
    global Database.QueryLocator start(Database.BatchableContext bc) { 

        // get Custom Pricebook Entries that are related to changed Standard Pricebook Entries
        return Database.getQueryLocator([SELECT Id, Product_Id__c,
                                         Discount__c,
                                         List_Price__c,
                                         CurrencyIsoCode,
                                         Publish_PriceBook__r.CurrencyIsoCode
                                         FROM Publish_PriceBook_Entry__c 
                                         //WHERE Pricebook2.IsStandard = false
                                         WHERE Active__c = true
                                         //AND Product2.IsActive = true 
                                         AND Fixed_Price__c = false
                                         AND Discount__c != null
                                         AND Publish_PriceBook__r.Program__r.Auto_Update_Price__c = true
                                         AND Product_Id__c in : productIds /*activeProductIds*/]);
        
        
      
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        List<Publish_PriceBook_Entry__c> ppbes = (List<Publish_PriceBook_Entry__c>) scope;

        for(Publish_PriceBook_Entry__c ppbe : ppbes) {

            // get standard price
            Double stdUnitPrice = prodIdToUnitPriceMap.get(String.valueOf(ppbe.Product_Id__c) + ppbe.Publish_PriceBook__r.CurrencyIsoCode);

            if(stdUnitPrice == null) continue;

            // set on program pricebook entry
            ppbe.List_Price__c = stdUnitPrice == 0 ? 0 : (stdUnitPrice - (ppbe.Discount__c / 100) * stdUnitPrice);
        }

        // update pricebook entry records
        RWS_PriceBookEntry_Util.insertUpdateRecords(ppbes, false);


        // set the flag to false so HasPricebook__c logic is NOT executed in the same invocation
        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = Test.isRunningTest();

        // update unit price/discount on the Publish Pricebook Entries and publish them
        RWS_PriceBookEntry_Util.publishPublicPriceBookEntries(ppbes);
    }

    global void finish(Database.BatchableContext BC) { }

    // util method to get standard price book id
    private Id getStandardPriceBookId() {
        if(Test.isRunningTest())
            return Test.getStandardPricebookId();
        else 
            return [select Id, Name from Pricebook2 where IsStandard = true limit 1].Id;
            
    }
}