force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Built for Timba Survey</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/TriggerSettings__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows &quot;send timba survey&quot; on closed case functionality to be turned off</description>
    <label>Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TriggerSettings.cls
public with sharing class TriggerSettings {

	static {
  		if (Test.isRunningTest()) {
   			TriggerSettings__c ts = new TriggerSettings__c(); //if a test is running - create the settings so the test classes dont have to
   			ts.Case__c = true;
   			User thisUser = [ select Id from User where Id = :UserInfo.getUserId()];
   			System.runAs(thisUser) {
    			try{
        			insert ts;
    			}
    			catch(DMLException e){
     				//probably fine - just means it already exists
    			}
   			}
  		} 
 	}
 	
 	public TriggerSettings__c triggers { get; set; }
 	
 	public TriggerSettings() {
 		this.triggers = TriggerSettings__c.getInstance();
 	}
}