force-app/main/default/objects/Status_History__c/Status_History__c.object-meta.xml
<CustomObject>
    <label>Status History</label>
    <nameField>
        <label>Case Status</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_History__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Status History</relationshipLabel>
    <relationshipName>Status_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Status_History__c/fields/Elapsed_Time__c.field-meta.xml
<CustomField>
    <fullName>Elapsed_Time__c</fullName>
    <label>Elapsed Time (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseStatusHistoryTest.cls
/**
* CHANGE HISTORY
* =============================================================================
* Date			Name			Description
* 2013-07-19	Mike Eaton		Added @isTest annotation which should be included
*									on ALL test classes      
* {Date}    	{Changed By}	({Ticket}) – {Change Description}
* =============================================================================
*/
@isTest
public class CaseStatusHistoryTest {
    public static testMethod void testCaseStatusHistory() {

        Case c = new Case();
        c.Status = 'New';
        insert c;

        c.Status = 'Closed';
        update c;

        c.Status = 'New';
        update c;

        c.Status = 'Closed';
        update c;
        
        List<Status_History__c> oSH = [Select Name, StartDate__c, EndDate__c, Elapsed_Time__c From Status_History__c where Case__c=:c.Id];
        for (Status_History__c sh:oSH){
	        System.assert(sh.Name!=null);
	        System.assert(sh.StartDate__c!=null);
	        if (sh.EndDate__c!=null)
	        	System.assert(sh.Elapsed_Time__c!=null);
        }

    }
}