force-app/main/default/objects/Document_Version__c/Document_Version__c.object-meta.xml
<CustomObject>
    <description>Electronic copy of documents to be sent to accounts for acceptance.</description>
    <label>Document Version</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Version__c/fields/Version_Date__c.field-meta.xml
<CustomField>
    <fullName>Version_Date__c</fullName>
    <description>Specified date of the document version.</description>
    <label>Version Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_TriggerUpdateDocumentVersionName.cls
@IsTest
public class Test_TriggerUpdateDocumentVersionName {

      // Test creation of Document Version name
      static testMethod void createDocumentVersionName() {

          //Get Record Type
          RecordType rt = [select id,Name from RecordType where SobjectType='Document_Version__c' and
                          DeveloperName='National_Accounts_Participation_Agreement' Limit 1];

          //Create Document Version
          Document_Version__c docVersion = new Document_Version__c (Version_Date__c = system.Today(), recordTypeId=rt.id);
          insert docVersion;

          //Re-query the data
          Document_Version__c checkDocVersion = new Document_Version__c();
          checkDocVersion = [SELECT Id,Version_Date__c,Name FROM Document_Version__c WHERE Id= :docVersion.id];

        }
}