force-app/main/default/objects/Account_Document__c/Account_Document__c.object-meta.xml
<CustomObject>
    <description>Junction object (many to many relationship) between Document Versions and Accounts. Associates an account to an electronic document.</description>
    <label>Account Document</label>
    <nameField>
        <label>Account Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Documents</relationshipLabel>
    <relationshipName>Account_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewAccountDocumentExtension.cls
public class NewAccountDocumentExtension {
    
    private Apexpages.StandardController controller;
    
    public Account_Document__c acctDocRecord {get;set;}
       
    public NewAccountDocumentExtension(ApexPages.StandardController stdController){
 
        this.controller = stdController;
        
        //Link to Account
        acctDocRecord = (Account_Document__c)stdController.getRecord();  
        String accid = ApexPages.currentPage().getParameters().get('accid');
        acctDocRecord.Account__c = accid;
            
        //Set Record Type
        String rt = ApexPages.currentPage().getParameters().get('RecordType');
        acctDocRecord.RecordTypeId = rt;    
                                        
    }

}