force-app/main/default/objects/Account_Document__c/Account_Document__c.object-meta.xml
<CustomObject>
    <description>Junction object (many to many relationship) between Document Versions and Accounts. Associates an account to an electronic document.</description>
    <label>Account Document</label>
    <nameField>
        <label>Account Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Documents</relationshipLabel>
    <relationshipName>Account_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Document__c/fields/Account_Contact__c.field-meta.xml
<CustomField>
    <fullName>Account_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the contact on the specified account.</description>
    <label>Account Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Documents</relationshipLabel>
    <relationshipName>Account_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Document__c/fields/Document_Version__c.field-meta.xml
<CustomField>
    <fullName>Document_Version__c</fullName>
    <description>Link to an account&apos;s electronic document.</description>
    <label>Document Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document_Version__c.Current_Active_Version__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document_Version__c</referenceTo>
    <relationshipLabel>Account Documents</relationshipLabel>
    <relationshipName>Account_Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Version__c/Document_Version__c.object-meta.xml
<CustomObject>
    <description>Electronic copy of documents to be sent to accounts for acceptance.</description>
    <label>Document Version</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Version__c/fields/Current_Active_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Active_Version__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this checkbox is checked, then this is the current active version of the document.</description>
    <label>Current Active Version</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Version__c/fields/Document_Text__c.field-meta.xml
<CustomField>
    <fullName>Document_Text__c</fullName>
    <description>The text of the electronic document. Rich text includes images, formatting, etc.</description>
    <label>Document Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Document_Version__c/fields/Version_Date__c.field-meta.xml
<CustomField>
    <fullName>Version_Date__c</fullName>
    <description>Specified date of the document version.</description>
    <label>Version Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_accountDocumentExtension.cls
@IsTest 
public class Test_accountDocumentExtension {

    public static testMethod void testAccountDocumentExtension() {
    
       PageReference pageRef = Page.AccountDocument; 
       Test.setCurrentPageReference(pageRef);
       
        //Create Account
        Account newAccount = new Account (name='Unit Test Account');
        insert newAccount;
       
        //Create Contact
        Contact newContact = new Contact (FirstName='Unit',LastName='Tester',AccountId=newAccount.id);
        insert newContact;
            
        //Create Document Version
        Date myDate = Date.newInstance(2007, 04, 08);
        Document_Version__c newDocVer = new Document_Version__c (Document_Text__c='Unit Test Document Version',Current_Active_Version__c=true,Version_Date__c=myDate);
        insert newDocVer;
        
        //Create Account Document
        Account_Document__c newAcctDoc = new Account_Document__c (Account__c=newAccount.id,Account_Contact__c=newContact.id,Document_Version__c=newDocVer.id);
        insert newAcctDoc;
        
        //Create standard controller
        ApexPages.standardController sc = new ApexPages.standardController(newAcctDoc);
        
        //Create an instance of the controller
        accountDocumentExtension acctDocExt = new accountDocumentExtension(sc);
        
        //Testing scenario
        String redirectPage = acctDocExt.save().getURL();      
        System.assertEquals(redirectPage,'http://www.redwingshoes.com');
    }

}