force-app/main/default/objects/Account_Document__c/Account_Document__c.object-meta.xml
<CustomObject>
    <description>Junction object (many to many relationship) between Document Versions and Accounts. Associates an account to an electronic document.</description>
    <label>Account Document</label>
    <nameField>
        <label>Account Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Documents</relationshipLabel>
    <relationshipName>Account_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Document__c/fields/Account_Contact__c.field-meta.xml
<CustomField>
    <fullName>Account_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the contact on the specified account.</description>
    <label>Account Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Documents</relationshipLabel>
    <relationshipName>Account_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Document__c/fields/Document_Version__c.field-meta.xml
<CustomField>
    <fullName>Document_Version__c</fullName>
    <description>Link to an account&apos;s electronic document.</description>
    <label>Document Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document_Version__c.Current_Active_Version__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document_Version__c</referenceTo>
    <relationshipLabel>Account Documents</relationshipLabel>
    <relationshipName>Account_Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Document__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dealer Agreement</fullName>
            </value>
            <value>
                <fullName>National Accounts Participation Agreement</fullName>
            </value>
            <value>
                <fullName>Price List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Document__c/recordTypes/National_Accounts_Participation_Agreement.recordType-meta.xml
<RecordType>
    <fullName>National_Accounts_Participation_Agreement</fullName>
    <active>true</active>
    <label>NA Participation Agreement</label>
</RecordType>

force-app/main/default/objects/Document_Version__c/Document_Version__c.object-meta.xml
<CustomObject>
    <description>Electronic copy of documents to be sent to accounts for acceptance.</description>
    <label>Document Version</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Version__c/fields/Current_Active_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Active_Version__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this checkbox is checked, then this is the current active version of the document.</description>
    <label>Current Active Version</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Version__c/fields/Version_Date__c.field-meta.xml
<CustomField>
    <fullName>Version_Date__c</fullName>
    <description>Specified date of the document version.</description>
    <label>Version Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_TriggerUpdateAccountDocumentName.cls
@IsTest
public class Test_TriggerUpdateAccountDocumentName {

    // Test creation of Account Document name
    static testMethod void createAccountDocumentName() {

        //Create Account
        Account newAccount = new Account (name='Unit Test Account');
        insert newAccount;

        //Create Contact
        Contact newContact = new Contact (FirstName='Unit',LastName='Tester',AccountId=newAccount.id,email='test@test.com');
        insert newContact;

        //Get Record Type
        RecordType docRt =
            [Select
                Id
                ,Name
             From
                RecordType
             where
                SobjectType='Document_Version__c' and
                DeveloperName='National_Accounts_Participation_Agreement'
             Limit 1];

        RecordType acctDocRt =
            [Select
                Name
             From
                RecordType
             Where
                SobjectType='Account_Document__c'
                And Name != null
             Limit 1];

        //Create Document Version
        Document_Version__c newDocVer = new Document_Version__c (
            Version_Date__c = system.Today()
            ,RecordTypeId=docRt.Id
            ,Current_Active_Version__c=true
        );
        insert newDocVer;

        Test.startTest();
        //Create Account Document
        Account_Document__c newAcctDoc = new Account_Document__c (
            Account__c=newAccount.Id
            ,Account_Contact__c=newContact.Id
            ,Document_Version__c=newDocVer.Id
            ,Record_Type__c = acctDocRt.Name
        );
        insert newAcctDoc;
        Test.stopTest();

        newDocVer = [Select Name From Document_Version__c Where Id = :newDocVer.Id];
        newAcctDoc = [Select Id,Account_Name__c,Name,RecordTypeId From Account_Document__c Where Id = :newAcctDoc.Id];
        System.assertEquals(newAcctDoc.Account_Name__c + ' - ' + newDocVer.Name,newAcctDoc.Name);
        System.assertEquals(acctDocRt.Id,newAcctDoc.RecordTypeId);
      }
  }