force-app/main/default/objects/Account_Document__c/Account_Document__c.object-meta.xml
<CustomObject>
    <description>Junction object (many to many relationship) between Document Versions and Accounts. Associates an account to an electronic document.</description>
    <label>Account Document</label>
    <nameField>
        <label>Account Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Document__c/fields/Document_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Document_Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox is checked when the account has accepted the document electronically.</description>
    <label>Document Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Document__c/fields/Document_Accepted_IP_Address__c.field-meta.xml
<CustomField>
    <fullName>Document_Accepted_IP_Address__c</fullName>
    <description>The IP address from where the electronic document was accepted (signed).</description>
    <label>Document Accepted IP Address</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Document__c/fields/Document_Accpeted_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Document_Accpeted_Date_Time__c</fullName>
    <description>The date/time that the document was electronically accepted (signed).</description>
    <label>Document Accepted Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/accountDocumentExtension.cls
public class accountDocumentExtension {

    private Apexpages.StandardController controller;
    
    public Account_Document__c acctRecord {get;set;}
       
    public accountDocumentExtension(ApexPages.StandardController stdController){
 
         this.controller = stdController;
 
        //Get the IP Address
        String ipAddress = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');  
    
        acctRecord = (Account_Document__c)stdController.getRecord();  
        acctRecord.Document_Accepted__c = true;     
        acctRecord.Document_Accpeted_Date_Time__c = datetime.now(); 
        acctRecord.Document_Accepted_IP_Address__c = ipAddress;                     
    }

    public PageReference save(){
        this.controller.save();
        PageReference newPage = New PageReference('http://www.redwingshoes.com');
        newPage.setRedirect(true);
        return newPage;
    }

}