force-app/main/default/objects/RWfB_Attachment__c/RWfB_Attachment__c.object-meta.xml
<CustomObject>
    <description>Object to house Business Partner Community Attachments for Accounts</description>
    <label>RWfB Attachment</label>
    <nameField>
        <displayFormat>RWFBA-{00000000}</displayFormat>
        <label>RWfB Attachments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWfB Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RWfB_Attachment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account which the RWfB Attachment is related to.</description>
    <inlineHelpText>Account which the RWfB Attachment is related to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RWfB Attachments</relationshipLabel>
    <relationshipName>RWfB_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/fields/Document_for_Credit_Application__c.field-meta.xml
<CustomField>
    <fullName>Document_for_Credit_Application__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the Document should be used in non-RWBAA Credit Application</description>
    <inlineHelpText>Identify if the Document should be used in non-RWBAA Credit Application</inlineHelpText>
    <label>Document for Credit Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if the RWfB Attachment should be public facing. The default is FALSE, not public.</description>
    <inlineHelpText>Determines if the RWfB Attachment should be public facing. The default is FALSE, not public.</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RWfB_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Define the Type of the Attachment.</description>
    <inlineHelpText>Define the Type of the Attachment.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_for_Credit_Application__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company Voucher</fullName>
            </value>
            <value>
                <fullName>Customer Bid Document</fullName>
            </value>
            <value>
                <fullName>Customer Master Service Agreement</fullName>
            </value>
            <value>
                <fullName>Customer Purchase Order</fullName>
            </value>
            <value>
                <fullName>Customer Trade Reference</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Red Wing Program Agreement</fullName>
            </value>
            <value>
                <fullName>Signed Contract</fullName>
            </value>
            <value>
                <fullName>Tax Exempt Certificate</fullName>
            </value>
            <value>
                <fullName>W-9</fullName>
            </value>
            <value>
                <fullName>Customer Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_AttachmentTrigger_Handler.cls
public with sharing class RWS_AttachmentTrigger_Handler {

	private static Id SYS_ADMIN_PROFILE_ID = [select Id from Profile where Name = 'System Administrator'].Id;

	public static void beforeUpdate(List<Attachment> newRecords) {
		//validateChange(newRecords, true);
	}

	public static void beforeDelete(List<Attachment> oldRecords) {
		validateChange(oldRecords, false);
	}

	public static void afterInsert(List<Attachment> newRecords) {
		updateAccount(newRecords);
	}

	public static void afterDelete(List<Attachment> oldRecords) {
		updateAccount(oldRecords);	
	}

	private static void validateChange(List<Attachment> records, Boolean isUpdate) {
		if(UserInfo.getProfileId() == SYS_ADMIN_PROFILE_ID )  return;

		Set<Id> attIds = getAttachmentIds(records);

		List<RWfB_Attachment__c> rwfbList  = getAttachments(attIds);

		if(rwfbList.isEmpty()) return;

		for(Attachment att : records) {
			att.addError('System Administrators can ' + (isUpdate ? 'edit' : 'delete') + ' RWfB Attachments that are flagged as Document for Credit Application');
		}
	}

	private static void updateAccount(List<Attachment> records) {
		List<RWfB_Attachment__c> rwfbList = getAttachments(records);

        if(rwfbList.isEmpty()) return;

        RWS_RWfB_AttachmentTrigger_Handler.updateAccount(rwfbList);
	}

	private static Set<Id> getAttachmentIds(List<Attachment> records) {
		String attKeyPrefix = RWfB_Attachment__c.SObjectType.getDescribe().getKeyPrefix();

		Set<Id> attIds = new Set<Id>();

		for(Attachment att : records) {
			if(String.valueOf(att.ParentId).startsWith(attKeyPrefix)) {
	            attIds.add(att.ParentId);
	        }	
		}

		return attIds;
	}

	private static List<RWfB_Attachment__c> getAttachments(List<Attachment> records) {
		List<RWfB_Attachment__c> rwfbList = new List<RWfB_Attachment__c>();

		Set<Id> attIds = getAttachmentIds(records);

		if(attIds.isEmpty()) return rwfbList;

		rwfbList = getAttachments(attIds);

         return rwfbList;

	}

	private static List<RWfB_Attachment__c> getAttachments(Set<Id> attIds) {
		return [Select Id, Type__c, Public__c,
	            Document_for_Credit_Application__c, Account__c 
            from RWfB_Attachment__c where Document_for_Credit_Application__c = true 
            and Id in :attIds];
	}
}