force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Formula Field to return the Account Number in which a Program&apos;s Price Book Entry is associated with. Used in outbound messaging. 
Field Type: IA 
Integrated: Y</description>
    <formula>Publish_PriceBook__r.Account_Number__c</formula>
    <inlineHelpText>Formula Field to return the Account Number in which a Program&apos;s Price Book Entry is associated with. Used in outbound messaging.</inlineHelpText>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</description>
    <inlineHelpText>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</inlineHelpText>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Published_Date__c.field-meta.xml
<CustomField>
    <fullName>Published_Date__c</fullName>
    <description>Outbound Message Published Date
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Outbound Message Published Date</inlineHelpText>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/Servicing_Store__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Object created to share programs based on servicing level with downstream systems via outbound message</description>
    <label>Servicing Store</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Servicing Store #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Servicing Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicing_Store__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Date/Time that is populated when the Servicing Store record is no longer Active.</description>
    <inlineHelpText>Date/Time that is populated when the Servicing Store record is no longer Active.</inlineHelpText>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/fields/Program_Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Service_Level__c</fullName>
    <label>Program Service Level</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servicing_Store__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RWS_CustomDeleteIterable.cls
/************************************************************************
* Custom Iterable Class - Implements 'Iterable' and 'Iterator' interfaces
*
* @Author: Brandon Willard
* @Date: 10/22/18
************************************************************************/ 
global class RWS_CustomDeleteIterable implements Iterable<SObject>, Iterator<SObject>{ 
    
    //Class variables
    List<SObject> sobjs {get; set;} 
    Integer i {get; set;} 
    
    //Sets the Iterator method of the Iterable interface to this class
    public Iterator<SObject> iterator() { 
        return this; 
    }  
    
    //Constructor
    public RWS_CustomDeleteIterable(){ 
        sobjs = new List<SObject>();

	   //Query for PPBE records 
	   //WHERE filter_number__c is null AND active__c = ‘false'￼ AND Publish_Status__c = 'Deactivated'￼ AND Account_Number__c is not null AND Published_Date__c is not null AND LastModifiedDate < '7 days ago’    
       sobjs.addAll( [SELECT Id FROM Publish_PriceBook_Entry__c WHERE filter_number__c = null AND active__c = false AND Publish_Status__c = 'Deactivated'
                AND Account_Number__c != null AND Published_Date__c != null AND LastModifiedDate = LAST_N_DAYS:7 ]); 
       
       //Query for Servicing Store records 
	   //WHERE active__c = 'false' AND Expiration_Date__c is not null AND Published_Date__c is not null AND ProgramIsActive__c = 'true' AND Program_Service_level_Formula__c like 'Dealer%'
       sobjs.addAll([SELECT Id FROM Servicing_Store__c WHERE active__c = false AND Expiration_Date__c != null 
                			 AND Published_Date__c != null AND Program_Service_Level__c LIKE 'Dealer%' ]);        
       
       //Set i to 0
        i = 0; 
   }   
    
   //generic has next method 
   global boolean hasNext(){ 
       if(i >= sobjs.size()) 
           return false; 
       else 
           return true; 
   }    
   
    //generic next method
   global SObject next(){ 
       i++;        
       return sobjs[i-1]; 
   }
}