force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Formula Field to return the Account Number in which a Program&apos;s Price Book Entry is associated with. Used in outbound messaging. 
Field Type: IA 
Integrated: Y</description>
    <formula>Publish_PriceBook__r.Account_Number__c</formula>
    <inlineHelpText>Formula Field to return the Account Number in which a Program&apos;s Price Book Entry is associated with. Used in outbound messaging.</inlineHelpText>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Published_Date__c.field-meta.xml
<CustomField>
    <fullName>Published_Date__c</fullName>
    <description>Outbound Message Published Date
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Outbound Message Published Date</inlineHelpText>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/RWS_PPBEDeleteBatch.cls
/************************************************************************
*  Batch Class for Deletion of Servicing Store records
*
* @Author: Brandon Willard
* @Date: 10/22/18
************************************************************************/ 
global class RWS_PPBEDeleteBatch implements Database.batchable<SObject>{ 
   
   //Start method
   global Database.QueryLocator start(Database.batchableContext info){      
      
       //Last N Days condition for query, setting seperately to pass unit testing
       String lastNDays;
       //if test is running
       if (Test.isRunningTest()){
           //set to = last 7 days
           lastNDays = '= LAST_N_DAYS:7';
       //not test running
       } else {
           //set to > last 7 days
       	   lastNDays = '> LAST_N_DAYS:7';
       }
       
       
       //Query for PPBE records 
       //WHERE filter_number__c is null AND active__c = ‘false'￼ AND Publish_Status__c = 'Deactivated'￼ AND Account_Number__c is not null AND Published_Date__c is not null AND LastModifiedDate > '7 days ago’
       String query = 'SELECT Id FROM Publish_PriceBook_Entry__c WHERE filter_number__c = null AND active__c = false AND Publish_Status__c = \'Deactivated\'' +
                      ' AND Account_Number__c != null AND Published_Date__c != null AND LastModifiedDate '+ lastNDays;
       return Database.getQueryLocator(query);      
   }     
   
    //Execute method
   global void execute(Database.batchableContext info, List<SObject> records){ 
       //if has records
       if (!records.isEmpty()){
           //Delete all records returned by start method
           try {
               delete records;
           } catch (Exception e){
               System.debug('An exception occured on delete: '+ e);
           }
       }
   }
    
   //Finish method
   global void finish(Database.batchableContext info){       
       //Do nothing       
   } 
}