force-app/main/default/objects/Contact/fields/Do_Not_Send_Surveys__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Surveys__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to flag contacts that do not want to receive surveys.</description>
    <label>Do Not Send Surveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Send_Annual_Survey__c.field-meta.xml
<CustomField>
    <fullName>Send_Annual_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Works in conjunction with the annual survey batch process and workflow and should NOT be deleted.</description>
    <label>Send Annual Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_Count__c.field-meta.xml
<CustomField>
    <fullName>Survey_Count__c</fullName>
    <description>Holds the count of the number of surveys that have been sent to a contact in a 12 month period.</description>
    <inlineHelpText>This is a calculated field.</inlineHelpText>
    <label>Survey Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_Threshold_Reached__c.field-meta.xml
<CustomField>
    <fullName>Survey_Threshold_Reached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field gets checked to TRUE when the survey threshold value has been reached for the number of surveys sent out in a 12 month period.</description>
    <label>Survey Threshold Reached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SurveySendAnnuallyBatch.cls
global class SurveySendAnnuallyBatch implements Database.Batchable<sObject> {

    public string query = 'Select Id, Send_Annual_Survey__c, (Select Id, CreatedDate From Tasks where Subject LIKE \'Email: Red Wing Shoes Survey%\' order by CreatedDate desc limit 1) From Contact where Do_Not_Send_Surveys__c = false AND HasOptedOutOfEmail = false AND Active__c = true';
    
    global database.querylocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, Sobject[] scope)
    {
        List<Contact> contactsToUpdate = new List<Contact>();
                
        for (sObject s : scope) {
            Contact c = (Contact)s;
            Task[] arrTasks = c.Tasks;
            if(arrTasks.isEmpty()) {
                c.Send_Annual_Survey__c = true;
                contactsToUpdate.add(c);
            }
            for(Task t : c.Tasks) {
                if(t.CreatedDate < system.today().addDays(-365)) {
                    c.Send_Annual_Survey__c = true;
                    c.Survey_Count__c = 0;
                    c.Survey_Threshold_Reached__c = false;
                    ContactsToUpdate.add(c);
                }
            }
        }
        
        if(!contactsToUpdate.isEmpty() && contactsToUpdate.size() > 0) {
            update contactsToUpdate;
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }

}