force-app/main/default/objects/Features__c/Features__c.object-meta.xml
<CustomObject>
    <description>Features for Products in Salesforce.  Updated with Integration.
Object Type: IA
Integrated: Y</description>
    <label>Features</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Features__c/fields/Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Feature_Name__c</fullName>
    <description>Name of a Feature
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Name of a Feature</inlineHelpText>
    <label>Feature Name</label>
    <length>63</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Features__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to IA Feature Object.  IA Features are those displayed in the Community. This associates a feature with an IA Feature.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to IA Feature Object.  IA Features are those displayed in the Community.  This associates a feature with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Features__c/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>External Id for MuleSoft
Field Type: IA
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id for MuleSoft.  Updated with integration.</inlineHelpText>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Features__c/fields/RWS_Last_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>RWS_Last_Updated_Date__c</fullName>
    <description>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.  Updated by integration.</inlineHelpText>
    <label>RWS Last Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Feature__c/fields/Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Feature_Name__c</fullName>
    <description>The name displayed in the Product Selection visualforce page. (i.e. Steel Toe).
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The name displayed in the Product Selection visualforce page. (i.e. Steel Toe).</inlineHelpText>
    <label>Feature Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>External Id for MuleSoft.
Field Type: IA
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id for MuleSoft.</inlineHelpText>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/RWS_Last_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>RWS_Last_Updated_Date__c</fullName>
    <description>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue. Updated via integration.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.  Updated via integration.</inlineHelpText>
    <label>RWS Last Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product_Features__c/Product_Features__c.object-meta.xml
<CustomObject>
    <description>Junction object which manages the many to many relationship between Product object and the Features object. Maintained via integration. 
Object Type: IA 
Integrated: Y</description>
    <label>Product Features</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>Product Feature Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Features__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <description>Lookup field (master-detail) to the Feature object.  Used to associate a Product to a Feature.  Maintained by integration.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup field to the Feature object.  Used to associate a Product to a Feature.  Maintained by integration</inlineHelpText>
    <label>Feature</label>
    <referenceTo>Features__c</referenceTo>
    <relationshipLabel>Product Features</relationshipLabel>
    <relationshipName>Product_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Features__c/fields/Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Feature_Name__c</fullName>
    <description>Formula field to display the feature name from the Features object. 
Field Type: IA
Integrated: N/A</description>
    <formula>Feature__r.Feature_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula field to display the feature name from the Features object.</inlineHelpText>
    <label>Feature Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Features__c/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>External Id for MuleSoft.
Field Type: IA
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id for MuleSoft</inlineHelpText>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Features__c/fields/RWS_Last_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>RWS_Last_Updated_Date__c</fullName>
    <description>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.</inlineHelpText>
    <label>RWS Last Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Used in apex to match to the style number unique id on the Product object.  Updated via apex.
Field Type: IA
Integrated: N</description>
    <externalId>true</externalId>
    <inlineHelpText>Used in apex to match to the style number unique id on the Product object. Updated via apex.</inlineHelpText>
    <label>Style Number Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/Product_Style_Features__c.object-meta.xml
<CustomObject>
    <description>Junction object which manages the many to many relationship between unique styles (Product Style Object) and the Features object. Records are created / updated via apex. Does not need to be maintained via integration. 
Object Type: IA 
Integrated: N</description>
    <label>Product Style Features</label>
    <nameField>
        <displayFormat>PSF-{000000}</displayFormat>
        <label>Product Style Feature #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Style Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style_Features__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Feature object.  Used to associate a Product Style to a Feature.  Maintained by apex.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup field to the Feature object.  Used to associate a Product Style to a Feature.</inlineHelpText>
    <label>Feature</label>
    <referenceTo>Features__c</referenceTo>
    <relationshipLabel>Product Style Features</relationshipLabel>
    <relationshipName>Product_Style_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/fields/Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Feature_Name__c</fullName>
    <formula>Feature__r.Feature_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Feature Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Product Style object. Used to associate a Product Style to a Feature. Maintained by apex. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup field to the Product Style object. Used to associate a Product Style to a Feature.</inlineHelpText>
    <label>Product Style</label>
    <referenceTo>Product_Style__c</referenceTo>
    <relationshipLabel>Product Style Features</relationshipLabel>
    <relationshipName>Product_Style_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/fields/RWS_Last_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>RWS_Last_Updated_Date__c</fullName>
    <description>Date/Time to identify RWS Integration Last Updated Date</description>
    <label>RWS Last Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Reference related Product Style Unique Style Id</description>
    <formula>Product_Style__r.Style_Number_Unique_ID__c</formula>
    <label>Style Number Unique ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductStyleFeaturesController.cls
@RestResource(urlMapping='/PrdStyFeatures')
global with sharing class ProductStyleFeaturesController {
    
    @TestVisible global class IAFeaturesJunction {
           public String FeatureID;
        }
    
    @TestVisible
    @HttpPost
    global static String createFeatureJunction(String SFDC_ProductID, String UPC, String styleNumber, String styleNumberId, String retailSku,
                                               String brandCode, String genderCode, String retailClassCode, String countryOfOriginId,
                                               DateTime RWS_Last_Updated_Date,List<IAFeaturesJunction> IAFeaturesJunction) 
    {
            RestResponse res = RestContext.response;
            res.addHeader('Content-Type', 'application/json');
            String jsonResponse = '';            
        try{
            //String SFDC_Id;   
            String PS_Id;
            String PS_SUId; //Style Unique ID from ProductStyle Object
            //List<Product2> SFDC_Prod_ID = [SELECT Id FROM Product2 where RWS_Id__c = :UPC LIMIT 1 FOR UPDATE];              
            //System.debug('SFDC Product ID 1:-' + UPC + SFDC_Prod_ID + SFDC_Prod_ID.size());
            //if(SFDC_Prod_ID.size() > 0)
            //{
                //for (Product2 SFDC_Prod: SFDC_Prod_ID)
                //{
                  // SFDC_Id = SFDC_Prod.Id;
                   //System.debug('SFDC Product ID:-' + SFDC_Id);
                //}
                List <Product_Style__c> prdStyId= [SELECT Id, Style_Number_Unique_ID__c  FROM Product_Style__c where Style_Number_Unique_ID__c = :styleNumberId and IsDeleted = false LIMIT 1 FOR UPDATE];
                System.debug('SFDC Style SF Size:-' + prdStyId.size() + prdStyId);
                if(prdStyId.size() > 0)
                {
                    for(Product_Style__c PS: prdStyId)
                    {
                        PS_Id = PS.Id;
                        PS_SUId = PS.Style_Number_Unique_ID__c;
                     }
            
                    //FeatureJunction add list
                       // List<Product_Features__c> ProductFeaturesList = new List<Product_Features__c>();
                     List<Product_Style_Features__c> ProductStyleFeaturesList = new List<Product_Style_Features__c>();
                     List<Product_Style_Features__c> Delete_PSFList = new List<Product_Style_Features__c>();
                    //For each IAFeature
                        Map<String,String> FeaturesMap = new Map<String,String>();
                        for(IAFeaturesJunction IAFeatureId : IAFeaturesJunction)
                        {
                            FeaturesMap.put(IAFeatureId.FeatureID, IAFeatureId.FeatureID + '-' + UPC);
                        }
                            FeaturesMap.put(brandCode, brandCode + '-' + UPC);
                            FeaturesMap.put(genderCode, genderCode + '-' + UPC);
                            FeaturesMap.put('C' + retailClassCode, 'C' + retailClassCode + '-' + UPC);
                            FeaturesMap.put(countryOfOriginId, countryOfOriginId + '-' + UPC);
                    
                            //System.debug('IA Feat' + IAFeaturesJunctionMap.keySet() + '-' + IAFeaturesJunctionMap.values());
                            List<Product_Style_Features__c>  prdStyFeatId = [SELECT  Id,Feature_Name__c, Feature__c, RWS_Last_Updated_Date__c ,Style_Number_Unique_ID__c, IsDeleted FROM Product_Style_Features__c where Product_Style__c  = :PS_Id and IsDeleted = false order by RWS_Last_Updated_Date__c DESC];//= 'a2YW0000000M7DGMA0'];                  
                    		System.debug('PSF Ids with Deleted field: ' + prdStyFeatId);
                                 Set<String> prdStyFeatIdSet = new Set<String>();
                    			 Map<String,String> prdStyFeatIdMap = new Map<String,String>();
                    			 datetime PSFDt;
                            if(prdStyFeatId.size() > 0)
                            {
                    			PSFDt = prdStyFeatId[0].RWS_Last_Updated_Date__c;
                    			System.debug('PSF Date ' + PSFDt);
                                for(Product_Style_Features__c SF : prdStyFeatId)
                                {
                                    //prdStyFeatIdMap.put(SF.Feature__c, SF.Feature_Name__c);
                                    prdStyFeatIdSet.add(SF.Feature__c);
                                    prdStyFeatIdMap.put(SF.Feature__c,SF.Id);
                                }
                            }
                    			List<Features__c> featuresList = [SELECT IA_Feature__c,Id,RWS_Id__c, Feature_Name__c  FROM Features__c WHERE RWS_Id__c in :FeaturesMap.keySet() and (RWS_Id__c <> '' and RWS_Id__c  <> null) and IsDeleted = false FOR UPDATE];
                                    Map<String,String> ItemFeatListMap = new Map<String,String>();
                                    Set<String> ItemFeatListSet = new Set<String>();
                                    //ItemFeatListSet.add(featuresList);
                            if(featuresList.size() > 0)
                            {
                                for(Features__c Fea : featuresList)
                                {
                                    ItemFeatListMap.put(Fea.RWS_Id__c, Fea.Id);
									System.debug('Item Feat List MAP' + ItemFeatListMap);
                                    ItemFeatListSet.add(Fea.Id);
                                }
                                System.debug('Features readly list size' + featuresList.size());
                                //Map<String,String> prdStyFeatIdMap = new Map<String,String>();
                                System.debug('Prod Style Feat ID list ' + prdStyFeatId);
                                if(prdStyFeatId.size() > 0 && PSFDt != null && RWS_Last_Updated_Date != null)
                                {
                                     if(PSFDt < RWS_Last_Updated_Date)
                                     {
                                        if(prdStyFeatId.size() > 0)
                                        {
                                          //  if(prdStyFeatId.size() == featuresList.size())
                                            //{
                                              //  System.debug('Both objects are equal ' + prdStyFeatId.size() + ', ' + featuresList.size());
                                              //  res.statusCode = 200;
                                              //  jsonResponse = '{"response": {"status": "Success", "message": "Features are upto date."}}';
                                              //  res.responseBody = blob.valueOf(jsonResponse);
                                            //}
                                            //else
                                            //{
                                                for(String IFea : ItemFeatListSet)
                                                {
                                                    System.debug('Item Fea ' + IFea);  
                                                    if(!prdStyFeatIdSet.contains(IFea))
                                                    {
                                                        System.debug('Item Fea not in Prod Style Feat ' + IFea);     
                                                        Product_Style_Features__c PSF = new Product_Style_Features__c(
                                                            Feature__c = IFea,
                                                            Product_Style__c = PS_Id,
                                                            RWS_Last_Updated_Date__c = RWS_Last_Updated_Date
                                                            );
                                                         //generate list for upsert                      
                                                        ProductStyleFeaturesList.add(PSF);
                                                    } 
                                                }
                                                for(String PSFea : prdStyFeatIdSet)
                                                {
                                                    System.debug('PS Fea ' + PSFea);  
                                                    if(!ItemFeatListSet.contains(PSFea))
                                                    {
                                                        System.debug('Prod Style Feat not in Item ' + PSFea);     
                                                        Product_Style_Features__c Delete_PSF = new Product_Style_Features__c(
                                                            Id = prdStyFeatIdMap.get(PSFea)
                                                            /*IsDeleted = true
                                                            Feature__c = PSFea,
                                                            Product_Style__c = PS_Id,
                                                            RWS_Last_Updated_Date__c = RWS_Last_Updated_Date*/
                                                            );
                                                         //generate list for Delete                      
                                                        Delete_PSFList.add(Delete_PSF);     
                                                        System.debug('Prod Style Feat delete list is ready ' + prdStyFeatIdMap.get(PSFea));
                                                    } 
                                                }
                                            //}
                                        }
                                        else
                                        {
                                            for(Features__c feat: featuresList)
                                            {
                                                if(String.isNotEmpty(feat.Id))
                                                {
                                                    Product_Style_Features__c PSF = new Product_Style_Features__c(
                                                        Feature__c = feat.Id,
                                                        Product_Style__c = PS_Id,
                                                        RWS_Last_Updated_Date__c = RWS_Last_Updated_Date
                                                    );
                                                     //generate list for upsert                      
                                                    ProductStyleFeaturesList.add(PSF);
                                                }
                                            }                                       
                                        }
                                     }
                                     else
                                     {
                                         List<String> a = new List<String>{brandCode,genderCode,retailClassCode,countryOfOriginId};
										 System.debug('list:' + a );                                                                                  
                                         for(String ILD : a)
                                         {
                                        	System.debug('For list:' + ILD);                                         
                                             if (ItemFeatListMap.containsKey(ILD) && ILD != null && prdStyFeatIdMap.containsKey(ItemFeatListMap.get(ILD)))
                                             {
                                                 System.debug('No Action needed for item level features: ' + ILD + '-' + ItemFeatListMap.get(ILD) + '-' + prdStyFeatIdMap.get(ItemFeatListMap.get(ILD)));
                                                 /*Product_Style_Features__c PSF = new Product_Style_Features__c(
                                                        Feature__c = ItemFeatListMap.get(ILD),
                                                        Product_Style__c = PS_Id,
                                                        RWS_Last_Updated_Date__c = RWS_Last_Updated_Date
                                                    );
                                                     //generate list for upsert                      
                                                    ProductStyleFeaturesList.add(PSF);
                                                    System.debug('Prod Style Feat @ equal list is ready ' + ProductStyleFeaturesList);
													*/
                                             }
                                             else if (ItemFeatListMap.containsKey(ILD) && ILD != null && !prdStyFeatIdMap.containsKey(ItemFeatListMap.get(ILD)))
                                             {
                                                 Product_Style_Features__c PSF = new Product_Style_Features__c(
                                                        Feature__c = ItemFeatListMap.get(ILD),
                                                        Product_Style__c = PS_Id,
                                                        RWS_Last_Updated_Date__c = RWS_Last_Updated_Date
                                                    );
                                                     //generate list for upsert                      
                                                    ProductStyleFeaturesList.add(PSF);
                                                    System.debug('Prod Style Feat @ equal list is ready ' + ProductStyleFeaturesList);
                                             }
                                             else if (!ItemFeatListMap.containsKey(ILD) && ILD != null && Delete_PSFList.size() == 0)
                                             {
                                                 System.debug('Clear Delete list: ' + Delete_PSFList);
                                                 //Delete_PSFList.clear();
                                                 System.debug('PS Fea ' + prdStyFeatIdSet);
                                                for(String PSFea : prdStyFeatIdSet)
                                                {
                                                    System.debug('PS Fea ' + PSFea);  
                                                    if(!ItemFeatListSet.contains(PSFea))
                                                    {
                                                        System.debug('Prod Style Feat not in Item ' + PSFea);     
                                                        Product_Style_Features__c Delete_PSF = new Product_Style_Features__c(
                                                            Id = prdStyFeatIdMap.get(PSFea)
                                                            );
                                                         //generate list for Delete                      
                                                        Delete_PSFList.add(Delete_PSF);     
                                                        System.debug('Prod Style Feat delete list is ready ' + prdStyFeatIdMap.get(PSFea));
                                                    } 
                                                }
                                             }
                                         }
                                         /*System.debug('Both objects are equal ' + prdStyFeatId.size() + ', ' + featuresList.size());
                                         res.statusCode = 200;
                                         jsonResponse = '{"response": {"status": "Success", "message": "Both objects are equal Features are up to date."}}';
                                         res.responseBody = blob.valueOf(jsonResponse);
										*/
                                     }
                                }
                                else
                                {
                                	for(Features__c feat: featuresList)
                                    {
                                        delete prdStyFeatId;
                                        System.debug('Deleted PSF');
                                        if(String.isNotEmpty(feat.Id))
                                        {
                                            Product_Style_Features__c PSF = new Product_Style_Features__c(
                                                Feature__c = feat.Id,
                                                Product_Style__c = PS_Id,
                                                RWS_Last_Updated_Date__c = RWS_Last_Updated_Date
                                            );
                                            //generate list for upsert                      
                                            ProductStyleFeaturesList.add(PSF);
                                        }
                                    }                                       
                                }
                           }
                    //Final Process
                    if(ProductStyleFeaturesList.size() > 0 && Delete_PSFList.size() > 0)
                    {
                        delete Delete_PSFList;
                        insert ProductStyleFeaturesList;
                        //Create success response message
                        res.statusCode = 200;
                        jsonResponse = '{"response": {"status": "Success", "message": "Successfully inserted & deleted features."}}';
                        res.responseBody = blob.valueOf(jsonResponse);
                    }
                    else if(ProductStyleFeaturesList.size() == 0 && Delete_PSFList.size() == 0)
                    {
                       res.statusCode = 200;
                       jsonResponse = '{"response": {"status": "Success", "message": "Features are upto date."}}';
                       res.responseBody = blob.valueOf(jsonResponse); 
                    } 
                    else if(ProductStyleFeaturesList.size() > 0 && Delete_PSFList.size() == 0)
                    {
                        insert ProductStyleFeaturesList;
                        //Create success response message
                        res.statusCode = 200;
                        jsonResponse = '{"response": {"status": "Success", "message": "Successfully inserted features."}}';
                        res.responseBody = blob.valueOf(jsonResponse);
                    }
                    else if(ProductStyleFeaturesList.size() == 0 && Delete_PSFList.size() > 0)
                    {
                        delete Delete_PSFList;
                        //Create success response message
                        res.statusCode = 200;
                        jsonResponse = '{"response": {"status": "Success", "message": "Successfully deleted invalid feature records."}}';
                        res.responseBody = blob.valueOf(jsonResponse);
                    }     
                }
                else
                {
                    res.statusCode = 201;
                    //jsonResponse = Json.serialize('{"response": {"status": "Bad Request", "message": "UPC Not found."}}');
                    jsonResponse = '{"response": {"status": "Bad Request", "message": "Style Unique ID "' + styleNumberId + '"not found in Product Style Object."}}';
                    res.responseBody = blob.valueOf(jsonResponse);
                }
            //}
            //else
              //  {
                //    res.statusCode = 201;
                    //jsonResponse = Json.serialize('{"response": {"status": "Bad Request", "message": "UPC Not found."}}');
                  //  jsonResponse = '{"response": {"status": "Bad Request", "message": "UPC Not found."}}';
                  //  res.responseBody = blob.valueOf(jsonResponse);
                //}
            return jsonResponse;
        }
        catch(exception ex) {
            //Create failure response message
            res.statusCode = 500;
            jsonResponse = '{"response": {"status": "Failure", "message": "Internal Server Error --> " ' + ex + '}}';
            res.responseBody = blob.valueOf(jsonResponse);                                 
            return jsonResponse;
        }
    }
}