force-app/main/default/objects/Features__c/Features__c.object-meta.xml
<CustomObject>
    <description>Features for Products in Salesforce.  Updated with Integration.
Object Type: IA
Integrated: Y</description>
    <label>Features</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Features__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to IA Feature Object.  IA Features are those displayed in the Community. This associates a feature with an IA Feature.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to IA Feature Object.  IA Features are those displayed in the Community.  This associates a feature with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Features__c/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>External Id for MuleSoft
Field Type: IA
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id for MuleSoft.  Updated with integration.</inlineHelpText>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Features__c/fields/RWS_Last_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>RWS_Last_Updated_Date__c</fullName>
    <description>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.  Updated by integration.</inlineHelpText>
    <label>RWS Last Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Feature__c/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>External Id for MuleSoft.
Field Type: IA
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id for MuleSoft.</inlineHelpText>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/RWS_Last_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>RWS_Last_Updated_Date__c</fullName>
    <description>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue. Updated via integration.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.  Updated via integration.</inlineHelpText>
    <label>RWS Last Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product_Features__c/Product_Features__c.object-meta.xml
<CustomObject>
    <description>Junction object which manages the many to many relationship between Product object and the Features object. Maintained via integration. 
Object Type: IA 
Integrated: Y</description>
    <label>Product Features</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>Product Feature Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Features__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <description>Lookup field (master-detail) to the Feature object.  Used to associate a Product to a Feature.  Maintained by integration.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup field to the Feature object.  Used to associate a Product to a Feature.  Maintained by integration</inlineHelpText>
    <label>Feature</label>
    <referenceTo>Features__c</referenceTo>
    <relationshipLabel>Product Features</relationshipLabel>
    <relationshipName>Product_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Features__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Product object.  Used to associate a Product to a Feature.  Maintained by integration.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup field to the Product object.  Used to associate a Product to a Feature.  Maintained by integration.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Features</relationshipLabel>
    <relationshipName>Product_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Features__c/fields/RWS_Id__c.field-meta.xml
<CustomField>
    <fullName>RWS_Id__c</fullName>
    <description>External Id for MuleSoft.
Field Type: IA
Integrated: Y</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id for MuleSoft</inlineHelpText>
    <label>RWS Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Features__c/fields/RWS_Last_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>RWS_Last_Updated_Date__c</fullName>
    <description>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to eliminate overwriting the latest item data with old item data if any old message flows from the queue.</inlineHelpText>
    <label>RWS Last Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ProductFeaturesController.cls
@RestResource(urlMapping='/IAFeatures')
global with sharing class ProductFeaturesController  {
    
    @TestVisible global class IAFeaturesJunction {
           public String FeatureID;
        }
    
    @TestVisible
    @HttpPost
    global static String createFeatureJunction(String SFDC_ProductID, String UPC, String brandCode, String genderCode, String retailClassCode, String countryOfOriginId,
                                               DateTime RWS_Last_Updated_Date,List<IAFeaturesJunction> IAFeaturesJunction) 
    {
            RestResponse res = RestContext.response;
            res.addHeader('Content-Type', 'application/json');
            String jsonResponse = '';
            
        try{
            List<Product2> SFDC_Prod_ID = [SELECT Id FROM Product2 where RWS_Id__c = :UPC LIMIT 1];
            String SFDC_Id;            
            //System.debug('SFDC Product ID 1:-' + UPC + SFDC_Prod_ID + SFDC_Prod_ID.size());
            if(SFDC_Prod_ID.size() > 0)
            {
            for (Product2 SFDC_Prod: SFDC_Prod_ID)
            {
               SFDC_Id = SFDC_Prod.Id;
               //System.debug('SFDC Product ID:-' + SFDC_Id);
            }
                List<Product_Features__c> deleteFeatures = [SELECT Id FROM Product_Features__c WHERE Product__c = :SFDC_Prod_ID];
                //System.debug('Delete Features:-' + deleteFeatures);
                delete deleteFeatures;
            
            //FeatureJunction add list
                List<Product_Features__c> ProductFeaturesList = new List<Product_Features__c>();
            
            //For each IAFeature
                Map<String,String> IAFeaturesJunctionMap = new Map<String,String>();
                for(IAFeaturesJunction IAFeatureId : IAFeaturesJunction)
                {
                    IAFeaturesJunctionMap.put(IAFeatureId.FeatureID, IAFeatureId.FeatureID + '-' + UPC);
                }
                    IAFeaturesJunctionMap.put(brandCode, brandCode + '-' + UPC);
                    IAFeaturesJunctionMap.put(genderCode, genderCode + '-' + UPC);
                    IAFeaturesJunctionMap.put('C' + retailClassCode, 'C' + retailClassCode + '-' + UPC);
                    IAFeaturesJunctionMap.put(countryOfOriginId, countryOfOriginId + '-' + UPC);
            
                    //System.debug('IA Feat' + IAFeaturesJunctionMap.keySet() + '-' + IAFeaturesJunctionMap.values());
                    List<Features__c> featuresList = [SELECT IA_Feature__c,Id,RWS_Id__c FROM Features__c WHERE RWS_Id__c in :IAFeaturesJunctionMap.keySet() and (RWS_Id__c <> '' and RWS_Id__c  <> null)];
                    if(featuresList.size() > 0){
                            System.debug(featuresList.size());
                        //Loop through Features
                            for(Features__c fea: featuresList){
                                System.debug('Fet ID: ' + fea.Id + ' MAP RWS ID: ' + IAFeaturesJunctionMap.get(fea.RWS_Id__c));
                                if(String.isNotEmpty(fea.Id)){
                                    Product_Features__c prodFea = new Product_Features__c(
                                        Feature__c = fea.Id,
                                        Product__c = SFDC_Id, 
                                        RWS_Id__c = IAFeaturesJunctionMap.get(fea.RWS_Id__c),
                                        RWS_Last_Updated_Date__c = RWS_Last_Updated_Date);
                                    //generate list for upsert                      
                                    ProductFeaturesList.add(prodFea);
                                }
                        }  
                    }
            if(ProductFeaturesList.size() > 0)
            {
                insert ProductFeaturesList;
            }
            //Create success response message
            res.statusCode = 201;
            jsonResponse = Json.serialize('{"response": {"status": "Success", "message": "Successfully inserted records."}}');
            res.responseBody = blob.valueOf(jsonResponse);
        }
            else{
                    res.statusCode = 201;
                    jsonResponse = Json.serialize('{"response": {"status": "Bad Request", "message": "UPC Not found."}}');
                    res.responseBody = blob.valueOf(jsonResponse);
            }
            return jsonResponse;
        }
        catch(exception ex) {
            //Create failure response message
            res.statusCode = 500;
            jsonResponse = Json.serialize('{"response": {"status": "Failure", "message": "Internal Server Error --> " ' + ex + '}}');
            res.responseBody = blob.valueOf(jsonResponse);                                 
            return jsonResponse;
        }
    }
}