force-app/main/default/objects/Features__c/Features__c.object-meta.xml
<CustomObject>
    <description>Features for Products in Salesforce.  Updated with Integration.
Object Type: IA
Integrated: Y</description>
    <label>Features</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Features__c/fields/Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Feature_Name__c</fullName>
    <description>Name of a Feature
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Name of a Feature</inlineHelpText>
    <label>Feature Name</label>
    <length>63</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Features__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to IA Feature Object.  IA Features are those displayed in the Community. This associates a feature with an IA Feature.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to IA Feature Object.  IA Features are those displayed in the Community.  This associates a feature with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/Filter_Criteria__c.object-meta.xml
<CustomObject>
    <description>Stores IA Features selected when creating a program.  A filters is often referred to as a &quot;price rule&quot;.  Records are created in this object via apex.  A new record is created when a user selects products in the product selection visualforce page.  
Object Type: IA
Integrated: N</description>
    <label>Filter Criteria</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Filter Criteria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filter Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Criteria__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>A formula field to bring in the category of the IA Feature.
Field Type: IA
Integrated: N</description>
    <formula>TEXT(IA_Feature__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A formula field to bring in the category of the IA Feature.</inlineHelpText>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used to associate filter criteria records with one another.  (i.e. if 3 filter criteria records have the same filter number they all go together and make up a &quot;price rule&quot;)</inlineHelpText>
    <label>Filter Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Lookup to the IA Feature object.  Associates a filter criteria record with an IA Feature.</inlineHelpText>
    <label>IA Feature</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filter_Criteria__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Program object. Associates a filter criteria record with a Program. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup to the Program object. Associates a filter criteria record with a Program.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Filter Criteria</relationshipLabel>
    <relationshipName>Filter_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/IA_Feature__c.object-meta.xml
<CustomObject>
    <description>Object for the features displayed in the IA2.0 Product Selection visualforce pages
Object Type: IA
Integrated: Y</description>
    <label>IA Feature</label>
    <nameField>
        <label>Red Wing ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Feature__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Product Category for the IA Feature.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Product Category for the IA Feature.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Workwear</fullName>
            </value>
            <value>
                <fullName>Outside Lines</fullName>
            </value>
            <value>
                <fullName>Accessories Apparel and Gear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Feature_Name__c</fullName>
    <description>The name displayed in the Product Selection visualforce page. (i.e. Steel Toe).
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The name displayed in the Product Selection visualforce page. (i.e. Steel Toe).</inlineHelpText>
    <label>Feature Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/Parent_IA_Feature__c.field-meta.xml
<CustomField>
    <fullName>Parent_IA_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to associate an IA Feature with a Parent IA Feature.  Lookup within the same IA Feature object.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Used to associate an IA Feature with a Parent IA Feature.  Lookup within the same IA Feature object.</inlineHelpText>
    <label>Red Wing Parent ID</label>
    <referenceTo>IA_Feature__c</referenceTo>
    <relationshipLabel>IA Feature</relationshipLabel>
    <relationshipName>IA_Feature</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/Selectable__c.field-meta.xml
<CustomField>
    <fullName>Selectable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked (TRUE) this feature can be selected in the product selection visualforce page (it has a checkbox).
If unchecked (FALSE) the feature cannot be selected (i.e. a header / parent)
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked (TRUE) this feature can be selected in the product selection visualforce page.
If unchecked (FALSE) the feature cannot be selected (i.e. a header / parent)</inlineHelpText>
    <label>Selectable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IA_Feature__c/fields/Tandem__c.field-meta.xml
<CustomField>
    <fullName>Tandem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Tandem, an additional Filter that is not flagged as Tandem must be selected. This is used for filters that will return large number of Products.</description>
    <inlineHelpText>If Tandem, an additional Filter that is not flagged as Tandem must be selected. This is used for filters that will return large number of Products.</inlineHelpText>
    <label>Tandem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Used in apex to match to the category on the Product object. Updated via apex.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used in apex to match to the category on the Product object. Updated via apex.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Workwear</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Accessories Apparel and Gear</fullName>
            </value>
            <value>
                <fullName>Outside Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Style__c/fields/Item_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Status_Code__c</fullName>
    <description>Rollup for the related Product Item Status Code (populated with the lowest possible value)</description>
    <inlineHelpText>Rollup for the related Product Item Status Code (populated with the lowest possible value)</inlineHelpText>
    <label>Item Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/Product_Style_Features__c.object-meta.xml
<CustomObject>
    <description>Junction object which manages the many to many relationship between unique styles (Product Style Object) and the Features object. Records are created / updated via apex. Does not need to be maintained via integration. 
Object Type: IA 
Integrated: N</description>
    <label>Product Style Features</label>
    <nameField>
        <displayFormat>PSF-{000000}</displayFormat>
        <label>Product Style Feature #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Style Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style_Features__c/fields/Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Feature_Name__c</fullName>
    <formula>Feature__r.Feature_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Feature Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style_Features__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Product Style object. Used to associate a Product Style to a Feature. Maintained by apex. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup field to the Product Style object. Used to associate a Product Style to a Feature.</inlineHelpText>
    <label>Product Style</label>
    <referenceTo>Product_Style__c</referenceTo>
    <relationshipLabel>Product Style Features</relationshipLabel>
    <relationshipName>Product_Style_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Auto_Add_Products__c.field-meta.xml
<CustomField>
    <fullName>Auto_Add_Products__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If TRUE your price book is automatically updated with new products that meet stored filter criteria. EXAMPLE: a program for Red Wing &amp; Steel Toe and a new product product is manufactured that is Red Wing &amp; Steel Toe it will be added to your price book.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If TRUE your price book is automatically updated with new products that meet stored filter criteria. EXAMPLE: a program for Red Wing &amp; Steel Toe and a new product product is manufactured that is Red Wing &amp; Steel Toe it will be added to your price book.</inlineHelpText>
    <label>Auto Add Products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Auto_Update_Price__c.field-meta.xml
<CustomField>
    <fullName>Auto_Update_Price__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If TRUE your price books is automatically adjusted with MSRP changes.  EXAMPLE:  If you had 20% off Red Wing and the MSRP increases; your 20% remains but it is off the new MSRP.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If TRUE your price book is automatically adjusted with MSRP changes.  EXAMPLE:  If you had 20% off Red Wing and the MSRP increases; your 20% remains but it is off the new MSRP.</inlineHelpText>
    <label>Auto Update Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Publish Pricebook record directly to the Program</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_Production_Selection_Controller_Test.cls
@isTest
private class RWS_Production_Selection_Controller_Test {

    @TestSetup
    static void setupData() { 
        Id rtId = RWS_TestUtil.getRecordTypeIdByDeveloperName('Business_Partner_Community', 'Account');
        Account acc = RWS_TestUtil.createAccount(rtId, true);
        Program__c pr = RWS_TestUtil.createProgram(acc.Id, true);
        Id pricebookId = Test.getStandardPricebookId();

        List<Product2> prod_lst = new List<Product2>();
        Product2 fw1 = RWS_TestUtil.createProductwithDetail('Footwear Prod 1','Footwear',false);
        fw1.ProductCode = '0001';
        fw1.Item_Status_Code__c = '20';
        fw1.Item_Status__c = 'Active';

        Product2 fw2 = RWS_TestUtil.createProductwithDetail('Footwear Prod 1','Footwear',false);
        fw2.ProductCode = '0001';
        fw2.Item_Status_Code__c = '80';
        fw2.Item_Status__c = 'Active';

        prod_lst.add(fw1);
        prod_lst.add(fw2);

        prod_lst.add(RWS_TestUtil.createProductwithDetail('Accessories Prod 1','Accessories Apparel and Gear', false));
        prod_lst.add(RWS_TestUtil.createProductwithDetail('Workwear Prod 1','Workwear', false));
        prod_lst.add(RWS_TestUtil.createProductwithDetail('OL Prod 1','Outside Lines', false));
        insert prod_lst;

        //List<Product_Style__c> styles = [select Id from Product_Style__c];

        List<PriceBookEntry> pricebookentry_lst = new List<Pricebookentry>();
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[0].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[1].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[2].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[3].Id, false));
        pricebookentry_lst.add(RWS_TestUtil.createPricebookEntry(pricebookId, prod_lst[4].Id, false));
        insert pricebookentry_lst;

        List<IA_Feature__c> Iafeature_lst1 = new List<IA_Feature__c>();
        Iafeature_lst1.add(RWS_TestUtil.createIAFeature('Brand',null, 'Footwear', false, false));
        Iafeature_lst1.add(RWS_TestUtil.createIAFeature('Color',null, 'Accessories Apparel and Gear', false, false));
        Iafeature_lst1.add(RWS_TestUtil.createIAFeature('Country Of Origin',null, 'Workwear', false, false));
        insert Iafeature_lst1;
        List<IA_Feature__c> Iafeature_lst2 = new List<IA_Feature__c>();
        Iafeature_lst2.add(RWS_TestUtil.createIAFeature('Red wing',Iafeature_lst1[0].id, 'Footwear', true, false));
        Iafeature_lst2.add(RWS_TestUtil.createIAFeature('Red',Iafeature_lst1[1].id, 'Accessories Apparel and Gear', true, false));
        Iafeature_lst2.add(RWS_TestUtil.createIAFeature('USA',Iafeature_lst1[2].id, 'Workwear', true, false));
        insert Iafeature_lst2;

        List<IA_Feature__c> Iafeature_lst3 = new List<IA_Feature__c>();
        Iafeature_lst3.add(RWS_TestUtil.createIAFeature('Red wing 1',Iafeature_lst2[0].id, 'Footwear', true, false));
        Iafeature_lst3.add(RWS_TestUtil.createIAFeature('Dark Red',Iafeature_lst2[1].id, 'Accessories Apparel and Gear', true, false));
        Iafeature_lst3.add(RWS_TestUtil.createIAFeature('New York',Iafeature_lst2[2].id, 'Workwear', true, false));
        insert Iafeature_lst3;

        List<Features__c> features_lst1 = new List<Features__c>();
        features_lst1.add(RWS_TestUtil.createFeature('Red wing',Iafeature_lst2[0].id, false));
        features_lst1.add(RWS_TestUtil.createFeature('Red',Iafeature_lst2[0].id, false));
        features_lst1.add(RWS_TestUtil.createFeature('USA',Iafeature_lst2[0].id, false));
        insert features_lst1;

        List<Features__c> features_lst2 = new List<Features__c>();
        features_lst2.add(RWS_TestUtil.createFeature('Red wing 1',Iafeature_lst3[0].id,false));
        features_lst2.add(RWS_TestUtil.createFeature('Dark Red',Iafeature_lst3[1].id, false));
        features_lst2.add(RWS_TestUtil.createFeature('New York',Iafeature_lst3[2].id,false));
        insert features_lst2;

        /*
        List<Product_Style_Features__c> Product_Features_lst = new List<Product_Style_Features__c>();
        Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst2[0].id, styles[0].id, false));
        Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst2[1].id, styles[1].id, false));
        
        Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst2[2].id, styles[2].id, false));
        Product_Features_lst.add(RWS_TestUtil.createProductFeature(features_lst2[1].id, styles[2].id, false));
        insert product_Features_lst;
        */
        
        //Added by BW : 8/18/17
        //Creates IA_Feature__c (filters) with the Tandem__c field set
        List<IA_Feature__c> featureLst = new List<IA_Feature__c>();
        
        IA_Feature__c filter1 = new IA_Feature__c();
        filter1.Name = 'TandemTest1';
        filter1.Feature_Name__c = 'TandemTest1';
        filter1.Parent_IA_Feature__c = Iafeature_lst1[0].id;
        filter1.Tandem__c = true;
        filter1.Category__c = 'Outside Lines';
        filter1.Selectable__c = true;
        featureLst.add(filter1);        
        
        IA_Feature__c filter2 = new IA_Feature__c();
        filter2.Name = 'TandemTest1';
        filter2.Feature_Name__c = 'TandemTest2';
        filter2.Parent_IA_Feature__c = Iafeature_lst1[0].id;
        filter2.Tandem__c = true;
        filter2.Category__c = 'Outside Lines';
        filter2.Selectable__c = true;
        featureLst.add(filter2);
        
        IA_Feature__c filter3 = new IA_Feature__c();
        filter3.Name = 'NonTandemTest';
        filter3.Feature_Name__c = 'NonTandemTest';
        filter3.Parent_IA_Feature__c = Iafeature_lst1[0].id;
        filter3.Tandem__c = false;
        filter3.Category__c = 'Outside Lines';
        filter3.Selectable__c = true;
        featureLst.add(filter3);    
            
        insert featureLst;  
    }
    
   
    static testMethod void testProgramValidate() {
        RWS_Production_Selection_Controller c = new RWS_Production_Selection_Controller();
        c.validateProgram();

        System.assert(!c.showPage);
    }

   static testMethod void testMethod1() {
       PageReference pageRef = Page.RWS_Account_Creation;

       Program__c pr = [select Id, Name, Auto_Update_Price__c, Auto_Add_Products__c from Program__c limit 1];

       pageRef.getParameters().put('proid', pr.Id);

       Test.setCurrentPageReference(pageRef);

       RWS_Production_Selection_Controller cntrl = new RWS_Production_Selection_Controller();

       List<RWS_Production_Selection_Controller.ProductWrapperClass> cProds = new List<RWS_Production_Selection_Controller.ProductWrapperClass>();

       List<Product2> prod_lst = [select Id, Name, ProductCode, Category__c from Product2];

       Boolean hasFW = false;
       for(Product2 p : prod_lst) {

           if(p.Category__c == 'Footwear' && hasFW) continue;

           cProds.add(new RWS_Production_Selection_Controller.ProductWrapperClass(
                   String.isBlank(p.ProductCode) ? string.valueOf(p.Id) : p.ProductCode,
                   p.Name,
                   '100',
                   '2',
                   '98',
                   p.Id,
                   false
               ));

           if(p.Category__c == 'Footwear') hasFW = true;
       }

       cntrl.createdProgram = pr;

       cntrl.prdresult = JSON.serialize(cProds);
       cntrl.addProgram();

       cntrl.productsListbyFeature();
       cntrl.featureFWWrapperLst[0].childfeatureLst[0].selected = true;
       cntrl.featureFWWrapperLst[0].childfeatureLst[0].grandchildfeatureLst[0].selected = true;
        //cntrl.checkselectall();
       cntrl.productsListbyFeature();


       Test.startTest();
           Set<Id> fIds = new Map<Id, IA_Feature__c>([select Id from IA_Feature__c]).keySet();

           cntrl.createfiltercriteira(cProds, fIds, pr.Id, 2);
           cntrl.createfiltercriteira(cProds, fIds, pr.Id, 2);

           cntrl.createCustomListFilterCriteria(cProds, pr.Id);

           Publish_PriceBook__c cpb = [select Id From Publish_PriceBook__c where Program__c = :pr.Id limit 1];

           Publish_PriceBook_Entry__c prod = RWS_TestUtil.createPublishPricebookEntry(cpb.Id, [select Id from Product2 limit 1].Id, false);
           prod.Filter_Number__c = 1;
           insert prod;

           RWS_TestUtil.createFilterCriteria(pr.Id, [select Id from IA_Feature__c limit 1].Id, true);

           cntrl.selectedFilter = '1';

           cntrl.initializeSelectionView();

           cntrl.selectedFilter = '2';

           cntrl.initializeSelectionView();

           Product2 p = [select Id, Category__c, ProductCode from Product2 limit 1];
           IA_Feature__c iaf = [select Id from IA_Feature__c where Category__c = :p.Category__c limit 1];

           Filter_Criteria__c fc = RWS_TestUtil.createFilterCriteria(pr.Id, null, false);
           fc.Filter_Number__c = 3;
           fc.Filter_BE_Details__c = JSON.serialize(new Map<String, String>{'Name = \'Red wing\'' => ' AND '}) + 'SEPARATOR["' + iaf.Id + '"]';

           fc.Product_Code__c = '["' + p.ProductCode + '"]-FPC-["' + p.ProductCode + '"]';

           insert fc;

           cntrl.selectedFilter = '3';

           cntrl.initializeSelectionView();

           cntrl.searchKeyword = '0001';

           cntrl.searchByKeyword();

           Set<Id> styleIds = new Map<Id, Product_Style__c>([select Id from Product_Style__c]).keySet();

           cntrl.productsList(styleIds);

           cntrl.removePricebookEntries(null, 1, new Set<Id>());

       Test.stopTest();


       
   }
    
    static testMethod void testMethod2() {
        RWS_Production_Selection_Controller cntrl = new RWS_Production_Selection_Controller();
        cntrl.TabCategory = 'Accessories Apparel and Gear';
        cntrl.productsListbyFeature();
        cntrl.featureACWrapperLst[0].childfeatureLst[0].selected = true;
        cntrl.featureACWrapperLst[0].childfeatureLst[0].grandchildfeatureLst[0].selected = true;
        cntrl.productsListbyFeature();
        //cntrl.checkselectall();
    }
    
    static testMethod void testMethod3() {
        RWS_Production_Selection_Controller cntrl = new RWS_Production_Selection_Controller();
        cntrl.TabCategory = 'Workwear';
        cntrl.productsListbyFeature();
        cntrl.featureWWWrapperLst[0].childfeatureLst[0].selected = true;
        cntrl.featureWWWrapperLst[0].childfeatureLst[0].grandchildfeatureLst[0].selected = true;
        cntrl.productsListbyFeature();
        //cntrl.checkselectall();
    }
    
    //Added by BW : 8/18/17
    //This method checks to make sure controller variable returns true when tandem filters are used without at least one non-tandem 
     static testMethod void testTandemOnlyFilters() {   
        List<String> checkFilters = new List<String>(); 
        List<IA_Feature__c> filters = [SELECT Id FROM IA_Feature__c WHERE Tandem__c = true];
      
        for(IA_Feature__c filter : filters){
            checkFilters.add('chkStyle '+filter.Id);
        }

        String mockFilters = JSON.serializePretty(checkFilters);
        
        PageReference pageRef = Page.RWS_NewProgramSetup;
        Test.setCurrentPageReference(pageRef);
        pageRef.getParameters().put('checkedFiltersJSON', mockFilters);        
        RWS_Production_Selection_Controller cntrl = new RWS_Production_Selection_Controller();
        
        Test.startTest();
        cntrl.validateFilters();
        Test.stopTest();
        System.assertEquals(true, cntrl.chooseMoreFilters);
     }
    
    //Added by BW : 8/18/17
    //This method checks to make sure controller variable returns false when tandem filters are used with at least one non-tandem   
     static testMethod void testBothFilters() { 
        List<String> checkFilters = new List<String>(); 
        List<IA_Feature__c> filters = [SELECT Id FROM IA_Feature__c WHERE Category__c LIKE 'Outside Lines'];
        for(IA_Feature__c filter : filters){
            checkFilters.add('chkStyle '+filter.Id);
        }
        
        String mockFilters = JSON.serializePretty(checkFilters);
        
        PageReference pageRef = Page.RWS_NewProgramSetup;
        Test.setCurrentPageReference(pageRef);
        pageRef.getParameters().put('checkedFiltersJSON', mockFilters);        
        RWS_Production_Selection_Controller cntrl = new RWS_Production_Selection_Controller();
        
        Test.startTest();
        cntrl.validateFilters();
        Test.stopTest();
        System.assertEquals(false, cntrl.chooseMoreFilters);
     }  
}