force-app/main/default/objects/ZipCodeLatAndLong__c/ZipCodeLatAndLong__c.object-meta.xml
<CustomObject>
    <description>This is the base table of zip codes that is loaded from a purchased file from USPS</description>
    <label>ZipCodeLatAndLong</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZipCodeLatAndLong</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCodeLatAndLong__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This stored the City.</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeLatAndLong__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>This stored the latitude.</description>
    <label>Latitude</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeLatAndLong__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>This stored Longitude</description>
    <label>Longitude</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeLatAndLong__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This stores the state.</description>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeLatAndLong__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <description>External Id field used for upserts</description>
    <externalId>true</externalId>
    <label>Zipcode</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_TriggerControllerZipcodeLatAndLong.cls
/**
*   Test class for TriggerController_Account.
*
*   {Contact}   - support@demandchainsystems.com
*                 www.demandchainsystems.com
*                 612-424-0032
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   20160902    James Loghry DCS        Created
*   =============================================================================
*/@isTest
private class Test_TriggerControllerZipcodeLatAndLong{
	static testmethod void testCreate(){
		Test.startTest();
		ZipCodeLatAndLong__c z = new ZipCodeLatAndLong__c(
			Name = '12345'
			,Zipcode__c = '12345'
			,Latitude__c = '11.123'
			,Longitude__c = '11.124'
			,City__c = 'City'
			,State__c = 'MN'
		);
		insert z;
		Test.stopTest();

		z = [Select Location__Latitude__s,Location__Longitude__s From ZipCodeLatAndLong__c Where Id = :z.Id];
		System.assertEquals(11.123,z.Location__Latitude__s);
		System.assertEquals(11.124,z.Location__Longitude__s);
	}

	static testmethod void testUpdate(){
		Test.startTest();
		ZipCodeLatAndLong__c z = new ZipCodeLatAndLong__c(
			Name = '12345'
			,Zipcode__c = '12345'
			//,Latitude__c = '123.123'
			//,Longitude__c = '124.124'
			,City__c = 'City'
			,State__c = 'MN'
		);
		insert z;

		z.Latitude__c = '11.123';
		z.Longitude__c = '11.124';
		update z;
		Test.stopTest();

		z = [Select Location__Latitude__s,Location__Longitude__s From ZipCodeLatAndLong__c Where Id = :z.Id];
		System.assertEquals(11.123,z.Location__Latitude__s);
		System.assertEquals(11.124,z.Location__Longitude__s);
	}
}