force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style_Features__c/Product_Style_Features__c.object-meta.xml
<CustomObject>
    <description>Junction object which manages the many to many relationship between unique styles (Product Style Object) and the Features object. Records are created / updated via apex. Does not need to be maintained via integration. 
Object Type: IA 
Integrated: N</description>
    <label>Product Style Features</label>
    <nameField>
        <displayFormat>PSF-{000000}</displayFormat>
        <label>Product Style Feature #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Style Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style_Features__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Product Style object. Used to associate a Product Style to a Feature. Maintained by apex. 
Field Type: IA 
Integrated: N</description>
    <inlineHelpText>Lookup field to the Product Style object. Used to associate a Product Style to a Feature.</inlineHelpText>
    <label>Product Style</label>
    <referenceTo>Product_Style__c</referenceTo>
    <relationshipLabel>Product Style Features</relationshipLabel>
    <relationshipName>Product_Style_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Industrial Account programs.  Industrial Account programs can be created by community and internal users.  Programs have a lookup to associate them with an industrial account.  
Object Type: IA
Integrated: Y</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Auto_Add_Products__c.field-meta.xml
<CustomField>
    <fullName>Auto_Add_Products__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If TRUE your price book is automatically updated with new products that meet stored filter criteria. EXAMPLE: a program for Red Wing &amp; Steel Toe and a new product product is manufactured that is Red Wing &amp; Steel Toe it will be added to your price book.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If TRUE your price book is automatically updated with new products that meet stored filter criteria. EXAMPLE: a program for Red Wing &amp; Steel Toe and a new product product is manufactured that is Red Wing &amp; Steel Toe it will be added to your price book.</inlineHelpText>
    <label>Auto Add Products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>Record Type for Programs</description>
    <label>Program</label>
</RecordType>

force-app/main/default/classes/RWS_InsertNewProducts_Batch.cls
/**
* Batch class to get all the programs where Auto_Add_Products__c = true
* @DateCreated: 12/06/2016
* @Author: Kotapati Keerthi (Magnet360)
*/
global class RWS_InsertNewProducts_Batch implements Database.Batchable<sObject>, Schedulable {
    
    global void execute(SchedulableContext sc) {
        // execute the batch job with one record at a time
        Database.executeBatch(new RWS_InsertNewProducts_Batch(), 1);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        // find if any product updated yesterday
        Integer count = [select Id from Product2 where LastModifiedDate >= YESTERDAY 
                        and IsActive = true and Product_Style__c != null limit 1].size();

        // find if any product feature updated yesterday
        Integer featureCount = [select Id from Product_Style_Features__c where LastModifiedDate >= YESTERDAY limit 1].size();

        // do not process program if no product or product feature was changed yesterday
        return Database.getQueryLocator('Select Id From Program__c where Auto_Add_Products__c = true '
                                        + (featureCount == 0 && count == 0 && !Test.isRunningTest() ?  
                                            ' and Id = null ' 
                                            : '') );
    }
    
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        
        for (sObject p : scope) {
            //convert scope to actual Program
            Program__c program = (Program__c) p;

            // pass program to the logic handler for further processing
            RWS_InsertNewProducts_BatchHandler.createProducts(program.Id);
        }
        
    }     
    
    global void finish(Database.BatchableContext BC) {} 
}