force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Used in apex to match to the style number unique id on the Product object.  Updated via apex.
Field Type: IA
Integrated: N</description>
    <externalId>true</externalId>
    <inlineHelpText>Used in apex to match to the style number unique id on the Product object. Updated via apex.</inlineHelpText>
    <label>Style Number Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/Publish_PriceBook__c.object-meta.xml
<CustomObject>
    <description>Custom object to publish Price Book data via outbound messaging to external systems
Object Type: IA
Integrated: Y</description>
    <label>Publish PriceBook</label>
    <nameField>
        <label>Publish PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publish PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to the Price Book object.  Associates a Price Book (standard object) with Publish PriceBook (custom object).  Used in outbound messaging.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Publish PriceBooks</relationshipLabel>
    <relationshipName>Publish_PriceBooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <description>Formula field which returns the ID from a Price Book (standard object).  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <formula>IF( Historic_Pricebook_ID__c != NULL, Historic_Pricebook_ID__c, CASESAFEID(Id))</formula>
    <inlineHelpText>Formula field which returns the ID from a Price Book (standard object)  Used in outbound messaging.</inlineHelpText>
    <label>Price Book ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>The Publish Status of the outbound message.  Updated by workflow field update, when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/Publish_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <description>STRICT CHANGE CONTROL _ NO CHANGES UNLESS APPROVED FOR REPLICATION - Custom object to publish pricebook entry to downstream systems via outbound message</description>
    <label>Publish PriceBook Entry</label>
    <nameField>
        <displayFormat>PPBE-{0000000}</displayFormat>
        <label>Publish PriceBook Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publish PriceBook Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount Percent of a Price Book Entry. Used in outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Discount Percent of a Price Book Entry. Used in outbound messaging.</inlineHelpText>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</description>
    <inlineHelpText>Expiration Date of the Pricebook Entry when Pricebook Entry has been removed from Pricebook</inlineHelpText>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Filter_Number__c.field-meta.xml
<CustomField>
    <fullName>Filter_Number__c</fullName>
    <description>Used to identify the originating Filter Criteria for the resulting Product</description>
    <inlineHelpText>Used to identify the originating Filter Criteria for the resulting Product</inlineHelpText>
    <label>Filter Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Fixed_Price__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked (TRUE) it indicates the price for this product is fixed and will not be impacted by the price update batch job which runs for all Programs where Auto Update Prices = TRUE. Only applies to price book entries created for programs.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>If checked (TRUE) it indicates the price for this product is fixed and will not be impacted by the price update batch job which runs for all Programs where Auto Update Prices = TRUE. Only applies to price book entries created for programs.</inlineHelpText>
    <label>Fixed Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>List Price</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>MSRP</description>
    <label>MSRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/MSRP_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>MSRP_Effective_Date__c</fullName>
    <description>MSRP Effective Date</description>
    <label>MSRP Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/MSRP_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>MSRP_Expiration_Date__c</fullName>
    <description>MSRP Expiration Date</description>
    <label>MSRP Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Price Book standard object.  Associates the Publish Pricebook Entry Records with the Price Book record.  Used for outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Lookup to Price Book standard object.  Associates the Publish Pricebook Entry Records with the Price Book record.  Used for outbound messaging.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <description>Formula Field to return the Price Book ID from the Price Book standard object.  Used in outbound messaging. 
Field Type: IA 
Integrated: Y</description>
    <formula>Publish_PriceBook__r.Price_Book_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula Field to return the Price Book ID from the Price Book standard object.  Used in outbound messaging.</inlineHelpText>
    <label>Price Book Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Price_Level__c.field-meta.xml
<CustomField>
    <fullName>Price_Level__c</fullName>
    <description>Identify the Price Level of the related Price Book Entry record. Used for outbound messaging.</description>
    <inlineHelpText>Identify the Price Level of the related Price Book Entry record.</inlineHelpText>
    <label>Price Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Pricebook_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Entry_ID__c</fullName>
    <description>Contains the ID for the PPBE record for downstream systems, includes Historic record ID if present.</description>
    <formula>IF( Historic_Pricebook_Entry_ID__c != NULL,  Historic_Pricebook_Entry_ID__c ,  CASESAFEID(Id))</formula>
    <inlineHelpText>Contains the ID for the PPBE record for downstream systems, includes Historic record ID if present.</inlineHelpText>
    <label>Pricebook_Entry_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_RWS_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_RWS_ID__c</fullName>
    <description>Product RWS ID from the Product standard object.  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Product RWS ID from the Product standard object.  Used in outbound messaging.</inlineHelpText>
    <label>Product RWS ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <description>Product SKU from the Product standard object.  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Product SKU from the Product standard object.  Used in outbound messaging.</inlineHelpText>
    <label>Product SKU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Product_UPC__c.field-meta.xml
<CustomField>
    <fullName>Product_UPC__c</fullName>
    <description>Product UPC from the Product standard object.  Used in outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Product UPC from the Product standard object.  Used in outbound messaging.</inlineHelpText>
    <label>Product UPC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>Publish_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publish PriceBook</description>
    <inlineHelpText>Publish PriceBook</inlineHelpText>
    <label>Publish PriceBook</label>
    <referenceTo>Publish_PriceBook__c</referenceTo>
    <relationshipLabel>Publish PriceBook Entries</relationshipLabel>
    <relationshipName>Publish_PriceBook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <description>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Status of the Outbound Message.  Updated by workflow field update when outbound message is triggered.</inlineHelpText>
    <label>Publish Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ReadyToPublish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Name__c.field-meta.xml
<CustomField>
    <fullName>Style_Name__c</fullName>
    <description>Style Name</description>
    <label>Style Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number__c.field-meta.xml
<CustomField>
    <fullName>Style_Number__c</fullName>
    <description>Style Number (field is used to match against Product standard object). Used for outbound messaging. 
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number (field is used to match against Product standard object). Used for outbound messaging.</inlineHelpText>
    <label>Style Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Publish_PriceBook_Entry__c/fields/Style_Number_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_Id__c</fullName>
    <description>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Style Number Unique Identifier (field is used to match against Product Style custom object and Product standard object).  Used for outbound messaging.</inlineHelpText>
    <label>Style Number Unique Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_PriceBookEntry_Util.cls
/********************************************************************************
*   PURPOSE : To stage PriceBookEntry records for outbound publishing
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   12/07/2016  Usman Aslam/M360        Initial version
*	03/08/18	Brandon Willard(M360)   Modified for RWCP-3449
********************************************************************************/
public without sharing class RWS_PriceBookEntry_Util {

    //commented out by BW
    // util method to get publish pricebook entry records for the pricebook and products
    public static void createPublishPriceBookEntries(Id pricebookId, Set<Id> productIds) {
        List<Publish_PriceBook_Entry__c> ppbEntries = [SELECT Id, Name, Publish_PriceBook__c, Product_ID__c, 
                        CurrencyIsoCode, List_Price__c, Active__c, 
                        /*UseStandardPrice,*/ CreatedDate, CreatedById, 
                        LastModifiedDate, LastModifiedById, SystemModstamp, 
                        Style_Number__c	, IsDeleted, //RWS_Last_Updated_Date__c, 
                        Discount__c, Fixed_Price__c, MSRP_Effective_Date__c, 
                        MSRP_Expiration_Date__c, //RWS_Id__c, 
                        Filter_Number__c, //Pricebook2.IsStandard,
                        Price_Level__c 
                    FROM Publish_PriceBook_Entry__c WHERE Product_ID__c in :productIds AND Publish_PriceBook__c = :pricebookId];

        createPublishPriceBookEntries(ppbEntries);
    }

    // util method to get PricebookEntry records for the PricebookEntries
    // re-quering just to make sure all the fields are included
    public static void createPublicPriceBookEntries(List<Publish_PriceBook_Entry__c> pbEntries) {
        pbEntries = [SELECT Id, Name, 	Publish_PriceBook__c, Product_ID__c, 
                        CurrencyIsoCode, List_Price__c, Active__c, Price_Book_ID__c,
                        /*UseStandardPrice,*/ CreatedDate, CreatedById, 
                        LastModifiedDate, LastModifiedById, SystemModstamp, 
                        Style_Number__c, IsDeleted, /*RWS_Last_Updated_Date__c,*/ 
                        Discount__c, Fixed_Price__c, MSRP_Effective_Date__c, 
                        MSRP_Expiration_Date__c, /*RWS_Id__c, */
                        Filter_Number__c, /*Pricebook2.IsStandard,*/
                        Price_Level__c 
                    FROM Publish_PriceBook_Entry__c where Id in :pbEntries];

        createPublishPriceBookEntries(pbEntries);
        
    }

    // util method to create publish pricebook entry records for PricebookEntries
    private static void createPublishPriceBookEntries(List<Publish_PriceBook_Entry__c> pbEntries) {

        Set<Id> priceBookIds = new Set<Id>();
        Set<Id> productIds = new Set<Id>();

        // get product and pricebook IDs
        for(Publish_PriceBook_Entry__c pbe : pbEntries) {
            priceBookIds.add(pbe.Publish_PriceBook__c);
            productIds.add(pbe.Product_ID__c);
        }

        Id stdPbId;

        // get standard pricebook id
        if(Test.isRunningTest()) 
            stdPbId = Test.getStandardPricebookId();
        else
            stdPbId = [select id, name from Pricebook2 where IsStandard = true limit 1].id;

        // get standard price book entries, as we need both MSRP price and the program price
        List<PricebookEntry> stdEntries = [SELECT Id, Name, Product2Id, 
                                         UnitPrice, 
                                        UseStandardPrice, Discount__c, 
                                        MSRP_Effective_Date__c, MSRP_Expiration_Date__c,
                                        IsActive,
                                        CurrencyIsoCode
                                    FROM PricebookEntry
                                    WHERE Pricebook2Id = :stdPbId
                                    AND Product2Id in :productIds];

        System.debug('************stdEntries: '+stdEntries);
        
        // populate Product Id to Pricebook Entry Map
        Map<String, PricebookEntry> prodToPbeMap = new Map<String, PricebookEntry>();
        for(PricebookEntry pb : stdEntries) {
            prodToPbeMap.put(String.valueOf(pb.Product2Id) + pb.CurrencyIsoCode,  pb);
        }

        /*
        // create PriceBook to Publish Price Book Id map
        Map<Id, Id> pbToPpbIdMap = new Map<Id, Id>();
        for(Publish_PriceBook__c ppb : [select Id, 
                                            Price_Book__c
                                    from Publish_PriceBook__c 
                                    where Price_Book__c in :priceBookIds]) {

            pbToPpbIdMap.put(ppb.Price_Book__c, ppb.Id);
        }*/

        // get products information
        Map<Id, Product2> productsMap = new Map<Id, Product2>(
            [
                select Id, Name, RWS_Id__c, SKU__c, UPC__c, 
                        ProductCode, Style_Number_Unique_ID__c
                from Product2 
                    where Id in :productIds 
                    and Product_Style__c != null
            ]
        );

        // list to insert Publish Pricebook Entries
        List<Publish_PriceBook_Entry__c> ppbEntriesToInsert = new List<Publish_PriceBook_Entry__c>();

        // iterate over all PriceBookEntry records
        for(Publish_PriceBook_Entry__c ppbe : pbEntries) {

            // if Publish PriceBookEntry Id is null, move to next record
            if(ppbe.Id == null) continue;
			//system.debug('*****************Publish Pricebook: '+ppbe.Publish_PriceBook__c);
            // get the Publish Pricebook Id, if not found, move to next record
            //********Id ppbId = pbToPpbIdMap.get(ppbe.Price_Book_ID__c);
            //*****if(ppbId == null) continue;
			
            
            // get the Product record, if not found, move to next record
            Product2 p = productsMap.get(ppbe.Product_ID__c);
            if(p == null) continue;

            // get the Standard PricebookEntry record, if not found, move to next record
            PriceBookEntry stdPbe = prodToPbeMap.get(String.valueOf(ppbe.Product_ID__c) + ppbe.CurrencyIsoCode);
            if(stdPbe == null) continue;

            // Initialize Publish Pricebook Entry object
           /* Publish_PriceBook_Entry__c ppbe = new Publish_PriceBook_Entry__c();
            ppbe.Price_Book__c = pbe.Pricebook2Id;
            ppbe.Discount__c = pbe.Discount__c;
            ppbe.Price_Level__c = pbe.Price_Level__c;
            ppbe.Publish_PriceBook__c = ppbId;*/

            ppbe.Product_SKU__c = p.SKU__c;
            ppbe.Product_UPC__c = p.UPC__c;
            ppbe.Product_RWS_ID__c = p.RWS_Id__c;

            ppbe.Style_Number__c = p.ProductCode;
            ppbe.Style_Number_Unique_Id__c = p.Style_Number_Unique_ID__c;
            ppbe.Style_Name__c = p.Name;

            //ppbe.Pricebook_Entry_ID__c = pbe.Id;  //Set PriceBook_Entry_ID__c for upsert

            //ppbe.List_Price__c = pbe.UnitPrice;

            //System.debug('*************UnitPrice: '+stdPbe.UnitPrice);

            
            ppbe.MSRP__c = stdPbe.UnitPrice;
            
            //System.debug('*************MSRP: '+ppbe.MSRP__c);

            //ppbe.Active__c = pbe.IsActive;

         /*   // Standard Pricebook Entries are being processed, then fill Effective and Expiration date
            if(pbe.Pricebook2.IsStandard) {
                ppbe.MSRP_Effective_Date__c = pbe.MSRP_Effective_Date__c;
                ppbe.MSRP_Expiration_Date__c = pbe.MSRP_Expiration_Date__c;
            }
		 */
            // Add to List
            ppbEntriesToInsert.add(ppbe);
        }


        // no publish price book entry records initialized above, exit
        if(ppbEntriesToInsert.isEmpty()) return;

        // set the flag to true so HasPricebook__c logic is executed
        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = true;

        // insert/update records
        insertUpdateRecord(ppbEntriesToInsert);

        // set the flag to false so HasPricebook__c logic is NOT executed again in the same invocation
        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = Test.isRunningTest();

    }
    
    // util method to insert/update Publish Pricebook Entry records
    // try five times, if a try fails because of ROW LOCK issue
    public static void insertUpdateRecord(List<Publish_PriceBook_Entry__c> ppbEntriesToInsert) {
        Integer attempts = 5;
        while(attempts > 0){
            try {
                attempts --; 
                upsert ppbEntriesToInsert; 
                attempts = 0;
            } catch (System.DmlException dmlEx) {
                if (!dmlEx.getMessage().contains('UNABLE_TO_LOCK_ROW')) {  attempts = 0;  }
                if(attempts == 0) { throw dmlEx; }
            } // end of catch
        } // end of while retry loop
    }

     
     public static void deactivatePublicPriceBookEntries(List<Publish_PriceBook_Entry__c> ppbes) {
      /*  Set<Id> pbeIds = new Map<Id, Publish_PriceBook_Entry__c>(pbEntries).keySet();

        List<Publish_PriceBook_Entry__c> ppbes = [select Id, Active__c,
                                                        Pricebook_Entry_ID__c,
                                                        Expiration_Date__c 
                                                    from Publish_PriceBook_Entry__c
                                                    where Pricebook_Entry_ID__c in :pbeIds];
	*/
        if(ppbes.isEmpty()) return;

        for(Publish_PriceBook_Entry__c ppbe : ppbes) {
            ppbe.Active__c = false;
            ppbe.Expiration_Date__c = DateTime.now();
            ppbe.Filter_Number__c = null;
        }

        // set the flag to true so HasPricebook__c logic is executed
        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = true;        

        insertUpdateRecord(ppbes);

        // set the flag to false so HasPricebook__c logic is NOT executed again in the same invocation
        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = Test.isRunningTest();

    }
     
    
     //Commented this out to remove Pricbook_Entry_ID__c reference as it was used to hold pbe IDs - BW
     /* public static void deactivatePublicPriceBookEntries(List<PricebookEntry> pbEntries) {
        Set<Id> pbeIds = new Map<Id, PricebookEntry>(pbEntries).keySet();

        List<Publish_PriceBook_Entry__c> ppbes = [select Id, Active__c,
                                                        Pricebook_Entry_ID__c,
                                                        Expiration_Date__c 
                                                    from Publish_PriceBook_Entry__c
                                                    where Pricebook_Entry_ID__c in :pbeIds];

        if(ppbes.isEmpty()) return;

        for(Publish_PriceBook_Entry__c ppbe : ppbes) {
            ppbe.Active__c = false;
            ppbe.Expiration_Date__c = DateTime.now();
        }

        // set the flag to true so HasPricebook__c logic is executed
        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = true;        

        insertUpdateRecord(ppbes);

        // set the flag to false so HasPricebook__c logic is NOT executed again in the same invocation
        RWS_PublishPriceBookEntryTrigger_Handler.RUN_PROGRAM_UPDATE = Test.isRunningTest();

    }*/


    
    
    // util method to set price or discount and publish records
    public static void publishPublicPriceBookEntries(List<Publish_PriceBook_Entry__c> ppbEntries) {
        //Map<Id, Publish_PriceBook_Entry__c> pbesMap = new Map<Id, Publish_PriceBook_Entry__c>(pbEntries);


        Set<Id> productIds = new Set<Id>();
        // get product and pricebook IDs
        for(Publish_PriceBook_Entry__c pbe : ppbEntries) {
            productIds.add(pbe.Product_Id__c);
        }

        Id stdPbId;

        // get standard pricebook id
        if(Test.isRunningTest()) 
            stdPbId = Test.getStandardPricebookId();
        else
            stdPbId = [select id, name from Pricebook2 where IsStandard = true limit 1].id;

        // get standard price book entries
        List<PricebookEntry> stdEntries = [SELECT Id, Name, Product2Id, 
                                         UnitPrice, 
                                        UseStandardPrice, Discount__c, 
                                        MSRP_Effective_Date__c, MSRP_Expiration_Date__c,
                                        IsActive,
                                        CurrencyIsoCode
                                    FROM PricebookEntry
                                    WHERE Pricebook2Id = :stdPbId
                                    AND Product2Id in :productIds];

        // populate Product Id to Pricebook Entry Map
        Map<String, PricebookEntry> prodToPbeMap = new Map<String, PricebookEntry>();
        for(PricebookEntry pb : stdEntries) {
            prodToPbeMap.put(String.valueOf(pb.Product2Id) + pb.CurrencyIsoCode,  pb);
        }

        // get publish pricebook entry records
       /* List<Publish_PriceBook_Entry__c> ppbes = [select Id, Publish_Status__c, Pricebook_Entry_ID__c,
                                                        List_Price__c, Discount__c 
                                                    from Publish_PriceBook_Entry__c
                                                    where Pricebook_Entry_ID__c in :pbesMap.keySet()];*/

        // if associated publish pricebook entry records are not found, exit
        if(ppbEntries.isEmpty()) return;


        // iterate over all publish pricebook entry records
        for(Publish_PriceBook_Entry__c ppbe : ppbEntries) {

            // get related pricebook entry record
           // Publish_PriceBook_Entry__c pbe = pbesMap.get(ppbe.Pricebook_Entry_ID__c);

            // if not found, move to next record
            //if(pbe == null) continue;

            // get related standard pricebook entry record
            PriceBookEntry stdPbe = prodToPbeMap.get(String.valueOf(ppbe.Product_Id__c) + ppbe.CurrencyIsoCode);

            // if not found, move to next record
            if(stdPbe == null) continue;

            // set info on the publish pricebook entry record
            ppbe.MSRP__c = stdPbe.UnitPrice;

           // ppbe.List_Price__c = pbe.List_Price__c;
           // ppbe.Discount__c = pbe.Discount__c;

            
        }


        // update publish pricebook entry records
        insertUpdateRecord(ppbEntries);
    }


    // util method to insert/update Pricebook Entry records
    // try five times, if a try fails because of ROW LOCK issue
    public static void insertUpdateRecords(List<Publish_PriceBook_Entry__c> ppbes, Boolean insertRecords) {
        Integer attempts = 5;
        while(attempts > 0){
            try {
                attempts --; 
                if(insertRecords) insert ppbes; 
                if(!insertRecords) update ppbes; 
                attempts = 0;
            } catch (System.DmlException dmlEx) {
                if (!dmlEx.getMessage().contains('UNABLE_TO_LOCK_ROW')) {  attempts = 0;  }

                if(attempts == 0) { throw dmlEx; }
            } // end of catch
        } // end of while retry loop
    }

   /* // util method to delete Pricebook Entry records
    // try five times, if a try fails because of ROW LOCK issue
    public static void deleteRecords(List<Publish_PriceBook_Entry__c> entriesToDelete) {
        Integer attempts = 5;
        while(attempts > 0){
            try {
                attempts --; 
                delete entriesToDelete;
                attempts = 0;
            } catch (System.DmlException dmlEx) {
                if (!dmlEx.getMessage().contains('UNABLE_TO_LOCK_ROW')) {  attempts = 0;  }

                if(attempts == 0) { throw dmlEx; }
            } // end of catch
        } // end of while retry loop
    } */
    
    // util method to delete Pricebook Entry records
    // try five times, if a try fails because of ROW LOCK issue
    public static void deleteRecords(List<PricebookEntry> entriesToDelete) {
        Integer attempts = 5;
        while(attempts > 0){
            try {
                attempts --; 
                delete entriesToDelete;
                attempts = 0;
            } catch (System.DmlException dmlEx) {
                if (!dmlEx.getMessage().contains('UNABLE_TO_LOCK_ROW')) {  attempts = 0;  }

                if(attempts == 0) { throw dmlEx; }
            } // end of catch
        } // end of while retry loop
    }


    
}