force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Used in apex to match to the category on the Product object. Updated via apex.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used in apex to match to the category on the Product object. Updated via apex.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Workwear</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Accessories Apparel and Gear</fullName>
            </value>
            <value>
                <fullName>Outside Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Style__c/fields/Item_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Status_Code__c</fullName>
    <description>Rollup for the related Product Item Status Code (populated with the lowest possible value)</description>
    <inlineHelpText>Rollup for the related Product Item Status Code (populated with the lowest possible value)</inlineHelpText>
    <label>Item Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Used in apex to match to the style number unique id on the Product object.  Updated via apex.
Field Type: IA
Integrated: N</description>
    <externalId>true</externalId>
    <inlineHelpText>Used in apex to match to the style number unique id on the Product object. Updated via apex.</inlineHelpText>
    <label>Style Number Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_ProductStyle_Batch_Test.cls
@isTest
private class RWS_ProductStyle_Batch_Test {
    static testMethod void testBatch() {
        
        Product2 prod = RWS_TestUtil.createProductwithDetail('Product 1', 'Footwear', false);
        prod.Style_Number_Unique_ID__c = '00011';
        prod.Item_Status__c = 'Active';
        prod.Item_Status_Code__c = '20';

        Product2 prod2 = RWS_TestUtil.createProductwithDetail('Product 2', 'Footwear', false);
        prod2.Style_Number_Unique_ID__c = '00011';
        prod2.Item_Status__c = 'Active';
        prod2.Item_Status_Code__c = '50';

        Product2 prod3 = RWS_TestUtil.createProductwithDetail('Product 3', 'Workwear', false);
        prod3.Style_Number_Unique_ID__c = '00011';
        prod3.Item_Status__c = 'Active'; 
        prod3.Item_Status_Code__c = '40';

        insert new List<Product2>{prod, prod3, prod2};
            
        System.assert([select Id from Product_Style__c where Style_Number_Unique_ID__c = '00011' and Category__c = 'Footwear' ].size() == 1);
        System.assert([select Id from Product_Style__c where Style_Number_Unique_ID__c = '00011' and Category__c = 'Workwear' ].size() == 1);
        
        Test.startTest();
        
        RWS_ProductStyle_Batch b = new RWS_ProductStyle_Batch();
        b.execute(null);
        
        Test.stopTest();
        
        for(Product_Style__c p : [select Id, Item_Status_Code__c, 
                                  	Style_Number_Unique_ID__c, Category__c 
                                 from Product_Style__c]) {
            if(p.Style_Number_Unique_ID__c == '00011' && p.Category__c == 'Footwear')
                System.assertEquals('20', p.Item_Status_Code__c);
                                     
            if(p.Style_Number_Unique_ID__c == '00011' && p.Category__c == 'Workwear')
                System.assertEquals('40', p.Item_Status_Code__c);
        }
    }
}