force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Used in apex to match to the category on the Product object. Updated via apex.
Field Type: IA
Integrated: N</description>
    <inlineHelpText>Used in apex to match to the category on the Product object. Updated via apex.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Workwear</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Accessories Apparel and Gear</fullName>
            </value>
            <value>
                <fullName>Outside Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Style__c/fields/Item_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Status_Code__c</fullName>
    <description>Rollup for the related Product Item Status Code (populated with the lowest possible value)</description>
    <inlineHelpText>Rollup for the related Product Item Status Code (populated with the lowest possible value)</inlineHelpText>
    <label>Item Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Used in apex to match to the style number unique id on the Product object.  Updated via apex.
Field Type: IA
Integrated: N</description>
    <externalId>true</externalId>
    <inlineHelpText>Used in apex to match to the style number unique id on the Product object. Updated via apex.</inlineHelpText>
    <label>Style Number Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RWS_ProductTrigger_Test.cls
@isTest
private class RWS_ProductTrigger_Test {
    static testMethod void testTrigger() {

        Product2 prod = RWS_TestUtil.createProductwithDetail('Product 1', 'Footwear', false);
        prod.Style_Number_Unique_ID__c = '00011';
        prod.Item_Status__c = 'Active';
        prod.Item_Status_Code__c = '20';

        Product2 prod2 = RWS_TestUtil.createProductwithDetail('Product 2', 'Footwear', false);
        prod2.Style_Number_Unique_ID__c = '00011';
        prod2.Item_Status__c = 'Active';
        prod2.Item_Status_Code__c = '50';

        Product2 prod3 = RWS_TestUtil.createProductwithDetail('Product 3', 'Workwear', false);
        prod3.Style_Number_Unique_ID__c = '00011';
        prod3.Item_Status__c = 'Active'; 
        prod3.Item_Status_Code__c = '20';

        insert new List<Product2>{prod, prod3, prod2};
           

        System.assert([select Id from Product_Style__c where Style_Number_Unique_ID__c = '00011' and Category__c = 'Footwear' ].size() == 1);
        System.assert([select Id from Product_Style__c where Style_Number_Unique_ID__c = '00011' and Category__c = 'Workwear' ].size() == 1);


        prod.IsActive = false;

        update prod;

        prod.IsActive = true;

        update prod;

        
    }
}