force-app/main/default/objects/Product_Style__c/Product_Style__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the unique product styles.  Records are created / updated via apex with Product Object record inserts and updates.  Does not need to be maintained via integration. 
Object Type: IA
Integrated: N</description>
    <label>Product Style</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Style #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Style__c/fields/Item_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Status_Code__c</fullName>
    <description>Rollup for the related Product Item Status Code (populated with the lowest possible value)</description>
    <inlineHelpText>Rollup for the related Product Item Status Code (populated with the lowest possible value)</inlineHelpText>
    <label>Item Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Style__c/fields/Style_Number_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_Unique_ID__c</fullName>
    <description>Used in apex to match to the style number unique id on the Product object.  Updated via apex.
Field Type: IA
Integrated: N</description>
    <externalId>true</externalId>
    <inlineHelpText>Used in apex to match to the style number unique id on the Product object. Updated via apex.</inlineHelpText>
    <label>Style Number Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RW_Product.cls
@RestResource(urlMapping='/Product')
global with sharing class RW_Product {
  
    @HttpGet
    global static Product2 doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String productCodes = '23152';//req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        Product2 prd = [select Id, Product_Style__c, Parent_Product_Style__c, 
                     Style_Number_Unique_ID__c,
                     SKU__c,
                     Item_Status_Code__c
                     from Product2
                     where Style_Number_Unique_ID__c = '23152' LIMIT 1];
      	return prd;
    }

}