force-app/main/default/objects/Future_Price__c/Future_Price__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the Future Prices to be applied to Products (Product2) on specified Effective Dates</description>
    <label>Future Price</label>
    <nameField>
        <displayFormat>FP-{0}</displayFormat>
        <label>Future Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Future_Price__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the Future Price is available to be evaluated for applying Future Price to Product.  Value should be TRUE or FALSE, defaulted to TRUE.
Field Type: IA
Integrated: Y&quot;</description>
    <inlineHelpText>Indicates if the Future Price is available to be evaluated for applying Future Price to Product.  Value should be TRUE or FALSE, defaulted to TRUE.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Future_Price__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Indicates the date that the Future Price should be applied to the Product (Product2).
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the date that the Future Price should be applied to the Product (Product2).</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Future_Price__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>Indicates the MRSP value of the related Product for Future Price.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the MRSP value of the related Product for Future Price.</inlineHelpText>
    <label>MSRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Future_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates relationship of Future Price to Product (Product2) to apply Future Price.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates relationship of Future Price to Product (Product2) to apply Future Price.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Future Prices</relationshipLabel>
    <relationshipName>Future_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_FutureBatchJob.cls
global class RWS_FutureBatchJob implements Database.Batchable<sObject>, Schedulable {
    private Id stdPbId;



    // intialize the batch job
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new RWS_FutureBatchJob(), 1);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, CurrencyIsoCode, Active__c, 
                                                MSRP__c, Product__c, Effective_Date__c 
                                            FROM Future_Price__c
                                            WHERE Active__c = true 
                                            AND Product__c != null
                                            AND Effective_Date__c = TODAY]);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        // get standard pricebook id
        if(Test.isRunningTest()) 
            stdPbId = Test.getStandardPricebookId();
        else
            stdPbId = [select id, name from Pricebook2 where IsStandard = true limit 1].id;

        List<Future_Price__c> entries = (List<Future_Price__c>) scope;

        Set<Id> productIds = new Set<Id>();

        for(Future_Price__c pbe : entries) {
            productIds.add(pbe.Product__c);
        }

        // get standard price book entries
        List<PricebookEntry> stdEntries = [SELECT Id, Name, Product2Id, 
                                         UnitPrice, 
                                        UseStandardPrice, Discount__c, 
                                        MSRP_Effective_Date__c, MSRP_Expiration_Date__c,
                                        IsActive,
                                        CurrencyIsoCode
                                    FROM PricebookEntry
                                    WHERE Pricebook2Id = :stdPbId
                                    AND Product2Id in :productIds];

        // populate Product Id to Pricebook Entry Map
        Map<String, PricebookEntry> prodToPbeMap = new Map<String, PricebookEntry>();
        for(PricebookEntry pb : stdEntries) {
            prodToPbeMap.put(String.valueOf(pb.Product2Id) + pb.CurrencyIsoCode,  pb);
        }

        // update standard pricebook entries
        for(Future_Price__c pb : entries) {
        
            PricebookEntry spb = prodToPbeMap.get(String.valueOf(pb.Product__c) + pb.CurrencyIsoCode);

            if(spb == null) continue;

            spb.UnitPrice = pb.MSRP__c;
            spb.IsActive = true;

            pb.Active__c = false;
        }

        update prodToPbeMap.values();

        update entries;
    }

    global void finish(Database.BatchableContext BC) { }
}