force-app/main/default/objects/Future_Price__c/Future_Price__c.object-meta.xml
<CustomObject>
    <description>Object contains all of the Future Prices to be applied to Products (Product2) on specified Effective Dates</description>
    <label>Future Price</label>
    <nameField>
        <displayFormat>FP-{0}</displayFormat>
        <label>Future Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Future_Price__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the Future Price is available to be evaluated for applying Future Price to Product.  Value should be TRUE or FALSE, defaulted to TRUE.
Field Type: IA
Integrated: Y&quot;</description>
    <inlineHelpText>Indicates if the Future Price is available to be evaluated for applying Future Price to Product.  Value should be TRUE or FALSE, defaulted to TRUE.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Future_Price__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Indicates the date that the Future Price should be applied to the Product (Product2).
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the date that the Future Price should be applied to the Product (Product2).</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Future_Price__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>Indicates the MRSP value of the related Product for Future Price.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates the MRSP value of the related Product for Future Price.</inlineHelpText>
    <label>MSRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Future_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates relationship of Future Price to Product (Product2) to apply Future Price.
Field Type: IA
Integrated: Y</description>
    <inlineHelpText>Indicates relationship of Future Price to Product (Product2) to apply Future Price.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Future Prices</relationshipLabel>
    <relationshipName>Future_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RWS_UpdateStandardPricebookController.cls
/********************************************************************************
*   PURPOSE : Update Standard Pricebook and its entries based on data in Future Pricebook
*
*
*   CHANGE  HISTORY
*   =============================================================================
*   Date        Name                    Description
*   12/17/2016  Usman Aslam/M360        Initial version
********************************************************************************/
public with sharing class RWS_UpdateStandardPricebookController {

    // Instance variables
    public Id pricebookId {get; private set;}
    private Future_Price__c fpb;

    public RWS_UpdateStandardPricebookController() {
        // get pricebook id
        pricebookId = ApexPages.currentPage().getParameters().get('id');
        
    }

    public PageReference updateStandardPricebook() {

        PageReference pr = new PageReference('/' + pricebookId);

        Id stdPbId;

        try {
            // get future pricebook
            fpb = [select Id, CurrencyIsoCode, Active__c, MSRP__c, Product__c, Effective_Date__c 
                            FROM Future_Price__c
                        where Id = :pricebookId];

            if(!fpb.Active__c) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Future Price is Inactive.'));
            }

            if(fpb.Effective_Date__c == null || fpb.Effective_Date__c > Date.today()) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Invalid Effective Date.'));
            }

            if(fpb.Product__c == null) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Invalid Product.'));
            }

            if(fpb.MSRP__c == null) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Invalid MSRP.'));
            }

            // get standard pricebook id
            if(Test.isRunningTest()) 
                stdPbId = Test.getStandardPricebookId();
            else
                stdPbId = [select id, name from Pricebook2 where IsStandard = true limit 1].Id;

        } catch(Exception ex) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, ex.getMessage()));
        }

        if(ApexPages.hasMessages()) return null;

        // set save point, so we can rollback in case of any error
		SavePoint sp = Database.setSavepoint();

		try {

            // get standard price book entries
    		List<PricebookEntry> stdEntries = [SELECT Id, Name, Product2Id, 
    										 UnitPrice, 
    										UseStandardPrice, Discount__c, 
    										MSRP_Effective_Date__c, MSRP_Expiration_Date__c,
                                            IsActive,
                                            CurrencyIsoCode
    									FROM PricebookEntry
    									WHERE Pricebook2Id = :stdPbId
                                        and Product2Id = :fpb.Product__c
                                        and CurrencyIsoCode = :fpb.CurrencyIsoCode];

            if(stdEntries.isEmpty()) return pr;

            // update standard pricebook entries
    		for(PricebookEntry spb : stdEntries) {
                spb.UnitPrice = fpb.MSRP__c;
                spb.IsActive = fpb.Active__c;
    		}
			update stdEntries;

            // update future pricebook
    		fpb.Active__c = false;
    		update fpb;

		} catch (DmlException ex) {
			System.debug(ex.getMessage());
			ApexPages.addMessages(ex);
		} catch (Exception ex) {
			System.debug(ex.getMessage());
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, ex.getMessage()));
		}

		if(ApexPages.hasMessages()) {
			Database.rollback(sp);
			return null;
		}

        // retrurn to future pricebook
    	return new PageReference('/' + pricebookId);
    }
}